### ISSUE TITLE
buffer source is slow

### ISSUE THREAD

**Issue by pwntester** [Shougo/denite.nvim#102]
`buffer` source is really slow, wondering if it could be speeded up by caching the buffers when these are created.

Thanks

**Comment by Shougo** [comment]
Really?  I must reproduce the problem.

Please create the minimal example to reproduce it.

> buffer source is really slow, wondering if it could be speeded up by caching the buffers when these are created.

I don't want to add the hook and it is not easy.

**Comment by pwntester** [comment]
After some debugging, it seems the culprit is `qpkorr/vim-bufkill`, will try to find out why its slowing down `denite`

Thanks

**Comment by pwntester** [comment]
If someone else is having the same problem, I just replaced vim-bufkill with two aliases:

```
cabbrev bd <C-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'bp\<BAR>bd\ \#' : 'bd')<CR>
cabbrev bd! <C-r>=(getcmdtype()==':' && getcmdpos()==1 ? 'bp\<BAR>bd!\ \#' : 'bd!')<CR>
```

It woks great except if there is only one buffer in the window, but then you can just use `bdelete` to avoid the substitution.

**Comment by Shougo** [comment]
OK
