### ISSUE TITLE
Feature request:  Python2 compatibility

### ISSUE THREAD

**Issue by yannack** [Shougo/denite.nvim#108]
Many of the plugins I use are python2-only. I have vim8 installed, but compiled without py3 support because py3 caused breakage. How hard would it be to provide py2 compatibility ? I could even contribute if this is a manpower issue.
Thanks !

**Comment by Shougo** [comment]
> Many of the plugins I use are python2-only. 

Oh, it is bad.

I don't want to add support Python2 in 2017.

So you have the some options.

* Throw away the Python2 only plugins
* Throw away Debian/Ubuntu
* Use neovim instead

**Comment by lambdalisue** [comment]
> How hard would it be to provide py2 compatibility ?

It not hard at the beginning but maintenance both version would make the world complicated.

I also recommend you to try neovim instead but if you really need Vim 8, try

- Mac : https://gist.github.com/splhack/4ec93591aec286beac496bbd5cc8d764
- Ubuntu/Debian : https://gist.github.com/lambdalisue/102a1f9985b243cd0e71

But it's sometime bit tricky and this is an issue of Vim 8 so we cannot help anymore.

**Comment by yannack** [comment]
So unfortunately I use Vim at my work, and there are a lot of custom plugins using Python 2, several thousand employees relying on them, including myself. This is why Neovim and/or dropping those plugins and/or dropping the distro are not options. I have been  preaching for Unite inside of my company, but I guess this will have to stop now :(
I understand python2 compatibility might be a pain down the line, but maybe there could be some unofficial support for it initially, until it is no longer possible. There could be a disclaimer about this even. What are the main painpoints you anticipate around maintaining both ?

**Comment by Shougo** [comment]
> So unfortunately I use Vim at my work, and there are a lot of custom plugins using Python 2, several thousand employees relying on them, including myself.
> What are the main painpoints you anticipate around maintaining both ?

What does you support both Python2 and Python3 in your Python2 plugins?
I think it is because the additional cost.
So this is the same reason.  QED.
I don't want to support Python2 in 2017 (again).

>  This is why Neovim and/or dropping those plugins and/or dropping the distro are not options. I have been preaching for Unite inside of my company, but I guess this will have to stop now :(

???
neovim dropping the plugins?  Why?  Whats?
I don' understand the statements?
