### ISSUE TITLE
What's the difference between this and fzf

### ISSUE THREAD

**Issue by Swoorup** [Shougo/denite.nvim#109]

**Comment by Shougo** [comment]
Please don't just paste the issue template.
It no means!

I have removed the template.

**Comment by Shougo** [comment]
* fzf is the command line tool.  Denite is the real Vim plugin
* denite supports multiple sources
* denite only works in Vim/neovim
* denite supports various customization
* denite can call unite sources
etc...

**Comment by FinallyFinancialFreedom** [comment]
denite has more sources than fzf.vim, denite don not need a external xterm, it's important in vim(neovim build a term emulator inside so it's ok).

**Comment by unphased** [comment]
fzf works quite well in vim now, though, because terminal support is in.
