### ISSUE TITLE
source `grep`: context `input` and `path` non-functional

### ISSUE THREAD

**Issue by nfnty** [Shougo/denite.nvim#113]
- [Always have to manually press `<CR>` to confirm `input('Pattern: ')`](https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/source/grep.py#L57-L58)
- Narrowing is always applied resulting in extremely bad performance when filter is applied
- [Can't specify `path` and `args` at the same time, due to `directory` being overwritten by `args[0]`](https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/source/grep.py#L50-L54)

Works great with Unite:
```
function! custom#VisualGrep(options) abort
    call unite#start(['grep'], {
        \ 'path': getcwd(),
        \ 'input': custom#VisualGet(),
        \ 'custom_grep_default_opts': printf('%s %s', g:unite_source_grep_default_opts, a:options),
    \ })
endfunction
```

Denite:
```
function! custom#VisualGrep(...) abort
    let l:options = get(a:000, 0, [])
    let l:args = [getcwd()] + l:options
    call denite#start([{'name': 'grep', 'args': l:args}], {'input': custom#VisualGet(), 'mode': 'normal'})
endfunction
```

**Comment by Shougo** [comment]
> Always have to manually press <CR> to confirm input('Pattern: ')

> Narrowing is always applied resulting in extremely bad performance when filter is applied

Please use `matcher_cpsm` instead.

> Can't specify path and args at the same time, due to directory being overwritten by args[0]

It is the same with unite.vim.

```vim
function! custom#VisualGrep(...) abort
    let l:options = get(a:000, 0, [])
    let l:args = [''] + l:options
    call denite#start([{'name': 'grep', 'args': l:args}], {'input': custom#VisualGet(), 'mode': 'normal', 'path': getcwd()})
endfunction
```

**Comment by nfnty** [comment]
> Fixed.

Thanks.

> Please use `matcher_cpsm` instead.

Changing the filter doesn't fix this problem. I don't want the narrowing to apply at all before I manually type it in.

> It is the same with unite.vim.

Still is very unpredictable behavior.

**Comment by nfnty** [comment]
Request to reopen this issue; see previous comment.

**Comment by Shougo** [comment]
I cannot understand your issue.
Please describe the problem more clearly.
We have not ESP skills.

> Changing the filter doesn't fix this problem. I don't want the narrowing to apply at all before I manually type it in.

I don't get it.

> Can't specify path and args at the same time, due to directory being overwritten by args[0]

This problem is solved.
What's the problem?

**Comment by nfnty** [comment]
I opened a PR that fixes this issue; should clarify what I mean.

**Comment by iledarn** [comment]
@nfnty,
Where can I find your config files? I want to use VisualGrep/VisualGet
