### ISSUE TITLE
filter_project_files does not work.

### ISSUE THREAD

**Issue by okamos** [Shougo/denite.nvim#12]
# Problems summary

I try filter_project_files future.
But it does not work with below settings.

```vim
call denite#custom#source('file_rec', 'matchers',
\ ['matcher_fuzzy', 'matcher_project_files'])
```

It seems that `context['path']` isn't set in gather_candidates.

## Expected

Set filter project to .git exists directory.

## Provide a minimal init.vim with less than 50 lines (Required!)

settings with dein.vim

```toml
[[plugins]]
repo = 'Shougo/denite.nvim'
on_cmd = ['Denite']
merged = 0
hook_add = '''
nmap <silent> <C-u><C-u> :<C-u>Denite file_mru<CR>
nmap <silent> <C-u><C-p> :<C-u>Denite file_rec<CR>
nmap <silent> <C-u><C-j> :<C-u>Denite line<CR>
'''
hook_post_source = '''
call denite#custom#var('file_rec', 'command',
\ ['pt', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', ''])
call denite#custom#source('file_rec', 'matchers',
\ ['matcher_fuzzy', 'matcher_project_files'])
'''
```

## The reproduce ways from neovim starting (Required!)

1. Denite file_rec

**Comment by Shougo** [comment]
`matcher_project_files` is not implemented.

You should remove `--hidden` argument.

```vim
call denite#custom#var('file_rec', 'command',
\ ['pt', '--follow', '--nocolor', '--nogroup', '-g', ''])
```
