### ISSUE TITLE
Feature request: should have a sorter keep original sort

### ISSUE THREAD

**Issue by chemzqm** [Shougo/denite.nvim#133]
I use https://github.com/chemzqm/redismru.vim with denite.
It could contain thousands of files, I always have latest opened file on the top to open the file faster, but denite tend to sort files on filter, which is not a desired feature for me with MRU files.

**Comment by Shougo** [comment]
You can disable the sorters.

```python
  def __init__(self, vim):
    Base.__init__(self, vim)
    self.name = 'redis_mru'
    self.kind = 'file'
    self.home = expanduser('~')
    self.cwd = vim.eval('getcwd()') + '/'
    self.sorters = []
```
