### ISSUE TITLE
Migrate VimFiler dependency to denite.vim

### ISSUE THREAD

**Issue by varmanishant** [Shougo/denite.nvim#136]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

Currently VimFiler depends on unite.vim. As denite.vim is a replacement project, when can we expect the functionality from unite.vim to be ported to denite.vim? Also is it possible to keep functionalities standalone instead of having dependencies?

## Expected

Independent  and smoothly operational plugins!

**Comment by Shougo** [comment]
https://github.com/Shougo/vimfiler.vim/issues/380
https://github.com/Shougo/vimfiler.vim/issues/379
