### ISSUE TITLE
echo has("python3")

### ISSUE THREAD

**Issue by GianniGi** [Shougo/denite.nvim#139]
How do I enable python in vim 8, under windows 8.1?
thanks

**Comment by prabirshrestha** [comment]
* download vim from https://tuxproject.de/projects/vim/ 
* download python 3 from https://www.python.org/downloads/. Make sure you download the correct version based on `vim --version`. You should seen something like this `-DDYNAMIC_PYTHON3_DLL=\"python35.dll\"`
* make sure python 3 is in the path when installing.

**Comment by GianniGi** [comment]
thanks, I solved by installing this official version from github

https://github.com/vim/vim-win32-installer
