### ISSUE TITLE
Denite not working with latest Neovim

### ISSUE THREAD

**Issue by brandonpittman** [Shougo/denite.nvim#14]
# Problems summary
I have the latest Neovim installed, but Denite says the installed version doesn't work.

![screen shot 2016-09-23 at 8 46 50](https://cloud.githubusercontent.com/assets/967145/18769733/b5891ea6-816a-11e6-9899-cd34a080493a.png)

![screen shot 2016-09-23 at 8 47 07](https://cloud.githubusercontent.com/assets/967145/18769734/b76d2140-816a-11e6-818d-e17f901f4a24.png)

**Comment by brandonpittman** [comment]
Reinstalled Neovim without --HEAD and everything is okay. Sorry.

**Comment by dimidd** [comment]
I have a similar problem, did you manage to solve it?

**Comment by Shougo** [comment]
@dimidd I think your neovim is too old.
0.1.6 is already released.
