### ISSUE TITLE
File_rec not working in windows

### ISSUE THREAD

**Issue by GianniGi** [Shougo/denite.nvim#140]
is this plugin compatible with vim 8?

# Problems summary
file_rec doesn't work

## Expected
that it works

## Environment Information

 * OS: windows 8.1
* vim 8 

## The reproduce ways from neovim starting (Required!)

 1. start vim
 2. run denite file_rec

## Screen shot (if possible)

![clipboard02](https://cloud.githubusercontent.com/assets/9282332/21561899/92f3d8da-ce73-11e6-8516-5e4e5e240d38.jpg)

## vimrc

"vim windows 8.1 ufficio
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => General
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Set to auto read when a file is changed from the outside
set autoread

filetype plugin on

syntax on
filetype plugin indent on

set nocompatible

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => plugin manager settings
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"Reload .vimrc and :PlugInstall to install plugins.
call plug#begin('d:/sbin/vim/vimfiles/plugged')

Plug  'https://github.com/Shougo/unite.vim.git' 
Plug 'https://github.com/tpope/vim-surround.git'
Plug 'https://github.com/scrooloose/nerdcommenter.git'
Plug 'https://github.com/plasticboy/vim-markdown.git'
Plug 'https://github.com/tpope/vim-repeat.git'
Plug 'https://github.com/vim-perl/vim-perl.git'
"di questo mi interesserebbe solo perl-support
Plug 'https://github.com/WolfgangMehner/vim-plugins.git'
Plug 'mhinz/vim-grepper'
Plug 'https://github.com/Shougo/denite.nvim'

" Add plugins to &runtimepath
call plug#end()

**Comment by Shougo** [comment]
Fixed the error.
You must install the file listing command like ag or ripgrep.
