### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by nhooyr** [Shougo/denite.nvim#143]
We should have some nice screenshots included in the README.

**Comment by wsdjeg** [comment]
![2017-12-24-13-38-46](https://user-images.githubusercontent.com/13142418/34324674-b8ddd5b8-e840-11e7-9b77-d94e1b084bda.gif)

**Comment by Shougo** [comment]
I have added it.

**Comment by wsdjeg** [comment]
I like the mode feature, which do not supported in fzf ctrlp etc.

**Comment by wsdjeg** [comment]
![2017-12-24-14-32-22](https://user-images.githubusercontent.com/13142418/34324752-e5a89900-e842-11e7-9f87-6d8789ba3871.gif)

**Comment by wsdjeg** [comment]
This this the colorsheme gifs, I think when move curosr in the menu, It is better to change th e colorscheme, that will be easy for user to preview colorcheme:

![2017-12-24-14-40-38](https://user-images.githubusercontent.com/13142418/34324786-f4dd39a2-e843-11e7-97ef-7a48ee04d27b.gif)

in spacemacs:

![2017-12-24-14-41-40](https://user-images.githubusercontent.com/13142418/34324799-1bf852ce-e844-11e7-83f0-0e9f7f3dd96c.gif)

**Comment by wsdjeg** [comment]
ohh, sorry, denite has support this feature:

use `Denite colorscheme -no-quit`

![2017-12-24-14-43-33](https://user-images.githubusercontent.com/13142418/34324806-5cf5c00e-e844-11e7-8dd2-6bccf2ff3f0d.gif)

**Comment by oblitum** [comment]
Could someone plz provide a gif with floating windows :) (I'm not on NeoVim master for that).

**Comment by delphinus** [comment]
@oblitum Here :)

![J1EdEuJJxy](https://user-images.githubusercontent.com/1239245/54264804-3f9b8800-45b7-11e9-9e58-938e45ed967a.gif)

**Comment by oblitum** [comment]
@delphinus cool! Seeing that, I think it would be better if the window took a different background color, it seems kinda messy text soap.

**Comment by delphinus** [comment]
![CqdZcruYMW](https://user-images.githubusercontent.com/1239245/54329573-8b047380-4655-11e9-8b9a-ab4a91f4768f.gif)

I re-built NeoVim on HEAD, and I see floating windows has `Pmenu` highlight on background. It's just OK, but it should be customized by an option on denite...? 🤔

**Comment by Shougo** [comment]
OK.  I will update it

**Comment by Shougo** [comment]
I will remove current screenshots in README.
Because, ui branch is not same UI.

So please upload the screenshots in ui branch.

https://github.com/Shougo/denite.nvim/pull/624

**Comment by delphinus** [comment]
![DelBSPcFbe](https://user-images.githubusercontent.com/1239245/58742567-a155ea80-8460-11e9-9925-09082def2c80.gif)

recorded the new UI!

**Comment by Shougo** [comment]
Thanks.  I have added it.

**Comment by taigacute** [comment]
![Untitled](https://user-images.githubusercontent.com/41671631/58790351-cf832800-8622-11e9-912d-813408876b86.gif)

**Comment by Shougo** [comment]
Updated

**Comment by oblitum** [comment]
What's up with latest update?

![imgur-02:51:43_26-08-2019](https://user-images.githubusercontent.com/1269815/63668132-959e6980-c7ac-11e9-98a4-5475c2ffaf92.png)

I didn't change anything but now prompt is now on top, and I got some ugly artifacts in the background, instead of clean one.

**Comment by oblitum** [comment]
Hmm, nevermind, I think this was due to neovim-nightly update...

**Comment by wsdjeg** [comment]
Two version of denite:

1. old:

![old denite](https://user-images.githubusercontent.com/13142418/65154984-06107180-da5f-11e9-8cbf-e0a544d0dbc5.jpg)


2. new:

![new denite](https://user-images.githubusercontent.com/13142418/65154937-f002b100-da5e-11e9-8aef-723233e3704d.jpg)

**Comment by Shougo** [comment]
Updated.

@wsdjeg I want to use your screenshots in my VimConf 2019 presentation.
Can I use them?

**Comment by wsdjeg** [comment]
of cause you can do it.

**Comment by Shougo** [comment]
Thanks.

**Comment by nhooyr** [comment]
Going to close as it has been a long time and I'm not sure if this is relevant anymore.
