### ISSUE TITLE
Doesn't denite.nvim work with vim compiled with python3/dyn?

### ISSUE THREAD

**Issue by varmanishant** [Shougo/denite.nvim#148]
I am have installed Vim 8.0 from source with Python support and vim --version says +python3/dyn. However Denite says it requires Vim 8.0+ with Python3 support("+python3"). It works fine with plugins like YCM.

**Comment by Shougo** [comment]
YCM supports Python2.
I think YCM loads Python2 and disabled Python3.

Please read `:help python-2-and-3`
