### ISSUE TITLE
Change highlight of unmatched characters

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#149]
Hi @Shougo  and @lambdalisue. I know I can change the matched characters highlight by using:
```
call denite#custom#option('default', 'highlight_matched_char', 'Identifier')
```
However I would also like to change how unmatched characters are highlighted. Currently, as it can be seen in the screenshot below, they are underlined and highlighted in red. Is it possible to change this? (I read the documentation and skimmed through the issues but didn't find any pointers). Thanks in advance!!

![screen shot 2017-01-08 at 12 48 26](https://cloud.githubusercontent.com/assets/2583971/21751164/53e539f6-d5a1-11e6-9a30-73777bfa8ebf.png)

**Comment by 0phoff** [comment]
Didn't know you this was the way of changing options in denite... :clown_face: 
I usually edit the Syntax Highlighting groups themselves!

```vim
hi deniteMatchedChar ctermbg=INSERT_COLOR ctermfg=INSERT_COLOR
hi link deniteMatchedChar OTHER_NICE_LOOKING_HIGHLIGHT_GROUP
```

a quick look at the highlight groups (run :so $VIMRUNTIME/syntax/hitest.vim) and I found out you can change the deniteMatched group to edit the letters you want!

I dont know if there is anything bad about my way of doing things... ( @Shougo If so let me know... )
I gues you could try:
```vim
call denite#custom#option('default', 'highlight_matched', 'Identifier')
```
But I didnt test this myself :)

**Comment by petobens** [comment]
@Shougo  thank you!!

**Comment by viniciusarcanjo** [comment]
I'm glad I found this. Thank you guys. The documentation is clear enough, but just in case someone needs to change the background of the selected line when in insert mode:
```
call denite#custom#option('default', 'highlight_mode_insert', 'PMenu')
```
