### ISSUE TITLE
入力結果にもとづいて毎回 grepする

### ISSUE THREAD

**Issue by baronTommy** [Shougo/denite.nvim#150]
機能要望です。

- 入力しながら全文検索
- `Denite file_rec`の様なファイル名に対しての検索では無く、全文検索
- `Denite -auto_preview grep`だと*ながら*`anything`の様にならない
  - 文字を入力 -> enter -> 結果の流れになる為
- 対象は特定のディレクトリを事前に設定しておき、そこが全文検索対象
  - `~/data/`配下の`*.md`を対象の様な使い方

> [nvalt](http://brettterpstra.com/projects/nvalt/)
> [参考 issue](https://github.com/vim-jp/issues/issues/1007)

**Comment by Shougo** [comment]
この機能に関しては、以前に他の人から要望があり実装検討中です。
この機能を実装するためには denite 本体に入力に応じて source を呼び出すという機能が必要になります。
※：ちなみに、unite.vim には存在します
grep に特別な引数を与えることで挙動をかえることを検討しています。

**Comment by baronTommy** [comment]
技術メモを検索、修正での利用を検討しています。
可能でしたらよろしくお願いします。

closeはお任せします
