### ISSUE TITLE
Can't find configuration functions

### ISSUE THREAD

**Issue by gustavo-hms** [Shougo/denite.nvim#154]
# Problems summary

None of the configuration functions listed in the plugin doc can be found after the plugin is installed. So, for example, if I have this minimum init.vim:

``` vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Shougo/denite.nvim'
call denite#custom#var('file_rec', 'command',
        \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call plug#end()
```

then run `:PlugInstall` and `:UpdateRemotePlugins`, Denite works as expected (all the commands are available) except that at each nvim startup it prints the message 

> line 4:
> E117: Unknown function: denite#custom#var

The same can be said for all the denite#... functions I've tested.

## Expected

I was expecting that these functions were the way to go to make any configuration in the plugins, as explained in the doc.

## Environment Information

 * OS: Archlinux

 * `:CheckHealth` result:
```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - ERROR: key_backspace (kbs) entry is ^H (ASCII DELETE): key_backspace=^H,

    - SUGGESTIONS:
      - Set key_backspace to \177 (ASCII BACKSPACE). Run these commands:
          infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
          tic $TERM.ti
      - See https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.0
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.7

## Minimal init.vim

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Shougo/denite.nvim'
call denite#custom#var('file_rec', 'command',
        \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
call plug#end()
```

## The reproduce ways from neovim starting (Required!)

 1. Install the plugin manager: `curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim`
 2. Enter nvim
 3. Execute `:PlugInstall`
 4. Execute `:UpdateRemotePlugins`
 5. Exit nvim
 6. Enter nvim again. Then you can see the "Unknown funtion" message.

**Comment by Shougo** [comment]
This is vim-plug feature.

`call plug#end()` loads denite.nvim.  So you must write `call denite#custom#var()` after `call plug#end()`.

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Shougo/denite.nvim'
call plug#end()
call denite#custom#var('file_rec', 'command',
        \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])
```

**Comment by gustavo-hms** [comment]
Hmm! I didn't know that. Thank you for the quick response and sorry for the avoidable inconvenience.

**Comment by borenho** [comment]
I had the same issue. Can it be added as a `known issue` @Shougo ? It took me a couple of days to figure it out.

**Comment by Shougo** [comment]
Unfortunately, it is not denite's issue.

It is well known vim-plug's issue.
