### ISSUE TITLE
Does a DeniteDo command make sense in this plugin?

### ISSUE THREAD

**Issue by thalesmello** [Shougo/denite.nvim#155]
Hey, @Shougo, congratulations for the project. It's a lot cleaner and easier to setup.

Based on my implementation of the `[UniteDo](https://github.com/Shougo/unite.vim/pull/1169)` command, I'm writing to ask if implementing a `DeniteDo` command would make sense in this new organization?

I'm asking this because I've noticed, in the FAQ or the readme, the equivalents of `DeniteNext` and `DenitePrevious` are now options of the `Denite` command.

If this is indeed the case that you wish to keep the commands and settings minimal, I think it makes a lot of sense.

One possible alternative to this command would be to implement an action to send all inputs to the quickfix list, which allow the user to use the `cdo` command to do the same thing over the narrowed down items.

I'm curious to hear your opinion.

**Comment by Shougo** [comment]
> One possible alternative to this command would be to implement an action to send all inputs to the quickfix list, which allow the user to use the cdo command to do the same thing over the narrowed down items.

OK. I should add `quickfix` action for it.

> If this is indeed the case that you wish to keep the commands and settings minimal, I think it makes a lot of sense.

Yes, I don't want to add more commands.

**Comment by thalesmello** [comment]
That's excellent! Thank you very much.
