### ISSUE TITLE
E325 (Swap file error) should not be reported by denite.vim

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/denite.nvim#158]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

denite.vim shows E325 after opening a buffer which has a swap file.

```
[denite] function dein#autoload#_on_cmd[13]..denite#helper#call_denite[14]..denite#start[23].._denite_start[1]..denite#util#execute_path, line 2
[denite] Vim(edit):E325: ATTENTION
```

## Expected

E325 has already shown by Vim so denite should not report that exception.

## Environment Information

 * OS: MacOS X

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
set directory=.
```

## The reproduce ways from neovim starting (Required!)

1. `$ cd ~`
2. `$ mkdir test`
3. `$ cd test`
4. `$ vim -u ~/.vimrc.min` or `$ nvim -u ~/.vimrc.min`
5. `:e test.txt<CR>`
6. `aaaaa<Esc>`
7. `:w<CR>`
8. `abbbbb<Esc>`
9. Kill the Vim process without saving (to make a swap file)
10. `$ vim -u ~/.vimrc.min`
11. `:Denite file_rec`
12. Select and open `test.txt` and the following will be shown
    ![screenshot 2017-01-19 02 57 25](https://cloud.githubusercontent.com/assets/546312/22076348/13c51e68-ddf3-11e6-907d-226f46e09360.png)
13. Hit `o` to open the file
14. `:messages` shows which has already shown by Vim

    ```
    [denite] function dein#autoload#_on_cmd[13]..denite#helper#call_denite[14]..denite#start[23].._denite_start[1]..denite#util#execute_path, line 2
    [denite] Vim(edit):E325: ATTENTION
    ```

**Comment by Shougo** [comment]
Fixed.
