### ISSUE TITLE
When using file_rec, pt and rg don't work on Windows.

### ISSUE THREAD

**Issue by kashewnuts** [Shougo/denite.nvim#159]
# Problems summary
`file_rec` is executed using `pt` <del>or `rg`</del>, the file list is not displayed.
It seems that it will not be displayed in the list with the `-g` option.
I'd like to use `file_rec` even in `pt` <del>and `rg`</del> like `mattn/files`.

[Add: 2017/01/20 20:49] sorry. `rg` worked with `''` at the end of the option.

### ja
`pt`<del>や`rg`</del>を使用して`file_rec`するとファイルの一覧が表示されません。
どうやら`-g`オプションを付けると表示されなくなるようです。
`mattn/files`では問題なく動作しているので、`pt`<del>や`rg`</del>でも同じように`file_rec`を使用したいです。

[追記: 2017/01/20 20:49] ごめんなさい。`rg`はオプションの最後に`''`を追加したら動作しました。

## Expected
That it works.

## Environment Information

 * OS: Windows10 pro (64bit)
 * Vim: 8.0.0134 (kaoriya, 32bit)
 * denite.nvim: rev`321dcba`

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" My minimal vimrc
call plug#begin('~/.vim/plugged')
Plug 'Shougo/denite.nvim'
call plug#end()
call denite#custom#var('file_rec', 'command', ['pt', '--follow', '--nocolor', '--nogroup', '-g'])
```

## The reproduce ways from neovim starting (Required!)

 1. Start vim
 2. Run `:Denite file_rec`

## Screen shot (if possible)
![don t_work_denite_file_rec](https://cloud.githubusercontent.com/assets/1122795/22144678/e013b9bc-df41-11e6-97fd-971ad3b6221a.png)

**Comment by okamos** [comment]
I think lack of last variable `''`

```
call denite#custom#var('file_rec', 'command', ['pt', '--follow', '--nocolor', '--nogroup', '-g', ''])
```

It works for me.

**Comment by kashewnuts** [comment]
Thanks. However adding `''` did not work.

**Comment by kashewnuts** [comment]
The specification of the option was wrong. It worked with `-g:` or `-l` instead of `-g`.
