### ISSUE TITLE
Normal mode mappings don't work in Vim8

### ISSUE THREAD

**Issue by ragnese** [Shougo/denite.nvim#166]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
None of the mappings for "normal" mode work in Denite buffers.

## Expected
Expect to use "i" and "j" to navigate the list. Expect "i" to switch to insert mode. Etc.

## Environment Information (Required!)

 * denite version(SHA1): 9ff53c19454801789ed98d427d89321d00b7547d

 * OS: Arch Linux

 * Vim/neovim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jan 24 2017 17:27:32)
Included patches: 1-237
Compiled by Arch Linux
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     +tcl/dyn
+balloon_eval    +folding         +mouse_xterm     +termguicolors
+browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    +netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        +toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        +perl/dyn        +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
+cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con_gui  +lua/dyn         +rightleft       +writebackup
+diff            +menu            +ruby/dyn        +X11
+digraphs        +mksession       +scrollbind      -xfontset
+dnd             +modify_fname    +signs           +xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      +mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        +mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax          
+farsi           +mouse_netterm   +tag_binary

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/.vim/plugged/denite.nvim
```

## The reproduce ways from neovim starting (Required!)

 1. ```vim file1 file2```
 2. ```:Denite -mode='normal' buffer```
 3. Try any normal mode mappings. None will work.
 4. Try any "_" mappings and they do work.

**Comment by Shougo** [comment]
`:Denite -mode=normal buffer`

**Comment by ragnese** [comment]
Hi Shougo,

Thank you! I think I was confused because of the documentation on line 865 of /doc/denite.txt:

> 							*denite-options-mode*
>-mode={mode}
>                Specify the default mode.
>                Default: "insert"

It looks like you are supposed include the quotes.
