### ISSUE TITLE
Feature request: some missing sources from Unite

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#167]
Hi Shougo, I'm considering migrating from Unite to Denite. I have a few questions:

i) Will you (or @thinca) add command and search history sources similar to https://github.com/thinca/vim-unite-history ?

ii) Are you planning to add a tag source? Similar to https://github.com/tsukkee/unite-tag

iii) Will you add a vimgrep source or similar? Essentially my use case is that I wanted to grep on the current file. I know I can do this from the command line like this : `ag TODO\|FIXME vimrc` but I'm not sure how can i do this with Denite.

iv) Is there a command similar to `UniteWithInputDirectory`? I find that command really useful for the `file_rec` source.

Thank you! And sorry for asking too many questions.

**Comment by Shougo** [comment]
> i) Will you (or @thinca) add command and search history sources similar to https://github.com/thinca/vim-unite-history ?

No plan.  You can add it.

> ii) Are you planning to add a tag source? Similar to https://github.com/tsukkee/unite-tag

Yes.

> iii) Will you add a vimgrep source or similar? Essentially my use case is that I wanted to grep on the current file. I know I can do this from the command line like this : ag TODO\|FIXME vimrc but I'm not sure how can i do this with Denite.

I don't want to add it.  I don't think it is useful.

> iv) Is there a command similar to UniteWithInputDirectory? I find that command really useful for the file_rec source.

No.  You should do it by `:Denite file_rec -input=`input()``

**Comment by petobens** [comment]
Thank you @Shougo . I asked thinca[https://github.com/thinca/vim-unite-history/issues/6] if he plans to add denite support.

**Comment by petobens** [comment]
One last question, are you planning to add `converter_uniq_word`? Thanks once again.

**Comment by Shougo** [comment]
>i) there is no highlight

Please read other sources implementation.

> instead of the usual search hit BOTTOM, continuing at the TOP message.

Hm.  I will improve the behavior.
But I cannot fix the message.  It is Vim feature.

**Comment by Shougo** [comment]
I have fixed the error behavior.

**Comment by Shougo** [comment]
> One last question, are you planning to add converter_uniq_word? Thanks once again.

Why it is needed?

**Comment by petobens** [comment]
> Why it is needed?
I think it is really useful for the buffer source: https://github.com/Shougo/unite.vim/issues/1157

> But I cannot fix the message. It is Vim feature.
There is no way to thoe the `search hit BOTTOM...` message? 

> Please read other sources implementation.
Ok. I thought that the search command automatically highlighted the search matches.

**Comment by Shougo** [comment]
`There is no way to thoe the search hit BOTTOM... message?`

I have tested that.   The message is displayed when wrap scaned only.

> I think it is really useful for the buffer source: Shougo/unite.vim#1157

OK.  But I don't want to add it.  I have read the implementation, it is very complex and the tests are needed.
You can create it.

**Comment by petobens** [comment]
Hi @Shougo, I'm still trying to implement the search and command history sources. Consider the following `command_history.py` file:
```python
from .base import Base


class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = 'command_history'
        self.kind = 'command'

    def gather_candidates(self, context):
        hist_len = self.vim.eval("histnr('cmd')")
        history = list(
            filter(None, [
                self.vim.eval("histget('cmd', " + str(i) + ")")
                for i in range(1, hist_len + 1)
            ]))[::-1]
        return [{'action__command': ':' + i, 'word': i} for i in history]
```
Now  do the following:
i) run the command `:echo foo`
ii) run `:Denite command_history`
iii) select the candidate `echo foo` and press `<CR>` 
You will see that the message `foo` is not displayed in the command line. I actually expect it to appear (i.e echoed/printed)  in the command line.
Thanks in advance for the help.

**Comment by petobens** [comment]
Now regarding the search highlighting, if I run `execute "/foo"` then all matches of `foo` are highlighted. On the other hand if I use the following `search_history.py` source:
```python
from .base import Base


class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = 'search_history'
        self.kind = 'command'

    def gather_candidates(self, context):
        hist_len = self.vim.eval("histnr('search')")
        history = list(
            filter(None, [
                self.vim.eval("histget('search', " + str(i) + ")")
                for i in range(1, hist_len + 1)
            ]))[::-1]
        return [{'action__command': '/' + i, 'word': i} for i in history]
``` 
and select the candidate `foo` from the the search history then the matches are not highlighted. I actually expect them to be highlighted (since the `command` kind calls `denite#util#execute_command` which in turn calls `execute`).

**Comment by chemzqm** [comment]
@petobens you may need to create new Kind for your soure and use `feedkey` function of vim to feed charactors to command line at the defautl action of new Kind.

**Comment by petobens** [comment]
@chemzqm I'm afraid I don't quite follow what you are suggesting.
@Shougo also another problem I discovered when trying to implement the command source is that there is no `action__histadd` for the `command` kind. i.e that the newly executed commands are not stored in history.

**Comment by chemzqm** [comment]
@petobens you can create your own Kind class inherited from `command`, the documention is already added https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt#L1452

**Comment by Shougo** [comment]
> @Shougo also another problem I discovered when trying to implement the command source is that there is no action__histadd for the command kind. i.e that the newly executed commands are not stored in history.

You can create the kind for it.

**Comment by petobens** [comment]
@Shougo ok. 

Regarding my other two comments (about highlight and the fact that `echo foo` is not echoed), any ideas why this happens?

**Comment by Shougo** [comment]
> I actually expect them to be highlighted (since the command kind calls denite#util#execute_command which in turn calls execute).

I cannot reproduce the problem.
I think you have not set `hlsearch` option.

**Comment by Shougo** [comment]
> You will see that the message foo is not displayed in the command line. I actually expect it to appear (i.e echoed/printed) in the command line.

I have fixed the problem.
Please update denite.nvim.

**Comment by petobens** [comment]
> I have fixed the problem.

Thank you

> I cannot reproduce the problem.
> I think you have not set hlsearch option.

Where should i set `hlsearch` I tried using `self.vim.command('set hlsearch')` immediately before the return of `gather_candidates` but it did not work.

**Comment by Shougo** [comment]
> Where should i set hlsearch I tried using self.vim.command('set hlsearch') immediately before the return of gather_candidates but it did not work.

I cannot reproduce it.
Please create new issue for it.

**Comment by petobens** [comment]
@chemzqm any chance of adding search and command history sources to https://github.com/chemzqm/denite-extra/tree/master/rplugin/python3/denite/source ?

**Comment by chemzqm** [comment]
@petobens ok, I can add it.
