### ISSUE TITLE
Inconsisten reversed prompt behaviour

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#172]
Consider the following minimal vimrc:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', 'reversed', 1)
```

Start neovim with this minimal vimrc and then do  the following:
1) run `Denite file_rec`: you will see that the cursorline is on the very top of the denite buffer
2) start typing something to filter: the cursorline is now on the very bottom.

Withe `reversed` option I expect the cursorline to always start on the bottom candidate.

![feb-04-2017 13-42-31](https://cloud.githubusercontent.com/assets/2583971/22619979/d5243906-eadf-11e6-9b20-407e52152dc1.gif)

**Comment by Shougo** [comment]
I will check it.

**Comment by Shougo** [comment]
It is bug.  But it takes some time to fix.  It is not easy.

**Comment by petobens** [comment]
Ok. Thank you.

**Comment by petobens** [comment]
Thank you!

**Comment by petobens** [comment]
@Shougo this problem has reappeared. You can reproduce it with my original instructions. Do you want me to open a new issue?

**Comment by Shougo** [comment]
I will test it.

**Comment by Shougo** [comment]
@petobens Please git bisect the problem.

**Comment by petobens** [comment]
Were you able to reproduce the problem? I tried git bisecting but with several commit I cannot run `Denite file_rec` because  I get errors about missing`winwidth` or `cursor_shapes` keys.

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you!

**Comment by petobens** [comment]
@Shougo after your fix I can't move inside the buffer between candidates: the cursor is always stuck on the last line...

**Comment by petobens** [comment]
Using `reversed: 0` fixes it (but then the reversed option is not set)

**Comment by petobens** [comment]
Thank you
