### ISSUE TITLE
Duplicate path prefix added in grep source

### ISSUE THREAD

**Issue by skt041959** [Shougo/denite.nvim#173]
# Problems summary
When using `:Denite grep:foo` command, it will add the `foo` prefix to the file path which already in the path of candidates.

## Environment Information (Required!)

 * denite version(81b4176):

 * OS: Linux

 * Vim/neovim version: NVIM v0.2.0-527-gbb2f36d

 * `:CheckHealth` result(neovim only): fine

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Yes, I have tried the following minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. open a project with subdirectory `foo`
 2. execute `:Denite grep:foo`, and input the valid pattern
 3. open a candidate

**Comment by Shougo** [comment]
Fixed.
