### ISSUE TITLE
grep source ag (-input) no results

### ISSUE THREAD

**Issue by BarrettLowe** [Shougo/denite.nvim#175]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
With the addition of commit [50840c4](https://github.com/Shougo/denite.nvim/commit/50840c4fbee64dc3e89d19afc2d6a264f43f8667) denite can grep for a term by running `:Denite -input=wordToGrep grep`

When setting up the grep source default command as in [unite.txt](https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt) no results are displayed.

## Expected
Results are displayed from the output of the ag command when calling the grep source via `:Denite -input=wordToGrep grep`

## Environment Information (Required!)

 * denite version(SHA1): 81b4176

 * OS: RedHat Linux

 * Vim/neovim version: 8.0 patches 1-133

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" grep source ag setup
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts',
\ ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])

```

## The reproduce ways from neovim starting (Required!)

1. set ag as default command in .vimrc (just as stated in the help docs)
2. run :Denite -input=wordToGrep grep

**Comment by 5t111111** [comment]
From my understanding `input` is used to insert a string into an input line in a denite buffer (a.g. for fuzzy matching) , so you still need to specify a word you want to grep after running `:Denite -input=wordToGrep grep`, don't you?

I have been able to use ag as a denite grep source frawlessly in this way even before https://github.com/Shougo/denite.nvim/commit/50840c4fbee64dc3e89d19afc2d6a264f43f8667 has come.

**Comment by BarrettLowe** [comment]
Ah I see. You're right about '-input' being a term to use for matching - I guess that's not what I'm looking for. When using the grep source it seems that a pattern is required before being useful (you can't grep without a pattern). How can I input the pattern to grep for in the `:Denite grep` call?

**Comment by BarrettLowe** [comment]
What I'm looking for is a change like this I think - although this is just sort of hacked out but the operation is what I'm looking for. https://github.com/BarrettLowe/denite.nvim/commit/2fc89ac764c797e18312568711ab47a926935ab8
