### ISSUE TITLE
Is there a way to change prompt position?

### ISSUE THREAD

**Issue by sodiumjoe** [Shougo/denite.nvim#179]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

I would like to change my prompt position to the top of the screen. I can change the denite buffer position, but not the prompt.

## Expected

I expect the denite prompt to be at the top if I set `-direction=top` OR I expect there to be an option for prompt position.

## Environment Information (Required!)

 * denite version(SHA1): `55dc83b76d95baa372706ff60e73032bb93f1932`

 * OS: macOS Sierra 10.12.2

 * Vim/neovim version:

```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20161210-60330-1ace895/neovim-0.1.7/build/config -I/tmp/neovim-20161210-60330-1ace895/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20161210-60330-1ace895/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20161210-60330-1ace895/neovim-0.1.7/build/include
Compiled by jmoon@jmoon

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.1.7/share/nvim"

```

 * `:CheckHealth` result(neovim only):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/denite.nvim'
call plug#end()
```

## The reproduce ways from neovim starting (Required!)

`:Denite -direction=top file_rec`

## Screen shot (if possible)

<img width="1280" alt="screenshot 2017-02-18 21 30 37" src="https://cloud.githubusercontent.com/assets/845857/23099672/89ba0b42-f621-11e6-9aa7-fab27517e364.png">

**Comment by lambdalisue** [comment]
No. While denite.nvim use `input()` and `neovim-prompt` to get user input, it is impossible and it will never be supported AFAIK

**Comment by sodiumjoe** [comment]
ok, thanks for the quick answer, I guess I'll just get used to the prompt position!
