### ISSUE TITLE
grep bug

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [Shougo/denite.nvim#183]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
i configured vim below:
```vim
call denite#custom#var('grep', 'command', ['ack'])
nnoremap <space>/ :Denite grep<CR>
```
when i triggle it, means i press space and /, then press Esc to cancel this grep, but the candidate output window is show up. i must press esc again to close it.
## Expected
i hope esc to cancel the search with out window show up.

## Environment Information (Required!)

 * denite version(SHA1):

 * OS:macos

 * Vim/neovim version:vim8.0

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call denite#custom#var('grep', 'command', ['ack'])
nnoremap <space>/ :Denite grep<CR>
```

## The reproduce ways from neovim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by Shougo** [comment]
This is not bug.
Please read the documentation.

```vim
nnoremap <space>/ :Denite -no-empty grep<CR>
```
