### ISSUE TITLE
window position changed after delete current buffer

### ISSUE THREAD

**Issue by chemzqm** [Shougo/denite.nvim#185]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

After I run delete action for current buffer in Denite buffer source, current window would be closed and denite would be positioned as top.

## Expected

The window should be replaced be another buffer if possible and denite should not change it's position.

## Environment Information (Required!)

 * denite version(SHA1):8b1dc78

 * OS: MacOS

 * Vim/neovim version:

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. Open file a
 2. Run `Denite buffer`
 3. Hit tab and select delete action for current file.

## Screen shot (if possible)

![Uploading Screen Shot.jpeg…]()

**Comment by Shougo** [comment]
Confirmed.
