### ISSUE TITLE
Alternative buffer would be broken after invoke persist action

### ISSUE THREAD

**Issue by chemzqm** [Shougo/denite.nvim#189]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

An empty buffer named `[Denite]` would replace alternative buffer after invoke persist action

## Expected

Alternative buffer should not be replaced

## Environment Information (Required!)

 * denite version(SHA1): latest master

 * OS: MacOS

 * Vim/neovim version: NVIM v0.2.0-592-gf64f90b5 

 * `:CheckHealth` result(neovim only): all success

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. Open fileA with neovim then `:e fileB`
 2. Run `Denite file_rec`
 3. Select a candidate and choose action `preview` or `highlight`
 4. Close denite buffer by `esc`
 5. Hit `<C-^>` then the empty buffer would shown, but it should be `fileA`

**Comment by chemzqm** [comment]
Looks like all actions of file except open have this problem

**Comment by chemzqm** [comment]
Same error happens after hit `<tab>` and press `<esc>` to cancel selection, Iooks like it's a bug of https://github.com/lambdalisue/neovim-prompt

**Comment by lambdalisue** [comment]
It's not a bug. And not because of neovim-prompt.
