### ISSUE TITLE
Feature request: key mappings for scroll up and down the preview window

### ISSUE THREAD

**Issue by chemzqm** [Shougo/denite.nvim#191]
I want to navigate throught the preview window after preview action, but Denite prevent me from change current window, so the key mappings would be helpful.

**Comment by Shougo** [comment]
It will be low priority. Sorry.

**Comment by minusf** [comment]
this was an amazingly powerful feature in Unite and it's less usable in denite.

in Unite it was easy to search for a pattern in a whole project, open a preview window and see the preview window autoupdate as i was scrolling through results. now i have to press `ctrl-v` every time i scroll up or down (or exit insert mode and press `p` every time).  `-auto-preview` solves some of this, but i dont always want preview window, and it's not possible to close auto preview window with `ctrl-v` or `p` when opened with `-auto-preview`.

**Comment by Shougo** [comment]
@minusf You can test/fix the PR if you really need the feature.

https://github.com/Shougo/denite.nvim/pull/204

It is low priority.  Because, no person take care the problem.
(I don't need the feature)

**Comment by Shougo** [comment]
OK.  I should support `<C-w>P` behavior.
