### ISSUE TITLE
Could Kind and Source share some context attributes?

### ISSUE THREAD

**Issue by chemzqm** [Shougo/denite.nvim#192]
Quite often, I need the Kind instance to get some varibale from the source instance, for example: current buffer name.  Since the context of Kind and Source and different, I have to pass the attribute to candidates with custom attribute like `'source__file': context['__file']` and then retrive it from `context['targets']`. I'm wondering if the context argument for action could get some attributes copied from context of source to make the implementation easier.

**Comment by Shougo** [comment]
I will implement the feature.
