### ISSUE TITLE
denite#custom#option('default', ...) does not apply to other buffer-names

### ISSUE THREAD

**Issue by thatsmydoing** [Shougo/denite.nvim#197]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
`denite#custom#option('default', ...)` only applies to "default" buffer-name, but it does not apply to all other buffer-names.

## Expected
`denite#custom#option('default', ...)` should apply to all buffer-names like how  `unite#custom#profile('default', ...)` used to work

## Environment Information (Required!)

 * denite version(SHA1):9d33b945876f75cf81ad47a494d3ff591b37c471

 * OS: Archlinux

 * Vim/neovim version: 0.1.7

 * `:CheckHealth` result(neovim only): SUCCESS

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
denite#custom#option('default', 'prompt', '>')
```

## The reproduce ways from neovim starting (Required!)

 1. Run `:Denite -buffer-name=test buffer`
 2. Denite prompt is `#` but should be `>`

**Comment by chemzqm** [comment]
I can confirm this issue.

**Comment by Shougo** [comment]
Please use `_` instead.

**Comment by thatsmydoing** [comment]
I tried using `_` but now it does not apply to any profile

**Comment by Shougo** [comment]
Fixed the problem.
