### ISSUE TITLE
Input line backspace prints '�kb'

### ISSUE THREAD

**Issue by achilleas-k** [Shougo/denite.nvim#199]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Hitting `backspace` on the Denite input line produces `�kb`.

## Expected
Remove character to the left of the cursor.

## Environment Information (Required!)

 * denite version(SHA1): 15b9a93f6f9e8442577ffb605b3b8d2eb1abe282

 * OS: Arch Linux

 * Vim/neovim version: VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 14 2017 10:57:50)

 * `:CheckHealth` result(neovim only): N/A

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/denite.nvim'
call plug#end()
```

## The reproduce ways from neovim starting (Required!)

 1. :DeniteProjectDir file_rec
 2. Hit `backspace` key

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/2369197/23341485/f24678e4-fc48-11e6-9995-cca90e89810c.png)
Recording: https://asciinema.org/a/4gc3yyw4j152mnohvsg8sgjhl

**Comment by AlexMasterov** [comment]
I have the same thing.
Not only `<BS>`; the whole right side of keyboard.

**Comment by kashewnuts** [comment]
I also encountered the same problem.
It seems that it was broken due to [eae 28f9](https://github.com/Shougo/denite.nvim/commit/eae28f9522f423e747401b0bd01946ad52b0bf82).
There was no problem with `07cf125`.

**Comment by lambdalisue** [comment]
I already talked to Shougo that the commit breaks the basics of neovim-prompt. So that commit will be reverted soon

**Comment by Shougo** [comment]
Fixed.

**Comment by kashewnuts** [comment]
Thanx!
