### ISSUE TITLE
Please support vim and neovim

### ISSUE THREAD

**Issue by prabirshrestha** [Shougo/denite.nvim#2]
Especially given that neovim isn't so stable on windows yet I would love to see denite.vim working in vim too might be with a fallback to using vimproc or job/channels.

**Comment by wsdjeg** [comment]
meybe it will be hard to implement,as I know Shougo want rewrite unite as a remote plugin

**Comment by Shougo** [comment]
Yes, it is on the todo list.

**Comment by mrbiggfoot** [comment]
+1 for vim support. Thanks!

**Comment by Shougo** [comment]
https://github.com/Shougo/denite.nvim/commit/78b968fa9e65583d9b8e47f01753e484a83518d0
