### ISSUE TITLE
Highlight candidates in search source and jump to word

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#206]
Consider the following minimal vimrc:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on
```

I'm trying to write a search history source:
```python
from .base import Base


class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = 'search_history'
        self.kind = 'command'

    def gather_candidates(self, context):
        hist_len = self.vim.eval("histnr('search')")
        history = list(
            filter(None, [
                self.vim.eval("histget('search', " + str(i) + ")")
                for i in range(1, hist_len + 1)
            ]))[::-1]
        self.vim.command('set hlsearch')
        return [{'action__command': '/' + i, 'word': i} for i in history]
```

There are however two problems with this source.

i) when I select a candidate and press `<CR>` the search match is not highlighted
ii) when I select a candidate and press `<CR>`  the cursor is placed at the start of the line where the candidate is and not exactly at the candidate word location .

**Comment by Shougo** [comment]
Your reproduce way is incomplete.
We have not ESP skills.
Do you think it is reproduce-able by other people with the information?
Please  upload more described ways from starting.

For example:

* Create the buffer
* Input ...
* Denite...
* Select...

**Comment by petobens** [comment]
Closing since history source is now implemented in https://github.com/chemzqm/denite-extra.
Thanks @chemzqm !!

**Comment by Shougo** [comment]
> when I select a candidate and press `<CR>` the search match is not highlighted

I have reproduced it, but it seems Vim/neovim feature.
The highlight is only for user input.

> when I select a candidate and press `<CR>` the cursor is placed at the start of the line where the candidate is and not exactly at the candidate word location .

I cannot reproduce it.
