### ISSUE TITLE
Feature request: tag

### ISSUE THREAD

**Issue by Julian** [Shougo/denite.nvim#210]
Is it helpful to have an issue tracking adding the `tag` source?

(If so, here's one :)

**Comment by Shougo** [comment]
It is on the todo list

**Comment by jinleileiking** [comment]
👍

**Comment by petobens** [comment]
@Shougo  I see you've added a tag source. Unfortunately this does not have the same functionality as  the unite tag source. In particular I have this mapping:
```vim
nnoremap <silent> <Leader>te :NeoIncludeMakeCache<CR>:Unite
            \ tag/include<CR>
```
Can you implement something similar for denite? Thank you!

**Comment by Shougo** [comment]
Yes, I have added tag source.
tag/include source is not implemented though.

**Comment by petobens** [comment]
@Shougo do you plan to implement tag/include?

**Comment by Shougo** [comment]
Yes.

**Comment by petobens** [comment]
Awesome :)
