### ISSUE TITLE
Denite -no-split option, ideas about implementation direction

### ISSUE THREAD

**Issue by alexanderjeurissen** [Shougo/denite.nvim#217]
I noticed `-no-split` was mentioned in the Readme as a feature yet to be implemented. The lack of this option is what's keeping me from using denite as the nosplit has become an integral part of my workflow.

I was wondering how high the priority is of implementing this feature, and how difficult it is to implement. I know i can create a new buffer with `enew` but not sure how that ties in with the neovim python api.

**Comment by alexanderjeurissen** [comment]
I know FzF.vim is providing this feature although I just checked and they don't use the neovim python binding (a.i. it's pure vimscript as far as I can tell). they allow the user to set a `g:fzf_layout` variable that can be set to the following:

`let g:fzf_layout = { 'window': 'enew' }`

So basically they are using enew to replace the buffer in a given split with an empty buffer then populate it with fzf content. I'm pretty sure that they remap `<esc>` locally in fzf buffers to act like `C-6` I haven't looked into how they cleanup the fzf buffer afterwards.

I looked through the Denite codebase and this is what I found so far:
There is a method with signature `def _get_direction(self):` in `denite/ui/default.py:193`
This method is called in the `init_buffer(self)` method on line 144 in the same file.
The init_buffer method executes a helper function which is located in `autoload/denite/util.vim:38`

The statement on `denite/ui/default.py:144` looks like this:

```vim
            # Create new buffer
            self._vim.call(
                'denite#util#execute_path',
                'silent keepalt %s new ' % self._get_direction(),
                '[denite]')
```

Can't we use `enew` instead of `new` and leave out the `_get_direction()` call ? I'm pretty sure it's not that easy and that there are additional issues with resuming Denite buffers etc. Just wondering if this is a starting point.

**Comment by alexanderjeurissen** [comment]
So I replaced the earlier mentioned snippet with the following:
```vimscript
            # Create new buffer
            self._vim.call(
                'denite#util#execute_path',
                'silent keepalt enew',
                '[denite]')
```
it throws some warnings about trailing characters, but it does replace the current buffer with Denite, and in my testing Denite works correctly, I can search and the candidates are updated and I can choose a file and Denite opens it.

The `<esc>` key does not work but that can easily be fixed by letting it behave like `<C-6>`

**Comment by Shougo** [comment]
The priority is very low.

It is easy to implement the feature.
But it causes many problems.
Please read the issues in unite.vim.
https://github.com/Shougo/unite.vim/search?q=split&type=Issues&utf8=%E2%9C%93

I have not much time to fix the bugs.
As you know, I am very busy.

My higher priority is deoplete.

**Comment by alexanderjeurissen** [comment]
Thanks for replying @Shougo, I appreciate that I know your a busy men !! and we are all grateful for your contributions to several outstanding vim/neovim plugins 👍 

The reason I created this issue was first of all as a way to think out loud, and start a dialog on what potential blockers might be for getting this implemented. It's good to know where your priorities lie. As I said on Gitter, I'll try to get it working on my own and if I come across things worth sharing I'll do so.

**Comment by Shougo** [comment]
The PR is wellcome.
It should be developed in the another branch.
