### ISSUE TITLE
Match highlight on cursorline uses Search fg but CursorLine bg.

### ISSUE THREAD

**Issue by tmccombs** [Shougo/denite.nvim#218]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

## Environment Information (Required!)

 * denite version(SHA1): f2a1f5c89ca093ca286bfaef9e3d53ecb045390e

 * OS: linux (archlinux)

 * Vim/neovim version:neovim 0.1.7

 * `:CheckHealth` result(neovim only):
```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.0
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]
  - INFO: Host Executable: /home/thayne/.gem/ruby/2.4.0/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.1

## Provide a minimal init.vim with less than 50 lines (Required!)
```

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. `:Deonite colorscheme`
 2. type some text that matches a colorscheme
 3. notice that on the cursor line the matching text has the Search highlight forground but not the background, this makes it unreadable with some themes (for example onedark)

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/2541726/23786533/daa658c2-052a-11e7-8586-0dfec22311b6.png)

**Comment by wsdjeg** [comment]
I think highlight fg instead of bg will be better. I like the hilight feature of ctrlp, or should be abled to config.

**Comment by Shougo** [comment]
`:help denite-highlight-mode`

**Comment by wsdjeg** [comment]
Sorry, my denite is too old.

**Comment by tmsanrinsha** [comment]
I met same problem.
To avoid background color being overrided by cursor backgroud,  I used reverse.
```
hi Search guifg=#000000 guibg=#FFE792 ctermfg=0 ctermbg=222
|
v
hi Search guifg=#FFE792 guibg=#000000 ctermfg=222 ctermbg=0 cterm=reverse gui=reverse
```
