### ISSUE TITLE
Add wikipage on github for external sources similar to deoplete-wikipage

### ISSUE THREAD

**Issue by kiryph** [Shougo/denite.nvim#224]
There is following wikipage on your deoplete repository:

https://github.com/Shougo/deoplete.nvim/wiki/Completion-Sources

What do you think about creating a similar one for denite where people can simply add their external denite sources?

https://github.com/Shougo/denite.nvim/wiki/External-Sources

Github search reveals already many projects, e.g.:

- https://github.com/chemzqm/denite-git
- https://github.com/zyphrus/denite-git.nvim
- https://github.com/pocari/vim-denite-command-history
- https://github.com/Jagua/vim-denite-ghq
- https://github.com/chemzqm/unite-location
- https://github.com/pocari/vim-denite-gists
- https://github.com/JoZie/denite-make
- https://github.com/ozelentok/denite-gtags
- https://github.com/rafi/vim-denite-mpc
- https://github.com/5t111111/denite-rails
- https://github.com/carlitux/denite-cool-grep
- https://github.com/pocari/vim-denite-emoji

I don't know them and their status (maybe very early in their development). However, providing a wikipage as curated list of sources seems to be a good idea.

**Comment by wsdjeg** [comment]
help file will be better.

**Comment by Shougo** [comment]
OK.
I have created it.
