### ISSUE TITLE
Manage/separate buffers

### ISSUE THREAD

**Issue by kreedz** [Shougo/denite.nvim#228]
Is it possible with denite to separate list of buffers?
For example certain buffers are located in one tab and another certain buffers located in second tab.
I found that https://github.com/vim-ctrlspace/vim-ctrlspace plugin can provide it.
Or if denite can't do it with tabs, so can it just somehow group buffers?

I need it when I'm working with several projects.

**Comment by Shougo** [comment]
Unite.vim has the feature(buffer_tab source).
But I don't need the feature in denite.nvim.
I use file_old source instead.

```vim
call denite#custom#source('file_old', 'matchers',
      \ ['matcher_fuzzy', 'matcher_project_files'])
```
