### ISSUE TITLE
interactiveなgrepについて

### ISSUE THREAD

**Issue by baronTommy** [Shougo/denite.nvim#230]
# Problems summary
ドキュメントのEXAMPLESに、interactiveに項目を追加して欲しい
[EXAMPLES](https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt#L105)

## Expected
`pattern_opt`のところが難しいです。
[grep](https://github.com/Shougo/denite.nvim/blob/master/doc/denite.txt#L1128)

## 関連
[issue]https://github.com/Shougo/denite.nvim/issues/150
現状の説明で十分でしたら、もう少し努力して読みます

**Comment by Shougo** [comment]
残念ながら、この issue の意味が分かりません。
ドキュメントの改善は wellcome なので分かりにくいのなら、ぜひ改善してプルリクエストを送ってください。

**Comment by Shougo** [comment]
`pattern_opt` は検索パターンを指定するときに使う引数のことです。
これが -e だったら、-e 検索パターンというコマンドラインになります。

**Comment by baronTommy** [comment]
ありがとうございます
