### ISSUE TITLE
:Denite grep is very slow

### ISSUE THREAD

**Issue by jinleileiking** [Shougo/denite.nvim#232]
use the recommend setting:
```
164 ▸       " Ag command on grep source¬
   165 ▸       call denite#custom#var('grep', 'command', ['ag'])¬
   166 ▸       call denite#custom#var('grep', 'default_opts',¬
   167 ▸       ▸       ▸       \ ['-i', '--vimgrep'])¬
   168 ▸       call denite#custom#var('grep', 'recursive_opts', [])¬
   169 ▸       call denite#custom#var('grep', 'pattern_opt', [])¬
   170 ▸       call denite#custom#var('grep', 'separator', ['--'])¬
   171 ▸       call denite#custom#var('grep', 'final_opts', [])¬
```

type `:Denite grep` is very slow for finding

**Comment by Shougo** [comment]
This is well known problem.

**Comment by jinleileiking** [comment]
vim8 supports thread, can we use this feature ?

**Comment by Shougo** [comment]
> vim8 supports thread, can we use this feature ?

Vim8 supports *multiple processes*.
It is not multiple *threads*.

I can implement the feature.  Because, Python supports threads.
But it is difficult.

**Comment by chemzqm** [comment]
The grep could be very slow for big project, and unlike vim grep, you can't terminal the process by using `<C-c>`, which is unfortunately.

**Comment by BonarBeavis** [comment]
I use ripgrep and it is quite fast. The number of files with ripgrep are not limited by search time, but by the number of hits denite can handle. This is on a 5 years old laptop with SSD.

**Comment by jinleileiking** [comment]
I use fzf instead :)

**Comment by Shougo** [comment]
@jinleileiking I have fixed the problem in the latest version of denite.
Please test it.

Note: The modern grep command like ripgrep uses multi-process feature.
I have tested ripgrep, it uses 4 processes.
It is very heavy work in the dual core-CPUs.
If denite grep is slow, your CPU is slow.

**Comment by ledhed2222** [comment]
thanks @Shougo - do you now recommend `ripgrep` instead of `ag` as the grep tool? Thanks!

**Comment by Shougo** [comment]
It depends on your machine spec.

**Comment by theduke** [comment]
@Shougo could you provide a sample config for ripgrep?

That would be very useful

**Comment by Shougo** [comment]
```
  call denite#custom#var('file_rec', 'command',
        \ ['rg', '--files', '--glob', '!.git'])
  call denite#custom#var('grep', 'command', ['rg', '--threads', '1'])
  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'final_opts', [])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'default_opts',
        \ ['--vimgrep', '--no-heading'])
```

**Comment by theduke** [comment]
Oh, I just saw the docs already contain a ripgrep example, but thanks!
