### ISSUE TITLE
Flickering screen when closing a Denite buffers

### ISSUE THREAD

**Issue by AlexMasterov** [Shougo/denite.nvim#234]
4f83579 (Fix redraw problem) = Flicker workflow.

**Comment by Shougo** [comment]
OK.  I will fix it.

**Comment by AlexMasterov** [comment]
@Shougo now after closing the buffer, I have to press `<CR>` to continue:
> Press ENTER or type command to continue

**Comment by Shougo** [comment]
I have fixed the problem.

**Comment by AlexMasterov** [comment]
@Shougo thank you!

**Comment by MageJohn** [comment]
Hey! You said you had fixed the flicker problem, however I'm on the latest commit (7346b358f54f49ead93ce2dc09367b7c3c97df4d) and it's still flickering for me. This is what it looks like:

![peek 2018-02-20 00-04](https://user-images.githubusercontent.com/3520558/36401798-c2b8dc40-15d1-11e8-970f-1f2c7d199494.gif)

There is a flicker when Denite is used to switch the buffer, but no flicker when nvim's internal command is used.

**Comment by Shougo** [comment]
@MageJohn Have you read the issue template?
Please create the new issue for it.
I cannot reproduce the problem.

**Comment by MageJohn** [comment]
@Shougo sorry about that. I've been trying to reproduce this with a clean init.vim, unsuccessfully. Now it's gone from the full config, too. If it happens again, I'll figure out the problem and write a proper issue.

**Comment by Shougo** [comment]
OK.
