### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by mkomitee** [Shougo/denite.nvim#237]
It would be awesome if there was a variant of the Denite command which combined DeniteBufferDir and DeniteProjectDir to allow you to find a file rooted in the project directory for the buffer you have open.

Effectively, something where `context.path` was `denite#util#path2project_directory(fnamemodify(bufname('%'), ':p:h'))`.

**Comment by chemzqm** [comment]
That's what the project source of denite-extra did: https://github.com/chemzqm/denite-extra/blob/master/rplugin/python3/denite/source/project.py
User could set variable: `g:project_folders` to a list of project folders.

**Comment by Shougo** [comment]
Implemented.
Please change context `path` in DeniteProjectDir.

**Comment by mkomitee** [comment]
Thanks

On Apr 9, 2017, at 11:24 AM, Shougo <notifications@github.com> wrote:

Implemented.
Please change context path in DeniteProjectDir.

**Comment by mkomitee** [comment]
... actually, do you have an example of this? I'd like to make the context.path variable based on the buffer file, and I can't figure out how to do that without having to define my own function so I can concatenate strings and call execute:

e.g.:

    function MyFunction()
        let l:ctxpath=fnamemodify(bufname('%'), ':p:h')
        execute ":DeniteProjectDir ... -path=" . l:ctxpath
    endfunction

**Comment by Shougo** [comment]
<pre>
DeniteProjectDir ... -path=`fnamemodify(bufname('%'), ':p:h')`
</pre>
