### ISSUE TITLE
Feature request: bookmark source

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#239]
Unite has a bookmark source that integrates with vimfiler. Any plans to add a bookmark source that integrates with defx? Thank you

**Comment by Shougo** [comment]
I have the plan.
But defx is not implemented yet.

**Comment by hackrole** [comment]
I have the same Feature request.

**Comment by Shougo** [comment]
defx development is needed before that.

**Comment by amikai** [comment]
I misunderstand this issue. My implementation is to list built-in bookmark.
I will change the commit.

**Comment by Shougo** [comment]
https://github.com/kmnk/denite-dirmark is available.
