### ISSUE TITLE
Feature request: limit number of results

### ISSUE THREAD

**Issue by baopham** [Shougo/denite.nvim#251]
It would be great if I could set the limit of the results. I don't really need to see the whole list at once. I'm using Ag but it doesn't have that option...

**Comment by Shougo** [comment]
Why this feature is needed?
I don't think it is useful.
This feature is useful for unite.vim.
But denite.nvim is not.

**Comment by Shougo** [comment]
I think it just confusing the users.

You can test the feature in grep source in unite.vim.
