### ISSUE TITLE
Different versions of file_rec?

### ISSUE THREAD

**Issue by 0phoff** [Shougo/denite.nvim#258]
# Problems summary
Is there a way to duplicate the file_rec source, so I can customize both versions differently?

## Expected
I want to be able to have 2 versions of file_rec, one with the -u (dont use .ignore files) flag and one without:
```
call denite#custom#var('file_rec', 'command', ['ag', '--follow', '--nocolor', '--nogroup',  '-g', ''])
call denite#custom#var('file_rec_copy', 'command', ['ag', '-r', '--follow', '--nocolor', '--nogroup', '-u', '-g', ''])
```

## Environment Information (Required!)

 * denite version(SHA1):
Plug says I am on the last version (commit 807c952)
 * OS:
Arch Linux
 * Vim/neovim version:
Nvim 0.1.7
 * `:CheckHealth` result(neovim only):
everything installed except rubygem

## Provide a minimal init.vim with less than 50 lines (Required!)
Everything is working fine, I just want an extra feature (or dont know how to achieve this, if it already exists)

**Comment by Shougo** [comment]
You can do it.
Example:

```vim
call denite#custom#alias('source', 'file_rec/git', 'file_rec')
call denite#custom#var('file_rec/git', 'command',
      \ ['git', 'ls-files', '-co', '--exclude-standard'])
```
