### ISSUE TITLE
RFC: Ctrl+n/Ctrl+p or Up/Down keys conflict with command-line history behaviour

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/denite.nvim#26]
I'm wondering to improve the denite.nvim prompt by coping a corresponding codes from [prompt.nvim](https://github.com/lambdalisue/prompt.nvim) (To be honest, I would like to *rely* rather than *copy* while prompt.nvim is under development but I thought you feel *copy* is better because of #23).

Once prompt.nvim is forked into denite.nvim, the denite.nvim prompt would have the following features

- Caret movement by `<Left>` and  `<Right>`
- Delete character before/under the caret (e.g. `<Backspace>` / `<Delete>`)
- Paste text from register after the caret (e.g. `<C-r>+`)
- Use a candidate of command-line history (e.g. **`<C-p>`**)
- Use a matched candidate of command-line history (e.g. **`<Up>`**)
- **Custom key mappings** (e.g. Use `<C-f>` to move the caret left)

However, currently denite.nvim uses `<C-n>/<C-p>` or `<Up>/<Down>` to select candidate.
This behaviour conflicts with Vim's default command-line behaviour :-(

So I would like to propose to change the default mapping for selecting candidate to `<C-t>/<C-g>` like Vim's incsearch behaviour ([doc](https://github.com/vim/vim/blob/2ec618c9feac4573b154510236ad8121c77d0eca/runtime/doc/cmdline.txt#L435-L446)).
As long as users can custom mappings, I feel that default mappings should follow Vim flavour.
What do you think about this?

### Example

You can custom key mappings by something like

```vim
let g:prompt#custom_mapping = [
      \ ["<C-D>", "<Del>"],
      \ ["<C-A>", "<Home>"],
      \ ["<C-E>", "<End>"],
      \ ["<C-F>", "<Left>"],
      \ ["<C-B>", "<Right>"],
      \ ["<C-P>", "<C-T>", 1],  " 1 means 'noremap'
      \ ["<C-N>", "<C-G>", 1],
      \]
```

**Comment by Shougo** [comment]
I have changed the default mappings.

**Comment by lambdalisue** [comment]
Thanks a lot :-)
