### ISSUE TITLE
guicursor lost after closing denite window

### ISSUE THREAD

**Issue by yamahigashi** [Shougo/denite.nvim#260]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

`guicursor` will not be restored correctly after closing the denite window when setting `guicursor` options (blinkon, blinkwait..etc)  but `block` is not set. (looks like `set guicursor=a:block-none`)

## Expected

Restore guicursor options to default when options are not fully supplyed.

## Environment Information (Required!)

 * denite version(SHA1):
 e5b58f005ea8216744953f2c20db3e03981bba94

 * OS:
 MS-Windows10 64bit

 * Vim/neovim version:
gvim.exe 8.0 1-134

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

 * ng
 ```ng.vim
set runtimepath+=~/path/to/denite.nvim/
set guicursor=a:blinkon0
```

 * ok 1
 ```ok1.vim
set runtimepath+=~/path/to/denite.nvim/
set guicursor=a:block-Cursor
set guicursor+=a:blinkon0
```

 * ok 2
 ```ok2.vim
set runtimepath+=~/path/to/denite.nvim/
" guicursor not set
" set guicursor=a:block-Cursor
" set guicursor+=a:blinkon0
```

## The reproduce ways from neovim starting (Required!)

 1. open denite window. (`:Denite buffer`)
 2. close denite window. (`q`)
 3. guicursor disappear(like `set guicursor:a:block-none`)

**Comment by Shougo** [comment]
I will check it.

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
guicursor feature seems broken.

You can test it.

```vim
set guicursor=a:blinkon0
set guicursor=n-v-c:hl-None
set guicursor=a:blinkon0
```

`set guicursor&` fixes the behavior though...

**Comment by Shougo** [comment]
I have created the issue.
https://github.com/vim/vim/issues/1657

**Comment by Shougo** [comment]
It is not bug.  This is GVim feature.  I will fix it later.

**Comment by AlexMasterov** [comment]
**btw.**
The cursor appears after using the EasyMotion bindings like `<Plug>(easymotion-s)` ([EasyMotion#S](https://github.com/easymotion/vim-easymotion/blob/1ca831d29dd52dc37a8e220dbff45e8f49b55fd9/autoload/EasyMotion.vim#L143])).

**Comment by Shougo** [comment]
Fixed.
