### ISSUE TITLE
Extremely long matching lines hang grep source

### ISSUE THREAD

**Issue by dmfay** [Shougo/denite.nvim#263]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

Using grep to search a string matched by an extremely long line (on the order of thousands of characters) can cause denite to peg a cpu at 100% and hang neovim. Examining `top` shows that it's python causing the problem so the choice of grep program shouldn't matter. `kill -9`ing the python process stops it from hanging, but neovim must be restarted in order to continue using denite.

I've tried to reproduce the problem by searching a generated file along the lines of 'aaaaaaaaaaaaaaaaa(...30000 more...)aaaaastring' for 'string', and denite has not exhibited the problem behavior. However, I have noticed every time it _does_ hang, grepping for the search string from the terminal shows a match in a large minified JavaScript file. I suspect it might have something to do with processing individual matches with regular expressions, but that's just a guess.

## Expected

denite grep should not hang when very long lines are matched.

## Environment Information (Required!)

 * denite version(SHA1): fd1288d206145ec916995d78c0885387cbb12d69

 * OS: Arch Linux (I have also seen it on OSX)

 * Vim/neovim version:

```
NVIM 0.1.7
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui  
```

 * `:CheckHealth` result(neovim only):

```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - WARNING: "denite.nvim" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: Using: g:python_host_prog = "/usr/bin/python2"
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
  - INFO: Host Executable: /home/dian/.gem/ruby/2.4.0/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.3
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/

if !empty(glob('/usr/bin/python2'))
  let g:python_host_prog = '/usr/bin/python2'
elseif !empty(glob('/usr/local/bin/python'))
  let g:python_host_prog = '/usr/local/bin/python'
endif

call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'default_opts', ['--vimgrep', '--no-heading', '--ignore-case'])
```

## The reproduce ways from neovim starting (Required!)

 1. Download a large minified JavaScript file ([jQuery](https://code.jquery.com/jquery-3.2.1.min.js) is a good one)
 2. `:Denite grep`
 3. Search for the string `jquery` or another string appearing in the file

## Upload the log file

I don't know where it logs; if you can tell me where to look, I'll supply the output.

**Comment by Shougo** [comment]
It is bug in matcher_ignore_globs.
