### ISSUE TITLE
find command gives different output in shell and in Denite

### ISSUE THREAD

**Issue by purpleP** [Shougo/denite.nvim#268]
I'm trying to exclude hidden folders in Denite.

Suppose I have a following directory structure.
```
.
├── .other
│   └── some.txt
├── some
│   └── .some
│       └── some.txt
├── somerc -> /home/michael/vimconf/vimrc
└── temp.py

3 directories, 4 files
```
`find -L . -type d -path "*/.*" -prune -o -type f -print -type l -print` would find exactly what I need.

But this isn't
```
let cmd = 'find -L :directory -type d -path "*/.*" -prune -o -type f -print -type l -print'
call denite#custom#var('file_rec', 'command', split(cmd))
```
This will print files in hidden directories.

And I actually found the culprit I believe. If I would remove `""` from command it works. Seems like you doing something wrong with quotes when passing command to a shell.

I've checked with latest master branch. The issue is there.

**Comment by Shougo** [comment]
I don't know why.
I will test it.

**Comment by Shougo** [comment]
I get it.
The quoting is not expanded by shell in denite.
Please study quoting behavior.


```vim
let cmd = ['find', '-L', ':directory', '-type', 'd', '-path', '*/.*', '-prune', '-o', '-type', 'f', '-print', '-type', 'l', '-print]'
```
