### ISSUE TITLE
Improve tag:include output

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#269]
Is it possible to improve tag:include ouput? With Unite we have:
![screen shot 2017-05-03 at 13 22 21](https://cloud.githubusercontent.com/assets/2583971/25670596/9c17eeb4-3003-11e7-9c56-0f9bbb321417.png)

But with denite:
![screen shot 2017-05-03 at 13 22 33](https://cloud.githubusercontent.com/assets/2583971/25670606/a4e6a7ec-3003-11e7-8572-e233bcab97d0.png)

**Comment by Shougo** [comment]
You can improve that!
It is not so hard.
Pull request is wellcome.

**Comment by petobens** [comment]
I would like to help but I don't know where to begin with...

**Comment by Shougo** [comment]
Here:
https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/source/tag.py#L35

And highlight examples:
https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/source/buffer.py#L12
https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/source/buffer.py#L41

**Comment by petobens** [comment]
Thanks, I will give it a shot once I find the time...

**Comment by petobens** [comment]
The highlighting of the output source should also be improved...

![jul-22-2017 11-53-05](https://user-images.githubusercontent.com/2583971/28492169-5c2aa700-6ed4-11e7-81fb-332638704dc1.gif)

**Comment by Shougo** [comment]
You can improve it!

**Comment by Shougo** [comment]
OK.  I have tested your code.
Please fix your `TAG_HIGHLIGHT_SYNTAX`.
I will wait the PR.

```python
TAG_HIGHLIGHT_SYNTAX = [
    {'name': 'tag', 'link': 'Constant', 're': r'\S\+\ze\s\['},
    {'name': 'kind', 'link': 'Type', 're': r'\s\[\w\]'},
]```

Note:  The regex must be Vim script regex.

**Comment by petobens** [comment]
Ok. Will look into it once I find some spare time. Thanks!
