### ISSUE TITLE
use <esc> or q can't exit denite buf return to the last file 

### ISSUE THREAD

**Issue by fcying** [Shougo/denite.nvim#271]
# Problems summary
when I use `esc` or `q` to exit the denite, it can't return to the last file.

==============================================
I found the cause, my test folder have a `t` folder, when I rename or delete it, denite will work right.
I test in other folder, when I create a new folder name `t`, then denite will work error. 

## Expected
exit the denite return to the last edit file

## Environment Information (Required!)

 * denite version(SHA1): 99f94a9b010e2225f899bd52ac9f0ae80fe668dd

 * OS: win10 

 * Vim/neovim version: vim8 MS-Windows 64-bit GUI version Included patches: 1-596

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible

let g:config_dir=$VIM
let g:plugin_dir = g:config_dir . '/plugged'
let g:plugin_manager_dir = g:plugin_dir . '/dein.vim'
exec 'set runtimepath+=' . g:plugin_manager_dir

if dein#load_state(expand(g:plugin_dir))
  call dein#begin(expand(g:plugin_dir))
  call dein#add(expand(g:plugin_manager_dir))
  call dein#add('Shougo/vimproc.vim', {'build' : 'Tools\update-dll-mingw.bat'})
  call dein#add('Shougo/denite.nvim')
  call dein#end()
  call dein#save_state()
endif

filetype plugin indent on
syntax enable


nnoremap <silent> ff :<C-u>Denite file_rec<CR>
```

## The reproduce ways from neovim starting (Required!)

 1. vim test.c
 2. type `ff`
 3. type `esc`  or type `c-o, q`
 4. can't see the test.c file

## Screen shot (if possible)
vim test.c
![1](https://cloud.githubusercontent.com/assets/106934/25781247/c6873c7c-3369-11e7-8c99-1d8044fc3024.jpg)
type `ff`
![2](https://cloud.githubusercontent.com/assets/106934/25781248/c68a75f4-3369-11e7-844a-d53ce1eef2e3.jpg)
type `esc`
![3](https://cloud.githubusercontent.com/assets/106934/25781246/c686f816-3369-11e7-8b08-51d1aecb8801.jpg)
[testvim.zip](https://github.com/Shougo/denite.nvim/files/981602/testvim.zip)

## Upload the log file
messages has nothing.

**Comment by Shougo** [comment]
I have created `t` directory and tested it, but I cannot reproduce the behavior.

**Comment by Shougo** [comment]
I have tested the below vimrc.

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/denite.nvim

filetype plugin indent on
syntax enable


nnoremap <silent> ff :<C-u>Denite file_rec<CR>
```

**Comment by fcying** [comment]
only reproduce  in windows..

I test in ubuntu, it work right.

**Comment by Shougo** [comment]
Oh....
It is hard to fix.

Please check the code.

https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/ui/default.py#L466

**Comment by AlexMasterov** [comment]
@Shougo Interesting behavior when opening `testvim` folder via `:Denite file_rec` command.

**Magic folder** (testvim)

![Magic folder](http://i.imgur.com/oJi4TZq.png)

**Normal folder** (dein.vim)

![Normal folder](http://i.imgur.com/J4V5oy2.png)

**Comment by Shougo** [comment]
Wow!  The initial window is already closed.
I don't know why...

**Comment by Shougo** [comment]
This is reproduced on the latest Vim and denite?

**Comment by Shougo** [comment]
No response.

**Comment by fcying** [comment]
It can be reproduced  on the Vim 8.0.728 and the latest denite in windows 10x64.

**Comment by Shougo** [comment]
@fcying It seems Vim related problem.
It can be reproduced in neovim?

**Comment by Shougo** [comment]
And you can debug it.
Denite uses `quit_buffer()` function to quit the buffer.

**Comment by fcying** [comment]
It can be reproduced in neovim, If I use the folder 't', it make error. 
NVIM v0.2.1-578-g07972f9e5
reproduced way:
cd D:\tool\testvim
d:\tool\Neovim\bin\nvim-qt
ff
![1](https://user-images.githubusercontent.com/106934/28419218-e935dc22-6d90-11e7-8691-c29c5402cfd2.png)


I have not used python....I'll try on the weekend.

**Comment by Shougo** [comment]
It seems the another problem.
Because it is not when quit.

**Comment by Shougo** [comment]
Why nomodifiable is set?  
Please check the denite buffer.
It seems open wrong buffer.

**Comment by Shougo** [comment]
Please check `:silent keepalt new botright [denite]` behavior from the command line.
I think it is broken.

**Comment by Shougo** [comment]
Oh, I get it. `[denite]` is used as wildcard in Windows.

**Comment by Shougo** [comment]
I will fix the problem.

**Comment by fcying** [comment]
I update the latest version. 
nvim work fine now.
vim make a lot of error.

![1](https://user-images.githubusercontent.com/106934/28493151-0979df6a-6f44-11e7-8b48-bb4524a30c56.png)

**Comment by Shougo** [comment]
@fcying I have fixed the errors.

**Comment by fcying** [comment]
Now everything is working fine~
