### ISSUE TITLE
denite outline can't jump to the function which use a pointer argument

### ISSUE THREAD

**Issue by fcying** [Shougo/denite.nvim#273]
# Problems summary
denite outline can't jump to the function which use a pointer argument

## Expected
jump to the select func.

## Environment Information (Required!)

 * denite version(SHA1): 99f94a9b010e2225f899bd52ac9f0ae80fe668dd

 * OS:ubuntu

 * Vim/neovim version:vim8-596

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible
set guioptions=

set runtimepath+=~/.vim/plugged/denite.nvim
set runtimepath+=~/.vim/plugged/unite-outline    "Shougo/unite-outline

filetype plugin indent on
syntax enable

nnoremap <silent> fo :Denite outline<CR>
```

## The reproduce ways from neovim starting (Required!)

 1. vim t.c
 2. fo
 3. b\<CR\>
 4. not jump to the func b

## test file
[t.zip](https://github.com/Shougo/denite.nvim/files/989972/t.zip)

I test the same way in unite, it work ok.

**Comment by Shougo** [comment]
Reproduced.
