### ISSUE TITLE
<CR> can not open file

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/denite.nvim#274]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I use denite as default file finder , but when only one result in denite buffer, press enter can not open file, but need to press enter twice, BTW the file is opened as read only.

It happened in both vim and neovim

here is a video:

https://asciinema.org/a/5w8svcukt4dx8g3eodpv3udkr

## Environment Information (Required!)

 * denite version(SHA1): master

 * OS: arch

 * Vim/neovim version: vim8 && neovim master

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/

```

## The reproduce ways from neovim starting (Required!)

 please checkout that vedio.

**Comment by Shougo** [comment]
Have you read the issue template?
Your vimrc in the video is different from the minimal init.vim.
I cannot test it!

**Comment by Shougo** [comment]
> I use denite as default file finder , but when only one result in denite buffer, press enter can not open file, but need to press enter twice, BTW the file is opened as read only.

Please create the reproduce ways

**Comment by Shougo** [comment]
> I use denite as default file finder , but when only one result in denite buffer, press enter can not open file, but need to press enter twice, BTW the file is opened as read only.

You should check `:messages` result.

**Comment by wsdjeg** [comment]
Nothing in :message, I will add minivimrc And reproduce ways. sorry.

**Comment by Shougo** [comment]
OK.

**Comment by aeruder** [comment]
Steps to reproduce

* Open a file in vim
* Open another instance of vim
* Select the same file that is already open in denite and press enter
* Doesn't do anything - I suspect it is an invisible prompt for how to handle opening the file
* Press enter again, file open read-only

**Comment by Shougo** [comment]
@aeruder I cannot reproduce it with minimal config.
The swap file warnings are visible.
It depends on your configuration.

**Comment by Shougo** [comment]
@wsdjeg Ping

**Comment by wsdjeg** [comment]
hmm, I can not reproduce it now, I am not sure, so closs it, if I get this issue again , I will try to find the mini vimrc.

**Comment by Shougo** [comment]
OK
