### ISSUE TITLE
Many problems with tags source

### ISSUE THREAD

**Issue by frioux** [Shougo/denite.nvim#287]
Mostly I just wanted to get a 👍 before I did the effort of making a pull request to fix this.  Let me know if you are willing to take a corrected tag implementation.  If not I'll just make my own.

# Problems summary

The tags source assumes more about the ctags format than it should.

## Expected

``` vim
:Denite tags
```

should work with, for example:

```
foo	bar.txt	Baz
```

To be clear, *only* the first three fields are required, and the third one could be a line, a search, *or any other ex command.*  (See `:h tags-file-format`)

## Environment Information (Required!)

 * denite version(SHA1): e8a0b3f88831

 * OS: Ubuntu 17.04

 * Vim/neovim version: Vim 8.0.94

**Comment by Shougo** [comment]
Please upload the testing tag file.
We have not ESP skills.

**Comment by Shougo** [comment]
OK.  I get it.
I will fix it.

**Comment by Shougo** [comment]
> To be clear, only the first three fields are required, and the third one could be a line, a search, or any other ex command. (See :h tags-file-format)

I will fix the three fields error.  But the third one must be a line or a search in Posix.
I don't want to support other ex commands.

```
 {tagaddress}	The Ex command that positions the cursor on the tag.  It can
		be any Ex command, although restrictions apply (see
		|tag-security|).  Posix only allows line numbers and search
		commands, which are mostly used.
```

**Comment by Shougo** [comment]
> The tags source assumes more about the ctags format than it should.

I know.  What is the *many* problems?
Please describe that.

**Comment by frioux** [comment]
Ok you got two, the third it filters out blank values. If I remember
another I'll let you know but those three were what I had in mind.

--

**Comment by Shougo** [comment]
> Ok you got two, the third it filters out blank values. 

Please describe it more clearly.

**Comment by frioux** [comment]
``` python
elem = [e for e in line.split("\t") if e != '']
```

should just be

``` python
elem = line.split("\t")
```

By the way, regarding the Ex commands; why do you need to support them at all?  Can't you just call the ex command in question?  (just curious.)

**Comment by Shougo** [comment]
> By the way, regarding the Ex commands; why do you need to support them at all? Can't you just call the ex command in question? (just curious.)

It is the security reason.

**Comment by frioux** [comment]
Oh here's the last problem (I hope:) the list doesn't show the actual file the
tag is from.  So if you had a bunch of the same tags (think classes that all
have methods of the same name) the list is not super helpful.  Here's a (real)
example:

```
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
addText [s]
```

**Comment by Shougo** [comment]
OK.  I will fix it.
