### ISSUE TITLE
Ag grep doesn't ignore directories in .agignore

### ISSUE THREAD

**Issue by monrcelik** [Shougo/denite.nvim#289]
# Problems summary
Denite grep with ag doesn't directories and files in .agignore and .gitignore.

## Expected

`:Denite grep`

shouldn't search directories in .agignore and .gitignore.

## Environment Information (Required!)

 * denite version(SHA1): e8a0b3f88831c6f26566e2de2412a3ec3d4f128b

 * OS: Fedora 25

 * Vim/neovim version: NVIM v0.2.0

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Denite:
call denite#custom#var('file_rec', 'command',
   \ ['ag', '--follow', '--nocolor', '--nogroup', '-g', ''])

call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts',
   \ ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
```

## The reproduce ways from neovim starting (Required!)

 1. `:Denite grep`
 2. `Pattern: foo`

**Comment by Shougo** [comment]
I cannot reproduce the problem.
It works.
