### ISSUE TITLE
Highlight matches only when manually previewing

### ISSUE THREAD

**Issue by rafi** [Shougo/denite.nvim#292]
With Unite I could have the default `no-auto-preview`, and set `auto_highlight` and only when I click 'p' for `<Plug>(unite_smart_preview)`, I can see the preview+highlight, but it _doesn't_ automatically open the preview when I move around candidates in the window.

Will it be possible for Denite to highlight matches _without_ automatically opening preview?
For example:
1) `Denite -auto-highlight -no-auto-preview grep`
2) Move in Denite window
3) Click 'p' for `<denite:do_action:preview>`
4) Expect to see preview+highlight
5) Expect to _not_ automatically preview when moving in Denite window

Currently Denite automatically opens preview if `-auto-highlight` is set, it disregards `-no-auto-preview`.

**Comment by Shougo** [comment]
Implemented.

**Comment by rafi** [comment]
Excellent, works great. Thanks
