### ISSUE TITLE
WinEnter does not work when close denite buffer

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/denite.nvim#294]
here is minivimrc
```vim
set rtp+=~/.cache/vimfiles/repos/github.com/Shougo/denite.nvim
scriptencoding utf-8
" load api


" denite option
let s:denite_options = {
      \ 'default' : {
      \ 'winheight' : 15,
      \ 'mode' : 'insert',
      \ 'quit' : 'true',
      \ 'highlight_matched_char' : 'MoreMsg',
      \ 'highlight_matched_range' : 'MoreMsg',
      \ 'direction': 'rightbelow',
      \ 'statusline' : 0,
      \ 'prompt' : '➭',
      \ }}

function! s:profile(opts) abort
  for fname in keys(a:opts)
    for dopt in keys(a:opts[fname])
      call denite#custom#option(fname, dopt, a:opts[fname][dopt])
    endfor
  endfor
endfunction

call s:profile(s:denite_options)

let s:normal_mode_mappings = [
      \   ['q', '<denite:quit>', 'noremap'],
      \ ]

for s:m in s:normal_mode_mappings
  call denite#custom#map('normal', s:m[0], s:m[1], s:m[2])
endfor
nnoremap <silent> <C-p> :Denite file_rec<CR>
function! test#st(...) abort
  if a:0 > 0
    return 'none active window'
  endif
  return 'active window'
endfunction
augroup test
  au!
  autocmd BufWinEnter,WinEnter,FileType
        \ * let &l:statusline=test#st()
  autocmd BufWinLeave,WinLeave * let &l:statusline=test#st(1)
augroup END

" vim:set et sw=2 cc=80:
```

reproduce step:
1. `vim -u test.vim test.vim`, then you will see `active window` in the statusline
2. `<c-p>` to open denite, `<esc>` close denite buffer, then in your vim should has only one window, but the statusline is `none-active wimdow`.

**Comment by Shougo** [comment]
You can reproduce it by `:bdelete` without denite.nvim.

**Comment by Shougo** [comment]
It seems `:bdelete` problem.
`WinEnter` is triggered properly.
But `statusline` is overwritten after `:bdelete`.

**Comment by wsdjeg** [comment]
@Shougo so can you use `:quit` for denite buffer?  I think it is same as `:bd` when `bufhidden=wipe`

**Comment by Shougo** [comment]
Yes, I will use it.

**Comment by wsdjeg** [comment]
@Shougo this issue is fixed, thanks. as unite development is done, but it is not deprecated, I still need to use unite for many other feature. but in unite, it use `noautocmd` to open unite buffer, so the statusline can not be updated via WinEnter and WinLeave.

**Comment by Shougo** [comment]
I think `doautocmd` is executed.

Please see `unite#view#_switch_unite_buffer()`.

**Comment by Shougo** [comment]
Note:  I don't want to support unite.vim.  Because it is already broken.
It is very hard to fix bugs for me.

**Comment by wsdjeg** [comment]
I see, but no WinLeave is send, I will try to fix it.

**Comment by wsdjeg** [comment]
I have fix it, I want to send a PR.

**Comment by Shougo** [comment]
OK

**Comment by wsdjeg** [comment]
hmm, It has been fixed by your commit. :)

**Comment by Shougo** [comment]
So, I should revert your commit?

**Comment by wsdjeg** [comment]
Yeah. but need more test. I will test it tonight.

**Comment by Shougo** [comment]
OK
