### ISSUE TITLE
I would like to help

### ISSUE THREAD

**Issue by theamazingfedex** [Shougo/denite.nvim#3]
I have been following you and your vim plugin development for some time, and I would like to help with this next project in any way that I can. Please let me know if there is anything I can do in the development or testing of this plugin.

**Comment by wsdjeg** [comment]
I think the best way to help shougo is create a project such as `Shougo-s-plugin`,show more about why use Shougo's plugin ,and how to config to let vim works better，and I think it is time for create a organization for Dark Powered vimmer

**Comment by Shougo** [comment]
Thank you.  I have not much time to develop it currently.
Because, I need fix/support for other plugins.
Can you support for me?

**Comment by theamazingfedex** [comment]
I can do my best to provide support for your plugins. I am on github often and can reply to issues regularly. What would you like for me to do?

**Comment by Shougo** [comment]
OK.  For example, the issue.
https://github.com/zchee/deoplete-jedi/issues/13

I cannot reproduce it.

**Comment by tony** [comment]
Help is great.

But as for reproducing bugs. I mean this python-client stuff is driving me nuts.  How do you begin to debug stuff like this?

Do you think python-client gets in the way?  Do you have any ideas for how neovim could help debugging. Why does plugins for neovim have to be so hard, when other IDE's do it easy?

Sublime 3 uses python 3 and there's no need to worry about messaging. Plugins just work.

https://www.sublimetext.com/docs/3/api_reference.html

**Comment by Shougo** [comment]
> But as for reproducing bugs. I mean this python-client stuff is driving me nuts. How do you begin to debug stuff like this?

It may be harder.  But I think it is same in external interface plugins in Vim.
For example, YouCompleteMe.

> Sublime 3 uses python 3 and there's no need to worry about messaging. Plugins just work.

You can do it.  I think current neovim development team has not the power to support it.

**Comment by bfredl** [comment]
debugging ability was improved slightly with python-client#169 (specifically for async handlers) but there still are quite a few gotchas that make plugin development harder that it should be. Most importantly documentation (well it exists, but spread out and hard to find). I hope to improve `README.md` the coming days.

**Comment by Shougo** [comment]
You can test denite.nvim.
The customization feature is not implemented though.

My easy test:

home directory 137042 files

`:Denite file_rec`: 0.7902[s] (The initialization until user input time)
`unite.vim`: N/A(freeze UI)
`CtrlP`: Almost 5~6[s]
`fzf`: Almost same time with `:Denite`

**Comment by balta2ar** [comment]
I can't wait to switch to asynchronous denite! From unite I mostly use buffers, file_rec/async, tags and grep sources. Lately, however, I'm using fzf `:Files` since unite is much slower.

@Shougo Besides the functionality, one thing that I wish would be there in denite is testing. Being a big fan of unite and using master branch on a daily basis, what often discouraged me from using the latest commit is that things occasionally get broken. I witnessed numerous issues about broken grep source. Fortunately, Shougo is exceptionally quick and good at fixing them. I do not mean to tell you how to write software (you are true master of vim and plugins for it), but maybe more efforts could be put into thoroughly testing denite? Of course this will inevitably slow down the development speed, but at the same time it will increase stability for end users. Just my humble thoughts.

**Comment by carlitux** [comment]
@Shougo I just tested and denite printed this:

[denite] candidates len = 25022
[denite] 1.6065280437469482

On second call:

[denite] candidates len = 25022
[denite] 0.3120131492614746

BTW.- I am loving the new UX.

**Comment by Shougo** [comment]
Oh, thanks.
Because my SSD speed is faster.

> BTW.- I am loving the new UX.

:-)
It will be more better than unite.

**Comment by Shougo** [comment]
> @Shougo Besides the functionality, one thing that I wish would be there in denite is testing. Being a big fan of unite and using master branch on a daily basis, what often discouraged me from using the latest commit is that things occasionally get broken. I witnessed numerous issues about broken grep source. Fortunately, Shougo is exceptionally quick and good at fixing them. I do not mean to tell you how to write software (you are true master of vim and plugins for it), but maybe more efforts could be put into thoroughly testing denite? Of course this will inevitably slow down the development speed, but at the same time it will increase stability for end users. Just my humble thoughts.

Yes, I know the reason.
It is hard to change the development model.
The faster development is important for me.

**Comment by carlitux** [comment]
Yes. I think so, too.

Would be good if you shared how is planned some UX to do and we can start coding some sources.

**Comment by Shougo** [comment]
The specification is not fixed...
