### ISSUE TITLE
:DeniteLast command is needed

### ISSUE THREAD

**Issue by wilywampa** [Shougo/denite.nvim#305]
It would be nice to have `:DeniteFirst` and `:DeniteLast` commands. Also, the documentation for using resume to act like `DeniteNext/Last` should be updated to use `-cursor-pos` instead of `-select` if the latter is deprecated.

**Comment by Shougo** [comment]
`:DeniteLast` is missing.
`:DeniteFirst` is `:Denite -cursor-pos=0`.

**Comment by wilywampa** [comment]
> `:DeniteFirst` is `:Denite -cursor-pos=0`.

But the cursor position is relative to the window, not an absolute candidate, so that only works if the denite window hasn't been scrolled down.

**Comment by Shougo** [comment]
> But the cursor position is relative to the window, not an absolute candidate, so that only works if the denite window hasn't been scrolled down.

I don't understand.  Please upload the example.

**Comment by wilywampa** [comment]
https://asciinema.org/a/7t68wcjJ797dqWNhC6SSLQs3N

First I open denite, then close it, then run the `-cursor-pos=0` command and it works as expected taking me to the first candidate (-std=gnu++0x.d). Then I open denite again and scroll down a few times, exit denite, and run the `cursor-pos` commands again. This time, it again selects the file that was at the top of the denite window, but this time it was causes-jedi-error.py instead of -std=gnu++0x.d like `:DeniteFirst` should do.

**Comment by Shougo** [comment]
Please upload the minimal vimrc and the reproduce ways.
I cannot reproduce it.

**Comment by wilywampa** [comment]
Minimal vimrc:

```vim
set runtimepath+=/Users/jniehus/Downloads/dev/denite.nvim
```

Steps to reproduce:
1. Run nvim from a directory with at least 40 files in it
2. Open denite with `:Denite file`. Note the name of the first candidate (top of visible window)
3. Press `<C-o><C-d>` to enter normal mode and scroll down a page. Note the name of the file that is now at the top of the visible window
4. Press `q` to exit the denite window
5. Run `:Denite -resume -immediately -cursor-pos=0`. This will open the file noted in step 3, not the first candidate notes in step 2

**Comment by Shougo** [comment]
I get it.  It is the bug.  Please create the different issue.

**Comment by Shougo** [comment]
Yes.  It should be.
