### ISSUE TITLE
Custom matcher doesn't work well

### ISSUE THREAD

**Issue by taki4416** [Shougo/denite.nvim#306]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

I wrote following line on my vimrc.
```
call denite#custom#source('_', 'matchers', ['matcher_substring'])
```
Applying filter function is well, but highlight-matched-range is wrong.
It seems to be the pattern of matcher_fuzzy.

![2017-07-09-01 48 15](https://user-images.githubusercontent.com/3838104/27987782-9e2cf5ee-644e-11e7-84c9-619aff745f1b.png)

Expected pattern is following one.

![2017-07-09-03 59 11](https://user-images.githubusercontent.com/3838104/27988356-0e4ad22c-645b-11e7-9f9d-176dcd968fa5.png)

99f94a9b010e2225f899bd52ac9f0ae80fe668dd caused this problem.
The screenshot as above was outputted by reverted repository.
However, commit message is "Fix copy() problem.".
I'm not sure right way to fix this issue...

## Environment Information (Required!)

 * denite version(SHA1): 8ec3a9fc9c9b1ec8a6de4d565d2b563fec24afb7

 * OS: Ubuntu 16.04

 * Vim/neovim version: NVIM 0.1.7

 * `:CheckHealth` result(neovim only): Success

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/denite.nvim/
call denite#custom#source('_', 'matchers', ['matcher_substring'])
```
## The reproduce ways from neovim starting (Required!)

 1. :Denite help
 2. type some character

**Comment by Shougo** [comment]
I will fix it.

**Comment by taki4416** [comment]
Thanks a lot.
