### ISSUE TITLE
Error in executing :Denite file_rec

### ISSUE THREAD

**Issue by emanpatricio** [Shougo/denite.nvim#310]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

Im very much new in NeoVim and I am getting bellow error everytime I execute :Denite file_rec
## Environment Information (Required!)

 * denite version(SHA1):

 * OS:

 * Vim/neovim version:

 * `:CheckHealth` result(neovim only):

>  54 health#deoplete#check
 53 ========================================================================
 52 ## deoplete.nvim
 51   - SUCCESS: has("nvim") was successful
 50   - SUCCESS: has("python3") was successful
 49   - INFO: If you're still having problems, try the following commands:
 48     $ export NVIM_PYTHON_LOG_FILE=/tmp/log
 47     $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
 46     $ nvim
 45     $ cat /tmp/log_{PID}
 44     and then create an issue on github
 43 
 42 health#nvim#check
 41 ========================================================================
 40 ## Configuration
 39   - SUCCESS: no issues found
 38 
 37 ## Performance
 36   - INFO: Build type: None
 35   - WARNING: Non-optimized build-type. Nvim will be slower.
 34     - SUGGESTIONS:
 33       - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
 32       - See https://github.com/neovim/neovim/wiki/FAQ
 31 
 30 ## Remote Plugins
 29   - SUCCESS: Up to date
 28 
 27 ## terminfo
 26   - INFO: key_backspace terminfo entry: key_backspace=\177,
 25 
 24 health#provider#check
 23 ========================================================================
 22 ## Clipboard
 21   - SUCCESS: Clipboard tool found: xsel
 20 
 19 ## Python 2 provider
 18   - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
 17   - INFO: Executable: /usr/bin/python2
 16   - INFO: Python2 version: 2.7.13
 15   - INFO: python2-neovim version: 0.1.13
 14   - SUCCESS: Latest python2-neovim is installed: 0.1.13
 13 
 12 ## Python 3 provider
 11   - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
 10   - INFO: Executable: /usr/bin/python3
  9   - INFO: Python3 version: 3.5.3
  8   - INFO: python3-neovim version: 0.1.13
  7   - SUCCESS: Latest python3-neovim is installed: 0.1.13
  6 
  5 ## Ruby provider
  4   - ERROR: Missing Neovim RubyGem
  3     - SUGGESTIONS:
  2       - Install or upgrade the neovim RubyGem using `gem install neovim`.
  1   - INFO: Ruby Version: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
56    - INFO: Host Executable: not found
  1   - INFO: Host Version: not found
  2 

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set nocompatible
  let mapleader = " "
  filetype plugin indent on
  syntax on

  set runtimepath+=~/.config/nvim/plugged/denite.nvim

```

## The reproduce ways from neovim starting (Required!)

 1. foo
 2. bar
 3. baz

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/1246276/28098367-6ddce3bc-66e8-11e7-898a-f69aee806dbf.png)

## Upload the log file

> [denite] Traceback (most recent call last):
[denite]   File "/home/emanpatricio/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/__init__.py", line 33, in start
[denite]     return self._uis[buffer_name].start(args[0], args[1])
[denite]   File "/home/emanpatricio/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 65, in start
[denite]     self._start(sources, context)
[denite]   File "/home/emanpatricio/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 113, in _start
[denite]     self.gather_candidates()
[denite]   File "/home/emanpatricio/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/ui/default.py", line 550, in gather_candidates
[denite]     self._denite.gather_candidates(self._context)
[denite]   File "/home/emanpatricio/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 58, in gather_candidates
[denite]     source.context, source)
[denite]   File "/home/emanpatricio/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/denite.py", line 67, in _gather_source_candidates
[denite]     candidates = source.gather_candidates(context)
[denite]   File "/home/emanpatricio/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/source/file_rec.py", line 72, in gather_candidates
[denite]     context['__proc'] = Process(args, context, directory)
[denite]   File "/home/emanpatricio/.config/nvim/plugged/denite.nvim/rplugin/python3/denite/process.py", line 25, in __init__
[denite]     cwd=cwd)
[denite]   File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
[denite]     restore_signals, start_new_session)
[denite]   File "/usr/lib/python3.5/subprocess.py", line 1283, in _execute_child
[denite]     raise child_exception_type(errno_num, err_msg)
[denite] FileNotFoundError: [Errno 2] No such file or directory: 'rg'
[denite] Please execute :messages command.

**Comment by Shougo** [comment]
You have set denite file_rec configuration to use "rg".
But it is not installed.
