### ISSUE TITLE
UnicodeDecodeError in tag source

### ISSUE THREAD

**Issue by wilywampa** [Shougo/denite.nvim#312]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
`UnicodeDecodeError` on tags file with non-ASCII characters

## Expected
Be able to load tags with utf-8 characters.

## Environment Information (Required!)

 * denite version(SHA1): 4316a9b

 * OS: macOS Sierra

 * Vim/neovim version: NVIM v0.2.1-533-g5f8f46ba8

 * `:CheckHealth` result(neovim only):
```

health#jedi#check
========================================================================
## jedi
#### Jedi-vim debug information
Using Python version: 3
 - sys.version: `3.6.1 (default, Apr  4 2017, 09:40:21), [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]`
 - site module: `/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site.py`
Jedi path: `/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi/jedi/jedi/__init__.py`
 - version: 0.10.2
 - sys_path:
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages/neovim_remote-1.7.1-py3.6.egg`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages/vim_vint-0.3.13-py3.6.egg`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages/ansicolor-0.2.4-py3.6.egg`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages/PyYAML-3.12-py3.6-macosx-10.12-x86_64.egg`
    - `/Users/jniehus/Documents/vimconfig/vimfiles/bundle/jedi`
    - `/Users/jniehus/.ipython`
    - `/Users/jniehus/Documents/vimconfig/misc/python`
    - `/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python36.zip`
    - `/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6`
    - `/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages/neovim_remote-1.7.1-py3.6.egg`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages/vim_vint-0.3.13-py3.6.egg`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages/ansicolor-0.2.4-py3.6.egg`
    - `/Users/jniehus/Documents/dev/py3.6.1env/lib/python3.6/site-packages/PyYAML-3.12-py3.6-macosx-10.12-x86_64.egg`
    - `_vim_path_`
 - jedi-vim git version: 0.8.0-83-g6411de0
 - jedi git submodule status:  5427b02712828b2875d35b5ee1c8b5e58f820537 jedi (v0.10.2)


##### Settings
```
g:jedi#force_py_version = '3' (default: 'auto')
g:jedi#popup_select_first = 0 (default: 1)
g:jedi#auto_close_doc = 0 (default: 1)
g:jedi#usages_command = '<silent> <Leader>ju' (default: '<leader>n')
g:jedi#rename_command = '<silent> <Leader>jr' (default: '<leader>r')
g:jedi#auto_vim_configuration = 0 (default: 1)
g:jedi#show_call_signatures_delay = -1 (default: 500)
g:jedi#smart_auto_mappings = 0 (default: 1)
g:jedi#goto_command = '' (default: '<leader>d')
g:jedi#show_call_signatures = 2 (default: 1)
g:jedi#completions_enabled = 0 (default: 1)

  omnifunc=htmlcomplete#CompleteTags
	Last set from /usr/local/Cellar/neovim/HEAD-5f8f46b_1/share/nvim/runtime/ftplugin/html.vim
  completeopt=menu,preview
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 50ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /Users/jniehus/Documents/dev/py3.6.1env/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.4.0

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=/Users/jniehus/Downloads/dev/denite.nvim
set tags=/Users/jniehus/Documents/vimconfig/vimfiles/bundle/mundo/tags
```

## The reproduce ways from neovim starting (Required!)

1. Set `'tags'` to include the attached tag file
2. Run `:Denite tag`

## Screen shot (if possible)
<img width="1103" alt="screen shot 2017-07-12 at 7 30 55 pm" src="https://user-images.githubusercontent.com/4472522/28147964-c8c5b704-6738-11e7-892b-82013a065ab8.png">

tags file (rename to just "tags"): 
[tags.txt](https://github.com/Shougo/denite.nvim/files/1143880/tags.txt)

**Comment by Shougo** [comment]
The file is really UTF-8 tags file?
It includes the invalid bytes.

I have opened the tags file, they are displayed by `?`.

**Comment by wilywampa** [comment]
It was generated with `ctags -R .` (then deleted the irrelevant rows).

**Comment by Shougo** [comment]
```
cat tags
!_TAG_FILE_FORMAT       2       /extended format; --format=1 will not append ;" to lines/
!_TAG_FILE_SORTED       1       /0=unsorted, 1=sorted, 2=foldcase/
!_TAG_PROGRAM_AUTHOR    Darren Hiebert  /dhiebert@users.sourceforge.net/
!_TAG_PROGRAM_NAME      Exuberant Ctags //
!_TAG_PROGRAM_URL       http://ctags.sourceforge.net    /official site/
!_TAG_PROGRAM_VERSION   5.8     //
�       tests/bundled/lh-vim-lib/tests/lh/test-command.vim      /^nnoremap � :call lh#command#new(TBTWcommand)<cr>$/;"  m
```

**Comment by Shougo** [comment]
So `UnicodeDecodeError on tags file with invalid UTF-8 characters` is the issue.

**Comment by wilywampa** [comment]
I also get a weird result with `cat`. Vim handles it right (and claims the file's encoding is `latin1`):
<img width="902" alt="screen shot 2017-07-12 at 7 39 22 pm" src="https://user-images.githubusercontent.com/4472522/28148155-d9e953c8-6739-11e7-8380-667431fa25d7.png">

The ctags documentation (https://media.readthedocs.org/pdf/ctags/latest/ctags.pdf) says:

> ctags doesn’t consider the input encoding; it just reads input as a sequence of bytes and uses them as is when writing tags entries

I tried adding `--output-encoding=utf-8` but that didn't help.

> So `UnicodeDecodeError on tags file with invalid UTF-8 characters` is the issue.

Yes, so maybe the answer is to open the tags file with `errors='replace'` and ignore lines with errors, but then some real tags will be ignored.

**Comment by Shougo** [comment]
OK.  I get it.  It is latin1 encoding.
You should convert the tags file to UTF-8 encoding.  If it is converted, denite works well.

**Comment by wilywampa** [comment]
I didn't do anything weird to generate that tags file. The output is from default settings of ctags. For me, maybe I can alter my workflow everywhere to convert tags file to the format denite.vim wants, but I don't think denite.nvim should handle invalid byte sequences by crashing.

**Comment by Shougo** [comment]
> but I don't think denite.nvim should handle invalid byte sequences by crashing.

Yes, the error should be fixed.

**Comment by wilywampa** [comment]
It should be fixed by converting the tags file to UTF-8?

**Comment by Shougo** [comment]
I will implement the error ignore, but it does not fix the characters.
To fix the characters, you must convert the encoding manually.
