### ISSUE TITLE
How to ignore type of files on file_rec list in folder which contains many files.

### ISSUE THREAD

**Issue by gongbingchan** [Shougo/denite.nvim#313]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I have a project folder contains over 70000 files, but about only 1000 file (which are *.h/cpp/java/xml/..) are what I want to be shown in file_rec list. Even I use this two lines:
```
call denite#custom#source('file_rec', 'matchers', ['matcher_ignore_globs'])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs', [ '.git/', '.gradle/', 'build/', '.idea/', 'app/', '*.png', '*.so', '*.a', '*.jar' ])
```
to ignore files，but still very slow. The good news is this two lines indeed narrow the list to what i what, show "file_rec(1296/77974)" at the bottom-left status bar.

I was Unite plugin user, on that time this line takes effect:
```
call unite#custom#source('file_rec/async', 'ignore_pattern', '\(build\|app\|.idea\|.gradle\|.png\)')
```
but not valid in Denite. How should i do?

## Environment Information (Required!)

 * denite version(SHA1): The latest.

 * OS: MacOS 10.12.5

 * Vim/neovim version: 8.0.666

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by Shougo** [comment]
Please configure it by file_rec command var like this:

```
	call denite#custom#var('file_rec', 'command',
	\ ['rg', '--files', '--glob', '!.git', ''])
```

**Comment by gongbingchan** [comment]
It works, thx. Great plugin.
