### ISSUE TITLE
Option to populate locations/quickfix list

### ISSUE THREAD

**Issue by amitbeka** [Shougo/denite.nvim#315]
Hi, this is not a bug, but a question/feature request. I was wondering if there is an option to populate the quickfix/locations list with whatever results are in denite's window, so I can jump between them easily.

The use case for this is when I refactor some code and want to search all the strings with the old name of the class and replace with the new one, so I would like to use the grep search once and then move between the results.

Thanks for the really awesome plugin and tons of work on it (and others!) - I'm a big fan :)

**Comment by wilywampa** [comment]
Have you tried running `:Denite` with `-no-quit` and/or using `:Denite -resume -select=+/-1 -immediately`?

**Comment by amitbeka** [comment]
It works great, thanks again
