### ISSUE TITLE
Candidates not updated on <denite:restart>

### ISSUE THREAD

**Issue by wilywampa** [Shougo/denite.nvim#317]
# Problems summary

Candidates not updated on `<denite:restart>`

## Expected

Be able to update candidates after making changes to denite.nvim configuration in a function

## Environment Information (Required!)

 * denite version(SHA1): 7a98f9b

 * OS: macOS Sierra

 * Vim/neovim version: NVIM v0.2.1-548-gda99ded25; Build type: Release

 * `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 50ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /Users/jniehus/Documents/dev/py3.6.1env/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.4.0

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
scriptencoding utf8
set runtimepath+=/Users/jniehus/Downloads/dev/denite.nvim

let s:reversed = v:true
function! Reverse() abort " {{{
    if s:reversed
        call denite#custom#source('_', 'sorters', [])
    else
        call denite#custom#source('_', 'sorters', ['sorter_reverse'])
    endif
    let s:reversed = !s:reversed
    return '<denite:redraw>'
endfunction " }}}
call Reverse()
call denite#custom#map('insert', '<C-r>', 'Reverse()', 'noremap expr')
```

## The reproduce ways from neovim starting (Required!)

 1. Run `:Denite file` in a directory with files in it and note the order of candidates
 2. Press `<C-r>` to reverse the sort order
 3. Observe that the order of candidates did not change
 4. Manually exit and re-run `:Denite file` and note that now the files are reversed like they should have been after `<denite:restart>`

**Comment by Shougo** [comment]
This is undefined behavior.
So it is the feature.

`call denite#custom#source()` does not change the current source.

**Comment by wilywampa** [comment]
The only way to bring a modification to a source into effect is to _manually_ exit and restart denite.nvim? Is `<denite:restart>` supposed to not work? Sorry, but this makes denite.nvim much less usable than unite.vim. What happened to "Has greater potential to implement new features"?

**Comment by Shougo** [comment]
> The only way to bring a modification to a source into effect is to manually exit and restart denite.nvim? 

Or add the feature.

> Is `<denite:restart>` supposed to not work?

`<denite:restart>` works as intended.  Just does not support for the feature.

**Comment by Shougo** [comment]
> Sorry, but this makes denite.nvim much less usable than unite.vim. What happened to "Has greater potential to implement new features"?

It is the short-circuited result.
This is not bug and you should the feature request of `change_sorter` mapping.
Please mix the bug or the feature request.

I didn't say "I don't want to add the feature to change sorter".

**Comment by wilywampa** [comment]
Sorry again! I think we're just having a communication mixup. "Feature" usually means something positive like an unusual capability. So, when I see some behavior being called a feature, I interpret that to mean it's something that's functional and intended.

**Comment by Shougo** [comment]
`<denite:restart>` behavior is intended.
So if you need the feature, it is the feature request of changing sorters.

**Comment by petobens** [comment]
@Shougo I also don't understand how does `<denite:restart>` works (or it is broken). Consider the following minimal vimrc:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'statusline': 0,
            \ 'winheight': 15,
            \ 'updatetime': 100,
            \ 'reversed': 1,
            \ 'prompt': '❯',
            \ 'prompt_highlight': 'Function',
            \ 'highlight_matched_char': 'Function',
            \ 'highlight_matched_range': 'Normal',
            \ 'highlight_mode_insert': 'WildMenu'
            \ })
call denite#custom#map('insert', 'jj', '<denite:enter_mode:normal>',
    \ 'noremap')
call denite#custom#map('normal', '<C-k>', '<denite:wincmd:k>', 'noremap')
call denite#custom#map('normal', '<C-r>', '<denite:restart>', 'noremap')
```
Now as in the GIF:
i) run `:Denite file_rec`
ii) press `jj` to get into normal mode and then `C-k` to move up
iii) press `C-w-j` to return to Denite buffer
iv) press `C-r` to restart denite.
I expect the denite buffer to restart at point iv (i.e to be able to filter the candidates) however this doesn't happen:
![jul-22-2017 12-56-44](https://user-images.githubusercontent.com/2583971/28492635-57e94bfc-6edd-11e7-8923-e06f2d0ede37.gif)

Also is there a way to force restarting the denite buffer upon entering it? (i.e without having manually call `<denite:restart>`.

**Comment by Shougo** [comment]
> iv) press C-r to restart denite.

Wrong.  You must resume the denite before that.
`-auto-resume` is recommended for you.

> Also is there a way to force restarting the denite buffer upon entering it? (i.e without having manually call `<denite:restart>`).

I don't understand it.  Why it is needed?

**Comment by petobens** [comment]
> -auto-resume is recommended for you.

This is what I needed! Thanks!!!
