### ISSUE TITLE
vim-airline extension

### ISSUE THREAD

**Issue by mhartington** [Shougo/denite.nvim#32]
# Problems summary
Hi there! 

So I'm looking to create a new airline extension for denite, based on the extension for unite.vim.

https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/unite.vim

But it seems there are a few missing APIs that are required .

Mostly:
- `unite_force_overwrite_statusline` for denite
- a get_status_string() function
- a `get_context()` function. 

I would like to help out where I can, but would like to get your thoughts on what the best approach would be for adding such features.

**Comment by Shougo** [comment]
This feature is really useful?

I need some features to implement it.
I have not much the time.

**Comment by HerringtonDarkholme** [comment]
It is doable by implementing custom UI. The basic idea is set some global variables, and in ui.py modify these global variables. Then in airline we can access the current state inside denite.

**Comment by wsdjeg** [comment]
@mhartington can you add `autoload/airline/extensions/denite.vim` into vim-airline?

**Comment by mhartington** [comment]
@wsdjeg you can, but it does not do anything
Using the unite extension as an example, you're able to disable the status bar being overwritten by the unite.

https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/unite.vim#L22

This is missing from denite at the moment.

**Comment by Shougo** [comment]
No you can disable the statusline.

```vim
Denite -no-statusline file_rec
```

**Comment by petobens** [comment]
@mhartington  any change of getting this to work by using?:
```vim
call denite#custom#option('default', 'statusline', 0)
```
Thanks in advance.

**Comment by petobens** [comment]
ping @mhartington
