### ISSUE TITLE
&guicursor/-cursor-shape not working

### ISSUE THREAD

**Issue by wilywampa** [Shougo/denite.nvim#321]
# Problems summary

`'guicursor'` support doesn't seem to do anything

## Expected

Cursor shape should be as defined in `&guicursor`

## Environment Information (Required!)

 * denite version(SHA1): 7a98f9b

 * OS: macOS Sierra

 * Vim/neovim version: NVIM v0.2.1-548-gda99ded25; Build type: Release

 * `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 50ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /Users/jniehus/Documents/dev/py3.6.1env/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.4.0

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
scriptencoding utf8
set runtimepath+=/Users/jniehus/Downloads/dev/denite.nvim
set guicursor=a:ver20
nnoremap <C-o> :<C-u>Denite -cursor-shape file<CR>
```

## The reproduce ways from neovim starting (Required!)

 1. `nvim ~/.config/nvim/init.vim`
 2. Ensure the cursor is a vertical bar as set in init.vim
 3. Open denite.nvim using `<C-o>`
 4. Cursor is a block instead of a bar

![cursorshape](https://user-images.githubusercontent.com/4472522/28250315-1dd77a78-6a1a-11e7-8eaf-008723f354b3.gif)

**Comment by Shougo** [comment]
`-cursor-shape` changes the cursor shape.  So it is the feature.

**Comment by Shougo** [comment]
And denite uses `n-v-c:None` cursorshape.
I think your terminal does not support it.

**Comment by wilywampa** [comment]
> I think your terminal does not support it.

I tested iTerm 2, mintty, and xterm. `n-v-c:None` does not work in any of them. I included the .gif to show that it does support &guicursor` just fine, but `None` does not hide the cursor.

May be related to https://github.com/neovim/neovim/issues/3688

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/issues/3688#issuecomment-291224222

> No, setting the cursor highlight group (which would enable to hide it) hasn't been implemented yet. There is some discussion going on in #6428.

The feature is not implemented.
The feature is for only GVim.

**Comment by teto** [comment]
just wanted to say that I have running code to set cursor invisible but that but it might take a couple more months to merge it. It is possible to set the cursor highlights but neovim doesn't differentiate between None and unitialized. And as such the TUI can't special case a "NONE" value.
