### ISSUE TITLE
Denite grep to target certain file types

### ISSUE THREAD

**Issue by nashio** [Shougo/denite.nvim#322]
When using "Denite grep", is there a way to target certain file types?
say I want to search for a term inside of .py files

I tried both "--include" from grep, and "--py" from Ag , but had no luck

**Comment by wilywampa** [comment]
`--python` (not just `--py`) works in ag.

**Comment by nashio** [comment]
hm, no luck
steps:
  Denite grp
  pattern: "thing" --python 
or
  pattern: "thing" --py

**Comment by wilywampa** [comment]
`--python` needs to be an argument for ag. Putting it in the pattern itself is silly. Try `call denite#custom#var('grep', 'default_opts', ['--python'])`

**Comment by nashio** [comment]
Writing that every time you do a search seems super inconvenient.
What if I want to search for different file types

**Comment by wilywampa** [comment]
If you put it in a function/map, it's not really inconvenient, but another way to do it is call

`:call denite#start([{'name': 'grep', 'args': ['.', ['--python'], pattern}])`

and make it a function so you can give it pattern and args.

OR you could make an alias for the grep source called `grep/python` or whatever and set the options only for the aliased action. See the help for a similar example:

```
Q: What is the correct way to say "if I'm in a git directory, git ls-files for
file_rec" ?

A: >
	call denite#custom#alias('source', 'file_rec/git', 'file_rec')
	call denite#custom#var('file_rec/git', 'command',
	\ ['git', 'ls-files', '-co', '--exclude-standard'])
	nnoremap <silent> <C-p> :<C-u>Denite
	\ `finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'`<CR>
```

**Comment by nashio** [comment]
Thanks, creating the function might work. I'm gonna try that, it'd still be nice if there was a realtime way of doing this.
For now I just saw that another way to accomplish this by doing a search for the pattern and then filter by putting the extension.
Pattern: "thing"
#.py
this returns "thing" on .py files, but could potentially return filenames inside files
The only problem with this, is that its kinda slow

**Comment by Shougo** [comment]
https://github.com/Shougo/denite.nvim/issues/328

**Comment by Shougo** [comment]
@nashio I think you should change the denite source arguments by filetype mappings.

**Comment by nashio** [comment]
HI @Shougo , not sure what you mean, example?

**Comment by Shougo** [comment]
You can specify the arguments by source arguments like `Denite grep::--python`.
So you can define the filetype mappings.

**Comment by nashio** [comment]
ahh great thats what I needed
