### ISSUE TITLE
Enhancements in grep source

### ISSUE THREAD

**Issue by purpleP** [Shougo/denite.nvim#328]
- `pattern` option should be added to grep source. Suppose I want to create a mapping to grep through Python functions. `<Esc>d :Denite grep -input=^\s*def\s+`. Works just fine If I would execute `Denite grep` and then typed the pattern, but when specified via input it's used both as pattern and as input resulting in empty result set.

- I think that the sources should be able to specify what area is searchable in each line. Because for example in `grep` source I don't want matcher to search via file names (nor do I think anyone else wants). In general distinction should be made between the source raw results and what it would present to the user.
- The same probably applies to other sources like tags.

**Comment by Shougo** [comment]
Note:  Please read grep source documentation.

> pattern option should be added to grep source.

Please use grep source argument 3.

**Comment by Shougo** [comment]
> I think that the sources should be able to specify what area is searchable in each line. Because for example in grep source I don't want matcher to search via file names (nor do I think anyone else wants). In general distinction should be made between the source raw results and what it would present to the user.

You can change the behavior by filter feature.  It is the same with unite.vim.
But I will fix grep and tag source default behavior.

> The same probably applies to other sources like tags.

**Comment by purpleP** [comment]
@Shougo I think you've broken highlighting in grep source with latest changes and also filepaths are still searchable. Also It's unclear to me how to use `use grep source argument 3`

**Comment by Shougo** [comment]
> @Shougo I think you've broken highlighting in grep source with latest changes and also filepaths are still searchable.

Really?
I cannot reproduce it.
Please create the new issue.
