### ISSUE TITLE
Denite window not updated when using -immediately

### ISSUE THREAD

**Issue by wilywampa** [Shougo/denite.nvim#343]
I have the following mappings to go to previous/next candidates:

```vim
nn <silent> [d :<C-u>Denite -resume -immediately -force-quit -cursor-pos=-<C-r>=v:count1<CR><CR>
nn <silent> ]d :<C-u>Denite -resume -immediately -force-quit -cursor-pos=+<C-r>=v:count1<CR><CR>
nn <silent> [D :<C-u>Denite -resume -immediately -force-quit -cursor-pos=0<CR>
nn <silent> ]D :<C-u>Denite -resume -immediately -force-quit -cursor-pos=$<CR>
```

When I use them to switch between grep results (using `-no-quit`), the denite.nvim window should update which row is selected. Instead, the same line stays highlighted as I switch between results.

**Comment by Shougo** [comment]
> When I use them to switch between grep results (using -no-quit), the denite.nvim window should update which row is selected. Instead, the same line stays highlighted as I switch between results.

Please create the reproduce ways from the starting!
I don't want to create the ways from your report.

**Comment by wilywampa** [comment]
Sure.

# Problems summary

Selecting next/previous candidate using `-immediately` is broken if the denite.nvim window is open

## Expected

Should be able to select next/previous candidate and have the denite.nvim update with the new cursor location

## Environment Information (Required!)

 * denite version(SHA1): f112b16

 * OS: macOS Sierra

 * Vim/neovim version: NVIM v0.2.1-596-g5a0acd09c Build type: Release


 * `:CheckHealth` result(neovim only):

```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 50ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /Users/jniehus/Documents/dev/py3.6.1env/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - WARNING: Gem "neovim" is out-of-date. Installed: 0.4.0, latest: 0.5.0
    - SUGGESTIONS:
      - Run in shell: gem update neovim
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
scriptencoding utf8
set runtimepath+=/Users/jniehus/Downloads/dev/denite.nvim
nnoremap <silent> [d :<C-u>Denite -resume -immediately -force-quit -cursor-pos=-<C-r>=v:count1<CR><CR>
nnoremap <silent> ]d :<C-u>Denite -resume -immediately -force-quit -cursor-pos=+<C-r>=v:count1<CR><CR>
nnoremap <silent> [D :<C-u>Denite -resume -immediately -force-quit -cursor-pos=0<CR>
nnoremap <silent> ]D :<C-u>Denite -resume -immediately -force-quit -cursor-pos=$<CR>
nnoremap <C-g> :<C-u>Denite grep -no-quit<CR>
```

## The reproduce ways from neovim starting (Required!)

 1. Start nvim from the denite.nvim directory with `nvim README.md`
 2. Start `:Denite grep` by pressing `<C-g>` and search for "git" as the pattern
 3. Select a result then enter normal mode with `<C-o>` then change to the buffer window with `<C-w>p`
 4. Use `]d` to select the next candidate
 5. Now the denite.nvim window takes up the whole screen and behaves bizarrely

**Comment by Shougo** [comment]
> Start `:Denite grep` by pressing `<C-g>` and search for "git" as the pattern

It must be `:Denite grep -no-quit`
