### ISSUE TITLE
file_rec cannot search under a large directory

### ISSUE THREAD

**Issue by brglng** [Shougo/denite.nvim#350]
# Problems summary
I took a screencast for this: [screencast](https://sololand.moe/denite.webm)

When searching under my HOME directory, denite gives no result.

## Expected
Denite should give result

## Environment Information (Required!)
 * denite version(SHA1): 4eb9724ca004e441987b1833d882d6355019ab4f
 * OS: Ubuntu GNOME 17.04
 * Vim/neovim version: Vim 8.0.685
 * `:CheckHealth` result(neovim only): N/A

## Provide a minimal init.vim with less than 50 lines (Required!)
```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
call denite#custom#option('_', 'auto_resize', 1)
call denite#custom#option('_', 'vertical_preview', 1)
call denite#custom#option('_', 'highlight_matched_char', 'Keyword')
call denite#custom#source('file,' .
      \                   'file_rec,' .
      \                   'directory_rec',
      \                   'matchers', ['matcher_fuzzy', 'matcher_project_files'])
call denite#custom#map('insert', '<C-j>', '<denite:move_to_next_line>', 'noremap')
call denite#custom#map('insert', '<C-k>', '<denite:move_to_previous_line>', 'noremap')
```

## The reproduce ways from neovim starting (Required!)

 1. Open Vim
 2. Use `:Denite file_rec` to start denite
 3. Type any charactors to do the search
 4. Check if denite gives any result

## Screen shot (if possible)
[screencast](https://sololand.moe/denite.webm)

**Comment by Shougo** [comment]
Reproduced.

**Comment by brglng** [comment]
Thanks! It works now.
