### ISSUE TITLE
File modifications lost using ":Denite line -auto-preview"

### ISSUE THREAD

**Issue by eltechnic0** [Shougo/denite.nvim#351]
# Problems summary

When calling Denite to search in the current buffer, if there are unsaved modifications, they are lost.

## Expected

Modifications shouldn't be lost.

## Environment Information (Required!)

 * denite version(SHA1): 0.5

 * OS: Windows 10

 * Vim/neovim version: v0.2.1-25-g2e3b78d1

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" minimal init.vim
if &compatible
	set nocompatible
endif
set runtimepath+=C:\Users\German\AppData\Local\nvim\dein\repos\github.com\Shougo\dein.vim

if dein#load_state('C:\Users\German\AppData\Local\nvim\dein')
	call dein#begin('C:\Users\German\AppData\Local\nvim\dein')
	call dein#add('C:\Users\German\AppData\Local\nvim\dein\repos\github.com\Shougo\dein.vim')

	" plugins

	call dein#add('Shougo/deoplete.nvim')
        call dein#add('Shougo/denite.nvim')
	call dein#add('vim-airline/vim-airline')
	call dein#add('scrooloose/nerdtree')
	call dein#add('scrooloose/nerdcommenter')
	call dein#add('tpope/vim-surround')
	call dein#add('terryma/vim-expand-region')
        "call dein#add('haya14busa/vim-asterisk')
        "call dein#add('easymotion/vim-easymotion')
        call dein#add('/mbbill/undotree')
        call dein#add('Shougo/neosnippet')
        call dein#add('Shougo/neosnippet-snippets')

	call dein#end()
	call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

## The reproduce ways from neovim starting (Required!)

1. Open neovim-qt by double-clicking.
2. Open a file
3. Make a modification
4. Run: ":Denite line -auto-preview"
5. Write a word to search for
6. Check that the modification has been lost

**Comment by Shougo** [comment]
I cannot get the error by the minimal vimrc.

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/denite.nvim/
```

Please upload the real minimal vimrc.
