### ISSUE TITLE
Does `narrow` action differ from the one on unite?

### ISSUE THREAD

**Issue by delphinus** [Shougo/denite.nvim#355]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

The `narrow` action on unite makes a new temporary buffer and shows files on the directory.  Users can search files deeper without re-launching unite.

On the other hand, it seems the `narrow` action on denite can only limit the candidates by the name.  Is this a spec? or I want the same `narrow` action as the one on unite.

## Expected

The `narrow` action does the same as the one on unite.  Or perhaps, it can do a similar action with launching denite on the selected candidate.

## Environment Information (Required!)

 * denite version(SHA1): 3c377eb2ede579a3fffd752e9051a1491cf5801e

 * OS: macOS Sierra

 * Vim/neovim version: MacVim 8.0.771

 * `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. foo
 2. bar
 3. baz

**Comment by Shougo** [comment]
> On the other hand, it seems the narrow action on denite can only limit the candidates by the name. Is this a spec?

This is the spec.

Why this feature is needed?
Please explain it more.

**Comment by delphinus** [comment]
Sorry, I found I mistook it for the narrow action.  It should be the file action that is set by `unite#custom_action` in [here][].

[here]: https://github.com/Shougo/unite.vim/blob/ad15f96365b5cb43a45d0ca779df6a497f954f15/autoload/unite/sources/file.vim#L473-L485

In unite, I do the default action by `<Enter>` on the candidates by `Unite directory`, and it shows files the directory below.

[![asciicast](https://asciinema.org/a/132374.png)](https://asciinema.org/a/132374)

But denite, it shows none.  Perhaps, it does the narrow action on default.

[![asciicast](https://asciinema.org/a/132375.png)](https://asciinema.org/a/132375)


I want the same behavior as unite on denite.

**Comment by delphinus** [comment]
And in this working, I found a bug on `directory_rec` that is the same as #354. I will PR

**Comment by Shougo** [comment]
Fixed.
