### ISSUE TITLE
"Denite buffer" order

### ISSUE THREAD

**Issue by pocari** [Shougo/denite.nvim#36]
`Unite buffer` enumerates previous buffer as first candidate, and current buffer as last candidate.
I hope so in `Denite buffer`

so, I workaround by these changes.
https://github.com/Shougo/denite.nvim/compare/master...pocari:fix-buffer-source-changes-alternately?expand=1

Is there any way to fix this problem?

**Comment by Shougo** [comment]
LGTM.

Please create new PR for it.
I will merge it.

**Comment by pocari** [comment]
thanks, I created PR!
