### ISSUE TITLE
The Denite output source does not open anything

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/denite.nvim#364]
# Problems summary
I'm trying to use the `output` source in order to avoid having to search files on a slow NFS share by reading a file with a list of files. Using the `output` source does not open files selected.

## Expected
Using `Denite output:!ls` or `Denite output:!cat\ file.list` should open the file selected, it does not.

## Environment Information (Required!)

 * denite version(SHA1): a9bc178
 * OS: `Ubuntu 16.04.3 LTS`
 * Vim/neovim version: `NVIM v0.2.1-dev`
 * `:CheckHealth` result(neovim only):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```

## Provide a minimal `init.vim` with less than 50 lines (Required!)

```vim
set runtimepath+=/home/local/ANT/jsokolow/.config/nvim/bundle/denite.nvim
nnoremap <c-i> :Denite output:!ls -default-action=default<cr>
```

## The reproduce ways from neovim starting (Required!)

 1. Open vim with my test `init.vim`
 2. Try using `<c-i>` mapping
 3. Select any file
 4. No action takes place

## Screen shot (if possible)
Wouldn't show anything, after pressing `enter` on a candidate I just go back to my previous buffer, nothing is opened.

## Upload the log file
[profile.txt](https://github.com/Shougo/denite.nvim/files/1256467/profile.txt)

**Comment by PonderingGrower** [comment]
I might add that the `auto-preview` function doesn't work either with the `output` source.

**Comment by Shougo** [comment]
output source does not support preview action.

**Comment by Shougo** [comment]
Unite.vim has file_list source.
But denite.nvim has not.

**Comment by PonderingGrower** [comment]
But the preview action is just a __side note__, the `output` source does not open files for me. At all.

**Comment by Shougo** [comment]
> But the preview action is just a side note, the output source does not open files for me. At all.

output source default action is yank and open action is not implemented.

**Comment by PonderingGrower** [comment]
I see, so that's not a bug, just lack of implementation. Okay, thanks for clearing that up.

**Comment by Shougo** [comment]
It should be "file_source" instead of "output" source.
But it is not implemented.

**Comment by PonderingGrower** [comment]
Though it might be a good idea to add a note in the documentation about `output` source using yank as default action. I was really confused as to why `output` had no effect.

Thanks anyway for working on this plugins, it's great despite some small flaws!

**Comment by Shougo** [comment]
> Though it might be a good idea to add a note in the documentation about output source using yank as default action. I was really confused as to why output had no effect.

Hm...  I should add the documentation.
