### ISSUE TITLE
Output source should execute external commands in the active buffer working dir

### ISSUE THREAD

**Issue by eltechnic0** [Shougo/denite.nvim#366]
# Problems summary

Using output source, e.g. `:Denite output:!ls`, the path used for the external command is not that of the working dir of the current buffer.

## Expected

That the path is the active buffer current working dir.

**Comment by blankname** [comment]
Both `:!ls` and `:Denite output:!ls` output the same thing for me. They differ for you?

**Comment by Shougo** [comment]
No.  It should not.

**Comment by Shougo** [comment]
You can use `:Denite output:!./ls` instead.

**Comment by eltechnic0** [comment]
Ok. Should that work for Windows too?

**Comment by Shougo** [comment]
Yes.

**Comment by eltechnic0** [comment]
Under Windows 10, I get a `FileNotFoundError`, so sth is wrong with the path.

I am trying to fix it myself, but I don't understand de development process with Neovim's rplugins. Could you please help me out just a bit?

- How do I reload the plugin so that changes I make in the plugin's code are reflected in the next call to any of its functions?
- Can I debug with pdb or similar (stepping, var printing, etc)?
- Whats a good debugging strategy?

**Comment by Shougo** [comment]
@eltechnic0 You should check `:!ls` in the first.
Output source just executes the Vim command.

**Comment by eltechnic0** [comment]
`!ls` works fine. However, output source runs the command through the shell with `subprocess.check_output()` when there is a `!` prefixing the command. 

As I said, I would like to see more into this on my own, but I don't know how to update the plugin in nvim when I make changes to it, so I can't debug it.

**Comment by Shougo** [comment]
OK.  I get it.

**Comment by Shougo** [comment]
It is the feature currently.
