### ISSUE TITLE
Denite shows duplicate matches in a large project

### ISSUE THREAD

**Issue by kalekseev** [Shougo/denite.nvim#368]
# Problems summary

After this [commit](9660900) `:Denite grep` shows the same matches (files) infinitely in its window. Reproduced only on large projects (lots of files)

## Expected
Only unique matches displayed.

## Environment Information (Required!)

 * denite version(SHA1):
d434872 - but all version fails after the commit 9660900.

 * OS: os x

 * Vim/neovim version: 
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/config -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/src/nvim/auto -I/tmp/neovim-20170707-80027-1bg0wcx/neovim-0.2.0/build/include
Compiled by brew@Sierra-2.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.0_1/share/nvim"
```

 * `:CheckHealth` result(neovim only):
no ERRORS

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
filetype plugin indent on
syntax on
call denite#custom#var('grep', 'command', ['rg', '--threads', '1'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'default_opts',
    \ ['--vimgrep', '--no-heading'])
```

With `ag` I get the same result.

## The reproduce ways from neovim starting (Required!)

```
:Denite grep
pattern: keyword
```

## Screen shot (if possible)
![2017-09-08 16 57 52](https://user-images.githubusercontent.com/367259/30215098-6cac733e-94b7-11e7-89e6-ae7b3f25d689.png)
In fact it must show only two unique matches

**Comment by kalekseev** [comment]
Edited link to commit which introduced the problem 9660900.

**Comment by anxolerd** [comment]
I experience this issue as well alongside with #367

**Comment by somini** [comment]
I can reproduce this with the default grep configuration.
The same thing happens for interactive mode: `Denite grep:::!`

I checked and it seems the underlying grep process stops but denite keeps rereading its output. Might be a nvim bug, I'm on nvim v0.2.0 too.

Here's my ripgrep Denite [configuration](https://gitlab.com/somini/dotnvim/blob/master/init.vim#L611-619):
```
"" Grep: ripgrep
call denite#custom#alias('source', 'grep/ripgrep', 'grep')
call denite#custom#var('grep/ripgrep', 'command', ['rg'])
call denite#custom#var('grep/ripgrep', 'default_opts',
			\ ['--vimgrep', '--no-heading', '--hidden'] + s:ignore_globs__ripgrep )
call denite#custom#var('grep/ripgrep', 'recursive_opts', [])
call denite#custom#var('grep/ripgrep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep/ripgrep', 'separator', ['--'])
call denite#custom#var('grep/ripgrep', 'final_opts', [])
```
With this configuration the problem disappears for both regular and interactive modes.
Use it with `Denite grep/ripgrep` or `Denite grep/ripgrep:::!`

**Comment by Shougo** [comment]
I will check the behavior.
Please wait.
