### ISSUE TITLE
選択したcandidateに応じてcandidatesリストを更新したい

### ISSUE THREAD

**Issue by tortuepin** [Shougo/denite.nvim#370]
# Problems summary
以下のようなものを作りたいと考えています。

- カレントバッファのある行を与えて、それに関連する行のリストを表示する

- 表示されたリストの中から1行選択すると、さらにそれに関連する行を集めてきて表示する

関連する行を集めるのはgather_candidatesで行っているので、選択された行の情報をgather_candidatesに伝える必要があるのですが、そのような方法はあるのでしょうか。(actionから渡す方法があるのか、あるいは別の方法があるのか)

## Expected

選択したcandidateの情報をgather_candidatesに伝え、表示するcandidatesリストを更新したい

## Environment Information (Required!)

 * denite version(SHA1): fbcaeb7

 * OS: macOS Sierra

 * Vim/neovim version: NVIM v0.2.0

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/denite.nvim/
```

**Comment by Shougo** [comment]
action 側から見ると context['source'] に source の context 情報があります。
こちらに情報を渡してください。
あとは action を readraw action として定義することで実現できるはずです。
