### ISSUE TITLE
Empty "-sorters=" option  in command does not work

### ISSUE THREAD

**Issue by kshpytsya** [Shougo/denite.nvim#378]
# Problems summary

Empty "-sorters=" option  in command does not work.

## Expected

Ability to somehow specify the use of "natural" -- i.e. as originating from source -- order.

## Environment Information (Required!)

 * denite version(SHA1): d707fe20c5fe8281e90356f8cf146eef7c189da8

 * OS: Gentoo Linux 64bit

 * Vim/neovim version: vim 8.0.1175

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set nocompatible
set runtimepath+=/home/uken/.vim/bundle//repos/github.com/Shougo/denite.nvim
filetype plugin indent on
syntax enable
```

## The reproduce ways from vim starting

 1. `:Denite -sorters= -matchers=matcher_substring output:"!seq 1000 -1 1"`
 2. type `99`
 3. observe that order of candidate corresponds to that of `sorter_rank`, which can be additionally confirmed by adding a `debug` in `denite/filter/sorter_rank.py` `filter` method.

Note: non-empty `-sorters` works as expected, e.g. `:Denite -sorters=sorter_reverse -matchers=matcher_substring output:"!seq 1000"`

**Comment by Shougo** [comment]
It is the feature.
Because, the sort is executed after the source sorter(`sorter_rank`).

**Comment by Shougo** [comment]
Empty `-sorters=` is nothing to do after the source sorter.
So it is expected behavior.

**Comment by kshpytsya** [comment]
If so, I would suggest tat the documentation is missing a high-level description of a pipeline, that would allow users to build a proper mental picture of interaction of sources, matchers, and sorters.

It is unclear, why it is possible to set default `sorters` to none as

```vim
call denite#custom#source('_', 'sorters', [])
```

and afterwards be able to override it via `-sorters` option in `Denite*` command, but impossible to do it the other way around, i.e. have implicit or even explicit default `sorters` set to something, e.g. `sorter_rank` and be able to override it to no sorter in specific command invocation. Seems like an oversight to me.

BTW, why `sorters` and not `sorter`? Does it ever make sense to have several sorters chained? Also, why `sorter_xxx` and not just `xxx` for option value?

**Comment by Shougo** [comment]
> If so, I would suggest that the documentation is missing a high-level description of a pipeline, that would allow users to build a proper mental picture of interaction of sources, matchers, and sorters.

You can improve it.  The PR is wellcome.

**Comment by Shougo** [comment]
> BTW, why sorters and not sorter? Does it ever make sense to have several sorters chained? Also, why sorter_xxx and not just xxx for option value?

Because it is list.
I don't think it is not so useful.  But `matchers` and `converters` must be list.

`sorter_xxx` is just filter for sorting.
It has the same interface with `matcher_xxx` and `converter_xxx`
Have you use unite.vim?
It is the same feature.
