### ISSUE TITLE
Unset `cursorcolumn`

### ISSUE THREAD

**Issue by kshpytsya** [Shougo/denite.nvim#379]
# Problems summary

If `cursorcolumn` option is globally enabled in `.vimrc`, it will be active in denite buffers as well but since there are no horizontal cursor movements, the column highlighting is distracting.

## Expected

Unset `cursorcolumn` for denite buffers

## Environment Information (Required!)

 * denite version(SHA1): d707fe20c5fe8281e90356f8cf146eef7c189da8

 * OS: Gentoo Linux 64bit

 * Vim/neovim version: vim 8.0.1175

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible
set runtimepath+=/home/uken/.vim/bundle//repos/github.com/Shougo/denite.nvim
filetype plugin indent on
syntax enable
set cursorcolumn
colorscheme slate
```

## The reproduce ways from vim starting

 1. `:Denite output:"!seq 10"`
 2. observe first column in denite buffer highlighted

## Possible fix

Add `'cursorcolumn': False,` to `window_options` in `rplugin/python3/denite/ui/default.py`

**Comment by Shougo** [comment]
Fixed
