### ISSUE TITLE
Can't input '9' key.

### ISSUE THREAD

**Issue by typetonk2** [Shougo/denite.nvim#38]
# Problems summary

I at the time of fuzzy search, can't input the '9' key.  
When I press the '9' key, the cursor will move down(it looks like 'move_to_next_line' mapping has been executed)
## Expected

That I can input '9' key.
## Environment Information
- OS:
  
  Windows10 64bit
- nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
  https://github.com/tweekmonster/nvim-python-doctor
  
  Because of my vim is vim8, not neovim. So :CheckHealth command is not.
## Neovim Python Diagnostic

nothing. :version output instead.

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 13 2016 09:59:10)
MS-Windows 64-bit GUI version
Included patches: 1-3
```
## Python versions visible to Neovim

`:py3 print('sys.version')` output is below.

```
3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
```
### 'python' info from /usr/local/bin/nvim

nothing
### 'python3' info from /usr/local/bin/nvim

nothing.
## Python versions visible in the current shell

same is `Python versions visible to Neovim`.
## Provide a minimal init.vim with less than 50 lines (Required!)

_vimrc is below.

``` vim
set shellslash
filetype plugin indent on
let $MY_VIMRUNTIME = $VIM . "/vimfiles"

if &compatible
  set nocompatible
endif
let s:dein_dir = expand('$MY_VIMRUNTIME/dein')
let g:dein#install_log_filename = s:dein_dir . '/dein.log'
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif
if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/denite.nvim')
call dein#end()
call dein#save_state()
endif
if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
```
## The reproduce ways from neovim starting (Required!)
1. pre-installed python3.5, and set the PATH environment.
2. Download kaoriya-vim.  
   [Vim — KaoriYa](https://www.kaoriya.net/software/vim/)
3. put the _vimrc same location as kaoriya-vim/gvim.exe.
4. run 'gvim.exe'.
5. run ':Denite file_rec' or command, buffer, line, etc.
## Generate a logfile if appropriate

nothing.
## Screen shot (if possible)

nothing.
## Upload the log file

nothing.

**Comment by HerringtonDarkholme** [comment]
Also reproduced in neovim 0.1.6, python3.5, ubuntu 16.04
