### ISSUE TITLE
Feature request: incremental search

### ISSUE THREAD

**Issue by kshpytsya** [Shougo/denite.nvim#380]
# Problems summary

Implement incremental search in denite buffers by pressing `/` key in `normal` mode. I used it quite a lot with `Unite`.

## Environment Information (Required!)

 * denite version(SHA1): d707fe20c5fe8281e90356f8cf146eef7c189da8

 * OS: Gentoo Linux 64bit

 * Vim/neovim version: vim 8.0.1175

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible
set runtimepath+=/home/uken/.vim/bundle//repos/github.com/Shougo/denite.nvim
filetype plugin indent on
syntax enable
```

**Comment by Shougo** [comment]
```vim
  nnoremap <silent> / :<C-u>Denite -buffer-name=search -auto-highlight line<CR>
```

**Comment by kshpytsya** [comment]
Apparently the description was not clear enough. I meant incremental search while navigating Denite buffers themselves. `normal` mode meant Denite's `normal` mode, and not vim's `normal` mode. Sometimes I want to navigate/choose a certain candidate by means of finding, and not by means of filtering.

**Comment by Shougo** [comment]
Hm.  OK.  It is not supported.
I don't think it is useful.

**Comment by wilywampa** [comment]
I also think it is very useful and often miss being able to do it. The most common situation is when I'm using denite grep. The candidates are in the format `filename: search result` and it's useful to be able to search the filenames of the grep results instead of only being able to filter the search result part.

**Comment by Shougo** [comment]
I don't want to create incremantal search feature.

> Implement incremental search in denite buffers by pressing / key in normal mode. I used it quite a lot with Unite.

It does not work in unite.vim.
Because unite creates the buffer lines dynamically.
