### ISSUE TITLE
Feature request: outline source improvements

### ISSUE THREAD

**Issue by kshpytsya** [Shougo/denite.nvim#381]
# Problems summary

To me, denite's outline source is missing two critical features `unite-outline` has: order (denite's source outputs candidates in alphabetical order, apparently just as produced by `ctags`, whereas `unite-outline` orders items according to their location in source file) and indentation. Without these two, the `outline` name is a misnomer, as it should be called just `tags` or `ctags`.

Somehow, without adding `--c++-kinds=cdefgmnstup` ctags option which was present in `unite ouline` some class methods are missing from the list.

Also desirable:

* to be able to process unsaved changes (i.e. if file has been modified, save a temp file, or, better yet, run `ctags   --language-force=... /dev/stdin`).
* to display function signatures
* to select current item according to the current position in source file, i.e. select the first tag that is above or in the same line as the current source line

## Environment Information

 * denite version(SHA1): d707fe20c5fe8281e90356f8cf146eef7c189da8

 * OS: Gentoo Linux 64bit

 * Vim/neovim version: vim 8.0.1175

## Provide a minimal init.vim with less than 50 lines

```vim
set nocompatible
set runtimepath+=/home/uken/.vim/bundle//repos/github.com/Shougo/denite.nvim
filetype plugin indent on
syntax enable
```

**Comment by wilywampa** [comment]
Being able to display function signatures would be a big help. The source is not very helpful when multiple functions of the same name take different types as an argument - they're all just shown with the same name repeated x times.

**Comment by Shougo** [comment]
You can improve the source.
It is the open source, isn't it?

**Comment by kshpytsya** [comment]
@Shougo, does this mean that you have no plans/visions for improving this? Of course, me or someone else can do it, but a clarification is needed so as not to collide with your possible work in progress.

**Comment by Shougo** [comment]
Yes.  I have not much time to improve the source.
I just have merged the PR.
https://github.com/Shougo/denite.nvim/pull/114
