### ISSUE TITLE
Relaunch Denite from an Kind action breaks refinement

### ISSUE THREAD

**Issue by dsummersl** [Shougo/denite.nvim#387]
I'm working on a new Kind plugin that has an action to change the list of items in Denite, and then wants to redisplay the changed list. I tried, something like:

```
class MyNewKind(Kind):
    def action_refine(self, context):
       # do my special filtering
       self.vim.command('Denite myplugin')
```

But the highlight is messed up - my modified list appears, but filtering and highlight groups look wrong...I suspect I need to restart denite is nome different way. How does one re-launch denite from within an action?

**Comment by Shougo** [comment]
It is not supported.
So, the behavior is undefined!

I think denite.nvim should support the feature.
But I am busy.

**Comment by dsummersl** [comment]
I understand, thank you for this great reboot to Unite. If I find time to figure this out, I'll submit a PR.

**Comment by Shougo** [comment]
I will add the feature.
If I have the free time.

**Comment by Shougo** [comment]
I have added the feature.

**Comment by dsummersl** [comment]
ty! Works great!
