### ISSUE TITLE
Error when opening denite file_rec buffer with matcher_cpsm enabled

### ISSUE THREAD

**Issue by FuzzOli87** [Shougo/denite.nvim#390]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When using matcher_cpsm on file_rec, I get the error when I start to type for filter files:
![image](https://user-images.githubusercontent.com/12246915/32384846-38536832-c08a-11e7-903b-bd9d7a5b143d.png)

## Expected
The files to be filtered by the words I type

## Environment Information (Required!)

 * denite version(SHA1):

 * OS:
OSX Sierra

 * Vim/neovim version:
NVIM v0.2.1-1124-g739bc5124
Build type: Release

 * `:checkhealth` or `:CheckHealth` result(neovim only):

![image](https://user-images.githubusercontent.com/12246915/32384944-8918ae80-c08a-11e7-8041-da31af301b20.png)

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/site/plugged')
""""""" Javascript ===============================================

Plug 'Shougo/denite.nvim'
Plug 'nixprime/cpsm', { 'do': 'PY3=ON ./install.sh' }

call plug#end()
"

" Change file_rec command.
call denite#custom#var('file_rec', 'command',
      \ ['ag', '--follow', '--nocolor', '--nogroup', '--hidden', '-g', '',
      \ '--ignore', '.git'])

" Change mappings.
call denite#custom#map(
      \ 'insert',
      \ '<Tab>',
      \ '<denite:move_to_next_line>',
      \ 'noremap'
      \)
call denite#custom#map(
      \ 'insert',
      \ '<s-Tab>',
      \ '<denite:move_to_previous_line>',
      \ 'noremap'
      \)

call denite#custom#map(
      \ 'insert',
      \ '<C-space>',
      \ '<denite:choose_action>',
      \ 'noremap'
      \)

call denite#custom#source(
      \ 'file_rec', 'matchers', ['matcher_cpsm'])

nmap <space> [denite]
nnoremap [denite] <Nop>

" Quick file search
nnoremap <silent> [denite]f :<C-u>Denite -buffer-name=files file_rec<CR>
```

## The reproduce ways from neovim starting (Required!)

1. Start neovim
2. Spacebar + f to trigger file search
3. Start typing to filter files

## Upload the log file

[pythonlog_py3_rplugin.log](https://github.com/Shougo/denite.nvim/files/1443769/pythonlog_py3_rplugin.log)

**Comment by Shougo** [comment]
Please update the log file!
Python process seems crashed.

It is required.

```
 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}
```

**Comment by Shougo** [comment]
I think your cpsm binary is broken.
Please re-build it manually.

**Comment by FuzzOli87** [comment]
@Shougo I've rebuilt the library manually several times and I still get the same errors. I've attached the Python logs.

**Comment by Shougo** [comment]
I get the log, but I cannot find the crash.

Please test your cpsm binary using other plugin like ctrlp.

**Comment by Shougo** [comment]
Oh, I get it.
You have used pyenv Python.
You must build cpsm by pyenv Python.
It seems version conflict.

**Comment by FuzzOli87** [comment]
Ohh! @Shougo wow! That makes sense. Bc I run the install step outside the pyenv context! Thanks for taking a look!
