### ISSUE TITLE
Documentation for 'switch' action is unclear

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Shougo/denite.nvim#391]
Hey! I've been reading the documentation, and trying to learn to use Denite; and the following really doesn't explain what the various `switch` actions do:

```
	open (default)
		Open the object.

	tabopen
		Open the object in the next tab.

… cut …

	switch
		Switch to the window that is opening the
		object.

	tabswitch
		Switch to the window that is opening the
		object. If it isn't opened, fallback tabopen.
```

I've tried mapping them to a key, but I can't quite figure out what the difference between `open` and `switch` is! `(=`

(“Environment Information” omitted, as this isn't a bug.)

**Comment by Shougo** [comment]
> I've tried mapping them to a key, but I can't quite figure out what the difference between open and `switch` is! `(=`

It means:
If you have opened the file, Vim/neovim switches to the window or buffer.
