### ISSUE TITLE
-auto-preview should support all entry-types

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Shougo/denite.nvim#392]
# Problems summary
When using `'auto_preview': v:true`, including any source that *doesn't* have a 'preview' action defined will cause the following error:

    [denite] Invalid action: preview

This is particularly noticeable in the following, very useful case — if `-auto-preview` is desired for `file_rec`, but `buffer` is included first, then the error-message will *always* appear immediately, because the initially-selected item is a `buffer`, which doesn't support the `preview` action.

    nnoremap <C-p>  :<C-u>Denite -source-names=hide buffer file_rec<CR>

Personally, I think `-auto-preview` should never cause an error. An error is reasonable when a user's mapped key invokes an action, so they know “why it didn't happen”, but in the case of an automatic action that happens for every line … well …

## Environment Information (Required!)
  * denite version(SHA1): I don't know how to get this information
  * OS: macOS **10.13.1** (17B25c)
  * Vim/neovim version:

        NVIM v0.2.1-331-g6650588c
        Build type: RelWithDebInfo
        Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170614-52857-dmx2ql/build/config -I/tmp/neovim-20170614-52857-dmx2ql/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/tmp/neovim-20170614-52857-dmx2ql/build/src/nvim/auto -I/tmp/neovim-20170614-52857-dmx2ql/build/include
        Compiled by ec@Fannie.local
        
        Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
        For differences from Vim, see :help vim-differences
        
           system vimrc file: "$VIM/sysinit.vim"
          fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-6650588/share/nvim"

  * `:checkhealth` or `:CheckHealth` result(neovim only):

        health#deoplete#check
        ========================================================================
        ## deoplete.nvim
          - SUCCESS: has("nvim") was successful
          - SUCCESS: has("python3") was successful
          - INFO: If you're still having problems, try the following commands:
            $ export NVIM_PYTHON_LOG_FILE=/tmp/log
            $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
            $ nvim
            $ cat /tmp/log_{PID}
            and then create an issue on github
        
        health#nvim#check
        ========================================================================
        ## Configuration
          - SUCCESS: no issues found
        
        ## Performance
          - SUCCESS: Build type: RelWithDebInfo
        
        ## Remote Plugins
          - WARNING: "deoplete.nvim" is not registered.
          - WARNING: Out of date
            - SUGGESTIONS:
              - Run `:UpdateRemotePlugins`
        
        ## terminal
          - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
          - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
        
        health#provider#check
        ========================================================================
        ## Clipboard (optional)
          - SUCCESS: Clipboard tool found: pbcopy
        
        ## Python 2 provider (optional)
          - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
          - INFO: Executable: /usr/local/bin/python2
          - INFO: Python2 version: 2.7.13
          - INFO: python2-neovim version: 0.1.13 (outdated; from /usr/local/lib/python2.7/site-packages/neovim)
          - WARNING: Latest python2-neovim is NOT installed: 0.2.0
        
        ## Python 3 provider (optional)
          - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
          - INFO: Executable: /usr/local/bin/python3
          - INFO: Python3 version: 3.6.3
          - INFO: python3-neovim version: 0.2.0
          - SUCCESS: Latest python3-neovim is installed: 0.2.0
        
        ## Ruby provider (optional)
          - INFO: Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
          - INFO: Host: /usr/local/bin/neovim-ruby-host
          - SUCCESS: Latest "neovim" gem is installed: 0.6.1

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/

" <Ctrl-P> for both switching between buffers, and opening new ones!
nnoremap <C-p> :<C-u>Denite -source-names=hide buffer file_rec<CR>

" ...


"" === Plugins ===

" #### Denite
call denite#custom#option('_', {
 \    'auto_preview':   v:true
 \ })
```

## The reproduce ways from neovim starting (Required!)

1. Open with the above configuration
2. <kbd>Ctrl</kbd>-<kbd>p</kbd>
3. <kbd>Ctrl</kbd>-<kbd>c</kbd>
4. `:messages`

## Screenshots
![](http://ell.io/iiJjykn+?.png)
![](http://ell.io/iDyJFUu+?.png)

**Comment by Shougo** [comment]
Implemented.
