### ISSUE TITLE
-auto-preview causes E903: Process failed to start: too many open files

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Shougo/denite.nvim#394]
# Problems summary
When using `'auto_preview': v:true`, Vim opens so many buffers that I very quickly run into the message:

    [denite] neovim.api.nvim.NvimError: b'Vim(call):E903: Process failed to start: too many open files: "sh"'

It seems the 'preview' window is leaving all those buffers open in the background, as you scroll down.

It's probably a better idea to clear each one when moving to the next — or at least have an internal limit (3? 5?) on the number to cache / keep open.

(Relatedly, the `buffers` source will happily display all the buffers that the `file_rec` source just created. I don't know if there's a way to hide those, but …)

## Environment Information (Required!)
  * denite version(SHA1): I don't know how to get this information
  * OS: macOS **10.13.1** (17B25c)
  * Vim/neovim version:

        NVIM v0.2.1-331-g6650588c
        Build type: RelWithDebInfo
        Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -g -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20170614-52857-dmx2ql/build/config -I/tmp/neovim-20170614-52857-dmx2ql/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk/usr/include -I/tmp/neovim-20170614-52857-dmx2ql/build/src/nvim/auto -I/tmp/neovim-20170614-52857-dmx2ql/build/include
        Compiled by ec@Fannie.local
        
        Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
        For differences from Vim, see :help vim-differences
        
           system vimrc file: "$VIM/sysinit.vim"
          fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD-6650588/share/nvim"

  * `:checkhealth` or `:CheckHealth` result(neovim only):

        health#deoplete#check
        ========================================================================
        ## deoplete.nvim
          - SUCCESS: has("nvim") was successful
          - SUCCESS: has("python3") was successful
          - INFO: If you're still having problems, try the following commands:
            $ export NVIM_PYTHON_LOG_FILE=/tmp/log
            $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
            $ nvim
            $ cat /tmp/log_{PID}
            and then create an issue on github
        
        health#nvim#check
        ========================================================================
        ## Configuration
          - SUCCESS: no issues found
        
        ## Performance
          - SUCCESS: Build type: RelWithDebInfo
        
        ## Remote Plugins
          - WARNING: "deoplete.nvim" is not registered.
          - WARNING: Out of date
            - SUGGESTIONS:
              - Run `:UpdateRemotePlugins`
        
        ## terminal
          - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
          - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
        
        health#provider#check
        ========================================================================
        ## Clipboard (optional)
          - SUCCESS: Clipboard tool found: pbcopy
        
        ## Python 2 provider (optional)
          - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
          - INFO: Executable: /usr/local/bin/python2
          - INFO: Python2 version: 2.7.13
          - INFO: python2-neovim version: 0.1.13 (outdated; from /usr/local/lib/python2.7/site-packages/neovim)
          - WARNING: Latest python2-neovim is NOT installed: 0.2.0
        
        ## Python 3 provider (optional)
          - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
          - INFO: Executable: /usr/local/bin/python3
          - INFO: Python3 version: 3.6.3
          - INFO: python3-neovim version: 0.2.0
          - SUCCESS: Latest python3-neovim is installed: 0.2.0
        
        ## Ruby provider (optional)
          - INFO: Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
          - INFO: Host: /usr/local/bin/neovim-ruby-host
          - SUCCESS: Latest "neovim" gem is installed: 0.6.1

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/

" <Ctrl-P> for both switching between buffers, and opening new ones!
nnoremap <C-p> :<C-u>Denite -source-names=hide buffer file_rec<CR>

" ...


"" === Plugins ===

" #### Denite
call denite#custom#option('_', {
 \    'auto_preview':   v:true
 \ })
```

## The reproduce ways from neovim starting (Required!)

1. Lower the `ulimit` of your terminal, launch Vim
2. `:Denite -auto-preview file_rec`
3. <kbd>↓</kbd>, <kbd>↓</kbd>, <kbd>↓</kbd>, etc
4. <kbd>Ctrl</kbd>-<kbd>c</kbd>
5. `:messages`

## Screenshots
* **29** file-descriptors open before launching Denite,

   ![](http://ell.io/iHj5bYu+?.png)

* *≥100* file-descriptors after hitting "down" a few times

   ![](http://ell.io/iRmIfyj+?.png)

**Comment by Shougo** [comment]
Oh, Mac OS X.
Mac OS X resource limitation is very few.
