### ISSUE TITLE
Denite prevents to focus the preview window (Regression to Unite)

### ISSUE THREAD

**Issue by maikelmeyers** [Shougo/denite.nvim#398]
# Problems summary
Using Denite with autopreview it is not possible to change the focus to the preview window for small editing tasks or moving around. This is a regression to Unite.

## Expected
I can change the focus to the preview window with a shortcut or the mouse

## Environment Information (Required!)

 * denite version(SHA1): 21940ea

 * OS: Arch Linux 4.13.12-1-ARCH x86_64 GNU/Linux

 * Vim/neovim version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 24 2017 16:04:43)
Included patches: 1-1333

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/

" no settings needed
```

## The reproduce ways from neovim starting (Required!)

 1. :Denite -auto-preview file_rec

**Comment by Shougo** [comment]
It is the feature.
Sorry.
