### ISSUE TITLE
Feature request: unmap key bind

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Shougo/denite.nvim#400]
Real simple:

`denite#custom#map({mode}, {lhs})` with no third `{rhs}` argument should remove the existing mapping for `{mode}`.

I ask this, because at the moment, to override a mode-specific mapping with an all-mode mapping, I have to do this:

    call denite#custom#map('_',      '<C-t>', '<denite:do_action:tabswitch>', 'noremap')
    call denite#custom#map('insert', '<C-t>', '<denite:do_action:tabswitch>', 'noremap')

In addition to that being not-very-D.R.Y., if I later want to dynamically *remap* those, or anything like that, I have to carefully remember that `<C-t>` is “one of the ones I doubly-mapped”.

Instead, I'd really like to be able to *unmap* it in `insert` mode, allowing a single `_` mapping to take effect globally:

    call denite#custom#map('insert', '<C-t>')
    call denite#custom#map('_',      '<C-t>', '<denite:do_action:tabswitch>', 'noremap')

(Alternatively, providing `denite#custom#unmap` might be a good idea? Up to you!)

**Comment by Shougo** [comment]
Please use `<Nop>` for it.
