### ISSUE TITLE
-no-quit option does not work on Vim8

### ISSUE THREAD

**Issue by totem3** [Shougo/denite.nvim#401]
**Warning:  I will close the bug issue without the minimal init.vim and the reproduce ways.**

# Problems summary

When passing `-no-quit` option to `:Denite` command, Denite buffer is closed after an action is executed.

## Expected

Denite buffer remains open after an action is executed.

## Environment Information (Required!)

 * denite version(SHA1):
ed39c3dd3c70bddedab3700d5906319adef6825e

 * OS:
Mac OSX 10.12

 * Vim/neovim version:
vim 8.0 1-1379

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. `:Denite -no-quit file`
 2. choose a file

## Screen shot (if possible)

![out](https://user-images.githubusercontent.com/1212611/34229069-4d7d55b8-e616-11e7-91e4-9af5c40a60b6.gif)

**Comment by Shougo** [comment]
Reproduced.
I will fix it.
