### ISSUE TITLE
Autocommand for other buffer is triggered when opening and closing denite

### ISSUE THREAD

**Issue by glacambre** [Shougo/denite.nvim#405]
# Problems summary
Open an empty nvim instance. Open two vertically split windows, the first one (on the left) for a buffer named "a" and the other one (on the right) for a buffer named "b". Move to the window containing the buffer b and add a BufEnter autocommand for buffer a. Then open denite, press escape to close the denite window. The cursor should be back into buffer "b", however you will notice that the autocommand for buffer "a" has been triggered.

## Expected
Since I'm back in buffer "b", I expect the autocommand for buffer "a" to not have been triggered.

## Environment Information

 * denite version(SHA1): 5b2cd926ba1e114f7851172fd799e610a4f0cc30
 * OS: Linux 4.12.5-gentoo
 * Vim/neovim version: NVIM v0.2.3-70-g27f9b1c7b
 * `:checkhealth` or `:CheckHealth` result(neovim only): Everything seems ok.

## The reproduce ways from neovim starting (Required!)
Reproducible with `nvim -u NONE` and adding Denite to the runtimepath:
```vimscript
set splitright
edit a
vsplit b
autocommand BufEnter a startinsert
Denite grep
<Esc>
```
  
Thank you for maintaining Denite by the way, it's an excellent plugin!

**Comment by Shougo** [comment]
Sorry, it is the feature.
denite.nvim must restore previous buffer behavior.
If you have opened denite buffer, the previous buffer will be changed to the denite buffer.
So, denite.nvim moves to the previous buffer `a` before jumping back `b`.

**Comment by glacambre** [comment]
@Shougo Couldn't this be "solved" by using `call win_gotoid(win_getid(winnr("#")))` before closing the denite window? Sorry if my question is dumb, I don't know much about Denite or Vim's internals.
