### ISSUE TITLE
Parameter 'buffers' not working in source 'line'

### ISSUE THREAD

**Issue by uinput** [Shougo/denite.nvim#408]
# Problems summary
I'd like to be able to search through all lines of all open buffers using Denite. When using `:Denite line:buffers`, I would only be able to search through the lines of the buffer currently open.

## Expected
I expect to see matches of lines of other buffers than the currently open one.

## Environment Information
 * denite version(SHA1): 5b2cd926ba1e114f7851172fd799e610a4f0cc30
 * OS: Fedora 27
 * Vim/neovim version: 0.2.1
 * `:checkhealth` or `:CheckHealth` result(neovim only): `python3-neovim version: 0.1.13 (outdated)`

## Provide a minimal init.vim with less than 50 lines
Reproducible with `nvim -u NONE` and adding Denite to the runtimepath.

## The reproduce ways from neovim starting

 1. Open two buffers
 2. Issue `:Denite line:buffers`
 3. Check if you get lines of the other buffer

**Comment by Shougo** [comment]
Sorry, it is the feature of Vim.
Vim/neovim cannot get the buffer lines until loading.

**Comment by uinput** [comment]
So what exactly is the `buffers` argument for when using the `line` source? I thought it was there to search the lines of all open buffers.

**Comment by Shougo** [comment]
> I thought it was there to search the lines of all open buffers.

Yes.  But it is not opened until loading.

**Comment by Shougo** [comment]
If you have executed `nvim a b`:

b is not opened until editing.  So `line:buffers` does not work for b.

**Comment by Shougo** [comment]
Vim/neovim uses lazy loading feature.

**Comment by uinput** [comment]
Yeah, but I open them one after each other using `:e <filename>`, so when issuing `:Denite buffer`, both files appear. Is only the buffer loaded, thats currently open in my window?

**Comment by Shougo** [comment]
If you use `e <filename>`, the file is loaded.
So you can use `line:buffers`.

**Comment by uinput** [comment]
Also, `context['__bufnrs']` of the `gather_candidates` method has length `3` at the moment of issuing. This tells me that `Denite` knows about both open buffers (i guess the third one is Denite's window). It also iterates through each of these, but I only get lines of the currently shown (in the opened window) buffer.

**Comment by Shougo** [comment]
Please provide the reproduce ways by the commands.
I don't understand the behavior.

**Comment by Shougo** [comment]
> Open two buffers

It is the important!
What are the commands?

**Comment by Shougo** [comment]
> This tells me that Denite knows about both open buffers (i guess the third one is Denite's window). It also iterates through each of these, but I only get lines of the currently shown (in the opened window) buffer.

Denite can get the all buffer lines.
But not loaded buffers are empty lines!
So I cannot fix it.

**Comment by uinput** [comment]
I updated the reproduce ways anyway. Not sure why the buffers are not loaded then.

**Comment by Shougo** [comment]
@uinput I cannot reproduce the problem.  It works.
I think you must scroll the denite buffer.

**Comment by uinput** [comment]
@Shougo I'm not sure how it worked for you. When using the `-u NONE` argument, `hidden` would be off by default according to the [vim documentation](http://vimdoc.sourceforge.net/htmldoc/options.html#'hidden'). I tested the `getbufline` method for both `hidden` and `nohidden` where it only worked when `hidden` was set. So if anyone stumbles across the same behavior, simply set `hidden` in your configuration.

**Comment by Shougo** [comment]
Ah, OK.  It is Vim/neovim's feature.
If nohidden, the buffer lines are emtpy.

**Comment by Shougo** [comment]
I have updated the documentation.
