### ISSUE TITLE
Documentation on accessing custom-*source*-context from custom-kinds needs clarification

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Shougo/denite.nvim#411]
The `denite-create-kind` documentation states (see `:help denite-kind-attribute-action_`),

> To get the source context, you could use `"source"` attribute in `{context}`:
>
>     source_context = context['source']
>
> Note: If the candidates source is not single, the `"source"` attribute is empty.

… despite this, I can't figure out how to access the `Source`-context properties from the `Kind`-context.

----

Now, in my custom source, I have a `{context}`-attribute named `__cursor_pos`:

```python
class Source(BaseSource):
    def on_init(self, context):
        # ...
        context['__cursor_pos'] = "{0}:{1}".format(pos[0], pos[1])
```

I attempt to access this, in my custom kind:

```python
class Kind(BaseKind):
    # ...
    def action_open(self, context):
        target = context['targets'][0]
        self.vim.call('merlin#Locate', target['source__identifier'], context['source']['__cursor_pos'])
```

This, however, spits out:

```
[denite]   File "/Users/ec/Documents/Code/Source/merlin/vim/merlin/rplugin/python3/denite/source/ocaml_identifier.py", line 63, in action_open
[denite]     self.vim.call('merlin#Locate', target['source__identifier'], context['source']['__cursor_pos'])
[denite] KeyError: '__cursor_pos'
```

I tried to debug this with `self.vim.command('echom "' + repr(context['source']) + '"')`, but all I get out of that is an empty representation: `"{}"`.

For context, [here's my entire Python file](https://github.com/ELLIOTTCABLE/merlin/blob/a7169cbaa37a8a659c9eb6650fa90c7dea141bf9/vim/merlin/rplugin/python3/denite/source/ocaml_identifier.py) implementing my `Source`/`Kind`, so far.

What am I doing wrong? `v.v`

**Comment by ELLIOTTCABLE** [comment]
(I did note the “If the candidates source is not single, the "source" attribute is empty.”-line, but I can't say I understood it clearly. It seems to be saying that `context['source']` will be the empty dictionary — which is what is happening to me — only if there is *more than one source* selected? I'm getting this error with only a single candidate selected, though, so as far as I can tell, that doesn't apply to this situation.)

**Comment by Shougo** [comment]
Please see below code.

```vim
    def do_action(self, context, action_name, targets):
        action = self.get_action(context, action_name, targets)
        if not action:
            return True

        sources = set()
        for target in targets:
            sources.add(target['source'])
        context['source'] = self._sources[
            sources.pop()].context if len(sources) == 1 else {}

        context['targets'] = targets
        return action['func'](context) if action['func'] else self._vim.call(
            'denite#custom#call_action',
            action['kind'], action['name'], context)
```

`context['source']` should set if the candidate is selected.
I want to test your code.
Please update your source.

**Comment by ELLIOTTCABLE** [comment]
I'll update and edit this post in a second …

**Comment by Shougo** [comment]
I get the problem.
It is the bug.

**Comment by ELLIOTTCABLE** [comment]
Oh, excellent! I was in the middle of writing up some precise reproduction instructions¹ — I'll scratch all that, then! Hahaha.

Did you already figure out the problem, or do you want me to take a look at it? (I've got the time, and motivation, to make this work, so if it saves you some effort, I'm happy to!)

----

> 1. (by the way, “reproduce ways” sounds a little strange, in English! just a tip. 😊)

**Comment by Shougo** [comment]
> by the way, “reproduce ways” sounds a little strange, in English!

Please teach for me the more better word.
I will fix the label.

> Did you already figure out the problem, or do you want me to take a look at it? (I've got the time, and motivation, to make this work, so if it saves you some effort, I'm happy to!)

No problem.  I can fix the problem.

But I should improve the implementation.
It takes some time.

**Comment by ELLIOTTCABLE** [comment]
Okay! And I suggest:

 - For the tag: “needs-instructions”, or “needs-reproduction-instructions”
 - For the new-issue-creation instructions:

       **WARNING:  I will close the issue without a minimal init.vim and reproduction instructions.**

**Comment by Shougo** [comment]
OK.  I will fix it later.

**Comment by Shougo** [comment]
I have updated the labels.

**Comment by ELLIOTTCABLE** [comment]
Regarding the original bug:

Part of the confusion of the documentation, for me, is that it didn't make much sense: Why is the *source*-context, a property of the *kind*-context, instead of each individual target? At the moment, the `context['source']` is useless, if more than one Source-candidate is selected; but if each candidate-target had its own `source` attribute, you could preform actions on heterogeneous kinds selected simultaneously.

For instance, instead of:

```python
class Kind(BaseKind):
    def action_open(self, context):
        for target in context['targets']:
            if context['source']:
                foo = context['source']['__foo']
            # ...
```

… you could use:

```python
class Kind(BaseKind):
    def action_open(self, context):
        for target in context['targets']:
            foo = target['source']['__foo']
            # ...
```

**Comment by Shougo** [comment]
>  but if each candidate-target had its own source attribute

`source` attribute is already used.
So it cannot be used.

>  if more than one Source-candidate is selected

You cannot fire the multiple sources action.

**Comment by ELLIOTTCABLE** [comment]
Unfortunately, this didn't fix the error for me! It looks like it should — I updated my code to use `targets[0]['source_context']['__cursor_pos']`, basically; but I'm still getting an empty object for `target['source_context']`, for some reason — despite `context['__cursor_pos']` being added to the Source during `on_init` …

Updated code [in the same place](https://github.com/ELLIOTTCABLE/merlin/blob/fe095687/vim/merlin/rplugin/python3/denite/source/ocaml_identifier.py#L60-L66)! Please help? `v.v`

**Comment by Shougo** [comment]
```
					*denite-kind-attribute-action_*
action_{name} (Function) 			(Optional)
		Custom action logic with {name} as action name. The function
		is passed with {self} and {context}.

		To get the seleted candidate list, you could use "targets"
		attribute in {context}: >

                    targets = context['targets']
<
		To get the source context, you could use "source" attribute in
		"target": >

		    for target in context['targets']:
		      source_context = target['source']
<
		Note: The source must be
		|denite-source-attribute-is_public_context|.
		Note: The source context is "__" prefixed keys (source
		specific keys) only.
```

Please read the documentation.

```python
    def __init__(self, vim):
        super().__init__(vim)

        self.vim = vim
        self.name = 'ocaml_identifier'
        self.kind = Kind(vim)
        self.is_public_context = True
```

`is_public_context = True` is needed for the feature.
