### ISSUE TITLE
file_rec cache feature does not work

### ISSUE THREAD

**Issue by xltan** [Shougo/denite.nvim#413]
# Problems summary
file_rec cache feature does not work.

## Expected
cache should work as documented.

every platform I tested has this problem. I think there is a logic bug in ui/default.py line 652, always redraw.

**Comment by Shougo** [comment]
Please read the issue template.

We need more information to reproduce the problem.

Please create the minimal vimrc and the reproduction instructions.

**Comment by xltan** [comment]
hi~ after the fix, another cache problem occured. **after redraw, the cache cannot be updated.**
steps to reproduce, suppose:
1. Denite file_rec.   result is list1.
2. add a file, then use Denite file_rec.   result is list1, use C-L to redraw, result is list2.
3. Denite file_rec<cr>   expect list2, but still get list1.

**Comment by Shougo** [comment]
@xltan Please test below patch.

```diff
diff --git a/rplugin/python3/denite/ui/action.py b/rplugin/python3/denite/ui/action.py
index cd14dc8..1fa135f 100644
--- a/rplugin/python3/denite/ui/action.py
+++ b/rplugin/python3/denite/ui/action.py
@@ -7,7 +7,7 @@ from denite.prompt.util import build_keyword_pattern_set


 def _redraw(prompt, params):
-    return prompt.denite.redraw()
+    return prompt.denite.redraw(True)


 def _quit(prompt, params):
```

**Comment by xltan** [comment]
no, but I figured out why.
denite/denite.py line 162. `source = copy.copy(self._sources[name])`
so each time the Denite cmd change will only affect the copy of source.

**Comment by Shougo** [comment]
I have tested the behavior.
But I cannot reproduced it!

> Please read the issue template.

> We need more information to reproduce the problem.

> Please create the minimal vimrc and the reproduction instructions.

If you don't get it, I will ignore your problem.

**Comment by Shougo** [comment]
I get the problem.

**Comment by Shougo** [comment]
You should use `-resume` feature instead.
I cannot fix the problem.

**Comment by Shougo** [comment]
I will remove file_rec cache feature.
It does not work properly.
