### ISSUE TITLE
How to set `max_candidates` for specific source?

### ISSUE THREAD

**Issue by unclechu** [Shougo/denite.nvim#414]
I tried this: `call denite#custom#source('file_rec', 'max_candidates', 10)` but got this error: `[denite] Invalid option_name: max_candidates`, how do I actually set `max_candidates` attribute?

**Comment by Shougo** [comment]
Reproduced.  I will fix it.

**Comment by unclechu** [comment]
@Shougo now it doesn't fail but have no effect.
I set:
```viml
call denite#custom#source('line', 'max_candidates', 5)
```
But when I call
```viml
Denite line
```
I see all the lines (in my case it was 39 because it is how many line was in my file).

**Comment by unclechu** [comment]
@Shougo should I create new issue or provide some more information?

**Comment by Shougo** [comment]
No problem.
I have fixed.
