### ISSUE TITLE
"grep" source: How to search by file names?

### ISSUE THREAD

**Issue by unclechu** [Shougo/denite.nvim#418]
When I search with "grep" source (`:Denite grep`) I have file path and matched content separatelly:
![screenshot from 2018-01-17 01-08-22](https://user-images.githubusercontent.com/799353/35010081-82c76be2-fb23-11e7-89a3-dfcd8d7f3737.png)
But I can filter results only by matched lines. I can't filter for instance by file extension, how can I do it?
![selection_036](https://user-images.githubusercontent.com/799353/35010342-62f1ae9e-fb24-11e7-9263-8d539846db07.png)

**Comment by Shougo** [comment]
Please read the FAQ.

```
Q: I want to narrow by path in grep source.

A: >
	call denite#custom#source('grep',
	\ 'converters', ['converter_abbr_word'])
```

**Comment by unclechu** [comment]
Sorry
