### ISSUE TITLE
Custom mappings with modified number keys don't work.

### ISSUE THREAD

**Issue by smackesey** [Shougo/denite.nvim#422]
# Problems summary

Using `call denite#custom#map` on modified number keys (e.g. `<C-1>` does not work.

## Expected

A command like the below should work -- pressing `<C-1>` in insert mode should have the desired effect:

```
call denite#custom#map('insert', '<C-1>', '<denite:move_caret_to_head>', '')
```

## Environment Information (Required!)

 * denite version(SHA1): 7d268cf

 * OS: MacOS 10.13.2

 * Vim/neovim version: Vim 8.0.1420

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
call denite#custom#map('insert', '<C-1>', '<denite:move_caret_to_head>', '')
```

## The reproduce ways from neovim starting (Required!)

 1. start a denite prompt
 2. type some text
 3. press <C-1>

**Comment by Shougo** [comment]
@lambdalisue This feature is supported in nvim-prompt?

**Comment by Shougo** [comment]
I have tested `<C-1>` mapping in Vim, it does not work.
Your Vim supported the mapping?

**Comment by Shougo** [comment]
> A command like the below should work -- pressing `<C-1>` in insert mode should have the desired effect:

If Vim supports it, should work.
But it is not supported.  So I think it is feature.

**Comment by Shougo** [comment]
It does not work in Vim.
Closing.
