### ISSUE TITLE
Denite file with different colors depending on extension

### ISSUE THREAD

**Issue by fab6** [Shougo/denite.nvim#424]
Hi,
Is there a chance to set the color for each file in "Denite file" depending on the extension or type?

**Comment by Shougo** [comment]
I don't want to implement the feature.
It should be implemented in file manager like defx.nvim though.
I think it is not denite.nvim work.

**Comment by fab6** [comment]
ok.

**Comment by fab6** [comment]
I am using https://github.com/inkarkat/vim-mark now with denite and vimfiler. works quite good

**Comment by Shougo** [comment]
OK.
