### ISSUE TITLE
Questions: how to switch to normal mode? how to set disable `hlsearch`?

### ISSUE THREAD

**Issue by artemave** [Shougo/denite.nvim#426]
Hello,

Couple of question:

- once in denite buffer, how to I switch to normal mode? I could see there is `denite:toggle_insert_mode` in the docs, but I don't know how to make use of it.

- I'd like to disable `hlsearch` that mirrors what I type. What is the best way to do that?

Thanks,
Artem

**EDIT**

More generally, `Unite` used to open a regular vim buffer and then all my custom mappings (e.g. `kj` to jump out of `Insert` more) applied. Is there a way to get the same behavior in `Denite`?

**Comment by Shougo** [comment]
`once in denite buffer, how to I switch to normal mode?`

It is mapped to `<C-o>`.

> I'd like to disable hlsearch that mirrors what I type. What is the best way to do that?

`Denite -highlight-matched-char=None`

> More generally, Unite used to open a regular vim buffer and then all my custom mappings (e.g. kj to jump out of Insert more) applied. Is there a way to get the same behavior in Denite?

Nothing.  It is the feature.

**Comment by artemave** [comment]
> Nothing. It is the feature.

What is the benefit of that feature?

I can see the benefit of regular vim buffer (I don't need to learn the whole new set of mappings), but the benefits of Denite approach aren't immediately apparent to me and perhaps some other new comers. Could you elaborate on that please?

Thanks!

**Comment by dkiyatkin** [comment]
@artemave I think <C-z> (suspend) feature is what you need. It's switch denite buffer in to vim-normal mode.

**Comment by gvassallo** [comment]
Is there a way to open Denite in normal mode by default?
