### ISSUE TITLE
Getting list of current suggestions

### ISSUE THREAD

**Issue by naquad** [Shougo/denite.nvim#427]
Is there a way to retrieve list of currently open Denite suggestions?

What about API in general? `denite#do_action` requires context which is not available unless you're within action context.

**Comment by Shougo** [comment]
> Is there a way to retrieve list of currently open Denite suggestions?

Nothing.

> denite#do_action requires context which is not available unless you're within action context.

Yes.

I don't understand why it is needed.

**Comment by wilywampa** [comment]
My fork has a [modification](https://github.com/wilywampa/denite.nvim/blob/master/rplugin/python3/denite/__init__.py#L56) to add `denite#context#get` and `denite#context#set`. I already use it for five different things in my configuration:

1. Get a list of current sorters so I can toggle a specific sorter on and off
2. Check if the current source is some kind of `grep` so my mapping can quit if it's a `grep` source or just switch windows if it's any other source
3. Get the current `grep` input so I can modify the context with a new set of option flags without having to re-enter the input
4. Insert the path of the current non-denite buffer by getting the `bufnr`
5. Insert the filename of the current buffer

I can think of countless use cases.

**Comment by naquad** [comment]
@wilywampa thank you! seems to be exactly what I'm looking for.

@Shougo for example if I want to pass all suggestions to another plugin. My particular case is Denite grep + [EnMasse](https://github.com/Olical/vim-enmasse)

**Comment by Shougo** [comment]
Under consideration

**Comment by Shougo** [comment]
> Get the current grep input so I can modify the context with a new set of option flags without having to re-enter the input

Why don't you use `:Dein -resume`?

**Comment by Shougo** [comment]
> @Shougo for example if I want to pass all suggestions to another plugin. My particular case is Denite grep + EnMasse

Why don't use `quickfix` action?

**Comment by Shougo** [comment]
> Get a list of current sorters so I can toggle a specific sorter on and off

Why don't use `<denite:toggle_sorters:{arg}>`?

**Comment by wilywampa** [comment]
> Why don't you use :Dein -resume?

I don't understand how that would work. How could I pass new context data (the new grep arguments)? Why would I want the two extra steps of quitting and resuming denite manually?

**Comment by Shougo** [comment]
OK.  I get the reason.
It is used for the custom mappings like this?

https://github.com/wilywampa/vimconfig/blob/10684409c629d40ea7c466c0aa3c40470d7cb8a2/_vimrc#L2331

**Comment by wilywampa** [comment]
> Why don't use <denite:toggle_sorters:{arg}>?

That does work and I'll probably switch to that, thanks!


> It is used for the custom mappings like this?

Correct, that's one of the examples.

**Comment by Shougo** [comment]
I don't want to add the APIs for the custom mappings.
It should be supported by more easily ways.

**Comment by Shougo** [comment]
I will add `b:denite_context` variable for the feature.

**Comment by Shougo** [comment]
For `Getting list of current suggestions`, I don't want to support the feature.

**Comment by wilywampa** [comment]
> Why don't use <denite:toggle_sorters:{arg}>?

This actually doesn't quite give the same behavior. If I have multiple sorters active, and I want to toggle only one specific sorter while leaving the others alone, I can't do that with <denite:toggle_sorters:{arg}>. But `b:denite_context` will probably make it possible.

**Comment by naquad** [comment]
> Why don't use quickfix action?

It adds only selected suggestion while I need all of them.
I've tried to make something like this:

```
function! s:DeniteQuickfix(context)
  norm *
  norm <C-E>
  Denite -resume -force-quit
endfunction

call denite#custom#action('file', 'quickfix_all', function('s:DeniteQuickfix'))


call denite#custom#map(
      \ 'insert',
      \ '<C-E>',
      \ '<denite:do_action:quickfix>',
      \ 'noremap'
      \)

call denite#custom#map(
      \ 'insert',
      \ '<C-e>',
      \ '<denite:do_action:quickfix_all>',
      \ 'noremap'
      \)

```

But that doesn't work at all.

**Comment by Shougo** [comment]
It is not supported.
You should create new source for it.

**Comment by naquad** [comment]
Seems I'm not following, could you please explain why it should be a custom source rather than just an action?

**Comment by Shougo** [comment]
Because an action is for `selected candidates`.
It is not for `all candidates`.

**Comment by naquad** [comment]
I'm looking in the docs and I don't see how source will help in that case. The original plan was to make action that will select all candidates (`norm *`) and then run quickfix, but that didn't work out. I'm thinking to try `feedkeys()` but seems I'm going in a wrong direction here.

**Comment by Shougo** [comment]
I use all selects `*` and use action quickfix.
So no need the feature.
