### ISSUE TITLE
delete key behaves as left arrow key

### ISSUE THREAD

**Issue by ggerico** [Shougo/denite.nvim#431]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**
I uses denite for years now, first time it happens.
 
# Problems summary
the delete key has the behavior of the left arrow key

## Expected
the delete key should delete the last character of my search 

## Environment Information (Required!)

 * denite version(SHA1):
8e4aacacd5509795cb94c7e42790cc173baaa276

 * OS: macOs high sierra, iTerm2 3.1.5 (report terminal type: xterm-256color)

 * Vim/neovim version: NVIM v0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.1.13 (outdated; from /usr/local/lib/python2.7/site-packages/neovim)
  - WARNING: Latest python2-neovim is NOT installed: 0.2.1

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.1
  - OK: Latest python3-neovim is installed: 0.2.1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Node provider (optional)
  - INFO: Node: v9.4.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
...
  call dein#add('shougo/denite.nvim')
...
set backspace=indent,eol,start " indent :: allow backspacingover everything in insert mode
...
call denite#custom#var('file_rec', 'command',
\ ['ag', '--follow', '--nocolor', '--nogroup', '-g', '', '--ignore=rel', '--ignore=releases', '--ignore=node_modules',
\ '--ignore=deps', '--ignore=elm-stuff', '--ignore=public/js', '--ignore=public/css'])
nnoremap <leader>f :Denite buffer<CR>
nnoremap <leader>o :Denite file_rec<CR>
...
```

## The reproduce ways from neovim starting (Required!)

 1. open vim in a project
 2. :Denite file_rec<CR>
 3. type "anything"
 4. hit the key 'delete'
 5. the cursor moves left

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
<img width="1440" alt="screen shot 2018-02-04 at 23 31 40" src="https://user-images.githubusercontent.com/2382216/35779165-ba7a098e-0a03-11e8-8b0b-9c159aad7ae2.png">

**Comment by lambdalisue** [comment]
> INFO: key_backspace (kbs) terminfo entry: key_backspace=\177

I'm not sure if it's correct. At least mine shows `key_backspace=^H`

Add the followings to your `init.vim`

```vim
function! s:getchar() abort
  redraw | echo 'Press any key: '
  let c = getchar()
  while c ==# "\<CursorHold>"
    redraw | echo 'Press any key: '
    let c = getchar()
  endwhile
  redraw | echo printf('Raw: "%s" | Char: "%s"', c, nr2char(c))
endfunction

command! GetChar call s:getchar()
```

And

1. `:GetChar`
2. Hit `<Backspace>`
3. Let us know what is shown.

Mine shows below with grayed `<80>`

```
Raw "<80>kb" | Char: ""
```

**Comment by petobens** [comment]
I can reproduce the same behaviour after the las two commits. i.e the problem is not present when using:
```
    call dein#add('Shougo/denite.nvim', { 'rev': '879cba7' })
```

**Comment by JochemKlingeler** [comment]
I was hit with this problem as well and was able to find the culprit. Made a pull request (#432).

**Comment by Shougo** [comment]
This is the fatal problem.
I will fix it later.

**Comment by Shougo** [comment]
```diff
diff --git a/rplugin/python3/denite/ui/prompt.py b/rplugin/python3/denite/ui/prompt.py
index 33cc36c..36f5c25 100644
--- a/rplugin/python3/denite/ui/prompt.py
+++ b/rplugin/python3/denite/ui/prompt.py
@@ -1,3 +1,5 @@
+import copy
+
 from .action import DEFAULT_ACTION_RULES
 from datetime import timedelta, datetime
 from ..prompt.prompt import (
@@ -90,8 +92,9 @@ class DenitePrompt(Prompt):
         if m:
             bufvars = self.denite._bufvars
             bufvars['denite_context'] = self.context
+            prev_context = copy.copy(self.context)
             ret = self.action.call(self, m.group('action'))
-            if bufvars['denite_context'] != self.context:
+            if bufvars['denite_context'] != prev_context:
                 # Update context
                 self.context = bufvars['denite_context']
             return ret
```

This is my fix for it.

**Comment by JochemKlingeler** [comment]
That fix seems to do the trick!
