### ISSUE TITLE
[Feature Request] outline source for markdown/rst?

### ISSUE THREAD

**Issue by Palpatineli** [Shougo/denite.nvim#434]
Hi Shougo,

Thanks for the wonderful project! There appears to be one thing in unite but not in denite. When using outline source, in unite the different levels of headings show up for both markdown and rst, but nothing shows up in denite. Is there a hidden switch somewhere to turn on this functionality? Or is this functionality not implemented yet? If it's not implemented yet I'll look into creating a PR for this.

**Comment by Shougo** [comment]
> Or is this functionality not implemented yet? If it's not implemented yet I'll look into creating a PR for this.

Yes.  It is not implemented.
The PR is welcome.

**Comment by lyndsysimon** [comment]
Any luck on this?

I came across [h1mesuke/unite-outline](https://github.com/h1mesuke/unite-outline) while investigating this very thing. I've no experience writing `n?vim` plugins, but I thought it might be helpful.

**Comment by Shougo** [comment]
If you need, you should implement it.

**Comment by lyndsysimon** [comment]
... and I shall, as soon as I can :)

**Comment by languitar** [comment]
Just as another option, there is the tagbar plugin and an extension for markdown: https://github.com/lvht/tagbar-markdown

**Comment by viniarck** [comment]
Thanks for pointing that out @languitar

**Comment by kiryph** [comment]
Another option is https://github.com/SidOfc/mkdx#open-toc-using-fzf-instead-of-quickfix-window

**Comment by delphinus** [comment]
Also another, with [Universal Ctags][], `Denite outline` can show indexes, but it is imcomplete (it can not parse GFM...).  You may improve it with config for that. 🤔 

[Universal Ctags]: https://ctags.io

**Comment by masatake** [comment]
@delphinus, do you mean there is a bug in u-ctags about parsing GFM?

**Comment by delphinus** [comment]
@masatake 

Yes. The current version (I installed by [Homebrew's tap][tap]) detects `#...` style comments in code blocks as headings. such as...

[tap]: https://github.com/universal-ctags/homebrew-universal-ctags

<pre><code>
# ctags tests

## fundamental style for code blocks

    # ctags ignores here because this is a comment.
    echo 'Hello, World!'

## GFM style for code blocks

```sh
# ctags detects here as a heading mistakenly!
echo 'Hello, World!'
```
</code></pre>

Universal ctags does not support GFM, but the original Markdown.

**Comment by masatake** [comment]
@delphinus, thank you.
I made a pull request for fixing the bug.

**Comment by lyndsysimon** [comment]
> Just as another option, there is the tagbar plugin and an extension for markdown: https://github.com/lvht/tagbar-markdown

Thank you - this solves my need, as since I commented I've moved to using tagbar anyhow.

**Comment by viniarck** [comment]
Alternatively, you can also use ctags to generate the outline and browser with `:Denite outline`: 

https://stackoverflow.com/questions/25742396/creating-ctags-extension-for-markdown

```
--langdef=markdown
--langmap=markdown:.md
--regex-markdown=/^#[ \t](.*$)/\1/h,heading,headings/
```
