### ISSUE TITLE
filter is break down after upgrade to the latest version

### ISSUE THREAD

**Issue by iamcco** [Shougo/denite.nvim#438]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

after upgrade to the latest version, open action in kind as below denite break down, the denite filter doesn't work
```
        context['sources_queue'].append([
            {'name': file, 'args': []},
            ])

```

## Expected

this commit 0f124c636495dd230fad38f678a80211149b0c78 works will

## Environment Information (Required!)

 * denite version(SHA1): c3fdd94ac0868c80ed0995b7f179b101727c807e

 * OS: mac os

 * Vim/neovim version: 0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin(expand('<sfile>:p:h') . '/plugged')
Plug 'Shougo/denite.nvim' 
Plug 'iamcco/denite-source.vim'
call plug#end()

```

## The reproduce ways from neovim starting (Required!)

 1. :Denite source
 2. Enter
 3. type any character

**Comment by Shougo** [comment]
Fixed.
