### ISSUE TITLE
Cursor line highlight takes precedence over matched chars

### ISSUE THREAD

**Issue by kirelagin** [Shougo/denite.nvim#447]
# Problems summary

Unlike in normal buffers in the denite window the background of `CursorLine` overrides the background of `Search` which highlights matched chars. This is a problem if the colorscheme is such that `CursorLine` background is dark and `Search` foreground is dark as well.

## Expected

As in normal buffers the `Search` background colour should take precedence over the `CursorLine` background colour.

## Environment Information (Required!)

 * denite version(SHA1): e4e83f3b668d9b872dde993b160c011241e289de

 * OS: macOS 10.13.4

 * Vim/neovim version: NVIM v0.2.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/nix/store/7i7d7g0jljwg6hzw3d7g0c8vhn6r5lv6-neovim-0.2.1/bin/nvim-python"
  - INFO: Executable: /nix/store/7i7d7g0jljwg6hzw3d7g0c8vhn6r5lv6-neovim-0.2.1/bin/nvim-python
  - INFO: Python2 version: 2.7.14
  - INFO: nvim-python-neovim version: 0.2.0 (outdated; from /nix/store/yp2l7qygfvn1ipj11hgkiz8h99h6pfdw-python-2.7.14-env/lib/python2.7/site-packages/neovim)
  - WARNING: Latest nvim-python-neovim is NOT installed: 0.2.1

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/nix/store/7i7d7g0jljwg6hzw3d7g0c8vhn6r5lv6-neovim-0.2.1/bin/nvim-python3"
  - INFO: Executable: /nix/store/7i7d7g0jljwg6hzw3d7g0c8vhn6r5lv6-neovim-0.2.1/bin/nvim-python3
  - INFO: Python3 version: 3.6.4
  - INFO: nvim-python3-neovim version: 0.2.0 (outdated; from /nix/store/gk356j8avyrbwgyf24hg4xx2vrpli1vl-python3-3.6.4-env/lib/python3.6/site-packages/neovim)
  - WARNING: Latest nvim-python3-neovim is NOT installed: 0.2.1

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
  - INFO: Host: /nix/store/7i7d7g0jljwg6hzw3d7g0c8vhn6r5lv6-neovim-0.2.1/bin/nvim-ruby
  - WARNING: Gem "neovim" is out-of-date. Installed: 0.6.1, latest: 0.6.2
    - ADVICE:
      - Run in shell: gem update neovim
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set cursorline

hi Search     ctermfg=black ctermbg=white
hi CursorLine               ctermbg=black

call append(line('$'), ['this', 'is', 'a test'])

set rtp+=~/.cache/nvim/plugins/repos/github.com/Shougo/denite.nvim
```

## The reproduce ways from neovim starting (Required!)

 1. `/is<CR>`
 2. observe that “is” has white background even on current line
 3. `:Denite file`
 4. type something that matches
 5. observe that matched text is black on black background in the selected line

## Screen shot (if possible)

![screen shot 2018-02-19 at 02 05 01](https://user-images.githubusercontent.com/451835/36358096-7782458a-1519-11e8-96d2-92bde76fde98.png)

**Comment by Shougo** [comment]
Unfortunately, it is Vim/neovim feature.

`/is<CR>` is just highlight search.
But denite highlight is not.

You should change the highlight by `-highlight-matched-char`.
