### ISSUE TITLE
Whole screen is blinking when opening Denite window since 610ccec

### ISSUE THREAD

**Issue by unclechu** [Shougo/denite.nvim#451]
# Problems summary

Whole screen is blinking when opening Denite window since 610ccec (previous commit a5bd4d1 doesn't have this issue). Opening Denite window also gets long freeze in *neovim-gtk* (see daa84/neovim-gtk#59) (in a5bd4d1, that is previous commit, everything works fine). See screencast posted below that demonstrates all of this.

## Environment Information

 * denite version(SHA1): 610ccec (previous a5bd4d1 works fine)
 * OS: Fedora Workstation 25
 * Vim/neovim version: `NVIM v0.2.3-515-ga3daa8c`
 * `:checkhealth` or `:CheckHealth` result (neovim only): [:checkhealth](https://github.com/Shougo/denite.nvim/files/1745615/123.txt)

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set rtp+=denite.nvim
```

## The reproduce ways from neovim starting (Required!)

 1. Open neovim
 2. Open any `:Denite` window
 3. Notice that whole screen is blinked before Denite window is appeared

## Screen cast

https://youtu.be/_Ooo-BHmPFU

**Comment by Shougo** [comment]
The blink is the problem of denite.  I will fix it.
But the hang is not denite problem.
