### ISSUE TITLE
Cannot specify multiple paths in grep source

### ISSUE THREAD

**Issue by wilywampa** [Shougo/denite.nvim#453]
# Problems summary

Cannot search multiple files  in grep source. Not one of these works:

```vim
call denite#start([{'name': 'grep', 'args': [['a.vim', 'b.vim'], '', 'pattern']}])
call denite#start([{'name': 'grep', 'args': ['a.vim b.vim', '', 'pattern']}])
call denite#start([{'name': 'grep', 'args': ['', '', 'pattern'], 'final_opts': ['a.vim', 'b.vim']}])
call denite#start([{'name': 'grep', 'args': [[], '', 'pattern'], 'final_opts': ['a.vim', 'b.vim']}])
call denite#start([{'name': 'grep', 'args': [['a.vim', 'b.vim'], '', 'pattern'], 'path': ['a.vim', 'b.vim']}])
call denite#start([{'name': 'grep', 'args': [v:null, '', 'pattern'], 'path': ['a.vim', 'b.vim']}])
```

The different variants result in slightly different errors. Please advise the correct syntax. Thanks!

## Expected

Be able to limit grep to list of files.

## Environment Information (Required!)

 * denite version(SHA1): e671b45

 * OS: macOS

 * Vim/neovim version: neovim v0.2.3

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)

 1. Try any of the commands above

**Comment by Shougo** [comment]
```vim
call denite#start([{'name': 'grep', 'args': [['a.vim', 'b.vim'], '', 'pattern']}])
```

It is the correct pattern.
But `get_status()` is broken.  I will fix it later.
