### ISSUE TITLE
Crash when using 5t111111/denite-rails after PR #440.

### ISSUE THREAD

**Issue by kiooss** [Shougo/denite.nvim#455]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Exception occurred when using [denite-rails](https://github.com/5t111111/denite-rails) source.

Note: This may be `denite-rails` side issue, but it works well before #440.

## Expected
No Exception happen.

## Environment Information (Required!)

 * denite version(SHA1): f5c29185e5b95a22955c26d1a1cb3ac45d7a0fc6
 * OS: Ubuntu 16.04.4 LTS
 * Vim/neovim version: NVIM v0.2.2 Build type: RelWithDebInfo

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/denite.nvim/
set runtimepath+=~/.cache/dein/repos/github.com/5t111111/denite-rails/
```

## The reproduce ways from neovim starting (Required!)

 1. do any Denite command

## Screen shot (if possible)

<img width="1400" alt="screencapture 2018-02-26 23 32 11" src="https://user-images.githubusercontent.com/842321/36679156-8080c17c-1b4d-11e8-8abc-753772ee788a.png">

**Comment by Shougo** [comment]
OK.

@lambdalisue Ping.

**Comment by Shougo** [comment]
Current denite-rails is incompatible with denite.nvim namespace feature.

**Comment by Shougo** [comment]
Sorry.  I don't want to support the source structure.
denite-rails should move `modules` directory to the other place.

https://github.com/5t111111/denite-rails/tree/master/rplugin/python3/denite/source

**Comment by Shougo** [comment]
> Note: This may be denite-rails side issue, but it works well before #440.

denite.nvim has supported namespace feature.
source directory behavior is changed.

**Comment by 5t111111** [comment]
Thanks for information. I've update denote-rails source.
