### ISSUE TITLE
With deodeplete multiple file previews lead to unresponsive nvim. 

### ISSUE THREAD

**Issue by BonaBeavis** [Shougo/denite.nvim#457]
# Problems summary

If https://github.com/Shougo/deoplete.nvim/ is installed, Neovim becomes unresponsive after previewing files several times (about 10 or more). 

## Environment Information

 * deoplete version(SHA1):
https://github.com/Shougo/deoplete.nvim/commit/642f9e9b0ed9457734d974aeb9417192077b7551
 * denite version(SHA1):
https://github.com/Shougo/denite.nvim/commit/b16579be4431a7eb708deb17d73ec641a8c89a54
 * OS:
Ubuntu 17.10
 * neovim/Vim version:
NVIM v0.2.3-dev

 * `:checkhealth` or `:CheckHealth` result(neovim only):

# health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - WARNING: $NVIM_TUI_ENABLE_CURSOR_SHAPE is ignored in Nvim 0.2+
    - ADVICE:
      - Use the 'guicursor' option to configure cursor shape. :help |'guicursor'|
      - https://github.com/neovim/neovim/wiki/Following-HEAD#20170402

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='4804'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.2.3
  - OK: Latest python2-neovim is installed: 0.2.3

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.3
  - INFO: python3-neovim version: 0.2.3
  - OK: Latest python3-neovim is installed: 0.2.3

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v6.13.0
  - WARNING: Missing "neovim" npm package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Is the npm bin directory in $PATH?

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin('~/.vim/bundle')

Plug 'Shougo/denite.nvim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

syntax on
filetype plugin indent on
filetype plugin on

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. :Denite file_rec
 2. Switch to normal mode
 3. Select file and keep pressing p for preview, after ~10 tries nvim hangs

Works fine with deodeplete disabled.

**Comment by Shougo** [comment]
Please use the latest deoplete.

**Comment by BonaBeavis** [comment]
It still hangs, but after ~15 tries, with the denite-git source after ~5 tries.

**Comment by Shougo** [comment]
Really?

I don't reproduce the problem.

Note: It is not denite.nvim error.
It is just deoplete (caching) error.

**Comment by Shougo** [comment]
Please create the new issue in deoplete.
If not, I will ignore your issue.
