### ISSUE TITLE
Feature request: a sorter that use scoring algorithm of fzy

### ISSUE THREAD

**Issue by chemzqm** [Shougo/denite.nvim#463]
https://github.com/jhawthorn/fzy/blob/master/ALGORITHM.md
I've tried to use fzy and find I can find the file faster with the help of it's algorithm

**Comment by Shougo** [comment]
`sorter_sublime` is already implemented.
Why another score algorithm is needed?

And you can implement it yourself.
The PR is wellcome.

**Comment by Shougo** [comment]
I don't have time to implement the feature.

**Comment by mrbiggfoot** [comment]
@chemzqm check out these two plugins:
https://github.com/cloudhead/neovim-fuzzy
https://github.com/srstevenson/vim-picker

Or you can try to use `fzf` which is even better IMO.

**Comment by chemzqm** [comment]
@mrbiggfoot thanks, I have tried to bundle fzy with denite.nvim by using the c binding of python, but find the sort result is almost the same as `sorter/sublime`
