### ISSUE TITLE
Vertical Preview Seems Not To Work

### ISSUE THREAD

**Issue by weilbith** [Shougo/denite.nvim#464]
# Problems summary
The preview window does not open vertically, if I set both options to true, like in the minimal `.vimrc`. I also removed all plugins from my bundle and just load `denite`. I do some experiments, where I set the `denite-options-vertical-preview` to `true` and `false` (to avoid missconception), I worked in a window over the whole screen and also switched the order I set the options (just cause desparation, don't expected a change). But in the end the preview window always shows on top of the list window.

Could it be, that this does not work with GVim or general not NeoVim?

## Expected
The preview window splits vertically with the list window, when the responsible option is set.

## Environment Information (Required!)
denite version(SHA1): ac93316
OS: Win7
Vim/neovim version: VIM - Vi IMproved 8.0

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible
execute pathogen#infect() " Only denit is in the bundle.
call denite#custom#option('_', {
      \ 'auto_preview': 'true',
      \ 'vertical_preview': 'true',
      \ })
```

## The reproduce ways from neovim starting (Required!)

 1. Set the both preview options as shown in the `.vimrc`
 2. Execute `:Denite file_rec`
 3. Check where the preview window is displayed.

## Screen shot (if possible)
![vim-denitepreviewbug](https://user-images.githubusercontent.com/12543647/37410567-324a8686-27a1-11e8-8b5c-bf1488833936.png)

**Comment by Shougo** [comment]
`Denite file_rec -vertical-preview` works.
But if you use `denite#custom#option()`, it does not work.

**Comment by Shougo** [comment]
I get it.

```vim
call denite#custom#option('_', {
      \ 'auto_preview': v:true,
      \ 'vertical_preview': v:true,
      \ })
```

**Comment by Shougo** [comment]
Please learn Vim script...

**Comment by weilbith** [comment]
Sure I will, but this is a process. Nearly every different plugin use 0 and 1. Therefore I haven't used pure boolean objects before. Sry. 
But many thanks for ur help! I'm glad that it works now. 😄

**Comment by weilbith** [comment]
@Shougo is it possible to switch the list and preview window? Cause I intuitive focus right, but the list I primary use here is on the left.
Just asking...

**Comment by Shougo** [comment]
OK.  It should be.
I will change the behviour.
