### ISSUE TITLE
context overwrites final_opts in grep source

### ISSUE THREAD

**Issue by uinput** [Shougo/denite.nvim#466]
Hi,

I'd like to specify the `final_opts` in my grep alias. However, I noticed that denite will just use my current folder path as the path passed to grep. Here is the piece of code I'm talking about:
```python
        if context['__paths']:
            args += context['__paths']
        else:
            args += self.vars['final_opts']
```
Is there any way to enforce a path I want to grep? In my case, the path would be `:/`, specifying the root path for a git project. Why was the `__paths` variable used here in the first place, if `.` is the default for `final_opts`?

**Comment by Shougo** [comment]
> Is there any way to enforce a path I want to grep?

Nothing.  It is used for the default path.

**Comment by uinput** [comment]
But I already set `final_opts` to my path, namely `:/`.
```
call denite#custom#var("grep/git", "final_opts", [":/"])
```
But this does not affect the source behavior. It will still look in the directory of my current file.
What am I doing wrong here? According to the documentation, `final_opts` is

> the final arguments (default: ["."] path to search argument)

**Comment by Shougo** [comment]
> But this does not affect the source behavior. It will still look in the directory of my current file.
> What am I doing wrong here? According to the documentation, final_opts is

The documentation is wrong.
I will fix it later.

**Comment by Shougo** [comment]
I should split `default_paths` and `final_opts`.

**Comment by uinput** [comment]
What about this?
```python
        final_opts = self.vars['final_opts']
        if len(final_opts) == 1 and final_opts[0] == "":
            args += context['__paths']
        else:
            args += final_opts
```
If we pass `[""]` as final_opts, Denite will replace it with the contents of `__paths`. This won't break setups passing an empty list like `[]` but will still allow for custom paths.

**Comment by Shougo** [comment]
It breaks default `['.']` behavior.

**Comment by uinput** [comment]
So we could just set `final_opts = ['']` as default? One could set it to `['.']` manually then, if a relative path output is preferred.

**Comment by uinput** [comment]
I referenced a pull request to propose this change.

**Comment by Shougo** [comment]
No.  It is just complex change.
Adding "default_paths" feature is better instead.

**Comment by Shougo** [comment]
I will fix the issue.  But it takes time.
Please wait.

**Comment by Shougo** [comment]
```diff
diff --git a/doc/denite.txt b/doc/denite.txt
index df0e1d9..a36f898 100644
--- a/doc/denite.txt
+++ b/doc/denite.txt
@@ -1511,7 +1511,7 @@ grep      Gather grep results and nominates them.
        separator   the argument separator
                (default: ["--"])
        final_opts  the final arguments
-               (default: ["."] path to search argument)
+               (default: [])

                        *denite-source-help*
 help       Search through doc tags
diff --git a/rplugin/python3/denite/source/grep.py b/rplugin/python3/denite/source/grep.py
index 64cfc7a..9244938 100644
--- a/rplugin/python3/denite/source/grep.py
+++ b/rplugin/python3/denite/source/grep.py
@@ -61,7 +61,7 @@ class Source(Base):
             'recursive_opts': ['-r'],
             'pattern_opt': ['-e'],
             'separator': ['--'],
-            'final_opts': ['.'],
+            'final_opts': [],
             'min_interactive_pattern': 3,
         }
         self.matchers = ['matcher_ignore_globs', 'matcher_regexp']
@@ -174,8 +174,7 @@ class Source(Base):
             args += context['__patterns']
         if context['__paths']:
             args += context['__paths']
-        else:
-            args += self.vars['final_opts']
+        args += self.vars['final_opts']

         self.print_message(context, args)
```

`final_opts` does not work.
It is the patch.

**Comment by uinput** [comment]
This would still pass `context['__paths']` to grep, which is what I want to prevent. In my case, `:/` should be passed as the path.

**Comment by uinput** [comment]
If I get it right, path can be emptied by calling `Denite grep/git::`? `print_messages` still shows me the path I'm in.

**Comment by Shougo** [comment]
`:Denite grep/git:: -path=`

**Comment by uinput** [comment]
Yes, together with the patch it works. Thanks, Shougo.
