### ISSUE TITLE
Denite Close Already Open Preview Window

### ISSUE THREAD

**Issue by weilbith** [Shougo/denite.nvim#469]
# Problems summary
When a preview window is already open and then use a denite function with the preview window enabled, it close the preview window afterwards.

## Expected
In case the preview window was already open before denite was called, it should remain open afterwards.

## Environment Information (Required!)
denite version(SHA1): 50bfdc31912b5b6ddea61a364ecb6abf87fe1aab
OS: Win7
Vim/neovim version: VIM - Vi IMproved 8.0

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible
execute pathogen#infect() " Only denit is in the bundle.
call denite#custom#option('_', {
      \ 'auto_preview': 'true',
      \ 'vertical_preview': 'true',
      \ })
```

## The reproduce ways from neovim starting (Required!)

 1. Open a tag in the preview window with `:ptjump <tag>`
 -> Preview window visible 
 2. Call a denite function which use the auto preview window by configurations (e.g. `:Denite file_rec`)
 -> The preview window is reused to display the
 3. Close the denite buffer.
 -> Preview window closed

**Comment by weilbith** [comment]
oc the `ptjump` require a tag file. As alternative split window can be opened and `set previewwindow`

**Comment by Shougo** [comment]
Fixed.
