### ISSUE TITLE
Filenames incorrectly highlighted for source 'buffer'

### ISSUE THREAD

**Issue by minusf** [Shougo/denite.nvim#476]
# Problems summary

in source `buffer`:
file/folder names starting with a letter that is also a buffer status ('a', 'h', etc) are highlighted in the file name.

## Expected

not highlighted file/folder name

## Environment Information (Required!)

 * denite version(SHA1): `c0c75a752577399be53aa7a7e235e6ff5387494c`

 * OS: `macOS`

 * Vim/neovim version: `NVIM v0.2.2`

 * `:checkhealth` or `:CheckHealth` result(neovim only): `all ok`

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Shougo/denite.nvim'
call plug#end()
```

## The reproduce ways from neovim starting (Required!)

 1. `:Denite buffer`

## Screen shot (if possible)

<img width="334" alt="screen shot 2018-04-16 at 12 18 04" src="https://user-images.githubusercontent.com/3632883/38803689-42fd9002-4170-11e8-8d35-ff37b76f0db8.png">

**Comment by Shougo** [comment]
Unfortunately, it is the feature.
denite.nvim just highlight the pattern in abbr.
