### ISSUE TITLE
Can't map <C-Space> in insert mode

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#481]
I'm on Mac and using Alacritty. Consider the following minimal `init.nvim`:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on


call denite#custom#map('insert', '<C-Space>', '<denite:toggle_select_up>',
            \ 'noremap')
call denite#custom#map('insert', '<C-v>', '<denite:toggle_select_up>',
    \ 'noremap')
```
I can use the `C-v` mapping to toggle select but I cannot use the `C-Space` one. In the following Gif the first time i use the `C-v` mapping and everything works as expected and the second one the `C-Space` one. 
![may-09-2018 17-41-25](https://user-images.githubusercontent.com/2583971/39838625-4b52c90a-53b0-11e8-9e8c-e9e18d3e032e.gif)

**Comment by Shougo** [comment]
It is not denite problem.

```
call denite#custom#map('insert', '<C-@>', '<denite:toggle_select_up>',
            \ 'noremap')
```

Works for me.

Note:  In GVim or neovim, `<C-space>` mapping works.
But if you use Vim8, you must use `<C-@>` instead.

Warning:  Please don't ignore issue template.

**Comment by petobens** [comment]
Probably an issue with Alacritty then. Thanks anyway.
