### ISSUE TITLE
Writing a custom matcher - where to place additional .py files that can be imported in the matcher?

### ISSUE THREAD

**Issue by raghur** [Shougo/denite.nvim#482]
# Problems summary

I'm writing a custom filter - so placing my file `gofuzzy.py` in `rplugins/python3/denite/filter/matcher` works if it is standalone. However, I want to do a grpc call from my filter and grpc generates two python files `api_pb2.py` and `api_pb2_grpc.py` that I need to import in my filter code. 

Problem is that wherever I place these files, I'm getting different errors. If I place them along side myfilter.py and try to import it as
```
import api_pb2
import api_pb2_grpc
```
Then I get:
```
[denite] Traceback (most recent call last):
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 119, in _start
[denite]     self.init_denite()
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 658, in init_denite
[denite]     self._denite.start(self._context)
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\denite.py", line 39, in start
[denite]     self.load_filters(context)
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\denite.py", line 259, in load_filters
[denite]     for Filter, path, module_path in rplugins:
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\util.py", line 244, in import_rplugins
[denite]     yield (getattr(module, name), path, module_path)
[denite] AttributeError: module 'denite.filter.matcher.api_pb2' has no attribute 'Filter'
[denite] Please execute :messages command.

```

If I put it in a subfolder in matcher 'fuzzy' and use a relative import like so
```
from .fuzzy import api_pb2
from .fuzzy import api_pb2_grpc
```

I get 
```
[denite] Traceback (most recent call last):
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\__init__.py", line 29, in start
[denite]     return ui.start(args[0], args[1])
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 71, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 119, in _start
[denite]     self.init_denite()
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\ui\default.py", line 658, in init_denite
[denite]     self._denite.start(self._context)
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\denite.py", line 39, in start
[denite]     self.load_filters(context)
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\denite.py", line 259, in load_filters
[denite]     for Filter, path, module_path in rplugins:
[denite]   File "C:/Users/xxxx/AppData/Local/nvim/bundle/denite.nvim/rplugin/python3\denite\util.py", line 242, in import_rplugins
[denite]     module = loader.load_module()
[denite]   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
[denite]   File "<frozen importlib._bootstrap_external>", line 823, in load_module
[denite]   File "<frozen importlib._bootstrap_external>", line 682, in load_module
[denite]   File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
[denite]   File "<frozen importlib._bootstrap>", line 675, in _load
[denite]   File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
[denite]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
[denite]   File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
[denite]   File "c:\users\xxxx\appdata\local\nvim\bundle\fuzzy-denite\rplugin\python3\denite\filter\matcher\gofuzzy.py", line 11, in <module>
[denite]     from .fuzzy import api_pb2
[denite] ImportError: cannot import name 'api_pb2'
[denite] Please execute :messages command.
```

## Expected
Be able to import other modules when writing custom filters/matchers

## Environment Information (Required!)

 * denite version(SHA1):

 * OS: Windows 8.1 

 * Vim/neovim version: 0.3 dev (nightly)

 * `:checkhealth` or `:CheckHealth` result(neovim only):

**Comment by raghur** [comment]
So after fiddling around a bit, here's what works, but this seems very kludgy

1. Change imports to relative ones - 
```
from . import api_pb2
from . import api_pb2_grpc
```

2. In `denite/utils.py` do not rethrow the exception if there's no `Filter` attribute
https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/util.py#L249

3. (This is the problem): `api_pb2_grpc` imports `api_pb2`. I have to modify this also to use a module relative import `from . import api_pb2`

There's got to be a better approach than this :)

**Comment by wilywampa** [comment]
I had the same problem and ended up putting the extra module in `rplugin/python3` but also added a symlink to it in my `$PYTHONPATH`. It would be nice if I didn't need the link.

**Comment by Shougo** [comment]
> 

(This is the problem): api_pb2_grpc imports api_pb2. I have to modify this also to use a module relative import from . import api_pb2

```python
sys.path.insert(1, os.path.dirname(__file__))
```

**Comment by raghur** [comment]
> `sys.path.insert(1, os.path.dirname(__file__))`

So I think this issue needs to be reopened. Modifying `sys.path` only works if my script is loaded before the generated scripts. Right now, on Linux, this works. But on Windows, `api_pb2_grpc.py` is loaded first and then it fails again with an import error. Given that it's a generated file, I don't want to edit it.

Placing an `__init__.py` in the folder also does not help - that is not loaded first. Perhaps you can check if the folder contains an `__init__.py` and load import that first - so that if plugins need to fiddle around with the environment, they have a place to do so?

**Comment by raghur** [comment]
>Or at least define the order in which files are loaded so that there's a well defined way to address this in the plugin that works across platforms.

Adding `fs.sort()` before L206 in `util.py`

https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/util.py#L206

seems to do the trick.

**Comment by Shougo** [comment]
> Would it be possible for you to add the plugin folder to sys.path as part of the load process so that imports work? Or at least define the order in which files are loaded so that there's a well defined way to address this in the plugin that works across platforms.

I think using `rplugin/python3/` directory is better.

@raghur You should not write the scripts depends the loading order.

**Comment by raghur** [comment]
> @raghur You should not write the scripts depends the loading order.

Oh I agree fully...this is all kludgy like anything. Trouble is that sys.path does not have the plugin folder (`rplugin/python3`) so putting the grpc generated python files in `rplugin/python3` isn't going to help either, right?

**Comment by raghur** [comment]
So, here's what I've done now - moved the grpc generated files to rplugin/python3 and then in `rplugin/python3/denite/filter/matcher/myplugin.py` have the following bit at the beginning

```
pkgPath = os.path.dirname(__file__).split(os.path.sep)[:-3]
pkgPath = os.path.sep.join(pkgPath)
if pkgPath not in sys.path:
    logger.debug("added %s to sys.path" % pkgPath)
    sys.path.insert(0, pkgPath)
```

I think it would be better to have denite do this rather than having to deal with this in the plugin. Is that something you'd consider?

**Comment by lambdalisue** [comment]
First of all, python files under `rplugin/python3/denite/filter` are **script** rather than *module* ([ref.](https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/util.py#L173)).
That's why you cannot put or import *modules* in that path and you need to put your *module* into a different path.

I recommend you to try to put your *module* in `{rtp}/python3` or `{rtp}/pythonx` directory instead while these are automatically added to `sys.path` by Vim/Neovim. See `:help python-special-path`. I'm not sure if that works on RPC plugins as well but it seems a proper place.

> In python vim.VIM_SPECIAL_PATH special directory is used as a replacement for 
the list of paths found in 'runtimepath': with this directory in sys.path and 
vim.path_hooks in sys.path_hooks python will try to load module from 
{rtp}/python2 (or python3) and {rtp}/pythonx (for both python versions) for 
each {rtp} found in 'runtimepath'.

If above doesn't work, probably you need to do `sys.path` replacement by yourself as you commented.
While denite just requires **script** rather than *module*, I don't think denite should deal the `sys.path` things.
