### ISSUE TITLE
Cursor is missing in denite window in Vim 8.0

### ISSUE THREAD

**Issue by tuarba** [Shougo/denite.nvim#483]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
There is no cursor in denite window in Vim 8.0

Update: I changed my $TERM from xterm to vt100. Now vim in terminal is ok but gvim still have the same issue.

## Expected
Cursor should show up

## Environment Information (Required!)

 * denite version(SHA1):
5f34391d
 * OS:
Linux
 * Vim/neovim version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled May  1 2018 14:21:08)
Included patches: 1-1783

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocp
set runtimepath+=~/.vim/plugged/denite.nvim/
```

## The reproduce ways from neovim starting (Required!)
:Denite file

## Screen shot (if possible)
![image](https://user-images.githubusercontent.com/2860410/40094611-942ac606-58fa-11e8-94ca-94a1b0b21db6.png)

**Comment by Shougo** [comment]
It is feature of Vim8.

**Comment by Shougo** [comment]
Vim8 hides the cursor automatically.
