### ISSUE TITLE
file/rec cause error, but file_rec work 

### ISSUE THREAD

**Issue by zgpio** [Shougo/denite.nvim#484]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I use shougo's vim config, the follow can work:
```vim
  nnoremap <silent> [Window]<Space>
        \ :<C-u>Denite file_rec:~/.vim/rc<CR>
```
but the follow cause FileNotFoundError:
```vim
  nnoremap <silent> [Window]<Space>
        \ :<C-u>Denite file/rec:~/.vim/rc<CR>
```

![](https://user-images.githubusercontent.com/19503791/40641034-ebbcf3d0-634a-11e8-9881-effccaa3b564.png)

## Environment Information (Required!)

 * denite version(SHA1): latest

 * OS: Windows10

 * Vim/neovim version:  Vim8

**Comment by lambdalisue** [comment]
What kind of error?

**Comment by zgpio** [comment]
cause FileNotFoundError
![default](https://user-images.githubusercontent.com/19503791/40641034-ebbcf3d0-634a-11e8-9881-effccaa3b564.png)

**Comment by Shougo** [comment]
@zgpio Please upload `:messages` result.

**Comment by zgpio** [comment]
![default](https://user-images.githubusercontent.com/19503791/40818405-820ec92c-6589-11e8-9d90-0dafa3c7f263.png)

**Comment by Shougo** [comment]
Please apply the below patch.
And upload `:messages` result.

```diff
diff --git a/rplugin/python3/denite/source/file/rec.py b/rplugin/python3/denite/source/file/rec.py
index 06053bb..f5f8076 100644
--- a/rplugin/python3/denite/source/file/rec.py
+++ b/rplugin/python3/denite/source/file/rec.py
@@ -70,6 +70,8 @@ class Source(Base):
         else:
             args = self.vars['command'] + [directory]
         self.print_message(context, args)
+        self.error_message(context, str(args))
+        self.error_message(context, directory)
         context['__proc'] = Process(args, context, directory)
         context['__current_candidates'] = []
         return self._async_gather_candidates(context, 0.5)
```

**Comment by zgpio** [comment]
![default](https://user-images.githubusercontent.com/19503791/40872490-8d7f5fb2-6681-11e8-9da3-1282acb4f280.png)

**Comment by Shougo** [comment]
@zgpio You have not applied the patch.
error messages are not displayed.

**Comment by zgpio** [comment]
I just changed that file, ...

**Comment by Shougo** [comment]
The error messages are printed for me.

**Comment by Shougo** [comment]
I need `args` information.

`WinError` means file not found error.
So script path is invalid.

**Comment by zgpio** [comment]
![default](https://user-images.githubusercontent.com/19503791/40872551-d26ecf3a-6682-11e8-8a6f-4bdcca387d11.png)
 

![default](https://user-images.githubusercontent.com/19503791/40872571-14451cca-6683-11e8-96c5-7e0e30138097.png)

**Comment by Shougo** [comment]
Please upload `file_rec` source result.

**Comment by zgpio** [comment]
![default](https://user-images.githubusercontent.com/19503791/40872606-8358a97e-6683-11e8-8d06-170a4f4cce19.png)

**Comment by zgpio** [comment]
![default](https://user-images.githubusercontent.com/19503791/40872611-91e973b0-6683-11e8-9daf-c1339b10de53.png)

**Comment by Shougo** [comment]
OK.  I get it.  It is not denite.nvim bug.
You have not install ag binary in Windows.
