### ISSUE TITLE
Can denite be configured as just listing buffers in current directory ?

### ISSUE THREAD

**Issue by kran** [Shougo/denite.nvim#486]
`:Denite buffer` list all buffers opened in current vim instance, when editing with multiple tabs, buffers mixed and hard to detect which one belongs to current tab(project), especially on switching terminals. 

how to change the default behavior and list buffers in current tab ? 

thanks.

**Comment by Shougo** [comment]
```vim
	call denite#custom#source(
	\ 'buffer', 'matchers', ['matcher/fuzzy', 'matcher/project_files'])
```
