### ISSUE TITLE
Action conditional on candidate type

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#489]
I'm using neovim on Mac OSX with Alacritty. Consider the following minimal vimrc:

```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/rafi/vim-denite-z
filetype plugin indent on

call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'reversed': 1,
            \ })
call denite#custom#map('insert', '<C-n>', '<denite:move_to_next_line>',
    \ 'noremap')
call denite#custom#map('insert', '<C-p>', '<denite:move_to_previous_line>',
    \ 'noremap')
nnoremap <silent> ,dz :Denite -default-action=narrow z<CR>
```
Now, as in the GIF, do the following:
i) run `,dz`
ii) press `<ENTER>` on one of the directory candidates
iii) press `<ENTER>` again one of the file candidates

An error will show saying: `[denite] Invalid action: narrow`:

![jun-18-2018 12-36-48](https://user-images.githubusercontent.com/2583971/41546548-55c8958c-72f4-11e8-8ed3-741a982d747f.gif)

So my question is: is it possible to have an action that exectues `narrow` if the
candidate is a directory and `open` if the candidate is a file?

Thanks in advance!

**Comment by Shougo** [comment]
```vim
call denite#custom#action('file', 'narrow',
      \ {context -> denite#do_action(context, 'open', context['targets'])})
```

It is the denite power.

**Comment by petobens** [comment]
Awesome. Thanks
