### ISSUE TITLE
Feature Request: Add all search results to the quickfix

### ISSUE THREAD

**Issue by somini** [Shougo/denite.nvim#494]
When you use Denite to search for thing using `grep` or similar, sometimes it is useful to add everything to the quickfix for easier movement (using `:cnext`/`:cprevious` and others).

This is already implemented with the `quickfix` action, so my current workaround for this is:
- Search for something
- Denite opens its window with the results
- `<C-o>` to go to normal mode
- `*` to select all results (actually toggle select all, but they are all unselected now)
- `<Tab>quickfix<CR>` to send all the results to the quickfix.

This is a request for a single action that does this, so that this can be mapped to a keybinding. Since #164 is not easy to solve, this is the second best way to implement it.

PS: I know about `-resume -cursor-pos=-1`, but this requires knowing the buffer name you used, and I use [several denite buffer types](https://gitlab.com/somini/dotnvim/blob/be871d724e7e140b318da1908af3696ef8aa3d76/init.vim#L929-953), this would work for all of them.

**Comment by Shougo** [comment]
I don't want to add the feature.

**Comment by Shougo** [comment]
```vim
call denite#custom#map('normal', '<C-a>',
      \ '<denite:multiple_mappings:denite:toggle_select_all'.
      \ ',denite:do_action:quickfix>', 'noremap')
```

**Comment by somini** [comment]
Many thanks, #164 and that snippet are good enough for me.
