### ISSUE TITLE
Feature request: Git commits (and buffer commits) source

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#495]
Now that denite is pretty stable, is there a plan to add a git commits source similar to fzf's `:Commits`? It would be really awesome.  I know that there is one such source: https://github.com/neoclide/denite-git however it requires installing an extra plugin (`vim-easygit`) which personally I prefer to avoid (since I, as many people, use fugitive). Thanks in advance.

**Comment by Shougo** [comment]
I don't want to add it officially.
You can create it yourself.

**Comment by Shougo** [comment]
https://github.com/lambdalisue/gina.vim

You can use it.  But it has not denite source.

**Comment by Shougo** [comment]
Another solution.

https://github.com/kmnk/gitn

**Comment by petobens** [comment]
> https://github.com/kmnk/gitn

Doesn't seem to be maintained (`Denite gitn_log` returns empty).

Do yourself use some git source for Denite ? I think that the ability to filter git commit history is something essential.

**Comment by lambdalisue** [comment]
Perronally, I use Gina and Denite line combination when I need to filter (it's seldom though)

**Comment by petobens** [comment]
Ok. Thanks to both of you!
