### ISSUE TITLE
denite#custom#map <C-h> 

### ISSUE THREAD

**Issue by qeatzy** [Shougo/denite.nvim#498]
How to achieve below behavior 

	call denite#custom#map(
	      \ 'insert',
	      \ '<C-h>',
	      \ '<denite:leave_mode> if no input else <denite:delete_char_before_caret>',
	      \ 'noremap'
	      \)

That is:
press `<C-h>` will quit denite if no character being typed, 
else do normal thing -- `<denite:delete_char_before_caret>`.

P.S. from ctrlp behavior

[|ctrlp_brief_prompt|..........Exit CtrlP on empty prompt by <bs>.](https://github.com/ctrlpvim/ctrlp.vim/blob/43cc73b8e7d4ab45f17118573eb81fd45704b989/doc/ctrlp.txt#L69)

**Comment by Shougo** [comment]
```vim
call denite#custom#map('insert', '<C-h>',
      \ '<denite:smart_delete_char_before_caret>', 'noremap')
```
