### ISSUE TITLE
swapfile trouble when two denites in same workdir

### ISSUE THREAD

**Issue by bfredl** [Shougo/denite.nvim#5]
# Problems summary
denite creates swapfile, which creates problems when starting denite in new instance.

Start nvim and run `:Denite file_rec`. Leave it like that
Start another nvim (in the same workdir) and run `:Denite file_rec`, now swap file message. After making any choice 

`neovim.api.nvim.NvimError: b'Vim(new):E325: ATTENTION'`

and denite fails

## Expected

Denite is nofile buffer. No swapfile is created. Can run denite in two instances the same time in the same workdir without problems.

## Environment Information

 * OS: arch linux

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

## Neovim Python Diagnostic

- Neovim Version: https://github.com/neovim/neovim/commit/c6ac4f84b16324b56c38bd2003f037d995262fa1

## Python versions visible to Neovim

python 3.5.2
python-client 0.1.9

## Provide a minimal init.vim with less than 50 lines (Required!)

`nvim -u NORC --cmd "set rtp+=/home/bjorn/config/vim/bundle/denite.nvim/"`

**Comment by Shougo** [comment]
Fixed.
