### ISSUE TITLE
Feature Request: Show grep program state(running/finished) in status line

### ISSUE THREAD

**Issue by ratheesh** [Shougo/denite.nvim#507]
When denite grep is running on large projects, it takes a while for the grep program to complete searching. It would be nice to show the status of the grep program (running/finished) in the denite status line.
If this feature is already present, can somebody please point me to the documentation?

**Comment by Shougo** [comment]
Please see `[async]` mark in statusline.
If `[async]` is exists, grep source is running.

**Comment by ratheesh** [comment]
In v.3.0, this feature is not present when `split` is set to `floating`. Can we extend this to `floating` split as well?

**Comment by Shougo** [comment]
It works on titlestring when floating window
