### ISSUE TITLE
Laggy

### ISSUE THREAD

**Issue by bbtdev** [Shougo/denite.nvim#508]
# Problems summary
':Denite grep' is laggy compared to something like fzf.vim's ':Ag'. Now I know Denite is a proper vim plugin, but is there something that can be done.

I tried, with ripgrep, ag, in the video I'm using ag to properly compare with :Ag

How is it laggy?
1. waiting for results
2.trying to delete some letters, inserting others

# INIT.VIM

```vim
set runtimepath+=/Users/bogdan/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('/Users/bogdan/.cache/dein')
  call dein#begin('/Users/bogdan/.cache/dein')
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

  call dein#add('Shougo/denite.nvim')
  call dein#add('/usr/local/opt/fzf')
  call dein#add('junegunn/fzf.vim')

  call dein#end()
  call dein#save_state()
endif

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif


call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
call denite#custom#var('grep', 'default_opts',
	\ [ '--skip-vcs-ignores', '--vimgrep', '--smart-case', '--hidden' ])

```

## Video :Ag vs :Denite grep:::!
(I hope the video shows the lag difference)
![denite](https://user-images.githubusercontent.com/30316258/43037655-3b7eab9c-8d18-11e8-82e9-c9519f31bec3.gif)

**Comment by Shougo** [comment]
Won't fix.  Closed.

**Comment by bbtdev** [comment]
@Shougo 

Even if I use just :Denite grep, enter the pattern and then add some new characters will be laggy. Should I open an issue for that or it's the same situation?

**Comment by Shougo** [comment]
It is already known problem.

I think denite should split UI process.

**Comment by bbtdev** [comment]
@Shougo 

Ok, thank you for your response and your amazing plugins!
