### ISSUE TITLE
Do not blast errors to the screen if file not found

### ISSUE THREAD

**Issue by andreyorst** [Shougo/denite.nvim#511]
# Problems summary
When I use `file/rec` I want my search tool (currently `rg`) to follow symlinks, but I'm using nvim in mounted sshfs folder, and therefore some files are not reachable to me via symlinks, because symlinks are broken. While indexing, Denite tries to open those directories, and receives `No such file or directory (os error 2)`. This is fine, because these files are not reachable from my machine, and I **know it**:

![image](https://user-images.githubusercontent.com/19470159/43201324-d52c2ad4-9020-11e8-8862-f1477840bb71.png)

## Expected

I want to suppress such errors, because they block nvim, and doesn't provide real information to me.

Is there any way of doing this?

**Comment by andreyorst** [comment]
Currently I've added those files to my `.ignore` to suppress these errors, so If there is no possible way, you can close this issue with no response, and I'll continue to use this workaround

**Comment by Shougo** [comment]
You should use `--no-messages` option in rg.

**Comment by andreyorst** [comment]
thanks
