### ISSUE TITLE
How to set denite tag correctly for jsfaint/gen_tags.vim ?

### ISSUE THREAD

**Issue by pittcat** [Shougo/denite.nvim#515]
When the jsfaint/gen_tags.vim  will  generate tags in ~/.cache/tags_dir and manage them,it seems like that `denite tag` will generate tags in project directoty.How to make `denite tag`  use tags that is placed in  ~/.cache/tags_dir.

**Comment by Shougo** [comment]
Please set `tags` option.
denite-tag use tags option.
