### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by acerphoenix** [Shougo/denite.nvim#52]
hi, this is not a issue. i need help info that migrate from unite to denite.
 i look into the help file before i open this issue.
1.how can i ignore some file types in file_rec and grep source?
2.does file_rec and grep accept a variable as directory parameter? for instance:
    i write a function GetGitDir() and it return the gitdir in .vimrc, i hope to use it as 
:Denite file_rec:\`GetGitDir()\`<CR> in vimrc.
3.about the denite#custom#var and denite#custom#source?what 's the difference? i saw both of them has a source like grep or file_rec parameter.

**Comment by Shougo** [comment]
> 1.how can i ignore some file types in file_rec and grep source?

Please use `:help denite-filter-matcher_ignore_globs`

> 2.does file_rec and grep accept a variable as directory parameter?

Yes.

> 3.about the denite#custom#var and denite#custom#source?what 's the difference? i saw both of them has a source like grep or file_rec parameter.

`denite#custom#var` is for custom source variables.
`denite#custom#source` is for custom source configurations.
