### ISSUE TITLE
source completion support

### ISSUE THREAD

**Issue by Shougo** [Shougo/denite.nvim#520]
`completion(args, arglead)`

**Comment by mrdgo** [comment]
Not sure, whether I am correct here.

I guess this source is related to the completion suggestions.

More great sources:
`warnings` which gathers warnings from the LSP client
`errors` same with errors

**Comment by Shougo** [comment]
> Not sure, whether I am correct here.

This is not correct.  It is for command line completion instead of LSP completion.

> More great sources:
> warnings which gathers warnings from the LSP client
> errors same with errors

It should be from LSP plugins.

**Comment by mrdgo** [comment]
> > Not sure, whether I am correct here.
> 
> This is not correct. It is for command line completion instead of LSP completion.
 
Thanks for clarification.

> > More great sources:
> > warnings which gathers warnings from the LSP client
> > errors same with errors
> 
> It should be from LSP plugins.

Even in the presence of the native LSP client?
Native support seems reasonable to me.

I would like to give it a try. Do you have some initial hints or suggestions?
I imagine this to  be quite messy, as it is implemented in Lua and Denite is implemented in Python.

**Comment by Shougo** [comment]
Maybe this.
https://github.com/Shougo/deoplete-lsp

**Comment by Shougo** [comment]
I don't add the feature.  I develop the next plugin.
