### ISSUE TITLE
Source highlight are lost in interactive mode

### ISSUE THREAD

**Issue by BonaBeavis** [Shougo/denite.nvim#521]
# Problems summary
`Denite grep:::` produces different highlights than `Denite grep:::!`

## Expected
Should be the same highlights.

## Environment Information (Required!)

 * denite version (SHA1): f06c6d613c0bc36d226deb9e07f91dbee2fd86cc

 * OS: Ubuntu 18.04

 * Vim/neovim version: NVIM v0.3.2-dev

 * `:checkhealth` or `:CheckHealth` result(neovim only): Everything ok

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible              " be iMproved, required
filetype off                  " required
call plug#begin('~/.vim/bundle')
Plug 'Shougo/denite.nvim'
call plug#end()
syntax on
filetype plugin indent on    " required
```

## Screenshot (if possible)
Two nvim instances with grep::: and grep:::!
![Two nvim instances with grep::: and grep:::!](https://user-images.githubusercontent.com/3330855/44106508-2569a4e8-9ff5-11e8-9d9d-4ba6a792c068.png)

**Comment by BonaBeavis** [comment]
Related to #509?

**Comment by Shougo** [comment]
Fixed.

> Related to #509?

No.
