### ISSUE TITLE
Option to unlink Denite -resume from original window

### ISSUE THREAD

**Issue by languitar** [Shougo/denite.nvim#522]
# Problems summary

When using `:Denite -resume` for selecting files, files will always open in the window in which Denite was originally triggered. There is no way to make Denite respect that the cursor is in a different window when resuming.

## Expected

If I switched the window before using `:Denite resume`, selected files should open in the window in which the cursor was before calling the resume action.

## Environment Information (Required!)

 * denite version (SHA1): 897a8d8d7068e037e1bcb4a1a2c2b51447af5b7a

 * OS: archlinux

 * Vim/neovim version: 0.3.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):

everything is fine

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set nocompatible

set runtimepath+=~/.local/share/nvim/bundle/denite.nvim
```

## How to reproduce problems from neovim startup (Required!)

 1. open vim
 2. `:vsplit`
 3. `:Denite file`
 4. select a file and press enter to open it in the right split
 5. `C-w l` to selet the left split6
 6. `:Denite -resume`
 7. Select another file and open it

The file will open up in the right split instead of the now focused left split. At least I would wish to have an option to disable this behavior.

**Comment by Shougo** [comment]
No.  `-resume` feature is not for the behavior.
You should not use `-resume` for it.

**Comment by languitar** [comment]
But if I want to reuse for instance a `grep` result to open multiple finds in different splits? How would I do that? Retyping the potentially complex search pattern that I have entered in interactive mode and filtering the list again is not feasible.

**Comment by languitar** [comment]
Thanks!
