### ISSUE TITLE
Open buffer by number

### ISSUE THREAD

**Issue by BigfootN** [Shougo/denite.nvim#526]
Hello,

I would like to know if it is possible to select the buffer by it's number ? I know how to select/filter by name with `:Denite buffer` but not by number.

Thank you very much in advance.

**Comment by Shougo** [comment]
```vim
call denite#custom#var('buffer', 'date_format', '')
call denite#custom#source('buffer', 'matchers', ['converter/abbr_word', 'matcher/substring'])
```
