### ISSUE TITLE
Quick setup example

### ISSUE THREAD

**Issue by grafa** [Shougo/denite.nvim#527]
I wanted to try out denite but I haven't found any default keybindings or quick setup how to. I've only looked into docs but I don't have time to read 2.3k lines.

Would be really nice to have some quick setup of the core functionality.

**Comment by Shougo** [comment]
Why you don't read `:help denite-usage`, `:help denite-install`, `:help denite-examples`?

**Comment by Shougo** [comment]
I have updated the documentation.

> any default keybindings

Please use `:help denite-default-key-mappings`.

**Comment by grafa** [comment]
I guess you didn't get what I meant by the issue title.

**Comment by Shougo** [comment]
Unfortunately, the issues is not QA site.
It should be asked in other place.
