### ISSUE TITLE
Does denite have is_multiline option?

### ISSUE THREAD

**Issue by delphinus** [Shougo/denite.nvim#531]
Do you have any plan to support `is_multiline` option the same as in unite?

**Comment by Shougo** [comment]
It is not supported and I have not the plan.
Why the feature is needed?
Please describe it.

**Comment by delphinus** [comment]
I want to implement a denite source for [LeafCage/yankround.vim][].  It already has [a unite one][] and it needs the `is_multiline` option.  The source can list up candidates including multiline ones and you can yank and paste them into buffers as you see in the unite buffer.

[LeafCage/yankround.vim]: https://github.com/LeafCage/yankround.vim
[a unite one]: https://github.com/LeafCage/yankround.vim/blob/master/autoload/unite/sources/yankround.vim

**Comment by Shougo** [comment]
OK.  So this feature is not required.
The source works without is_multiline feature.
