### ISSUE TITLE
matching files on input string

### ISSUE THREAD

**Issue by fab6** [Shougo/denite.nvim#532]
Does anyone have a hint, how to match only files based on the exact input string and not based on the characters? Attached is a small example: actually I just would like to narrow it down to files with "panel" as a complete word/string.
![denite_question](https://user-images.githubusercontent.com/3047695/45994271-26e3f800-c093-11e8-871a-7600b6c570fa.png)

**Comment by Shougo** [comment]
Please use `matcher/substring` instead.

```vim
call denite#custom#source('_', 'matchers', ['matcher/substring'])
```

**Comment by fab6** [comment]
thanks
