### ISSUE TITLE
Question - non greedy regex for highlight_matched_range

### ISSUE THREAD

**Issue by raghur** [Shougo/denite.nvim#533]
# Problems summary
This isn't a problem as such. I'm writing a fuzzy plugin that matches greedily and not able to figure out what to return from `convert_pattern`. returning `convert2fuzzy_pattern(input_str)` matches greedily in the denite buffer. I'd like the match highlight to be non greedy. Vim has regex `{-}` for indicating non greedy but as far as I can tell, the pattern returned from `convert_pattern` is a py regex, not a vim regex.

vimscript noob  - so please be gentle :)

## Expected
Be able to use non-greedy regex to highlight matched range in denite

**Comment by Shougo** [comment]
I have fixed `convert2fuzzy_pattern()`.

**Comment by raghur** [comment]
This implementation can be improved - generated pattern for input `abc -> a.{-}b.{-}.{-}c` but a better pattern is `a[^a]{-}b[^b]{-}c`
Would you consider?

**Comment by Shougo** [comment]
OK.  I have fixed.
