### ISSUE TITLE
Support caching file list.

### ISSUE THREAD

**Issue by kevincox** [Shougo/denite.nvim#535]
# Problems summary

I work on a project with a lot of files. Just listing the files to `/dev/null` takes 2 minutes. (I use a custom command for listing files). While the incremental searching is incredibly useful waiting for files that get listed later is still far too slow for everyday use. It would be great if recently listed directories could be cached in memory for fast searching.

## Expected

When I open Denite with the same configuration for the second time it should already have all of the files loaded for quick filtering.

## Environment Information (Required!)

 * denite version (SHA1): 9ba61c71e66154de71e349a4b02a4d90d630dfb3
 * OS: Linux

**Comment by Shougo** [comment]
You can use `-resume` option for it.

**Comment by kevincox** [comment]
This isn't really a viable solution as it just preserves denite state. For example the previous filter is still there.

Additional conveniences are missing as well. For example it reuses the cache even if the working directory has changed. This means that the results shown will be incorrect. It would be nice if the configuration was checked before reusing.

**Comment by Shougo** [comment]
I have added the feature.

**Comment by kevincox** [comment]
Thanks for the quick response. It works perfectly.
