### ISSUE TITLE
Vim 81 on windows fails to open _socket

### ISSUE THREAD

**Issue by idvorkin** [Shougo/denite.nvim#536]
*I know the root cause is using python on vim windows is a pain*

My machine is win10/vim81/py36. When ever I open denite (which is an AWESOME tool) it fails to load since ```:py3 import socket``` fails. 

I've copied the python distribution into my vim folder, and many python package imports work. However, import socket does not.  Any chance we could catch this exception, or not include socket? 

https://github.com/Shougo/denite.nvim/blob/0a089bb122eb88e182420334a4f1df0c22917856/rplugin/python3/denite/source/file/point.py#L7

**Comment by Shougo** [comment]
> My machine is win10/vim81/py36. When ever I open denite (which is an AWESOME tool) it fails to load since :py3 import socket fails.

Hm..  You should check why `import socket` does not work.
I don't get the same error ever.

**Comment by idvorkin** [comment]
For other who hit this, I found my issue.  When I copied the python distribution into the gvim directory ``` C:\Program Files (x86)\vim\vim81``` I only copied a subset of the files. When I copied in all the files, denite began working correctly.
