### ISSUE TITLE
The character "$" is not displayed correctly.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/denite.nvim#539]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
The character "$" is not displayed correctly.

## Environment Information (Required!)

 * denite version (SHA1): 3f90067b8c866eb085d648850400e7fc7783ba01

 * OS: Mac

 * Vim/neovim version: neovim v0.3.1

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
nnoremap <silent> <Leader>f :<C-u>Denite file_rec<CR>
```

## How to reproduce problems from neovim startup (Required!)

 1. `$ echo Hello > $Hello.txt`
 2. `nvim`
 3. `:Denite file_rec`

**Comment by Shougo** [comment]
`$ echo Hello > \$Hello.txt`
