### ISSUE TITLE
 No module named 'neovim'

### ISSUE THREAD

**Issue by gerroon** [Shougo/denite.nvim#542]
Hi

I installed under Vim 8.1 on Windows 10 x64  and I seem to have Python3 support with it according to echo. I installed it using Vundle. When I try to invoke Denite this is the error I am getting, not sure why it is looking for neovim

thanks

`
Error detected while processing function denite#helper#call_denite[15]..denite#start[4]..<SNR>86_start[1]..denite#initialize[1]..denite#init
#_initialize[10]..denite#vim#_initialize:
line   19:
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "C:\Users\USER\.vim\bundle\denite.nvim/rplugin/python3\denite\__init__.py", line 13, in <module>
    import neovim
ModuleNotFoundError: No module named 'neovim'
`

**Comment by Shougo** [comment]
It is well known issue.
Please remove neovim module and reinstall pynvim module.

**Comment by gerroon** [comment]
Hi

Sorry i was not aware of it, where an how I remove the neovim module? I am not very advanced with this stuff.

**Comment by Shougo** [comment]
I get the reason.  Please update denite.nvim and use the latest version.

**Comment by gerroon** [comment]
Hi

Thanks for the update. But

`
denite] Traceback (most recent call last):
[denite]   File "<string>", line 9, in _temporary_scope
[denite]   File "C:\Users\USER\.vim\bundle\denite.nvim/rplugin/python3\denite\ui\default.py", line 70, in start
[denite]     self._start(context['sources_queue'][0], context)
[denite]   File "C:\Users\USER\.vim\bundle\denite.nvim/rplugin/python3\denite\ui\default.py", line 120, in _start
[denite]     self.init_denite()
[denite]   File "C:\Users\USER\.vim\bundle\denite.nvim/rplugin/python3\denite\ui\default.py", line 636, in init_denite
[denite]     self._denite.on_init(self._context)
[denite]   File "C:\Users\USER\.vim\bundle\denite.nvim/rplugin/python3\denite\denite.py", line 180, in on_init
[denite]     raise NameError('Source "' + name + '" is not found.')
[denite] NameError: Source "C" is not found.
[denite] Please execute :messages command.
`

**Comment by Shougo** [comment]
Hm.  I think your denite usage is wrong.
You should read denite usage.

You have executed `:Denite {some-path}`.  It does not work.
It must be `:Denite {source-name}:{path}`.

**Comment by Shougo** [comment]
And you should read the issue template and other issues.
Your report requires ESP skills.

I will ignore non-understanding report.

**Comment by gerroon** [comment]
Hi

Sorry i was acting quickly. It works now.
