### ISSUE TITLE
Ignore current buffer

### ISSUE THREAD

**Issue by mMontu** [Shougo/denite.nvim#543]
After many years using Ctrlp I've just started playing around with this plugin, and I'm wondering if it is possible to ignore the current buffer when running the following commands:

    :Denite file/rec
    :Denite file_mru

In another words, in a test directory with only three files, `fileA`,  `fileB`, and `fileC`:

    :cd <test directory>
    :e fileA
    :e fileB
    :e fileC

Currently both commands displays the three files (considering an empty mru cache). I'm looking for way to prevent the current file (`fileC`) from being displayed in the lists, as it seems useless and a distraction.

I've checked the documentation and google but couldn't find any clues. I guess the `--ignore` option isn't evaluated on every command execution, and probably would understand `%` as the current file, given the preference for implementing the plugin mostly on python.

**Comment by Shougo** [comment]
```
call denite#custom#source('buffer', 'matchers',
      \ ['matcher/fuzzy', 'matcher/ignore_current_buffer'])
```

**Comment by mMontu** [comment]
@Shougo works like a charm
Thanks!

**Comment by Shougo** [comment]
I have tested it and it works.

I think you have used wrong source name.
The source name must be `file_mru`.

If you think it is really bug,  please new issue with the minimal vimrc and the reproduce instructions.
If not, I will ignore it.
Please read issue template.  I have already warned in it.

**Comment by mMontu** [comment]
Thanks @Shougo 
I've been thinking and I am certain that it was working in the day you closed this ticket.
And it is very strange that I've tried again now and it is working.

I guess it may be a bug that only happens in specific scenarios. I'll pay attention when it happens again and try to come up with steps to reproduce the issue.
