### ISSUE TITLE
<denite:assign_previous_text> is incorrect after the first execution

### ISSUE THREAD

**Issue by mMontu** [Shougo/denite.nvim#547]
# Problems summary

Wrong result for `<denite:assign_previous_text>`  and `<denite:assign_previous_matched_text>`. After typing a match in `:Denite <source>` the text returned with <kbd>up</kbd> or <kbd>Ctrl</kbd>+<kbd>p</kbd> is wrong after the first execution.

## Expected

`<denite:assign_previous_text>`  and `<denite:assign_previous_matched_text>` returning always the same value until a different a match is selected.

## Environment Information (Required!)

 * denite version (SHA1): db2d7c30

 * OS: linux (Salix)

 * Vim/neovim version:
VIM - Vi IMproved 8.1 - Included patches: 1-431
Huge version with GTK3 GUI.

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

Reproduced without any init file.

## How to reproduce problems from neovim startup (Required!)

```
$ touch abc
$ touch def
$ gvim -u NONE -U NONE -N -i NONE
set nocompatible
let &rtp.=','.$HOME.'/.vim/bundle/denite.nvim'
source ~/.vim/bundle/denite.nvim/plugin/denite.vim
:Denite file/rec
abc<CR>
:Denite file/rec
def<CR>
:Denite file/rec
<up> --> shows 'def', as expected
<CR>
:Denite file/rec
<up> --> shows 'abc', expected 'def' again
```

Note it is the behavior doesn't change if <kbd>Ctrl</kbd>+<kbd>p</kbd> is used instead of <kbd>up</kbd>, or if the `<CR>` is replaced with `<Esc>` after the previous text is retrieved.

**Comment by Shougo** [comment]
Reproduced.

**Comment by mMontu** [comment]
Great!
