### ISSUE TITLE
Feature Request - Grep Replay

### ISSUE THREAD

**Issue by weilbith** [Shougo/denite.nvim#549]
I differ between populate search results to the quickfix list or to _Denite_ by the `grep` source to have fuzzy finding available. I guess the use cases are quite obvious. But I find myself to retype the same pattern again cause I missed something, turn to the false place, ... With the quickfix list I can go back in history in case I should have overwrite it already. But with `:Denite grep` I've to retype it again and maybe (usually not the case with `rg`) it need time to run the grep again. It would be awesome if I could define another `grep` source argument to reuse the old pattern or even reload its output and leave me directly to the _Denite_ buffer.
I tried to tinker a dirty solution with wrapper input and fill _Denite_'s input with it, but I can't get it working so far. Would be awesome to have such option! :upside_down_face:

**Comment by Shougo** [comment]
`:Denite grep -resume`
