### ISSUE TITLE
error after launch macvim in terminal

### ISSUE THREAD

**Issue by acerphoenix** [Shougo/denite.nvim#55]
i solve the original problem myself.
so said said another:
call denite#custom#filter('matcher_ignore_globs', '{variable_name}',['*.bak'])
what is the variable_name should i write?

**Comment by acerphoenix** [comment]
ok, i find it in  rplugin/python3/denite/filter/matcher_ignore_globs.py, the answer is ignore_globs

**Comment by Shougo** [comment]
I have fixed the default globs.
