### ISSUE TITLE
Is doautocmd ColorScheme _really_ necessary?

### ISSUE THREAD

**Issue by oblitum** [Shougo/denite.nvim#551]
I put a good amount of colorscheme tweaking on several `autocmd ColorScheme *`, which I expected to be called _only_ when I change colorscheme, after starting using denite.nvim, I got an issue, and figured out it was because denite calls `silent doautocmd ColorScheme` on every close of denite's windows:

https://github.com/Shougo/denite.nvim/blob/7d9e12653dcf8a1b4384114953bf109a00ee9a4b/rplugin/python3/denite/ui/default.py#L562

I wonder whether that can be done another way because colorscheme loading **and** associates is something expected to be done with low frequency, but denite makes it high frequency, besides triggering autocommands for colorschemes when actually no new colorscheme is loaded. I can circumvent my issue by saving and verifying whether `g:colors_name` really changed or not, but still, I have to do it in several places.

**Comment by oblitum** [comment]
I haven't checked the code to check possible fix. I've hit related colorscheme reloading issues with Goyo, which I ended up fixing by saving/restoring specific color groups, instead of full colorscheme reload:

- https://github.com/junegunn/goyo.vim/issues/156#issuecomment-441338333

**Comment by Shougo** [comment]
I don't know why the reloading is needed.
I have removed it.

**Comment by oblitum** [comment]
OK thanks :)

**Comment by oblitum** [comment]
Notice though that it was not reloading colorscheme, but instead calling its ColorScheme `autocmd`.
