### ISSUE TITLE
Cursor highlight disappears when using move_up_path action

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#559]
Consider the following minimal vimrc:

```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/petobens/colorish

syntax enable
colorscheme onedarkish

call denite#custom#option('default', {
            \ 'highlight_mode_insert': 'WildMenu'
            \ })
call denite#custom#map('insert', '<A-p>', '<denite:move_up_path>', 'noremap')
```
then open vim and run:
i) `:Denite directory_rec` and (as in the GIF) select a candidate and press `<CR>`
ii) Press `<A-p>` to return to the previous path -> the cursor highlighting disappears.

I expect that after using `move_up_path` the cursor highlight is respected:

![denite_cursor](https://user-images.githubusercontent.com/2583971/51076266-0d33e400-1675-11e9-99a9-63febb40be2d.gif)

**Comment by Shougo** [comment]
Reproduced.

**Comment by petobens** [comment]
Thanks.
