### ISSUE TITLE
"Denite grep", quote required?

### ISSUE THREAD

**Issue by pocari** [Shougo/denite.nvim#56]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
In `Denite grep`, Using search word separated space, error has occured in `process.py`  

`test.txt` contents is
```
Dark powered for Nvim
Dark powered for Vim8
```

and I run `Denite grep` , entered `dark powerd`.

I logged the arguments passed to `subprocess.Popen` in `Process#__init__`.
and I run it on IPython repl. 

So, following error.
```
In [9]: command2
Out[9]: ['grep', '-inH', '-r', '--', 'dark', 'powered', '.']

In [10]: subprocess.Popen(command2)
Out[10]: grep: powered: No such file or directory
./test.txt:1:Dark powered for Nvim
./test.txt:2:Dark powered for Vim8
<subprocess.Popen at 0x10f811048>
```
 use only `dark`,  ignored `powered`.

If I enterd `'dard powered'`, Arguments passed to `subprocess.Popen` is `['grep', '-inH', '-r', '--', 'dark powered', '.']`

```
In [4]: command
Out[4]: ['grep', '-inH', '-r', '--', 'dark powered', '.']

In [5]: subprocess.Popen(command)
./test.txt:1:Dark powered for Nvim
./test.txt:2:Dark powered for Vim8
Out[5]: <subprocess.Popen at 0x10e639d30>
```

It seems good.

## Expected

Input patterns should be quoted automatically(?)

## Provide a minimal init.vim with less than 50 lines (Required!)

`test_vimrc`
```vim
let s:dein_dir = expand('~/.cache/dein2')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

call dein#begin(s:dein_dir)

call dein#add('Shougo/denite.nvim')

call dein#end()
call dein#save_state()

if dein#check_install()
  call dein#install()
endif
```

## The reproduce ways from neovim starting (Required!)

```
% cat test.txt
Dark powered for Nvim
Dark powered for Vim8
```

nvim -u test_vimrc
 
:Denite grep
dark powered

**Comment by Shougo** [comment]
It is the feature.
https://github.com/Shougo/denite.nvim/pull/17
