### ISSUE TITLE
:Denite coloscheme -post-action=open

### ISSUE THREAD

**Issue by tracyone** [Shougo/denite.nvim#562]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

## Environment Information (Required!)

 * denite version (SHA1):

 * OS:mac os 10.14.2

 * Vim/neovim version:

```


NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/config -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/src/nvim/auto -I/tmp/neovim-20190113-94620-d8vv4n/neovim-0.3.4/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.4/share/nvim"

```

Run :checkhealth for more info

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible
let &rtp=&rtp.','.$HOME.'/.vim/bundle/denite.nvim'
colorscheme desert "default setting 
filetype plugin indent on
syntax on
```

## How to reproduce problems from neovim startup (Required!)

 nvim -u vimrc_mini

:Denite colorscheme -post-action=open

colorscheme will restore after denite buffer is closed!

**Comment by Shougo** [comment]
I have tested it and it works as expected.

**Comment by Shougo** [comment]
> colorscheme will restore after denite buffer is closed!

You should explain it in more detailed.
If not, OK I will ignore your report.

**Comment by tracyone** [comment]
@Shougo Please see the screen record, can not apply colorscheme!!!

**Comment by Shougo** [comment]
The behavior is expected.
You should use `Unite colorscheme -auto-preview` instead.

**Comment by Shougo** [comment]
Note:  The behavior is same with unite-colorscheme.

**Comment by tracyone** [comment]
ok, ths

**Comment by zhuangya** [comment]
> The behavior is expected.
> You should use `Denite colorscheme -auto-preview` instead.

for now, if you wanna preview colorscheme automatically, use this command instead:

`Denite colorscheme -auto-action=preview`
