### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by henrllb** [Shougo/denite.nvim#566]
Hi,

I am using vim 8.1.744 under ubuntu 18.04.

I have two questions. Maybe someone could be help me ?

(1) In source file, how can we add the action "delete the selected file" ?

(2) In any source, how can we add a command to open the selected files with xdg-open ?   In the file denite.nvim/autoload/denite/util.vim, I see the command denite#util#open(filename) that seems to will do exactly what I want. However, I don't know how we can write such a customized command.

Thank you very much for your help !

Best

**Comment by Shougo** [comment]
> (1) In source file, how can we add the action "delete the selected file" ?

`:help denite#custom#action()`

> (2) In any source, how can we add a command to open the selected files with xdg-open ? In the file denite.nvim/autoload/denite/util.vim, I see the command denite#util#open(filename) that seems to will do exactly what I want. However, I don't know how we can write such a customized command.

`denite#custom#action()`.
You should use `file` as kind.

**Comment by henrllb** [comment]
Hi,

sorry to ask again. I am not computer scientist. Then it is not so easy for me. I try the following

call denite#custom#action('file','test','denite#util#open')

There is a new action entry in the source file, called 'test' as expected, but an error is returned. What am I doing wrong ?

Thx very much for the help.

Best

**Comment by Shougo** [comment]
You should read `denite#custom#action()`documentation and learn Vim script.

```vim
	call denite#custom#action('file', 'test',
	      \ {context -> denite#util#open(context['targets'][0])})
```

Note: I am very busy to develop plugins and support like you.
Please don't wast my time.
