### ISSUE TITLE
Root markers

### ISSUE THREAD

**Issue by abylkasymovkuat** [Shougo/denite.nvim#569]
I am sorry, I am a noob. The problem is not with the plugin, but with me. I want to set root directory in the django project. And the root is the folder where the Pipfile is. So, I tried to read the docs. 
After trying, I wrote in init.vim
`call denite#custom#option('_', 'root_markers', 'Pipfile')`
But nothing changed. When I press `<ctrl-p>` it prints files only from currend directory.
I don't know how to set the root correctly

**Comment by abylkasymovkuat** [comment]
@viniarck, big thanks to you

**Comment by abylkasymovkuat** [comment]
@viniarck, it is working as a charm, ^_^

**Comment by viniarck** [comment]
Cool :)

@abylkasymovkuat, I believe you could close this issue then?

**Comment by kuator** [comment]
@Shougo, big thanks, I only saw your response
