### ISSUE TITLE
quick-move not working as expected

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#571]
Consider the following minimal vimrc:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on
```
Now:
i) open nvim and open two random files such as `foo.html` and `foo.json`
ii) Run `Denite mode=normal buffer`
iii) Press X to  use `quick_move` 
iv) Quick matches (`a, s, d, f` ,etc ) are not displayed in the buffer

![screenshot_2019-02-09_14 58 14](https://user-images.githubusercontent.com/2583971/52524394-38f9b800-2c7b-11e9-8d1a-1f4a9354e7b4.png)

So my question is: how do i get `quick-move` to work as Unite's quickmatch? Basically I would like to run `Denite -mode=normal -quick-move buffer` and be able to select candidates with `a,s,d,f` , etc. Thanks in advance!

**Comment by petobens** [comment]
Thank you!. One question though:

> I would like to run `Denite -mode=normal -quick-move buffer` and be able to select candidates with `a,s,d,f`

Is that possible? i.e I want to have mapping that automatically opens in `quick-move` mode and once I select a candidate with `a,s,d,f` it executes the default action.

**Comment by Shougo** [comment]
I have added `quick-move` option.

**Comment by petobens** [comment]
> I have added `quick-move` option.

Thank you! Is there a way to both select and execute the candidate when pressing `a,s,d,f`? Currently the candidate is only selected and in order to execute the default action I have to press an extra `<CR>`.

**Comment by Shougo** [comment]
I don't want to add the feature.  Because, you may want to execute other actions.

**Comment by petobens** [comment]
And you don't want to add an argument to `-quick-move` such as `-quick-move=immediately`?

**Comment by Shougo** [comment]
I have implemented it.

**Comment by petobens** [comment]
Thank you!
