### ISSUE TITLE
Feature: Add file/rec and directory_rec argument to pass extra flags to command

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#572]
I currently use `fd` like so:
```viml
if executable('fd')
    call denite#custom#var('file/rec', 'command',
        \ ['fd', '--type', 'f', '--follow', '--hidden', '--exclude', '.git',
        \ ''])
    call denite#custom#var('directory_rec', 'command',
        \ ['fd', '--type', 'd', '--follow', '--hidden', '--exclude', '.git',
        \ ''])
endif
```
and have the following mappings:
```viml
nnoremap <silent> <Leader>ls :lcd %:p:h<CR>:Denite file/rec<CR>
nnoremap <silent> <A-c> :lcd %:p:h<CR>:Denite directory_rec<CR>
```

I would like to define a new mapping that adds a `--no-ignore` flag to the `file/rec`/`directory_rec` commands.  The grep source allows to do this by doing something like:
```viml
    call denite#start([{'name': 'grep',
                \ 'args': [narrow_dir, extra_args]}])
```
but the `file/rec` and `directory_rec` only accept one argument (arg 0) which is search directory. So my questions is: can you add an extra argument that allows to pass extra flags to the `file/rec`/`directory_rec` commands? Thanks!

**Comment by Shougo** [comment]
> I would like to define a new mapping that adds a `--no-ignore` flag to the `file/rec`/`directory_rec` commands. The grep source allows to do this by doing something like:

Please use `denite#custom#alias()` instead.

```vim
call denite#custom#alias('source', 'file/rec/noignore', 'file/rec')
```

**Comment by petobens** [comment]
Neat!. Thank you!!
