### ISSUE TITLE
Smartcase does not seem to work as expected.

### ISSUE THREAD

**Issue by uinput** [Shougo/denite.nvim#573]
# Problems summary

The `smartcase` option does not seem to work like intended. While having a file with a capitalized name and entering the exact few first letters in the search bar (using `file/rec`), the candidate disappears from the denite buffer.

As I'll show later in an example, the feature does not behave according to the documentation. Please run the example as given below to mimic the described behavior.

## Expected

When filtering a list of candidates, `denite` should ignore the case when the input contains uppercase characters as according to the documentation.

## Environment Information (Required!)

 * denite version (SHA1): 334fce21f798a3c4c7b33a37b107df28069e2bd7
 * OS: Fedora 28
 * Vim/neovim version: NVIM v0.3.1
 * `:checkhealth` or `:CheckHealth` result(neovim only): `python3-neovim version: 0.2.6`

## Provide a minimal init.vim with less than 50 lines (Required!)

Reproducible with `nvim -u NONE` and adding Denite to the runtimepath.

## How to reproduce problems from neovim startup (Required!)

* `$ touch example.txt General.txt`
* `$ nvim -u NONE example.txt`
* `:set runtimepath+=~/path/to/denite.nvim`
* `:source ~/path/to/denite.nvim/plugin/denite.vim`
* `:call denite#custom#option('_', 'smartcase', v:true)`
* `:Denite file/rec`
* Type `Gen` into the search bar. You will find that the candidate `General.txt` disappears from the list.

**Comment by Shougo** [comment]
Reproduced.  But it is not smartcase problem.
