### ISSUE TITLE
no-quit not working with dein_log

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#576]
I'm not sure if this is a problem with dein or denite but when I use the following mapping to update my plugins:
```viml
function! s:dein_update()
  call dein#update()
  Denite -no-quit -mode=normal dein_log:!
endfunction
nnoremap <Leader>bu :call <SID>dein_update()<CR>
```
and hit `<ENTER>` in the url of an updated plugin then the denite buffer closes. This has recently started to happen (i.e it used to work fine respecting the `-no-quit`) option. I'm not adding a minimal vimrc since I've only noticed the behaviour when plugins actually update (which doesn't happen all the time).

**Comment by Shougo** [comment]
It is deprecated option.

```
* Remove "-force-quit" and "-no-quit" options.  Please use "post-action"
  option instead.
```

**Comment by Shougo** [comment]
The feature is already deprecated in the last year.
I just have removed the compatibility layer.

**Comment by petobens** [comment]
Ahh ok. Thanks!
