### ISSUE TITLE
something broken

### ISSUE THREAD

**Issue by zgpio** [Shougo/denite.nvim#579]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Something broken afterI updated denite.nvim.

## Expected
see below

## Environment Information (Required!)

 * denite version (SHA1): commit c779cc48d

 * OS: Windows10

 * Vim/neovim version: vim8.1 included patches: 1-906

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/vimfiles/denite.nvim/
nnoremap <silent> / :<C-u>Denite -buffer-name=search -auto-highlight line<CR>
call denite#custom#action('file', 'test', {context -> execute('let g:foo = 1')})
```

## How to reproduce problems from neovim startup (Required!)

 1. startup gvim
 2. press `/`, you will see follow info:
![image](https://user-images.githubusercontent.com/19503791/52859384-8092af00-3167-11e9-9c2b-8a36cc13b90b.png)

**Comment by Shougo** [comment]
```vim
call denite#custom#action('file', 'test', {context -> execute('let g:foo = 1')})
```

In Vim8, lambda function is not supported.  It works on neovim.
Please don't use lambda.
