### ISSUE TITLE
[feature request] vertical preview

### ISSUE THREAD

**Issue by rafi** [Shougo/denite.nvim#59]
Would it be possible to implement a _vertical_ preview option?

This was a really helpful feature with Unite's `vertical_preview` option, giving much more context around if the window is high enough. Example:

![image](https://cloud.githubusercontent.com/assets/147918/20238702/ffcf3e58-a8f9-11e6-9156-5b308fc3a7b1.png)

**Comment by rafi** [comment]
Thank you @Shougo.
Is it possible to have the preview window adjacent to Denite's window?
It was very helpful with Unite for people who use a lot of splits in one tab...
```
+--------------------------+
|Win 1    |Win 2   |Win 3  |
|         |        |       |
|         |        |       |
|         +--------+       |
|         |Win 4   |       |
|         |        |       |
+---------+--------+-------+
|Denite         |Preview   |
|               |          |
|               |          |
+---------------+----------+
```

**Comment by Shougo** [comment]
Implemented.
