### ISSUE TITLE
noautocmd when running preview action and open preview file in specific line

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#595]
In my vimrc I have some autocommands that fire upon `BufWinEnter`. For example
```viml
au BufWinEnter {*.*,vimrc,bashrc,config}  silent! loadview
au WinEnter,BufWinEnter *.py call virtualenv#activate('', 1)
```
As far as I can tell the preview action also triggers these autocommands when displaying a file in the preview window (through the preview action). Can such autocommands be disabled?

Also: is it possible to specify a line number when triggering the preview action?
Thanks in advance!

**Comment by Shougo** [comment]
> As far as I can tell the preview action also triggers these autocommands when displaying a file in the preview window (through the preview action). Can such autocommands be disabled?

You should check `'previewwindow'` option's value.

> Also: is it possible to specify a line number when triggering the preview action?
Thanks in advance!

It is not possible.  You should create the new action.

**Comment by petobens** [comment]
Thank you!
