### ISSUE TITLE
Custom action invalid

### ISSUE THREAD

**Issue by zgpio** [Shougo/denite.nvim#597]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I don't know if it's a denite problem, or if I use it incorrectly. I think I got enough information from the reference manual to customize the action and use the action.

## Environment Information (Required!)

 * denite version (SHA1): 885ca67

 * OS: Linux

 * Vim/neovim version: NVIM v0.4.0-420-g29d6993cc

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set rtp+=~/test_nvim/denite.nvim/
call denite#custom#action('echo', 'update', {context -> execute('let g:foo = 1')})
call denite#custom#map('insert', '<c-u>', '<denite:do_action:update>', 'noremap')
```

## How to reproduce problems from neovim startup (Required!)

 1. nvim -u init.vim
 2. :Denite file
 3. press ` <C-u>`
 4. It show below:
![image](https://user-images.githubusercontent.com/19503791/54860667-5f217600-4d58-11e9-85b5-f040b6ca99cf.png)

**Comment by Shougo** [comment]
```vim
call denite#custom#action('file,directory', 'update', {context -> execute('let g:foo = 1')})
```

Please read the documentation.
