### ISSUE TITLE
How to search for files in root

### ISSUE THREAD

**Issue by kuator** [Shougo/denite.nvim#615]
So, actually I got answer here https://github.com/Shougo/denite.nvim/issues/569, but still don't get it to work. I want to search for files from root directory, but `DeniteProjectDir file/rec` prints files of current directory. Init.vim: 
`call denite#custom#option('_', 'root_markers', 'Pipfile')`

**Comment by Shougo** [comment]
Reproduced.  It is bug.

**Comment by kuator** [comment]
Thanks
