### ISSUE TITLE
[Q] Single menu instead of submenus

### ISSUE THREAD

**Issue by idanko** [Shougo/denite.nvim#618]
Hello there. I use denite as frontend and a bit confusing on how to use the custom menu. In the examples provided, firstly it creates a parrent menu and then adds some others submenus:

```vim
" Create the global menu
let s:menus = {}
" Create inner zsh submenu
let s:menus.zsh = ...
" Create inner my_commands submenu
let s:menus.my_commands = ...
" Register the menu
call denite#custom#var('menu', 'menus', s:menus)

" Call menu
exec "Denite menu"
```

Is there a way to call submenu directly like `exec "Denite menu/my_commands"` or register a single submenu?

**Comment by Shougo** [comment]
Please use `Denite menu:my_commands` instead.
