### ISSUE TITLE
Remove prompt.nvim and replace current UI

### ISSUE THREAD

**Issue by Shougo** [Shougo/denite.nvim#625]
To fix #509 problem, I need to remove prompt.nvim unfortunately.

The changes are compatible with current sources, filters, kind.
But no compatible with current mode and mappings features.

**Comment by Shougo** [comment]
The implementation will be like defx.nvim.

**Comment by Shougo** [comment]
`denite#custom#map()` will be removed.

**Comment by tex** [comment]
I am using `denite#custom#map()` heavily. Will there be some other way to customize mappings in Denite?

**Comment by Shougo** [comment]
> Will there be some other way to customize mappings in Denite?

The mappings will be like defx.nvim.
Another mappings API will be added.
