### ISSUE TITLE
Feature request: Customize default-action per kind.

### ISSUE THREAD

**Issue by Milly** [Shougo/denite.nvim#628]
# Problems summary

The default-action can be changed for global or per buffer-name.
Can not change it for per kind.

Are there plans this new feature?

I wanted to create a PR if no plans, but I'm waiting to merge #624 that conflicts.

## Environment Information (Required!)

 * denite version (SHA1): ae432f2

 * OS: Linux, Ubuntu 18.04.2 LTS

 * Vim/neovim version: Vim 8.1.1176

**Comment by Shougo** [comment]
> Are there plans this new feature?

It is no plan.

> I wanted to create a PR if no plans, but I'm waiting to merge #624 that conflicts.

Hm.  But it takes time.
Please upload the PR.  I will check it later.

**Comment by Shougo** [comment]
You can test #624

**Comment by Shougo** [comment]
I will implement the feature later.
