### ISSUE TITLE
Feature Request: don't steal focus when denite is opened.

### ISSUE THREAD

**Issue by dsummersl** [Shougo/denite.nvim#630]
# Problems summary

Given the plethora of plugins that operate asynchronously, there are cases where Denite could be used to handle the result of an asynchronous request. Create an option to launch Denite, but don't change the cursor's current position/focus.

Example: I use Grepper for search, and have configured Grepper to use Denite as its quickfix viewer with `autocmd User Grepper :Denite quickfix`. Since Grepper searches asynchronously, when a search takes several seconds I can continue to work within my current buffer. Once Grepper has collected its search results it launches Denite, and interrupts whatever other task I may be performing in the editor. Ideally I could configure Denite to launch in the background so that I can see the search results, but whatever task I am currently performing is not interrupted.

**Comment by Shougo** [comment]
You should use `wincmd p` in ui branch.

**Comment by dsummersl** [comment]
kinda confused here...how would I do that? I tried something like `autocmd User Grepper :Denite -do='wincmd p' quickfix` or `autocmd User Grepper :Denite quickfix \| wincmd p`...neither of which ended well!

**Comment by Shougo** [comment]
Please use the branch.
https://github.com/Shougo/denite.nvim/pull/624

And:

`autocmd User Grepper Denite quickfix | wincmd p`

**Comment by dsummersl** [comment]
Interesting, it sort of works...except the quickfix window is opened rather than denite's window (seems to be a problem with `Denite quickfix` ittself)

**Comment by Shougo** [comment]
You can close the quickfix window by `cclose` command.

**Comment by Shougo** [comment]
`autocmd User Grepper cclose | Denite quickfix | wincmd p`

**Comment by dsummersl** [comment]
It works, thank you! I didn't realize with this `ui` branch merge I would have to define my own mappings. Once I got through that, I was able to get it working.

One interesting little bug is that specifying `-matchers=matcher/regexp` I see an error `[denite] Empty sources`. Taking it out works fine. 🤷‍♂

Thank you!

**Comment by Shougo** [comment]
> One interesting little bug is that specifying -matchers=matcher/regexp I see an error [denite] Empty sources. Taking it out works fine. man_shrugging

`:Denite file -matchers-matcher/regexp` works for me.
I think you don't provide sources in arguments.

**Comment by dsummersl** [comment]
I had done `-matchers="matcher/regexp"` and it didn't like it for some reason. Removing the double quotes and it works. Thanks!
