### ISSUE TITLE
[Q] Floating ui centered

### ISSUE THREAD

**Issue by JackShannon** [Shougo/denite.nvim#633]
Can the ui be centered in the middle?

The defaults and the readme screenshot do not do this:
https://user-images.githubusercontent.com/1239245/54329573-8b047380-4655-11e9-8b9a-ab4a91f4768f.gif

If possible how can I configure this? If not, I think this might be worth implementing as it would look smarter.

**Comment by Shougo** [comment]
`:Denite -split=floating`

You can change the position by `winrow` option.
