### ISSUE TITLE
[Feature Request] option -immediately-1 when live-filtering

### ISSUE THREAD

**Issue by sheoak** [Shougo/denite.nvim#637]
When filtering live (for example : `:Denite file/rec`, then typing a search) I would like to jump immediately to the matching result when it becomes the only one. This would be similar to Ranger "find " command.

If I understand correctly the -immediately-1 option only works when opening the Denite window, not when filtering live? Is there a way to implement this with simple mapping or does it require an implementation in Denite?

Thank you!

**Comment by Shougo** [comment]
No.

**Comment by Shougo** [comment]
> If I understand correctly the -immediately-1 option only works when opening the Denite window, not when filtering live? 

Yes.

I don't add the feature. Because, it is not so useful and has the problem in especially in https://github.com/Shougo/denite.nvim/pull/624.
