### ISSUE TITLE
How to switch source from within denite?

### ISSUE THREAD

**Issue by mgraham** [Shougo/denite.nvim#638]
If I am in the `buffer` source, I would like to make a mapping to switch to the `file_mru` source, preserving the search text.

Is that possible?

**Comment by Shougo** [comment]
>  preserving the search text.

This is not possible.

I think this is better answer for you.

`:Denite buffer file_mru`

Denite is not ctrlp.

**Comment by mgraham** [comment]
Ah, that's too bad.  I came to rely on this feature in Unite.  :(   Thanks for the clarification!
