### ISSUE TITLE
matcher_ignore_globs does not ignore files properly

### ISSUE THREAD

**Issue by ohcibi** [Shougo/denite.nvim#64]
# Problems summary

Ignoring globs in `file_rec` source will still scan all the ignored globs and makes the whole search less performant.

## Expected

The ignored globs should not be scanned at all.

## Environment Information

 * OS: macOS 10.12.1

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

```

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - ERROR: key_backspace (kbs) entry is ^H (ASCII DELETE): key_backspace=^H,

    - SUGGESTIONS:
      - Set key_backspace to \177 (ASCII BACKSPACE). Run these commands:
          infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
          tic $TERM.ti
      - See https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.11
  - SUCCESS: Latest python2-neovim is installed: 0.1.11

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.11
  - SUCCESS: Latest python3-neovim is installed: 0.1.11

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  - INFO: Host Executable: /Users/ohcibi/.rvm/gems/ruby-2.3.1/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.1

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath^=~/.vim/dein/repos/github.com/Shougo/dein.vim

" Required:
call dein#begin(expand('~/.vim/dein'))

" Let dein manage dein
" Required:
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/denite.nvim')

" Required:
call dein#end()

" Required:
filetype plugin indent on

" If you want to install not installed plugins on startup.
if dein#check_install()
 call dein#install()
endif

call denite#custom#source('file_rec', 'matchers', ['matcher_fuzzy', 'matcher_ignore_globs'])
call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
      \ [ '*~', '*.o', '*.exe', '*.bak',
      \ '.DS_Store', '*.pyc', '*.sw[po]', '*.class',
      \ '.hg/', '.git/', '.bzr/', '.svn/',
      \ 'node_modules/', 'bower_components/', 'tmp/', 'log/', 'vendor/ruby',
      \ '.idea/', 'dist/',
      \ 'tags', 'tags-*'])
```

## The reproduce ways from neovim starting (Required!)

I cloned this repository and run `npm install`: https://github.com/ember-cli/ember-cli. Can be tested with any directory that contains a rather large `node_modules` directory.

 1. Call `:Denite file_rec`
 2. Type something

With the ignore_globs matcher enabled typing will react very slowly and the total number of files that is displayed is the total number of files in the directory and not the total number of files after filtering out the ignored globs. In another project I even have the problem that scanning never stops. I cannot investigate why and I wasn't able to reproduce this with this smaller example.

It should be possible to completely ignore some globs as it is possible with ctrl-p

**Comment by Shougo** [comment]
This is not bug.
`matcher_ignore_files` just ignore globbed files.
So globbed candidates are already generated by file_rec source.
You must filter in file_rec source in the large directory.
ag can ignore .gitignore files and you can add the more directories.

**Comment by Shougo** [comment]
> It should be possible to completely ignore some globs as it is possible with ctrl-p

Ctrlp uses glob().  It ignores 'wildignore' files automatically.
Ctrlp works.  Because it has different implementation.

**Comment by legendar** [comment]
@Shougo 
can you please provide example how to ignore and prevent scanning large directories like 'node_modules' ?

**Comment by ohcibi** [comment]
@legendar: it has to be done in the `command`. See the example in `:help denite` which uses ag as a command. `ag` ignores `.gitignore`ed files and if `node_modules` is ignored it's blazingly fast. So the bottomline is: use a command that ignores those directories.

Due to restrictions of the command customizing implementation and the special format of the `find` syntax it is currently not possible to use `find` properly to ignore directories but I'll make a pr that addresses this next week.

**Comment by tmdlzp** [comment]
hi, @lambdalisue, could you show your solutions after this discussion?

**Comment by lambdalisue** [comment]
Hum? Why did you mention me?

Well, anyway, I'm standing on the Shougo's side. I don't think this is a bug on denite. What you need is read the documentation of denite and e.g. ag for proper options.

Additionally, I don't use file_rec often. Usually I use my plugin to list and filter files tracked by git. If you interested, gina.vim + lista.nvim combination is what I rely on but don't ask me how to use these in this issue while this issue is for denite.nvim :smile:

**Comment by nadya-p** [comment]
Workaround: specify patterns to be ignored in `wildignore`

**Comment by nickmcdonnough** [comment]
@nadya-p can you provide an example? This is what i have:

`set wildignore+=**/bower_components/**,**/node_modules/**,**vendor/bundle**,**target/scala**,**project/target**,*.jpg,*.gif,*.png,*.svg,*.zip`

Yet I keep seeing files from node_modules appear in my `file_rec` results.

**Comment by Shougo** [comment]
@nickmcdonnough 

file_rec does not ignore wildignore by default.
You must specify scantree.py like this.

```
call denite#custom#var('file/rec', 'command', ['scantree.py'])
```

**Comment by nickmcdonnough** [comment]
Interesting. Thanks @Shougo

**Comment by nickmcdonnough** [comment]
I'll try that. Thanks @Shougo

**Comment by nickmcdonnough** [comment]
I dont understand how your example helps ignore files.

**Comment by ohcibi** [comment]
@nickmcdonnough Read the other comments. The point is that the command itself needs to ignore the files whatever that might look like for the specific command. So if the command that ignores the specific files would look like e.g. `scantree.py --flag-that-tells-scan-tree-which-patterns-to-ignore=node_modules,bower_components,tmp,log` the example should read

    call denite#custom#var('file/rec', 'command', ['scantree.py', '--flag-that-tells-scan-tree-which-patterns-to-ignore=node_modules,bower_components,tmp,log'])

It is possible to ignore results with denite; however that is not very performant in large directories as your subcommand would still return the entire list of matches.

It is *not* the point of denite to filter the lists it's subcommands generate in the best performant ways. The point is to provide a generic way to generate lists with whatever tools and then augment those lists with specific actions for each item in the list (e.g. list of all files matching a specific pattern inside the current directory and open each file in a new buffer when hitting enter) . By having a generic API for generating those lists one can use the power and knowledge of well established command line tools like find, ack-grep, ag, git, etc. which are the best what you can get for the specific tasks they solve. Therefore stuff like filtering the lists is best done with those tools itself as its impossible to defeat their performance from inside vim (except by simply calling them directly). If one wants a ctrlp like file opener that does all that in a performant way from inside vim with by default respecting `wildignore`, one needs to use a different plugin like ctrlp itself.

@Shougo the issue I originally opened was due to my misunderstanding and is thoroughly solved by yours and mine explanations. Close it (I would but I can't)?

**Comment by Shougo** [comment]
> @Shougo the issue I originally opened was due to my misunderstanding and is thoroughly solved by yours and mine explanations. Close it (I would but I can't)?

The issue is already closed.

**Comment by Shougo** [comment]
OK
