### ISSUE TITLE
Denite起動後、何故かnormal modeでmodifiable is offで言われる

### ISSUE THREAD

**Issue by take** [Shougo/denite.nvim#640]
# Problems summary

タイトルの通りです、以下の画像の様に起動後入力を受け付けない状態です

`:Denite file/rec`

<img width="1920" alt="Screen Shot 2019-06-03 at 0 36 02" src="https://user-images.githubusercontent.com/1095842/58763641-59d27a00-8598-11e9-8add-0b5565e2baaa.png">

## Expected

入力を付けつける

## Environment Information (Required!)

 * denite version (SHA1): f1d40d0

 * OS: macOS Mojave 10.14.4

 * Vim/neovim version: 

```
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 30 2019 19:14:02)
macOS version
Included patches: 1-1400
Compiled by Homebrew
```

## Provide a minimal init.vim with less than 50 lines (Required!)

init.vimが何かちょっとわからず、再現するための最小限の.vimrcでしたら以下になります

```vim
if &compatible
  set nocompatible
endif

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
        call dein#begin('~/.cache/dein')
        call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

        call dein#add('Shougo/Denite.nvim')
        if !has('nvim')
                call dein#add('roxma/nvim-yarp')
                call dein#add('roxma/vim-hug-neovim-rpc')
        end

        call dein#end()
        call dein#save_state()
endif

filetype plugin indent on
syntax enable
```

`.cache/dein`を消し、上記の.vimrcでプラグインのインストールもし直しましたが、同じ現象が起きており困ってます… :( 

過去のissuesを漁ってみたのですが、同じような報告が無く、過去に似たような事例等や、解決に関わりそうな事等ありましたら教えていただけると助かります :bow:

**Comment by kazukazuinaina** [comment]
おそらくですが，以下の設定を.vimrcに書いていないからだと思います．
<img width="503" alt="スクリーンショット 2019-06-03 1 49 51" src="https://user-images.githubusercontent.com/36619465/58764445-fb11fe00-85a1-11e9-8fcf-04a22a8df747.png">
自分の手元で確認したら，再現しました．

**Comment by take** [comment]
@kazukazuinaina 

おおおおおおありがとうございます！僕の設定不足でした… :bow: 

そういえばDeniteの入力モード中、デフォルトだと c-g や c-t でカーソル移動出来た気がするんですが気の所為でしょうか… :eyes:

**Comment by Shougo** [comment]
> そういえばDeniteの入力モード中、デフォルトだと c-g や c-t でカーソル移動出来た気がするんですが気の所為でしょうか… eyes

その機能は削除されました。
Insert mode での移動は推奨していません。

**Comment by take** [comment]
なるほどです！アップデートしたら出来なくなったのはそういうことなんですね、ありがとうございます！

**Comment by languitar** [comment]
Could someone translate this to English? I am probably facing the same issue.

**Comment by tex** [comment]
You need to provide mappings. In this case probably for 'i' to call open_filter_buffer.

**Comment by languitar** [comment]
Ok, thanks. Is there any chance to go into insert mode immediately after all the changes?

**Comment by take** [comment]
>  immediately after all the changes?

you mean immediately after `:Denite` command? what do you mean by "all the changes" ? :eyes:

**Comment by languitar** [comment]
yes, immediately after calling `:Denite`, which further keyboard interaction.

At least the mapping configuration has changed significantly.

**Comment by Shougo** [comment]
> Ok, thanks. Is there any chance to go into insert mode immediately after all the changes?

```
						*denite-option-start-filter*
-start-filter
		Start filtering on default.
		Default: false
```

**Comment by languitar** [comment]
Thanks!

**Comment by take** [comment]
ooooo I didn't know this as well, thanks!
