### ISSUE TITLE
【質問】リアルタイム検索（インクリメンタルサーチ）がオフになる境目

### ISSUE THREAD

**Issue by take** [Shougo/denite.nvim#641]
お世話になっております。

`:Denite file/rec`を使っていて、ファイル数が多いプロジェクトだと自動的にインクリメンタルサーチがオフになっていることに気づきました。

具体的には56046ファイルのプロジェクトだとオフで、18730ファイルだとオン

何ファイル以上だとオフになっている、というのがあるのでしょうか？ :eyes: 
またそのファイル数を設定で変えれたりしますでしょうか？

以上お手数ですが回答いただけると助かります :bow:

**Comment by Shougo** [comment]
```
				*denite-option-max-dynamic-update-candidates*
-max-dynamic-update-candidates={length}
		If the candidates are more than it, denite will ignore the
		dynamic filtering.

		Default: 20000
```

**Comment by Shougo** [comment]
> 具体的には56046ファイルのプロジェクトだとオフで、18730ファイルだとオン

かなりやばいプロジェクトで編集しているんですね……

**Comment by take** [comment]
おおおおありがとうございます！！！！！ :pray:
