### ISSUE TITLE
split option is being ignored

### ISSUE THREAD

**Issue by timjackleus** [Shougo/denite.nvim#642]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
When looking at the screenshots for this amazing plugin I was very inspired but after reading through the docs I am still unable to make the floating window option work.
When using the split option. no matter what I pass into -split e g `-split="floating"` I still get the horizontal direction.

## Expected
Floating window.

## Environment Information (Required!)

 * denite version (SHA1): `f1d40d0`

 * OS: MacOS `10.14.5`

 * Vim/neovim version: `0.3.4`

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
Plug 'Shougo/denite.nvim'

nmap ; :Denite buffer -split=floating -winrow=1<CR>
```

## How to reproduce problems from neovim startup (Required!)

 1. `:Denite buffer -split=floating`

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/5394335/58779157-47c2fc80-85d5-11e9-9415-889a2280945e.png)

**Comment by Shougo** [comment]
Your neovim version is old.
neovim 0.3.5+ is needed for the feature.
