### ISSUE TITLE
Question : How to remap in "denite-filter" buffer

### ISSUE THREAD

**Issue by JCavallo** [Shougo/denite.nvim#644]
Hi,

I'm currently on latest master (https://github.com/Shougo/denite.nvim/commit/7eefcb6075ceb7934fe3f2af8f024a59604aa7ee), and I switched to the 'floating' window of neovim.

I used to have a mapping that would exit from insert-mode in the filtering window to focus the list of candidates, but I found no way to do that with the new UI.

Am I missing something ? Maybe it is not possible yet ?

**Comment by Shougo** [comment]
```vim
	autocmd FileType denite-filter call s:denite_filter_my_settings()
	function! s:denite_filter_my_settings() abort
	  imap <silent><buffer> <C-c> <Plug>(denite_filter_quit)
	endfunction
```

**Comment by JCavallo** [comment]
@Shougo thanks a lot for this, and for all your work.
