### ISSUE TITLE
[Feature Request]Add custom symbol and highlight syntax group

### ISSUE THREAD

**Issue by taigacute** [Shougo/denite.nvim#645]
# Problems summary
Hi @Shougo 
1. Add the highlight for menu name
2. Can add a option to add  a symbol which ahead the menu name  

p1: highlight the  `files thinkvim dein etc...` p2: Add a symbol like `◉ dein ` `◉ project` 
![123](https://user-images.githubusercontent.com/41671631/58887686-a775f080-8718-11e9-903f-719e60b43a55.png)

# Environment Information (Required!)
- denite version (SHA1): the latest

- OS:mac os 10.13.6

- Vim/neovim version: neovim-0.4.0-dev

**Comment by Shougo** [comment]
It is possible, but I don't add the feature.
Because I need to develop other plugins and features.

If you really needed the feature, you can implement it.
This is open source.

**Comment by taigacute** [comment]
@Shougo  thanks a lot 。 I will develop this feature
