### ISSUE TITLE
denite buffer is named `\[denite\]` on Windows

### ISSUE THREAD

**Issue by Bakudankun** [Shougo/denite.nvim#650]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

denite's buffer is named `\[denite\]` on Windows.

## Expected

It should be named `[denite]`.

## Environment Information (Required!)

 * denite version (SHA1): 6937f1d

 * OS: Windows 10 Pro

 * Vim/neovim version: Vim 8.1.1032

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" ~/_vimrc
set encoding=utf-8
scriptencoding utf-8

set runtimepath+=~/path/to/Shougo/denite.nvim
set runtimepath+=~/path/to/roxma/nvim-yarp
set runtimepath+=~/path/to/roxma/vim-hug-neovim-rpc

let g:python3_host_prog = "python.exe"
```

## How to reproduce problems from neovim startup (Required!)

 1. `gvim --clean -N -u _vimrc` 
 2. `:Denite buffer`
 3. `:ls!`

## Screenshot (if possible)

![\\[denite\\]](https://user-images.githubusercontent.com/4504807/59042494-84347800-88b5-11e9-9b90-317866a8f177.png)

**Comment by Bakudankun** [comment]
https://github.com/Shougo/denite.nvim/blob/bfc010bfeed56681929b67e70662f8bb11977da7/autoload/denite/util.vim#L38

`escape(s:expand('[denite]'), '[]$')` returns `\[denite\]` and thus `:silent keepalt botright split \[denite\]` is executed.
It's valid in UNIX, while in Windows backslashes are treated as file separator. (cf. Note of `:h isfname`)
You may want to use `fnameescape()` or something instead of `escape()`.


This may be another issue but I think the denite buffer should be set `buftype=nofile` or denite creates `[denite]` buffers for every directory where denite is called.

**Comment by Shougo** [comment]
> This may be another issue but I think the denite buffer should be set buftype=nofile or denite creates [denite] buffers for every directory where denite is called.

`buftype=nofile` is already set.  Please read the source code.
