### ISSUE TITLE
Disable deoplete on denite-filter

### ISSUE THREAD

**Issue by afk-mario** [Shougo/denite.nvim#657]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Currently when using denite-filter deoplete starts suggesting things and the UI gets distracting.

## Expected
Be able to disable deoplete when using denite filter

## Environment Information (Required!)

 * denite version (SHA1):
b684541362bba929e45c4a03550ca44f31533332

 * OS:
Arch Linux

 * Vim/neovim version:
neovim 0.3.7

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/1025751/59383069-cbdb5980-8d24-11e9-9a7f-bd402706aca1.png)

**Comment by Shougo** [comment]
I will update the documentation for it.
Please wait.

**Comment by Shougo** [comment]
```vim
	autocmd FileType denite-filter call s:denite_filter_my_settings()
	function! s:denite_filter_my_settings() abort
	  call deoplete#custom#buffer_option('auto_complete', v:false)
	endfunction
```
