### ISSUE TITLE
[Doc update request] Old behavior set up

### ISSUE THREAD

**Issue by naquad** [Shougo/denite.nvim#661]
Hi.

I haven't updated for quite some time and after updating to the current master version I've found out Denite now wants me to define some own mappings + there's a separate filter... Ugh... This change has literally broken the whole set up I have and rendered Denite completely useless in my configuration.

Could you please provide a complete settings code in docs to:
1. Make the filter mode default (`call denite#do_map('open_filter_buffer')` didn't work).
2. Let arrows navigate in the filter mode.
3. Make <CR> to invoke an action on the selected item while being in the filter buffer.

Thanks.

P. S. I don't know what's the argument behind this change, but it makes things so much more complicated that I'm sure only like 1% of users will benefit from this change. Not to speak of bad UX provided by default doc solution.

**Comment by afk-mario** [comment]
1.
```viml

   " For all buffers
    call denite#custom#option('_', {
                \ 'start_filter': 1,
                \ })

    " Only buffers named interactive
    call denite#custom#option('interactive', {
                \ 'start_filter': 1,
                \ })

   :Denite file/rec -buffer-name=interactive

```

@Shougo  Don't really know if there is a way to set buffer name for a source instead of defining the buffer name on the function calling


2. From the docs 

```
Q: I want to move the cursor in a Denite filter window, while in insert mode.

A: Really? It is not the Vim way to move the cursor while in insert mode. You
must force this behaviour. >

	autocmd FileType denite-filter call s:denite_filter_my_settings()
	function! s:denite_filter_my_settings() abort
	  inoremap <silent><buffer> <C-j>
	  \ <Esc><C-w>p:call cursor(line('.')+1,0)<CR><C-w>pA
	  inoremap <silent><buffer> <C-k>
	  \ <Esc><C-w>p:call cursor(line('.')-1,0)<CR><C-w>pA
	endfunction
```

3. I actually wan't to do the same, and not really sure how to.

**Comment by Shougo** [comment]
>@Shougo Don't really know if there is a way to set buffer name for a source instead of defining the buffer name on the function calling

Nothing.  You need to specify buffer name.
It is denite's policy.

**Comment by Shougo** [comment]
> Make to invoke an action on the selected item while being in the filter buffer.

Why don't read the documentation?

```
Q: I want to call default action in denite filter window.

A: >

	autocmd FileType denite-filter call s:denite_filter_my_settings()
	function! s:denite_filter_my_settings() abort
	  inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
	endfunction
```

**Comment by Shougo** [comment]
> P. S. I don't know what's the argument behind this change, but it makes things so much more complicated that I'm sure only like 1% of users will benefit from this change. Not to speak of bad UX provided by default doc solution.

Sorry.  I have decided to change the behavior.
It may be complicated if you don't want to configure.

But if you don't want to configure denite, you should not use it.

**Comment by afk-mario** [comment]
> > Make to invoke an action on the selected item while being in the filter buffer.
> 
> Why don't read the documentation?
> 
> ```
> Q: I want to call default action in denite filter window.
> 
> A: >
> 
> 	autocmd FileType denite-filter call s:denite_filter_my_settings()
> 	function! s:denite_filter_my_settings() abort
> 	  inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
> 	endfunction
> ```

Totally missed it, thanks !

**Comment by sheoak** [comment]
See issue [654](https://github.com/Shougo/denite.nvim/issues/654#issuecomment-502355991) for a basic configuration with home row remapping.

**Comment by naquad** [comment]
Thank you for the info. Sorry about sort of a "panic" post, I'm sharing what I did to make configuration compatible with the old one:

```

function! s:DeniteSetup() abort
  nnoremap <silent><buffer><expr> <CR>
        \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
        \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
        \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> <Esc>
        \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
        \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
        \ denite#do_map('toggle_select').'j'
endfunction

" Somewhy this mess is working faster than <C-w>p and related commands.
" most probably related to the way win_gotoid handling autocommands 
function! s:DeniteChoice(dir) abort
  let wid = win_findbuf(g:denite#_filter_parent)
  if empty(wid)
    return
  endif

  call win_gotoid(wid[0])

  if a:dir == 0
    norm k
  else
    norm j
  endif

  call win_gotoid(g:denite#_filter_winid)
endfunction

function! s:DeniteFilterSetup() abort
  let b:coc_enabled = 0

  imap <silent><buffer><expr> <CR> denite#do_map('do_action')
  imap <silent><buffer><expr> <Esc> denite#do_map('quit')

  imap <silent><buffer> <Up> <C-o>:call <SID>DeniteChoice(0)<CR>
  imap <silent><buffer> <Down> <C-o>:call <SID>DeniteChoice(1)<CR>
endfunction


call denite#custom#option('_', {
      \ 'start_filter': 1,
      \ })

au FileType denite call s:DeniteSetup()
au FileType denite-filter call s:DeniteFilterSetup()
```

Can't say it's perfect, but satisfies my needs.

@Shougo I'm more than fine with configuring things, I've made a huge amount of menus and related functionality for them (snippet expansion, file insertion commands, and other stuff). Denite is one of the very best things happened to NeoVIM and its importance in my setup can't be overestimated :) And thank you for that very much. 

Though when you have everything configured relying on some behavior a change in this behavior is absolutely disastrous. This literally causes the whole workflow to be broken.

When I've run into this problem I've been in the process of system setup from scratch (caused SSD failure), I install plugins and BOOM! my one and only super productive NeoVIM setup is down. Disaster! On top of that, I've got several emergency changes requested at work and I'm super slow without my menus, file jumping and etc.

My writing wasn't really polite and I apologize for that. What I want to say here though is the fact that such fundamental changes in the functionality shouldn't be simply written somewhere in FAQ section of the doc, but highlighted with big red letters and have a separate section. In the other case, one has to re-read the whole doc or look through changes in Git and the figure out what to do. Considering the number of plugins average setup uses (not even taking my setup with insane 87 plugins into account) this is not an easy task.

Your work is very important. As I've mentioned not once and won't stop repeating Denite is a vital plugin for advanced NeoVIM setups and lots of advanced setups rely on it. Breaking it = disaster. Highlighting such major changes in doc in a separate section with some notes on how to get back old behavior at least before one will have time to update his configs would save lots of time and nerves.

Thank you.

**Comment by sheoak** [comment]
Hi @naquad ,

> When I've run into this problem I've been in the process of system setup from scratch (caused SSD failure), I install plugins and BOOM! my one and only super productive NeoVIM setup is down. Disaster! On top of that, I've got several emergency changes requested at work and I'm super slow without my menus, file jumping and etc.

I suggest that you use fix versions of your plugins if you want a more stable setup. See you plugin manager documentation (with vim-plug you can use "tag" option). Then you can update when you have time to fix issues – if they occur. This way when you checkout your configuration with fixed tags you should always get the same results. You can also play around on your machine and revert to a previous version easily by going back to the previous version of your configuration file.

Cheers!

**Comment by Shougo** [comment]
Yes.  I know the breakage.
I have updated the documentation.

But people don't read it before updating.

**Comment by oblitum** [comment]
Frustrating update. I have no idea how to bring back the old filter UI in master. Now there's multiple buffers, one for the filtering, another for the result set. Previously, filtering was the default application for denite and it was done like through a command line. The new split buffer UI is not friendly when you have a setup for your statusline because now there will be a statusline even for the filter buffer.

**Comment by afk-mario** [comment]
@oblitum  from the docs

```
Q: I want to use external statusline plugin like lightline/vim-airline etc.

A: You should disable the internal statusline. >

	call denite#custom#option('_', 'statusline', v:false)
```

**Comment by oblitum** [comment]
@afk-mario thx. So many docs to check :-/

**Comment by oblitum** [comment]
sadly I didn't obtain the UI I was expecting...

**Comment by Shougo** [comment]
You can disable the status line by using floating window.
-split=floating

**Comment by kuator** [comment]
@Shougo, I think the approach you are taking it's too aggressive, like maybe have some announcements, cause I personally really love your plugins and I want them to work, but I don't really feel like changing my settings every time there is an update. Like, if it is going to be this way, a lot of people will switch to other alternatives, but I would really like for your plugins to more popular.

**Comment by Shougo** [comment]
Thank you for the comment.
Yes.  The update is very aggressive.
But it is needed.

I don't want to maintain new/old UIs.
And people does not read the documentation/announcement.

**Comment by Shougo** [comment]
I think the compatibility is important.
I think you know all sources/filters/kinds are compatible in current version.

The compatibility problems are about mappings and some options.

**Comment by Shougo** [comment]
> Like, if it is going to be this way, a lot of people will switch to other alternatives, but I want for your plugins to more popular.

I avoid the compatibility problem if possible.

**Comment by oblitum** [comment]
> The compatibility problems are about mappings and some options.

There's UI compatibility problems too. New UI isn't compatible with common Vim settings (`set laststatus=2`), it seems I have two options for UI now with my setup, ugly UI with many additional statusline, use `-split=floating` to get a clean UI that remove unwanted statusline. I like the floating UI, but it has drawbacks, it requires master NeoVim and it's not automatically re-sizable/centralized.

**Comment by oblitum** [comment]
@Shougo could you please set default `-winwidth` to `&columns / 2`? The current `-wincol` is `&columns / 4`, which adapts to screen size, but `-winwidth` doesn't, it's fixed to `90`.

**Comment by oblitum** [comment]
I'm in the process of fully reconfiguring denite, and my impression is that it's better now than before, specially because I can edit filter buffer as a normal buffer. Only better when you can use floating windows. I just hope I'll not have to reconfigure it from ground up again :-/

**Comment by Shougo** [comment]
> could you please set default -winwidth to &columns / 2? 

OK.  I have changed it.

**Comment by oblitum** [comment]
> Note: Denite.nvim does not define any of default mappings. You need to define them.

I've noticed one mapping that seems built in? In the filter buffer in normal mode, if I press <kbd>q</kbd>, the filter is closed.

**Comment by Shougo** [comment]
> I've noticed one mapping that seems built in? In the filter buffer in normal mode, if I press q, the filter is closed.

Yes.  In filter buffer, some mappings are built in.
In denite buffer, no default mappings.

**Comment by Shougo** [comment]
I have added `:help denite-filter-default-key-mappings`.
