### ISSUE TITLE
Question: Denite buffer -default-action=switch

### ISSUE THREAD

**Issue by thecontinium** [Shougo/denite.nvim#665]
Should  there be a problem with using this command after opening a single file from the command line 

> Denite buffer -default-action=switch

and then opening the current buffer that is at the top of the list.

I get error messages and can give details if this is not really simple to replicate.

cheers

**Comment by Shougo** [comment]
Fixed.

**Comment by thecontinium** [comment]
Yep - fixed for me. Cheers
