### ISSUE TITLE
[feature request] list denite-options in wildmenu only when hyphen is typed

### ISSUE THREAD

**Issue by kiryph** [Shougo/denite.nvim#67]
By default `:Denite <TAB>` shows in the `wildmenu` all possible options and the sources at the end of the wildmenu

![denite-cli-completion](https://cloud.githubusercontent.com/assets/371756/20436427/8999029e-adb0-11e6-9836-243ed54c51d6.png)

I would prefer following behavior:

`:Denite <TAB>` shows only all possible sources in the `wildmenu`.

If I type `:Denite -<TAB>`, the `wildmenu` should show the options.

What do you think?

**Comment by Shougo** [comment]
Implemented.

**Comment by kiryph** [comment]
Great! Thanks for the quick implementation.
