### ISSUE TITLE
Feature request: multiple denite instance (one denite window per tab)

### ISSUE THREAD

**Issue by kghost** [Shougo/denite.nvim#671]
# Problems summary
With multiple tabs, when I am opening a denite window, it jump to the tab with denite opened previously. It is quite annoying, can I have one denite window per tab ?

## Expected
When I am opening a denite window, it create or reuse the denite window in the current tab, It shouldn't jump to any other tab.

**Comment by Shougo** [comment]
> With multiple tabs, when I am opening a denite window, it jump to the tab with denite opened previously. It is quite annoying, can I have one denite window per tab ?

Please change `-buffer-name` option.
If `-buffer-name` is same, the previous buffer is used.

>  can I have one denite window per tab ?

You can use like this.

```vim
:Denite file -buffer-name=`tabpagenr()`
```

**Comment by kghost** [comment]
This won't work smoothly, because `tabpagenr()` is not unique. When you open/close tabs, there is a large chance that buffer name will conflict.

**Comment by Shougo** [comment]
Yes.  But it is Vim's problem not denite.nvim.
