### ISSUE TITLE
Documentation: How to grep source interactively

### ISSUE THREAD

**Issue by mikepc** [Shougo/denite.nvim#673]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
* Problem is, I'm new to Denite and pretty new to nvim/vim 
* Wow, this project is amazing and does so much it's mind-blowing, but it's hitting me like a Mack truck. There could be an entire youtube series on denite and there would still be holes.
* Ok, to the point.  I'm certain that denite can do this, but I'm trying to piece the documentation together and I'm struggling.  I would like to open a grep search in interactive mode, and type in my expression and have it grep the current directory for the specified pattern.

From my digging I've come up with this.
```
  nnoremap <silent> <leader>a :Denite grep:::!<CR>
" I also tried this: map <leader>a :DeniteProjectDir -buffer-name=grep -default-action=quickfix grep:::!<CR>
" I flailed with this with an error Source "" is not found, I tried a few variations of this and faceplanted some more.


```

## Expected
I would expect to type a pattern, and be presented a list of files (within the project directory) containing a specified regular expression.

## Environment Information (Required!)

 * denite version (SHA1):
Installed from master yesterday.

 * OS:
MacOS 10.14
 * Vim/neovim version:
NVIM v0.3.7
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20190619-87615-1erj6t7/neovim-0.3.7/build/config -I/tmp/neovim-20190619-87615-1erj6t7/neovim-0.3.7/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-20190619-87615-1erj6t7/neovim-0.3.7/build/src/nvim/auto -I/tmp/neovim-20190619-87615-1erj6t7/neovim-0.3.7/build/include
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.7_2/share/nvim"

Run :checkhealth for more info
`

health#defx#check
========================================================================
## defx.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen
  - INFO: default-terminal: screen-256color
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=0).  This might be due to some previous error.
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.2
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v11.8.0
  - INFO: Neovim node.js host: /Users/michael/.nvm/versions/node/v11.8.0/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.5.0

`

* `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```
" These are the relevent sections, but I know this is a user problem, I just don't know what to do.

" Denite --------------------------------------------------------------------{{{

  let s:menus = {}
  call denite#custom#option('_', {
        \ 'prompt': '❯',
        \ 'winheight': 10,
        \ 'updatetime': 1,
        \ 'auto_resize': 0,
        \ 'highlight_matched_char': 'Underlined',
        \ 'highlight_mode_normal': 'CursorLine',
        \ 'reversed': 1,
        \ 'auto-accel': 1,
        \})
  call denite#custom#option('TSDocumentSymbol', {
        \ 'prompt': ' @' ,
        \})
  call denite#custom#option('TSWorkspaceSymbol', {
        \ 'prompt': ' #' ,
        \})

 call denite#custom#source('file/rec', 'vars', {
        \ 'command': ['rg', '--files', '--glob', '!.git'],
        \ 'matchers': ['matcher/fruzzy'],
        \ 'sorters': ['sorter/sublime'],
        \})
        " \'matchers': ['matcher/cpsm']
  let g:fruzzy#usenative = 1
  "     \ 'command': ['ag', '--follow','--nogroup','--hidden', '--column', '-g', '', '--ignore', '.git', '--ignore', '*.png', '--ignore', 'node_modules'

 call denite#custom#source('grep', 'vars', {
        \ 'command': ['ag', '--follow','--nogroup','--hidden', '--column', '-g', ''],
        \'default_opts': ['-i', '--vimgrep'],
        \'recursive_opts': [],
        \'pattern_opt': [],
        \'separator': ['--'],
        \'final_opts': [],
        \'matchers': ['matcher/ignore_globs', 'matcher/regexp', 'matcher/pyfuzzy']
        \})

  nnoremap <silent> <c-p> :Denite file/rec<CR>
  nnoremap <silent> <leader>h :Denite help<CR>
  nnoremap <silent> <leader>v :Denite vison<CR>
  nnoremap <silent> <leader>c :Denite -auto-action=preview colorscheme<CR>
  nnoremap <silent> <leader>b :Denite buffer<CR>
  nnoremap <silent> <leader>l :Denite line<CR>
  nnoremap <silent> <leader>a :Denite grep:::!<CR>
  nnoremap <silent> <leader>u :DeinUpdate<CR>
  call denite#custom#map('insert','<C-n>','<denite:move_to_next_line>','noremap')
  call denite#custom#map('insert','<C-p>','<denite:move_to_previous_line>','noremap')
  call denite#custom#filter('matcher_ignore_globs', 'ignore_globs',
    \ [ '.git/', '.ropeproject/', '__pycache__/','node_modules/','*.png',
    \   'venv/', 'images/', '*.min.*', 'img/', 'fonts/'])
  call denite#custom#var('menu', 'menus', s:menus)
call denite#custom#kind('file', 'default_action', 'open')
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction
"}}}

```

## How to reproduce problems from neovim startup (Required!)

1. Google "how to grep source with denite".
2. Flounder.

## Generate a logfile if appropriate

N/A

## Screenshot (if possible)
<img width="965" alt="Screen Shot 2019-06-23 at 3 15 04 PM" src="https://user-images.githubusercontent.com/878739/59982648-880d0d80-95ca-11e9-9727-49bb7188c125.png">

## Upload the log file
N/A

**Comment by mikepc** [comment]
With more digging, it appears that :DeniteProjectDir is just not being set somehow, so I'm digging into that.

**Comment by Shougo** [comment]
```vim
  nnoremap <silent> <leader>a :Denite -start-filter grep:::!<CR>
```

I have update the documentation.

```
" I also tried this: map <leader>a :DeniteProjectDir -buffer-name=grep -default-action=quickfix grep:::!<CR>
" I flailed with this with an error Source "" is not found, I tried a few variations of this and faceplanted some more.
```

I have tested it and it works for me.
You need to upload the minimal vimrc to reproduce the problem.
