### ISSUE TITLE
Slowdown linked to filtering

### ISSUE THREAD

**Issue by JCavallo** [Shougo/denite.nvim#676]
# Problems summary

In a given neovim session, after some usage of denite (meaning opening / closing denite buffers), the denite-filter starts to hang.

Basically, calling "Denite file/rec" for instance would work as expected, but after some time working it will take a few seconds to respond.

## Expected

Behavior of denite should be consistent across a neovim session

## Environment Information (Required!)

 * denite version (SHA1): b6a0c7d

 * OS: Ubuntu 18.04

 * Vim/neovim version: NVIM v0.4.0-1016-g6f27f5ef9

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: pyenv: Path: /home/giovanni/.pyenv/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/giovanni/.pyenv
  - INFO: Using: g:python_host_prog = "/home/giovanni/.pyenv/versions/neovim2/bin/python"
  - WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.
    - ADVICE:
      - If you are using Zsh, see: http://vi.stackexchange.com/a/7654
  - INFO: Executable: /home/giovanni/.pyenv/versions/neovim2/bin/python
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/giovanni/.pyenv/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/giovanni/.pyenv
  - INFO: Using: g:python3_host_prog = "/home/giovanni/.pyenv/versions/neovim3/bin/python"
  - WARNING: $VIRTUAL_ENV exists but appears to be inactive. This could lead to unexpected results.
    - ADVICE:
      - If you are using Zsh, see: http://vi.stackexchange.com/a/7654
  - INFO: Executable: /home/giovanni/.pyenv/versions/neovim3/bin/python
  - INFO: Python version: 3.7.1
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v8.16.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

## Provide a minimal init.vim with less than 50 lines (Required!)

Calling "Denite file/rec -no-filter" does not have the problem. I've also tried floating / non-floating behaviors for the denite window, but that does not change anything.

Once the slowdown appears, it applies to all denite buffers (meaning I used file/rec as an example, but all sources have the problem as long as -filter is set).

I also notice that the python process for neovim goes 100% CPU at this moment (which probably explains the slowdown)

I do not know if there could be a link (and if it is a normal behavior), but using backspace in denite-filter on an empty line will switch back to the previous filter I used.

If that helps, I use deoplete but deactivated if for the denite-filter buffer.

I think the problem is somewhere in how denite-filter initializes.

I am willing to investigate further (minimal vimrc & co), but could you please confirm it is not a known problem first ?

**Comment by Shougo** [comment]
Please test https://github.com/Shougo/denite.nvim/pull/677 version.
It fixes timers problem.

**Comment by JCavallo** [comment]
@Shougo Tested, unfortunately it does not seem to resolve the problem for me.

After some time, everytime I start denite in filter mode, I have to wait a few seconds before any input is properly registered.

Is there some logging that would help ? If you do not have enough information, I'll try to provide a minimal vimrc but it may take some time.

FYI I did not have any problems before the UI rework you did a few weeks ago.

**Comment by Shougo** [comment]
Really???

Hm.  But fortunately, denite.nvim is open source.
You can investigate the problem.

**Comment by Shougo** [comment]
I think `max-dynamic-update-candidates` fixes your problem.

```
				*denite-option-max-dynamic-update-candidates*
-max-dynamic-update-candidates={length}
		If the candidates are more than it, denite will ignore the
		dynamic filtering.

		Default: 20000
```

**Comment by Shougo** [comment]
> Is there some logging that would help ?

logging hint:

You can add the log in the function.

https://github.com/Shougo/denite.nvim/blob/master/autoload/denite.vim#L51

I think update candidates action is called frequently.

**Comment by Shougo** [comment]
>  If you do not have enough information, I'll try to provide a minimal vimrc but it may take some time.

You should create the minimal vimrc, if not I will close the issue.
I don't work for non reproducible problems.

**Comment by JCavallo** [comment]
I'll try to investigate myself a little

**Comment by JCavallo** [comment]
> I think max-dynamic-update-candidates fixes your problem.

Does not change a thing, once the slowdown appears, it applies to all sources (even "small" sources like buffer)

**Comment by Shougo** [comment]
I have tested it, but I don't reproduce it.

**Comment by JCavallo** [comment]
Well after a little more investigation, it only happens on one of my two machines, so I think it may be because of low resources (it only happens on the machine with the least RAM / CPU).

I'll close this and come back if I find a consistent way to reproduce.

**Comment by Shougo** [comment]
OK.

**Comment by Shougo** [comment]
The problem is not denite's problem.
