### ISSUE TITLE
Denite no longer interactive

### ISSUE THREAD

**Issue by japorized** [Shougo/denite.nvim#678]
## Problems summary
Denite is no longer interactive

## Expected
Denite as an interactive popup

## Environment Information

 * denite version (SHA1): 90f8367

 * OS: Linux 5.1.12

 * Vim/neovim version: 0.3.7

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5602'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
...
## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/bin/python2"
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python"
  - INFO: Executable: /usr/bin/python
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.
...
```

## Minimal vimrc

```vim
set rtp+=~/.vim/bundle/optional/denite.nvim/
```

## How to reproduce problem from startup

1. Run `nvim -u minimalvimrc`
2. Hit `:Denite colorscheme`
3. Type anything

## Logfile

[nvim-tmp-log_py3_rplugin.txt](https://github.com/Shougo/denite.nvim/files/3356506/nvim-tmp-log_py3_rplugin.txt)

Log file seems to have certain info about denite which may be helpful in debugging.

**Comment by Shougo** [comment]
If you want to interactive, you need to enable start-filter option.
Please read the documentation.

```
						*denite-option-start-filter*
-start-filter
		 Start filtering on default.
		Default: false
```

`:Denite -start-filter colorscheme` fixes your problem.

**Comment by japorized** [comment]
Sorry, I should have been clearer. Not only is it no longer interactive by default (which I guess it was updated to be so), but I can no longer use Denite... like the way it used to.

I just saw the [Examples](https://github.com/Shougo/denite.nvim#examples) shown on the README. Those helped me, but getting updated to a state where there were no defaults surprised me quite a bit. But thank you.

**Comment by Shougo** [comment]
If so, I cannot help you.
I have removed all default key mappings.
I think it should be.
Denite.nvim is more customizable than before.

**Comment by Shougo** [comment]
If you don't want to custom denite.nvim, you should use other plugin.

**Comment by japorized** [comment]
Oh no, I did not mean that. It was just surprising until I finally saw that the README itself was updated to indicate this. I've gone through the updated documentation and yes it has become more customizable, which I am thankful for.

**Comment by Shougo** [comment]
OK.
