### ISSUE TITLE
Question: Is there a way to filter by file names and contents

### ISSUE THREAD

**Issue by thecontinium** [Shougo/denite.nvim#679]
When you are typing to filter the "files" is it also possible to filter by the contents as well as the name ?

e.g. if you had a file named "foo.txt" that had "bar" in the files text and a file named "foobar.txt" that did not contain bar in it's text. When you type bar "foo.txt" and "foobar.txt" will be included in the file list. 

Thanks as always.

**Comment by delphinus** [comment]
How about `:Denite file/rec grep:::!` ?

**Comment by thecontinium** [comment]
This gets the right files which is great but is there any way to make it do it dynamically as you type ?

Thanks

--
The Continium


On 4 July 2019 at 16:22:56, JINNOUCHI Yasushi (notifications@github.com<mailto:notifications@github.com>) wrote:

How about :Denite file/rec grep:::! ?

**Comment by delphinus** [comment]
`:Denite file/rec grep:::!` makes it! Reproducible steps.

1. preparing...

   ```sh
   git clone https://github.com/Shougo/denite.nvim
   ```

   ```vim
   set runtimepath+=/tmp/denite.nvim
   autocmd FileType denite call <SID>denite_my_settings()
   function! s:denite_my_settings() abort
     nnoremap <silent><buffer><expr> i       denite#do_map('open_filter_buffer')
     nnoremap <silent><buffer><expr> q       denite#do_map('quit')
   endfunction
   filetype plugin indent on
   syntax enable
   ```

   ```vim
   :UpdateRemotePlugins
   ```

3. and do it.

   ![IwM9HysZRa](https://user-images.githubusercontent.com/1239245/60749449-36ef1780-9fd5-11e9-85c9-cfdc92d6025f.gif)

**Comment by Shougo** [comment]
> How about :Denite file/rec grep:::! ?

This is the answer.

**Comment by thecontinium** [comment]
cool - I had included the "?" :)

thanks

**Comment by thecontinium** [comment]
Is there a way to sort across all the results picked up by fie/rec and grep ?

I am looking to sort by last modified date with the most recently changed files showing towards the top of the list. So that in the example if foo.txt has been modified/edited after foobar.txt it would appear at the top of the list when it has been picked up by the grep searching for bar.

cheers

**Comment by Shougo** [comment]
It is possible.  Please read the documentation.

```
						*denite-option-sorters*
-sorters
		Specify a list of sorter names.  They are source independent.
		Default: ""
```

**Comment by Shougo** [comment]
Note:
Last modified sorter is not implemented in denite.nvim.
If you really needed, you can create it.

**Comment by thecontinium** [comment]
Thanks for the quick reply.

When I have a moment I’ll reach out for a steer and give it a go.

Cheers.

--
The Continium

On 6 July 2019 at 15:58:37, Shougo (notifications@github.com<mailto:notifications@github.com>) wrote:

Note:
Last modified sorter is not implemented in denite.nvim.
If you really needed, you can create it.

**Comment by thecontinium** [comment]
Hi - Can you give me a good sorter to use as a template to write a last modified sorter from please. 

Cheers

**Comment by Shougo** [comment]
https://github.com/Shougo/denite.nvim/blob/master/rplugin/python3/denite/filter/sorter/word.py

You should read the source code.

**Comment by mn-dimension** [comment]
I have started to write this. Can you advise on what you use to debug python plugins; I want to be able to set a breakpoint like you can for VimL - is this possible ?

cheers

**Comment by Shougo** [comment]
> I want to be able to set a breakpoint like you can for VimL - is this possible ?

You cannot use the debugger.
You need to `print()` debug.
`self.debug(string)` is useful for it.

**Comment by thecontinium** [comment]
Thanks for the confirmation. I thought as much.

Cheers

--
The Continium

On 22 July 2019 at 20:32:29, Shougo (notifications@github.com<mailto:notifications@github.com>) wrote:

I want to be able to set a breakpoint like you can for VimL - is this possible ?

You cannot use the debugger.
You need to print() debug.
self.debug(string) is useful for it.

**Comment by thecontinium** [comment]
Feel free to add if you want it as part of Denite:

https://github.com/thecontinium/vim-denite-sorter-lastmod

**Comment by Shougo** [comment]
Thanks!  But I don't want to add default filters.  Sorry.

**Comment by nadya-p** [comment]
@thecontinium Thank you for the sorter, it is very helpful!
