### ISSUE TITLE
Question: ignore man entries is neomru source

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#680]
If I run `:Man xinit` and then `Denite neomru` then myy neomru source shows:
```
man://xinit(1)
```
I don't want to show man entries in any source so I tried adding:
```viml
call denite#custom#source('_', 'matchers', ['matcher/fruzzy',
        \ 'matcher/ignore_globs'])
call denite#custom#filter('matcher/ignore_globs', 'ignore_globs',
        \ ['.git/', '__pycache__/', 'venv/',  'tmp/', 'doc/', 'man:*'])
```
to my init.vim but the man entry is still there. So my question is: how can I prevent denite from showing man entries? Thanks!

**Comment by Shougo** [comment]
It is not denite.nvim's issue.

```
g:neomru#do_validate				*g:neomru#do_validate*
		Specify whether automatically remove invalid file paths from
		mru history.
```

**Comment by petobens** [comment]
Consider the following minimal init.vim:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/neomru.vim
filetype plugin indent on

call denite#custom#option('default', {
            \ 'start_filter': 1,
            \ })

call denite#custom#source('_', 'matchers', ['matcher/fuzzy', 'matcher/ignore_globs'])
call denite#custom#filter('matcher/ignore_globs', 'ignore_globs',
        \ ['.git/', '__pycache__/', 'venv/',  'tmp/', 'doc/', 'man://*'])

let g:neomru#do_validate = 1
```
Now open nvim and do:
1. Run `:Man xinit`
2. Run `:Denite file_mru` and filter by `xinit` 

After 2. I get, as it seen in the image, that `man://xinit(1)` is in denite candidates. I expect it not to be there since I'm filtering with `ignore_globs`.

![image](https://user-images.githubusercontent.com/2583971/60751705-f7064100-9f90-11e9-86f9-d475985e8f5e.png)

**Comment by Shougo** [comment]
I have read the implementation.
To ignore `man:xinit`, you need to set `g:neomru#file_mru_ignore_pattern` properly.

**Comment by Shougo** [comment]
> I expect it not to be there since I'm filtering with ignore_globs.

To filter it by `ignore_globs`, you need to set matchers.

```vim
	call denite#custom#source(
	\ 'file_mru', 'matchers', ['matcher/fuzzy', 'matcher/ignore_globs'])
```

**Comment by Shougo** [comment]
I have fixed `matcher/ignore_globs` bug.

**Comment by petobens** [comment]
Thank you!
