### ISSUE TITLE
Denite filter window grows in size when filtering

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#681]
Consider the following minimal vimrc:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'start_filter': 1,
            \ })
```
Now, as in the gif, open nvim in a small window and then run:
1. `Denite file/old`
2. Start typing some filtering text -> the denite filter buffer starts growing in size covering the other opened buffer

I expect the denite filter buffer to always stay the same size (1 line)

![denite-window](https://user-images.githubusercontent.com/2583971/60747663-3450db80-9f5d-11e9-8e83-0d329fb6d349.gif)

**Comment by Shougo** [comment]
I have fixed the behavior.

But you should not use `auto_resize` in small window.
This is Vim's behavior.

**Comment by petobens** [comment]
Mmm I think you actually broke the behaviour. Now with the following minimal init.vim:

```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'auto_resume': 1,
            \ 'winheight': 15,
            \ 'winminheight': -1,
            \ 'reversed': 1,
            \ 'prompt': '❯',
            \ 'start_filter': 1,
            \ })

augroup ps_denite_setup
    au!
    au FileType denite-filter call s:denite_filter_mappings()
augroup END
function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <ESC> denite#do_map('quit')
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
endfunction
```
If you press enter on a candidate from within the denite filter buffer then all other windows are resized to 1:
![Peek 2019-07-06 01-42](https://user-images.githubusercontent.com/2583971/60751648-60855000-9f8f-11e9-8f6c-94f42e797006.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by petobens** [comment]
Thank you
