### ISSUE TITLE
Backspace breaks prompt

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#682]
Consider the following minimal init.vim
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'auto_resume': 1,
            \ 'winheight': 15,
            \ 'winminheight': -1,
            \ 'reversed': 1,
            \ 'prompt': '❯',
            \ 'start_filter': 1,
            \ })

augroup ps_denite_setup
    au!
    au FileType denite-filter call s:denite_filter_mappings()
augroup END
function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <ESC> denite#do_map('quit')
endfunction
```
Now, as in the GIF, open nvim and do:
1. Run `Denite file/old`
2. Type some filtering characters (for example `func`)
3. Press `ESC` to exit Denite
4. Run `Denite file/old` again
5. Type some new filtering characters (for example `f`)
6. Press backspace repeatedly

After step 6, when pressing backspace, the cursor goes beyond the prompt (i.e the whole prompt gets broken) and the previous filtering search (in my example `func`) is shown:

![breaks-prompt](https://user-images.githubusercontent.com/2583971/60748046-66177180-9f60-11e9-95a6-0051bedf29e9.gif)

**Comment by Shougo** [comment]
It is the feature.
filter buffer saves your prompt history.

You can change `<BS>` behavior.

**Comment by petobens** [comment]
How am I supposed to change it? Can you show me how/ add it to the FAQ? I think the default behaviour should be not to the save the history and hence prevent "erasing" the prompt when pressing `<BS>`.

**Comment by Shougo** [comment]
I have added `<BS>` mapping in default.

**Comment by petobens** [comment]
Awesome! Thank you
