### ISSUE TITLE
Outline: ignore types

### ISSUE THREAD

**Issue by freder** [Shougo/denite.nvim#684]
# Problems summary
I'm trying to exclude certain types from `:Denite outline`, but setting `ignore_types` has no effect.

it could be that I'm using it wrong, but it also looks like `ignore_types` isn't actually used at all. see https://github.com/Shougo/denite.nvim/search?q=ignore_types&type=Code

## Expected
should exclude certain tags

## Environment Information (Required!)

 * denite version (SHA1):
`f2fea7e01ad5799a3ddf920f2f3f3b6901485afb`

 * OS:
linux

 * Vim/neovim version:
neovim `0.3.4`

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
if &compatible
        set nocompatible
endif

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
  
if dein#load_state('~/.cache/dein')
        call dein#begin('~/.cache/dein')

        call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
        call dein#add('Shougo/denite.nvim')

        call dein#end()
        call dein#save_state()
endif

call denite#custom#var('outline', 'ignore_types', ['v', 'p', 'c'])

nnoremap <leader>r :<C-u>Denite outline<CR>

autocmd FileType denite call s:denite_settings()
function! s:denite_settings() abort
        highlight! link CursorLine Visual
        nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
        nnoremap <silent><buffer><expr> i    denite#do_map('open_filter_buffer')
        nnoremap <silent><buffer><expr> <Esc>   denite#do_map('quit')
endfunction

autocmd FileType denite-filter call s:denite_filter_settings()
function! s:denite_filter_settings() abort
        nnoremap <silent><buffer><expr> <Esc> denite#do_map('quit')
endfunction
```

## How to reproduce problems from neovim startup (Required!)
open buffer with test content

```js
const x = 99;

function f1 () {}

const f2 = () => {};   
  
const o = {
        prop: 123,  
        math: () => {},
};          

class C {
        meth2() {}
}
```

## Screenshot (if possible)

![denite-outline-2](https://user-images.githubusercontent.com/724844/60758168-4ccffd00-a014-11e9-8d42-62d111df753d.png)

**Comment by Shougo** [comment]
Yes, `ignore_types` is not implemented.
