### ISSUE TITLE
Is there an equivalent of unite#do_action('replace')?

### ISSUE THREAD

**Issue by carlbunny** [Shougo/denite.nvim#685]
Hello Shougo,

I am recently trying to move from unite to denite. One feature I like unite the best is find and replace, by 
```
  if unite.profile_name ==# 'search'
    nnoremap <silent><buffer><expr> r     unite#do_action('replace')
  endif
```
Which will invoke qfreplace vim plugin so I can modify each selected line separately.

In denite, there is a replace action but that seems to do something a lot different than qfreplace. Am I missed something or that part has not been developed yet?

Thank you!

**Comment by Shougo** [comment]
`replace` is not supported.  So you need to use quickfix action to replace.

```vim
	autocmd FileType denite
	\ call s:denite_my_settings()
	function! s:denite_my_settings() abort
	  nnoremap <silent><buffer> <C-b>
	  \ :<C-u>call <SID>denite_quickfix()<CR>
	endfunction
	function! s:denite_quickfix()
	  call denite#call_map('toggle_select_all')
	  call denite#call_map('do_action', 'quickfix')
	endfunction
```

**Comment by carlbunny** [comment]
Thank you Shougo!

Quickfix is not great as the old way. Wondering do you have plan in the future for something like qfreplace?

**Comment by Shougo** [comment]
Nothing.
