### ISSUE TITLE
【質問】特定のフォルダ直下全てをexcludeする方法

### ISSUE THREAD

**Issue by take** [Shougo/denite.nvim#691]
お世話になっております。

[特定のfiletypeを除外するオプション](https://github.com/Shougo/denite.nvim/blob/0538a6449e9d1237d6df738ec612b7c3fe01b6f1/doc/denite.txt#L936-L938)があるのは確認出来たんですが、特定のフォルダ直下を除外するオプションはあったりしますでしょうか :eyes: ❓

**Comment by Shougo** [comment]
残念ながらありません。
自分でフィルタ作るか、file/recのコマンドの引数によりフィルタするかで工夫してください

**Comment by take** [comment]
返答ありがとうございます！ :pray:
