### ISSUE TITLE
Command history source not working

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#693]
Consider the following minimal init.vim:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

au FileType denite call s:denite_mappings()
function! s:denite_mappings() abort
    nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
endfunction
```
Now, as in the GIF, do
1. Open nvim and run `echo 'foo'`
2. Run `:Denite command_history` and select the `echo 'foo'` candidate
3. Press `<CR>` on the candidate

After 3. nothing happens: I expect the command to be executed.

![denite-command-history](https://user-images.githubusercontent.com/2583971/61095081-6adc9980-a428-11e9-84e0-962adcc2d0a2.gif)

**Comment by petobens** [comment]
Mmm this is still not working from the filter window. Consider the following minimal vimrc now:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', { 'start_filter': 1})

au FileType denite-filter call s:denite_filter_mappings()
function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
    inoremap <silent><buffer> <C-j>
    \ <Esc><C-w>p:call cursor(line('.')+1,0)<CR><C-w>pA
endfunction
```
Now repeat the steps above -> when selecting and pressing `<CR>` on the `echo 'foo'` candidate nothing happens.

**Comment by Shougo** [comment]
You need to set `set cmdheight=2` to fix the problem.

**Comment by Shougo** [comment]
Your cmdline is too small.  It is not denite.nvim's issue.

**Comment by petobens** [comment]
Why so? If it works from within the normal denite window why should I change the `cmdheight` setting to make it work from within the denite filter window? It should work in both cases as far as I can tell

**Comment by Shougo** [comment]
Insert mode behavior and normal mode behavior is different.
It seems extra output exists.

I have checked the code.  But it seems difficult to fix and you can fix it by `cmdheight`.

I don't want to work for the problem.
It is possible but I don't recommend for you to execute action in filter window.

If you can create the PR to fix, it is wellcome.   This is open source.
Why don't you fix the problem?

**Comment by Shougo** [comment]
I fix the problem if possible, true.
But I don't fix all problems.

I can choose fix or not fix the problem.

**Comment by petobens** [comment]
> Why don't you fix the problem?

Because as you said it's hard, there is a lot of code and I wouldn't know where to start.

Can you fix the problem that the that executed candidate is not added to the command history? i.e with the original minimal init.vim:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

au FileType denite call s:denite_mappings()
function! s:denite_mappings() abort
    nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
endfunction
```
If I do:
1. Run `:echo 'foo'` and then `:echo 'bar'`
2. Run `:Denite command_history` and select `:echo 'foo'`
After running `:echo 'foo'`, the `:echo 'foo'` still shows after the `echo 'bar'` candidate (i.e it was not added to the history). I expect the history to be updated.

**Comment by Shougo** [comment]
>Because as you said it's hard, there is a lot of code and I wouldn't know where to start.

It is really needed, you can do it.

**Comment by Shougo** [comment]
> Can you fix the problem that the that executed candidate is not added to the command history? 

Fixed.

**Comment by petobens** [comment]
> It is really needed, you can do it.

It's needed in the sense it's a bug... I'll try to have a look but, as I said before, if it's hard for you to fix it then it's way harder for me to do so

> Fixed

Thank you!
