### ISSUE TITLE
E21: Cannot make changes, 'modifiable' is off

### ISSUE THREAD

**Issue by arkottke** [Shougo/denite.nvim#701]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I haven't changed any configuration on my side, but recently Denite no long accepts input and reports: "E21: Cannot make changes, 'modifiable' is off". I can scroll through the buffer, but Enter (which used to open the file) just advances to the next line.

## Expected
Typing to filter results and Enter to open file

## Environment Information (Required!)

 * denite version (SHA1): 00ce66260291d059386f1aac6ef707e6dbd0c13f

 * OS: Arch Linux

 * Vim/neovim version: NVIM v0.3.8

 * `:checkhealth` or `:CheckHealth` result(neovim only): All pass

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/.nvim/plugged/denite.nvim
```

## How to reproduce problems from neovim startup (Required!)

 1. :Denite file/rec
 2. Start typing :face_with_head_bandage: 

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

Attached.

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/1033651/62315985-60238c00-b44b-11e9-86e4-a5faf8e67a10.png)

## Upload the log file
[log_py3_rplugin.log](https://github.com/Shougo/denite.nvim/files/3458105/log_py3_rplugin.log)

**Comment by Shougo** [comment]
Please read the issue.

https://github.com/Shougo/denite.nvim/issues/640

And why don't read the documentation?

**Comment by arkottke** [comment]
I tried to read the documentation and couldn't figure it out. My apologies for wasting your time.

**Comment by gunar** [comment]
I had the same trouble myself but `:help denite` clarified it all.

This is very well written documentation, @Shougo.
And I love the new UX.
Thank you.
