### ISSUE TITLE
error occurred when mixing use `-split='floating'`

### ISSUE THREAD

**Issue by zgpio** [Shougo/denite.nvim#706]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

## Environment Information (Required!)

 * denite version (SHA1): 5d9798c

 * OS: macos

 * Vim/neovim version: NVIM v0.4.0-1713-g1852dfdf9

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set rtp+=./denite.nvim/
let $NVIM_RPLUGIN_MANIFEST = './denite_rplugin.vim'

nnoremap <silent> /  :<C-u>Denite -split='floating'  line<CR>
nnoremap <silent> ;g :<C-u>Denite  grep<CR>
```

## How to reproduce problems from neovim startup (Required!)

 1. nvim -u init.vim
 2. use `;g` to search something
 3. use `/` to search something
 4. Again, use `;g` to search something, it will cause error

see [video](https://asciinema.org/a/4V9hvMZ2MBpBKhgkoDUgE9OfA)

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/19503791/63208327-4483db00-c105-11e9-9f80-63a022305760.png)

**Comment by zgpio** [comment]
Now cause another error with same reproduce step.
![image](https://user-images.githubusercontent.com/19503791/63218967-611e2280-c19a-11e9-88c0-832daec186ef.png)

**Comment by Shougo** [comment]
Please update again.

**Comment by zgpio** [comment]
Again, Now another error occur with same reproduce step.
![image](https://user-images.githubusercontent.com/19503791/63221034-5f1d8900-c1c5-11e9-8688-d6f22dab7031.png)

**Comment by Shougo** [comment]
Please update again.

**Comment by zgpio** [comment]
Error disappeared with reproduce step, but split behavior of step 4 `;g` is wrong, it should use default `-split=horizontal` rather than `floating`.
see [video](https://asciinema.org/a/Ijl7gWkdaSWb4w2DhmnHAngte)

**Comment by Shougo** [comment]
Sorry.  I don't reproduce your problem with the minimal vimrc.\

```vim
set runtimepath+=~/work/denite.nvim/
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/
" set runtimepath+=~/src/neomru.vim
" set runtimepath+=~/src/vim-airline

filetype plugin indent on
syntax enable

colorscheme desert

set cmdheight=2

nnoremap <silent> /  :<C-u>Denite -split='floating'  line<CR>
nnoremap <silent> ;g :<C-u>Denite  grep<CR>
```

And you have not uploaded the reproduce instructions.
For example: you have executed `:bd` in the video, but it is not in the instructions.
So I will ignore your report.

**Comment by Shougo** [comment]
I have got the reason.  Fixed.
