### ISSUE TITLE
Not passing the path correctly to scantree causing unrecognized arguments error

### ISSUE THREAD

**Issue by nelsyeung** [Shougo/denite.nvim#707]
# Problems summary
Using `:Denite file/rec` with scantree.py shows this error:
```sh
 error: unrecognized arguments: /Users/nelsyeung/Documents/
```
It seems like the path is passed into scantree.py without the `--path` flag thus causing the error.
I have to use the following vim setting for it to work:
```vim
call denite#custom#var('file/rec', 'command', ['scantree.py', '--path'])
```
Note that the documentation only mentions:
```vim
call denite#custom#var('file/rec', 'command', ['scantree.py'])
```

## Expected
Work without errors.

## Environment Information (Required!)

 * denite version (SHA1): commit: 8eb17c727c1ab2a3fc67fbcc093074e807d2a5d8

 * OS: macOS 10.14.6

 * Vim/neovim version: VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 21 2019 22:54:00)

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/.vim/plugged/nvim-yarp/
set runtimepath+=~/.vim/plugged/vim-hug-neovim-rpc/
set runtimepath+=~/.vim/plugged/denite.nvim/
call denite#custom#var('file/rec', 'command', ['scantree.py'])
```

## How to reproduce problems from neovim startup (Required!)

 1. `:Denite file/rec`

**Comment by Shougo** [comment]
OK.  I have fixed the documentation.

```vim
call denite#custom#var('file/rec', 'command', ['scantree.py'])
```

This is wrong.  You must set `--path` argument.

**Comment by Shougo** [comment]
I have fixed the compatibility problem.
