### ISSUE TITLE
Feature request: Custom floating header

### ISSUE THREAD

**Issue by rafi** [Shougo/denite.nvim#711]
Do you have plans of implementing a custom (floating) header, to show source-names, path, # of candidates, etc. ?

Example: 
![image](https://user-images.githubusercontent.com/147918/63771137-3c832280-c8df-11e9-9033-00f1940a69a3.png)

**Comment by Shougo** [comment]
Sorry.  I don't want to add the feature.
It is too complex.

You can implement similar feature by `b:denite_statusline`.
