### ISSUE TITLE
Floating doesn't work (-split=floating)

### ISSUE THREAD

**Issue by igorlakic** [Shougo/denite.nvim#712]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Description of my problem is the same as in #664 
:Denite -split=floating working exactly as :Denite -split=horizontal

## Environment Information (Required!)

 * denite version (SHA1): f2abcaf7e1bf

 * OS: Ubuntu 18.04.3

 * Vim/neovim version: v0.3.8

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```

health#coc#check
========================================================================
  - OK: Environment check passed
  - OK: Javascript bundle found
  - OK: Service started

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.2.6 (outdated; from /usr/lib/python2.7/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.3.2

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.6.8
  - INFO: pynvim version: 0.2.6 (outdated; from /usr/lib/python3/dist-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.3.2

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v10.16.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim


```

## Provide a minimal init.vim with less than 50 lines (Required!)

```
call plug#begin('~/.config/nvim/plugged')

Plug 'ntpeters/vim-better-whitespace'
Plug 'rstacruz/vim-closer'
Plug 'easymotion/vim-easymotion'
Plug 'neoclide/coc.nvim', {'do': { -> coc#util#install()}}
Plug 'Shougo/denite.nvim'
Plug 'Shougo/neosnippet'
Plug 'Shougo/neosnippet-snippets'
Plug 'Shougo/echodoc.vim'
Plug 'mhinz/vim-signify'
Plug 'tpope/vim-fugitive'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'mxw/vim-jsx'
Plug 'heavenshell/vim-jsdoc'
Plug 'lumiliet/vim-twig'
Plug 'chr4/nginx.vim'
Plug 'othree/javascript-libraries-syntax.vim'
Plug 'othree/yajs.vim'
Plug 'scrooloose/nerdtree'
Plug 'mhartington/oceanic-next'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'

call plug#end()
```

## How to reproduce problems from neovim startup (Required!)

 1. nvim
 2. :Denite file/rec -split=horizontal
 3. :Denite file/rec -split=floating -wincol=20 -winrow=20
 4. :Denite buffer -split=floating -winrow=1

Every of this options ends like I typed `:Denite file/rec -split=horizontal`

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)
![Imgur](https://i.imgur.com/m7rIODQ.png)

**Comment by Shougo** [comment]
>Description of my problem is the same as in #664

Have you read #664 carefully???

floating window is neovim 0.4's feature.
It is not merged yet in neovim 0.3.8.

https://github.com/Shougo/denite.nvim/issues/664#issuecomment-502495759

So you need to use neovim nightly instead.

**Comment by igorlakic** [comment]
Sorry @Shougo , I thought you meant on the latest nvim in a sense of the latest stable version - 0.3.8...
I switched to unstable 0.4 version of nvim and now floating window works. Thanks @Shougo !

I have few smaller issues that would like to ask you (I hope that it will not be a problem if I ask you here and not in the new issue).

When I try using `:Denite buffer` I get the window that partially have background color 
![buffer](https://imgur.com/r3ptyIP) 
When I try using `:DeniteProjectDir file/rec` I get the window that have normal background color over the whole floating window
![projectdir](https://imgur.com/eFWKppc)
As you can see, prompt is not at the same place in those 2 cases and background color is not over the whole floating window in 1st case (when `:Denite buffer`).
I've tried with these Denite settings:
```
let s:denite_options = {'default' : {
\ 'split': 'floating',
\ 'start_filter': 1,
\ 'auto_resize': 1,
\ 'source_names': 'short',
\ 'direction': 'botright',
\ 'prompt': 'λ:',
\ 'statusline': 0,
\ 'highlight_matched_char': 'WildMenu',
\ 'highlight_matched_range': 'Visual',
\ 'highlight_window_background': 'Visual',
\ 'highlight_filter_background': 'StatusLine',
\ 'highlight_prompt': 'StatusLine',
\ 'winrow': 1,
\ 'vertical_preview': 1,
\ }}
```
and with these settings but the result is almost the same (with slightly different window position)
```
let s:denite_options = {'default' : {
\ 'split': 'floating',
\ 'start_filter': 1,
\ 'auto_resize': 1,
\ 'source_names': 'short',
\ 'direction': 'botright',
\ 'prompt': 'λ:',
\ 'highlight_filter_background': 'CursorLine',
\ 'highlight_matched_char': 'Type',
\ }}
```
Can you give me some advice what could be an issue here? Does this have anything with the Neovim itself (unstable version)?

Thanks once again for your prompt reply and help and thanks for all the hard work you're investing in making amazing Vim plugins.

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
It is bug.  But it takes time to fix.

**Comment by Shougo** [comment]
Fixed auto resize problem.

**Comment by igorlakic** [comment]
It looks ok now... Thanks @Shougo !
