### ISSUE TITLE
xdg-open running 3 times instead of 1

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#713]
Consider the following minimal init.vim:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

au FileType denite call s:denite_mappings()

function! s:denite_mappings() abort
    nnoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
endfunction
```
Now create a source called `url_open.py` with the following content:
```python
from denite.base.source import Base

class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = 'url_open'
        self.kind = 'file'

    def gather_candidates(self, context):
        return [
            {'word': 'google', 'action__path': 'https://google.com'},
            {'word': 'github', 'action__path': 'https://github.com'},
        ]
```
Now do:
1. Install [brave-browser](https://github.com/brave/brave-browser) and make it the default browser so that running `xdg-settings get default-web-browser` shows `brave-browser.desktop`.
2. Open nvim and run `:Denite url_open`
3. Select one candidate (either google or github) and press `<CR>`

After 3. the url is opened 3 times in the browser (I expect it to only be opened only once).

I think this is not strictly related to brave-browser but to `xdg-open`. I've seen a similar behaviour with defx. Using the following minimal init.vim now:
```viml
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/defx.nvim
filetype plugin indent on

au FileType defx call s:defx_settings()

function! s:defx_settings()
    nnoremap <silent><buffer><expr> o defx#do_action('execute_system')
endfunction
```
Do:
1. Run `:Defx` in a directory containing an image (`.jpg` or whatever)
2. Press `o` in the image candidate

After 2. the image is opened three times.

For the record I'm using Arch and run `NVIM v0.5.0-23-gafd576ee9` on `alacritty 0.3.3`

**Comment by petobens** [comment]
If I remove the `&` from this line https://github.com/Shougo/denite.nvim/blob/a4969dfe9decc6184548b919379ec39027d627c6/autoload/denite/util.vim#L100-L101 then things seem to work ok. I don't know though if that breaks something elsewhere.

**Comment by Shougo** [comment]
> Install brave-browser and make it the default browser so that running xdg-settings get default-web-browser shows brave-browser.desktop.

Why I need to install brave-browser???
I use firefox for xdg-settings.

**Comment by Shougo** [comment]
I don't reproduce your problem.
I don't want to fix non reproduce-able problem.

And,

https://github.com/Shougo/denite.nvim/issues/713#issuecomment-533826271

I don't remove `&`.  Because, it blocks your Vim/neovim.

**Comment by petobens** [comment]
Mmm apparently it has something to do with setting `export BROWSER='brave'`. Removing that seems to have solved it. Sorry about the noise.

**Comment by Shougo** [comment]
OK.
