### ISSUE TITLE
Can't add a custom action to the 'output' source

### ISSUE THREAD

**Issue by Tylerc230** [Shougo/denite.nvim#714]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I can't add a custom action to the 'output' source

## Expected
I would expect a custom action I add to an existing source to show up in the action menu when I double tap tab.

## Environment Information (Required!)

 * denite version (SHA1):
a4969dfe9decc6184548b919379ec39027d627c6 
 * OS:
macos 10.14.6
 * Vim/neovim version:
NVIM v0.4.2
 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set nocompatible

let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

function! s:send_to_zsh(context)
  let command = a:context['targets'][0]['word']
  echom "executing ".command
endfunction

call denite#custom#action('output', 'send_to_zsh', function('s:send_to_zsh'))


```

## How to reproduce problems from neovim startup (Required!)
`:Denite output:!ls`
Then tap tab twice to show action menu
Notice that send_to_zsh doesn't show up
(I am able to add it to other sources)

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Please read the documentation.

```
denite#custom#action({kind}, {name}, {func}[, {options}])
```

It must be `{kind}` name.  Not `{source}` name.

**Comment by Shougo** [comment]
It works.

```vim
function! s:send_to_zsh(context)
  let command = a:context['targets'][0]['word']
  echom "executing ".command
endfunction

call denite#custom#action('base', 'send_to_zsh', function('s:send_to_zsh'))
```

**Comment by Tylerc230** [comment]
Ok, what is the `kind` for the output candidates? I'm looking at output.py and don't see a `kind` specified. and when I look at denite.source.base.Base I don't see one either. Should the `kind` for output but `word`?

**Comment by Shougo** [comment]
OK.   I have changed `kind` to `word`.

**Comment by Tylerc230** [comment]
Thank you! Works well!
