### ISSUE TITLE
Denite Python NameError on every search

### ISSUE THREAD

**Issue by Trial-In-Error** [Shougo/denite.nvim#715]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
`:Denite some_string` throws a python error.

## Expected
`:Denite some_string` shows a list of matches.

## Environment Information (Required!)

 * denite version (SHA1):
`commit 0832b22a880632510a6a3d85c3943f635a496059`

 * OS:
`OS X`

 * Vim/neovim version:
`NVIM v0.4.2`

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.4
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 1.9.3p551 (2014-11-13 revision 48407) [x86_64-darwin16.7.0]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v11.2.0
  - INFO: Neovim node.js host: /Users/ebashton/.nvm/versions/node/v11.2.0/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.5.0
```
## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/denite.nvim'
call plug#end()
```

## How to reproduce problems from neovim startup (Required!)

1. Open nvim anywhere:
  `nvim .`
2. Search for a file you know to be there:
  `:Denite pack`
3. Observe python error

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)
<img width="739" alt="Screen Shot 2019-09-27 at 11 29 07 AM" src="https://user-images.githubusercontent.com/759892/65793188-1f2db800-e11a-11e9-9091-5b5dc90ba90f.png">

## Upload the log file
[Pastebin of log file](https://pastebin.com/yF1ewQUd)

**Comment by Shougo** [comment]
You should read the documentation.
`Denite`'s first argument is source name instead of file/directory.

If you want to search files, `:Denite file/rec:pack`.
