### ISSUE TITLE
Can't handle ":" character in paths

### ISSUE THREAD

**Issue by jakubgs** [Shougo/denite.nvim#717]
# Problems summary
When a path given to `Denite` - for example `grep` - contains the `:` character the results are empty.

## Expected
Get results.

## Environment Information

 * denite version: 18ab1648891e360345e1d9f3b004fb2eabf69ee7
 * OS: `Debian 8.11`
 * Neovim version: `NVIM v0.3.8`
 * `:checkhealth` result: All green

## Provide a minimal.vim

```vim
" Your minimal.vim
set runtimepath+=~/.config/nvim/bundle/denite.nvim
" nothing else is necessary
```

## How to reproduce problems from neovim startup

 0. Create a directory with `:` in the name:
  ```
   $ mkdir ~/some\:path
   $ touch ~/some\:path/test{1,2,3}
   $ ls -l ~/some:path 
  total 0
  -rw-r--r-- 1 sochan sochan 0 Nov  6 23:54 test1
  -rw-r--r-- 1 sochan sochan 0 Nov  6 23:54 test2
  -rw-r--r-- 1 sochan sochan 0 Nov  6 23:54 test3
  ```
 1. `nvim -u minimal.vim`
 2. `:Denite file:~/some:path`
 3. See no results

![denite_01](https://user-images.githubusercontent.com/2212681/68345273-400e0380-00f1-11ea-8140-51593bc9766e.png)

I tried escaping the `:` character with `\:` but the result that it just goes to my home(`~/`):

![denite_02](https://user-images.githubusercontent.com/2212681/68345278-42705d80-00f1-11ea-956a-01db12e6badc.png)

I also tried quoting it:

![denite_03](https://user-images.githubusercontent.com/2212681/68345281-44d2b780-00f1-11ea-90d6-1c5ec21efd83.png)
![denite_04](https://user-images.githubusercontent.com/2212681/68345287-47cda800-00f1-11ea-8d08-48310eb41526.png)

**Comment by Shougo** [comment]
I get it.

Please read the documentation.

```
						*denite-source-file*
file
		Gather files from the user input.

		Source args:
			0. if it is "new", file source create the file.
			1. the search directory
```

You must use argument 1 instead of 0.

`:Denite file::some\:path` works.

**Comment by jakubgs** [comment]
Okay, but that doesn't help with `grep` source:
```
		Source args:
			0. path string or list of paths
			1. string or list of arguments
			2. pattern string or list of patterns
```
If I specify a path with `:` in it for first(`0`) argument then I get no results.

**Comment by jakubgs** [comment]
Actually, in `grep` it does work when I escape thew `:` with `\:`:
![denite_06](https://user-images.githubusercontent.com/2212681/68349050-0f7f9700-00fc-11ea-8659-aa42fdbc5b42.png)

**Comment by jakubgs** [comment]
Oh, sorry, I was still using `file`, this is correct:
![denite_grep_01](https://user-images.githubusercontent.com/2212681/68349121-52416f00-00fc-11ea-8725-30519105f8d1.png)
![denite_grep_01_000](https://user-images.githubusercontent.com/2212681/68349136-64231200-00fc-11ea-9b41-28cb7f7b4071.png)
So yeah, not sure how to make this work for `grep`.

**Comment by Shougo** [comment]
Really???
I need to reproduce the problem.
Please wait.

**Comment by Shougo** [comment]
Reproduced.
I have fixed.

**Comment by jakubgs** [comment]
Thank you, I can confirm it works now with single quotes around the path:
![denite_grep_success](https://user-images.githubusercontent.com/2212681/68388847-da0d9480-0161-11ea-821f-d0f3fb8034ca.png)
Appreciate it man, I really do. Cheers!
![thumb_up](https://user-images.githubusercontent.com/2212681/68388926-02958e80-0162-11ea-9e85-ef1e14029dfd.jpg)
