### ISSUE TITLE
Path issue opening multiple files with "lcd %:p:h" autocmd

### ISSUE THREAD

**Issue by ljohnston** [Shougo/denite.nvim#719]
# Problems summary
Opening multiple files from different directories with "lcd %:p:h" BufEnter autocmd doesn't correctly open all files, prompting "<file> does not exist. Create? [yes/no]:".

Without the lcd autocmd things work as expected.

## Expected
All selected files should open with no issues.

## Environment Information (Required!)

 * denite version (SHA1): 8962d57791f6c373053ee3e6175659c5158ecd47

 * OS: OS X Mojave

 * Vim/neovim version:
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Oct 29 2019 11:57:42)
macOS version
Included patches: 1-2224
```
 * `:checkhealth` or `:CheckHealth` result(neovim only): N/A

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set nocompatible

set pyxversion=3
let $PATH = $HOME . '/.vim/python/bin:' . $PATH

if !has('nvim')
    set pythonthreehome=$HOME/.vim/python
    set pythonthreedll=$HOME/.vim/python/lib/libpython3.7m.dylib
endif

call plug#begin('~/.vim/plugged')

    if !has('nvim')
        Plug 'roxma/nvim-yarp'
        Plug 'roxma/vim-hug-neovim-rpc'
    endif

    Plug 'Shougo/denite.nvim'

call plug#end()

autocmd BufEnter * silent! lcd %:p:h 
```

## How to reproduce problems from neovim startup (Required!)

 1. In an empty directory, run the following commands:
    ```
    $ mkdir {a,b}
    $ echo a >a/a.txt
    $ echo b >b/b.txt
    ```
 2. `$ vim -u ~/minimal.vimrc`
 3. Execute the following:
    ```
    :Denite file/rec
    :call denite#call_map('toggle_select_all')
    :call denite#call_map('do_action')
    ```

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/361524/68553923-4d253e00-03e2-11ea-9e20-ba0777f6f547.png)

**Comment by Shougo** [comment]
Fixed.
