### ISSUE TITLE
I can not open a file that contains LF in the name

### ISSUE THREAD

**Issue by rkuchumov** [Shougo/denite.nvim#728]
When I create a file that contains LF:

```
echo aaa > "$(printf 'aa\nbb')"
```

I can not use Denite to open it.

One of the workaround that I've found is to use `:edit **/*` instead of Denite

**Comment by Shougo** [comment]
I have fixed file source display.

But you have not upload the reproduce instruction.
I can open the file.

**Comment by Shougo** [comment]
https://github.com/Shougo/denite.nvim/blob/master/.github/ISSUE_TEMPLATE.md

>Warning: I will close the issue without the minimal init.vim and the reproduction instructions.
