### ISSUE TITLE
Can denite and YCM run simultaneously?

### ISSUE THREAD

**Issue by weiguoquan422** [Shougo/denite.nvim#730]
It worked fine when I just installed denite. But when I run ycm at the same time, ycm works. But denite was wrong.

**Comment by Shougo** [comment]
Sorry.  I don't want to support YCM in denite.
Because the installation and test is very hard for me.

**Comment by weiguoquan422** [comment]
ok，thanks.

**Comment by Shougo** [comment]
If you can upload the installation and how to test, I cant test it later.

**Comment by weiguoquan422** [comment]
I have modified my installation program, and there may be no way to restore the phenomenon. It doesn't affect me much. Thank you all the same.

**Comment by Shougo** [comment]
OK
