### ISSUE TITLE
[Feature request] floating-filter option

### ISSUE THREAD

**Issue by orokasan** [Shougo/denite.nvim#731]
I noticed denite-filter get more prompt-like appearance when set just denite-filter to floating window.

```diff
diff --git a/autoload/denite/filter.vim b/autoload/denite/filter.vim
index e151fc1..2576fea 100644
--- a/autoload/denite/filter.vim
+++ b/autoload/denite/filter.vim
@@ -88,19 +88,30 @@ function! s:init_buffer() abort
 endfunction
 
 function! s:new_filter_buffer(context) abort
-  if a:context['split'] ==# 'floating' && exists('*nvim_open_win')
+  if ( a:context['split'] ==# 'floating' || a:context['floating_filter'] )
+        \ && exists('*nvim_open_win')
     let row = win_screenpos(win_getid())[0] - 1
     " Note: win_screenpos() == [1, 1] if start_filter
     if row <= 0
       let row = str2nr(a:context['winrow'])
     endif
-    call nvim_open_win(bufnr('%'), v:true, {
-          \ 'relative': 'editor',
-          \ 'row': row + winheight(0),
-          \ 'col': str2nr(a:context['wincol']),
-          \ 'width': str2nr(a:context['winwidth']),
-          \ 'height': 1,
-          \})
+    if a:context['floating_filter']
+      call nvim_open_win(bufnr('%'), v:true, {
+        \ 'relative': 'editor',
+        \ 'row': row + winheight(0),
+        \ 'col': win_screenpos(0)[1],
+        \ 'width': winwidth(0),
+        \ 'height': 1,
+        \})
+    else
+      call nvim_open_win(bufnr('%'), v:true, {
+            \ 'relative': 'editor',
+        \ 'row': row + winheight(0),
+        \ 'col': str2nr(a:context['wincol']),
+        \ 'width': str2nr(a:context['winwidth']),
+        \ 'height': 1,
+        \})
+    endif
     if exists('*bufadd')
       let bufnr = bufadd('denite-filter')
       execute bufnr 'buffer'
diff --git a/autoload/denite/init.vim b/autoload/denite/init.vim
index b1f6cfa..687c657 100644
--- a/autoload/denite/init.vim
+++ b/autoload/denite/init.vim
@@ -103,6 +103,7 @@ function! denite#init#_user_options() abort
         \ 'do': '',
         \ 'empty': v:true,
         \ 'expand': v:false,
+        \ 'floating_filter': v:false,
         \ 'filter_split_direction': 'botright',
         \ 'filter_updatetime': 100,
         \ 'highlight_filter_background': 'NormalFloat',
```

![denite](https://user-images.githubusercontent.com/47175337/70452175-07938800-1aea-11ea-9048-2eceed622a5a.gif)

In this gif, floating denite-filter overwrites statusline because floating window can't overwrite command line.
But by adding some restriction of direction, it's gonna be good.
If you are interested, I will create PR.

**Comment by tex** [comment]
I tested it and it works nicely! Good work!

**Comment by Shougo** [comment]
OK.  Please create the issue.  But `floating_filter` option name is not good for me.

It should be `filter_prompt`.

**Comment by Shougo** [comment]
> In this gif, floating denite-filter overwrites statusline because floating window can't overwrite command line.

`-split=floating` has same feature.  So you should use titlestring instead.

**Comment by orokasan** [comment]
Thank you.

> > In this gif, floating denite-filter overwrites statusline because floating window can't overwrite command line.

My original plan is like
this ( ` 'row': row + winheight(0) - 1`)
<img width="1025" alt="スクリーンショット 2019-12-10 17 55 08" src="https://user-images.githubusercontent.com/47175337/70515139-30625e80-1b78-11ea-98a3-98e0e9f26918.png">

and this ( ` 'row': row + winheight(0)  + 1`)
<img width="1025" alt="スクリーンショット 2019-12-10 18 00 11" src="https://user-images.githubusercontent.com/47175337/70515122-26406000-1b78-11ea-8f1a-5a56de1584e2.png">

Statusline can be shown by this setting, but its behavior is not clean.
 ( above example setting hide last line of denite buffer and below hide statusline when statusline is located one line above command line. etc... )

> `-split=floating` has same feature. So you should use titlestring instead.

I didn't know this feature because usually I let denite-statusline disable. (for  lightline.vim ) 
Now I think this is more clean way.
But, I want to leave a way to show statusline with filter-prompt ( like `-prompt-with-statusline` )

**Comment by Shougo** [comment]
The below behavior is better.

To add the status option is ugly.
I don't want to add it.

**Comment by orokasan** [comment]
I get it.

Wait for a while please.

**Comment by Shougo** [comment]
filter-split=floating may be better name.

**Comment by orokasan** [comment]
> The below behavior is better.

Oh, if  your 'below behavior' means 
> -split=floating has same feature. So you should use titlestring instead.

I should fix this PR.
