### ISSUE TITLE
Source depend key mappings

### ISSUE THREAD

**Issue by NeverI** [Shougo/denite.nvim#735]
Hi, 

I created a [multi git repository source!](https://github.com/NeverI/denite-git-repo.nvim) and I wondered how can I create key mappings which are applied only when this source is used.
Could you help me out?

Also thank you for this awesome plugin!

**Comment by Shougo** [comment]
It is not supported. But you can define |denite-option-buffer-name| depend
key mappings. 

```vim
	autocmd FileType denite call s:denite_my_settings()
	function! s:denite_my_settings() abort
	  if b:denite.buffer_name == 'foo'
	    nnoremap <silent><buffer><expr> p
	    \ denite#do_map('do_action', 'preview')
	  endif
	endfunction
```

**Comment by NeverI** [comment]
That is enough for me!

But sadly the denite variable is not defined yet when this autocmd executed.
Hovewer this works perfectly: `if bufname('%') == '[denite]-foo'` 

Thank you

**Comment by Shougo** [comment]
I have fixed the error.

**Comment by NeverI** [comment]
Awesome, thank you very much!
