### ISSUE TITLE
Can't opened the target file if the text contains xx: xx: xx time

### ISSUE THREAD

**Issue by deresmos** [Shougo/denite.nvim#736]
# Problems summary
If use Denite grep is xx: xx: xx time in the file, the target file cannot be opened.

## Expected
Please fix problem.

## Environment Information

 * denite version (SHA1): `908cd3a3fe5b03783da7186441b2fe0c146f31b3`

 * OS: `Mac OS X 10.15.2`

 * Vim/neovim version: `v0.5.0-1217-gfa9b057d3`

 * `:checkhealth` or `:CheckHealth` result(neovim only): All green

## Provide a minimal init.vim with less than 50 lines

```vim
" Your init.vim
set runtimepath+=~/.cache/nvim-dein/repos/github.com/Shougo/denite.nvim
nnoremap <silent><expr> <CR> denite#do_map('do_action')
```

## How to reproduce problems from neovim startup

0. Create file

```bash
$ echo "2020/01/06 11:48:19 error log" > error.log
$ cat error.log
2020/01/06 11:48:19 error log
```

1. `nvim -u init.vim`
1. `:Denite grep:::error`
1. Select error.log and Enter
1. Can't open `error.log` and attempts to open `error.log:1:21:2020/01`

## Screenshot
<img width="1270" alt="スクリーンショット 2020-01-06 13 00 53" src="https://user-images.githubusercontent.com/27688389/71794392-a0370c80-3084-11ea-94a0-979c30633631.png">

**Comment by Shougo** [comment]
Fixed.

**Comment by deresmos** [comment]
Thanks!
