### ISSUE TITLE
Add feedkeys action to command_history source

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#738]
Is it possible to add a "feedkeys" action to the `command_history` source so as to easily modify a command in the history? Something like this: https://github.com/neoclide/denite-extra/blob/af18257544027ce89269dba70c12aba1f5b9e23c/rplugin/python3/denite/source/history.py#L65-L75

**Comment by Shougo** [comment]
You can edit the history by `edit` action.

**Comment by petobens** [comment]
But the `edit` action currently has some drawbacks:

i) if I use `edit` action on a `echo "foo"` candidate and transform the candidate into `echo "bar"` and press <CR> then the new text is not echoed back (i.e "bar" is not shown in the command output)
ii) there is no autocompletion for the "edited" commands

**Comment by Shougo** [comment]
OK.  I have fixed.

**Comment by petobens** [comment]
Thank you!

**Comment by petobens** [comment]
The only problem that I notice now is that if I execute the `default` action on a `echo "foo"` candidate (i.e without running the `edit` action) I get no echo.

**Comment by Shougo** [comment]
I have tested it and it is echoed.
I don't work for non reproduce-able problems.

**Comment by petobens** [comment]
With the following minimal init.vim:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

au FileType denite-filter call s:denite_filter_mappings()

function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
endfunction
```
1. Open nvim and run `:echo "foo"`
2. Run `Denite -start-filter command_history`
3. Search for the `:echo "foo"` candidate and press `<CR>` on it
After 3. there is no echo.

**Comment by Shougo** [comment]
```vim
inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
```

I have tested it.  Unfortunately, it seems feature.
The command line is cleared when `do_action` in filter buffer.

**Comment by Shougo** [comment]
I have fixed the problem.

**Comment by petobens** [comment]
Awesome. Thanks

**Comment by petobens** [comment]
One last question. Consider the following minimal init.vim
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

set lazyredraw

au FileType denite-filter call s:denite_filter_mappings()
function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
    inoremap <silent><buffer><expr> <Tab> denite#do_map('do_action', 'edit')
endfunction
```
Now do:
1. Open nvim and run `:Denite -start-filter command_history`
2. Select any candidate and press `Tab`

After  2) the denite buffer remains open. However if I remove the `set lazyredraw` line then it doesn't (i.e the denite buffer is properly closed after firing the edit action). So my question is: what's the correct behaviour (should it remain open o be closed)? Is it correct that the denite buffer behaviour depends on the `lazyredraw` setting? Thanks

**Comment by Shougo** [comment]
Reproduced.  It is `lazyredraw` problem.

> So my question is: what's the correct behaviour (should it remain open o be closed)?

It must be closed.  It is redraw problem.

You should not use `lazyredraw`.

I can fix the problem to add redraw.
But if it is added, https://github.com/Shougo/denite.nvim/issues/738#issuecomment-573632140 is reverted again.
So I don't add redraw for it.

Closing.  Q.E.D

**Comment by petobens** [comment]
Ok so the recommendation is to not use `lazyredraw`. Thanks

**Comment by petobens** [comment]
I don't know if this is related to the recent echo change (I think so). But consider the following minimal init.vim file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

set shortmess=aoOtTIc

au FileType denite-filter call s:denite_filter_mappings()
function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
endfunction
```
Now do:
1. Open nvim and run `:Denite file -start-file`
2. Select a file candidate and press `<CR>`
After 2 a `Press ENTER or type command to continue` message is echoed.

If this is a tradeoff I prefer having the command cleared (i.e loosing the ability to have the `command_history` source echo commands) rather than having this annoying `Press ENTER...` message all the time (in other words maybe it makes sense to revert: https://github.com/Shougo/denite.nvim/commit/dd831acc7a22217b3b8085307f1041fac3fcf736).
Thanks

**Comment by Shougo** [comment]
> If this is a tradeoff I prefer having the command cleared (i.e loosing the ability to have the command_history source echo commands) rather than having this annoying Press ENTER... message all the time (in other words maybe it makes sense to revert: dd831ac).

Yes.  It is trade off.

I will revert the echo.

**Comment by petobens** [comment]
Thank you
