### ISSUE TITLE
Denite options isn't applied until running Denite once

### ISSUE THREAD

**Issue by Shamaoke** [Shougo/denite.nvim#743]
`denite#custom#option` requires to run Denite once in order the options to be applied.

```vim
" :::denite:::

nmap <C-f>f :Denite file<CR>
nmap <C-f>b :Denite buffer<CR>

autocmd FileType denite call s:set_denite_options()
                     \| call s:set_denite_bindings()

let s:denite_options = { 'direction'        : 'topleft',
                       \ 'split'            : 'vertical',
                       \ 'sorters'          : 'sorter/word',
                       \ 'winwidth'         : 45,
                       \ 'statusline'       : 0,
                       \ 'vertical_preview' : 1 }

fun s:set_denite_options()
  call denite#custom#option('_', s:denite_options)
endfun

fun s:set_denite_bindings()
  nmap <silent><buffer><expr> <CR> denite#do_map('do_action')

  nmap <silent><buffer><expr> q denite#do_map('quit')

  nmap <silent><buffer><expr> t denite#do_map('toggle_select')

  nmap <silent><buffer><expr> i denite#do_map('choose_action')

  nmap <silent><buffer><expr> f denite#do_map('open_filter_buffer')

  nmap <silent><buffer><expr> p denite#do_map('do_action', 'preview')
endfun

```

1. Run Vim;

2. Run `:Dinite file` → the options, specified in the configuration file (`direction`, `split`, `sorters` etc.) isn't applied;

3. Run `:Denite file` again → the options _is_ applied.

Note, that the Denite bindings set in the `s:set_denite_bindings` function is applied without any problems on the first try.

![2nd-try](https://user-images.githubusercontent.com/625266/72677518-44ba4500-3aae-11ea-8e7e-1708e1d0e840.gif)

_Linux (Arch); Vim 8.2; Denite f9bedc6_

**Comment by Shougo** [comment]
You should not call `denite#custom#option()` in `autocmd FileType denite`.

```vim
autocmd FileType denite call s:set_denite_bindings()

let s:denite_options = { 'direction'        : 'topleft',
                       \ 'split'            : 'vertical',
                       \ 'sorters'          : 'sorter/word',
                       \ 'winwidth'         : 45,
                       \ 'statusline'       : 0,
                       \ 'vertical_preview' : 1 }

fun s:set_denite_options()
  call denite#custom#option('_', s:denite_options)
endfun
call s:set_denite_options()
```

**Comment by Shougo** [comment]
Because `autocmd FileType denite` will be called after denite initialization.
But you need to set denite options before denite initialization.

**Comment by Shougo** [comment]
> denite#custom#option requires to run Denite once in order the options to be applied.

So this is feature as you have written.

**Comment by Shamaoke** [comment]
@Shougo This is clear. Thank you.

`autocmd VimEnter * call s:set_denite_options()` also works.
