### ISSUE TITLE
【質問】Uniteのhistory/yankにあたるsource

### ISSUE THREAD

**Issue by take** [Shougo/denite.nvim#744]
お世話になっております。

Uniteであったhistory/yankにあたるsourceは現在提供されてないという認識であってますでしょうか？ :eyes: 
docの方見たのですがそれらしきものがなかったので質問させていただきました :pray:

**Comment by Shougo** [comment]
Please use neoyank plugin.
It includes `neoyank` source.

https://github.com/Shougo/neoyank.vim

**Comment by take** [comment]
thx! :pray:
