### ISSUE TITLE
[Question] Can we move the cursor to the selected window?

### ISSUE THREAD

**Issue by delphinus** [Shougo/denite.nvim#745]
Unite.vim has the `window` source/kind and the kind has `jump` action that we can move the cursor to the selected window. Can we achieve this with Denite.nvim?

**Comment by Shougo** [comment]
It is not implemented in denite(Because I don't use the feature).
But you can add it.

**Comment by delphinus** [comment]
I am used to opening many windows at once. I think I will implement it.

If I send a PR, any chance to merge here? Or should I make it on a different repo?

**Comment by Shougo** [comment]
Hm.  It depends on how many users need the feature.

**Comment by delphinus** [comment]
In actual, I want an integration for [dwm.vim][] such as [unite-dwm][] that its features are derived from the `window` source.

[dwm.vim]: https://github.com/spolu/dwm.vim
[unite-dwm]: https://github.com/kannokanno/unite-dwm

So I created another repo: [vim-denite-window][]. There it provides the `dwm` source in addition to the `window` one.

[vim-denite-window]: https://github.com/delphinus/vim-denite-window
