### ISSUE TITLE
Can't map <Esc> in the filter-window?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [Shougo/denite.nvim#746]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Setting a mapping for `<Esc>` in the filter_window doesn't seem to work (see example config below). Hitting `<Esc>` with the below config simply leaves me in the filter-window, but in Normal mode, as if the map weren't changed.

## Expected
Hitting `<Esc>` would close the filter-bar, *without* clearing the filtertext.

## Environment Information (Required!)

 * denite version (SHA1): f9bedc6cc32d284692a23f8141fdde0930a54a0a

 * OS: macOS 10.15.2

 * Vim/neovim version: 0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
autocmd FileType denite-filter call s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
   map  <silent><buffer>         <CR>        <Plug>(denite_filter_update)
   imap <silent><buffer>         <CR>        i_<Plug>(denite_filter_update)
   vmap <silent><buffer>         <CR>        <Plug>(denite_filter_update)

   map  <silent><buffer>         <Esc>       <Plug>(denite_filter_update)
   imap <silent><buffer>         <Esc>       i_<Plug>(denite_filter_update)

   map  <silent><buffer>         <C-c>       <Plug>(denite_filter_quit)
   imap <silent><buffer>         <C-c>       i_<Plug>(denite_filter_quit)

   " (Chosen to match the easymotion-bd-jk mapping)
   nmap <silent><buffer> <Leader>j <Plug>(denite_filter_update)<Plug>(easymotion-bd-jk)
endfunction
```

**Comment by Shougo** [comment]
Please use `<Plug>(denite_filter_update)` instead of `i_<Plug>(denite_filter_update)`.
`i_` is just used as tag prefix in the documentation.

**Comment by Shougo** [comment]
Note: You need to upload reproduce instructions.

> Warning: I will close the issue without the minimal init.vim and the reproduction instructions.

I need to use ESP skills to reproduce the problem from your configuration.

**Comment by ELLIOTTCABLE** [comment]
Unfortunately, removing the `i_` doesn't help! I'm still having no effect.

(Once we get this figured out, maybe I can patch in a documentation-improvement? It's pretty unclear how to use these mappings!)

P.S. I'm not sure what reproduction instructions you want, beyond the `vimrc` I already included — uh,

1. copy-paste the settings into vimrc,
2. open filter-window,
3. hit `<Esc>`

Does that explain it?

**Comment by Shougo** [comment]
I get it.  If you use `start_filter` and ``split=floating, hitting <Esc> does not close the filter-window.

It is my decision.

https://github.com/Shougo/denite.nvim/pull/741

**Comment by Shougo** [comment]
> (Once we get this figured out, maybe I can patch in a documentation-improvement? It's pretty unclear how to use these mappings!)

You can improve the documentation of course.

**Comment by Shougo** [comment]
So your problem is configuration related.

Please read this.

> Provide a minimal init.vim with less than 50 lines (Required!)

Have you uploaded minimal init.vim in the first???

**Comment by Shougo** [comment]
You can use `<Plug>(denite_filter_quit)` instead.
It closes denite filter window.

```vim
   map  <silent><buffer>         <Esc>       <Plug>(denite_filter_quit)
   imap <silent><buffer>         <Esc>       <Plug>(denite_filter_quit)
```
