### ISSUE TITLE
Feature request: Floating window borders

### ISSUE THREAD

**Issue by oblitum** [Shougo/denite.nvim#747]
Some projects are using borders for floating windows to great effect, see this from fzf and floaterm:

![](https://user-images.githubusercontent.com/26684313/73285874-fe27c180-41f6-11ea-8fda-01f2529b740e.png)

Source: https://github.com/neoclide/coc.nvim/issues/1485#issuecomment-579347584

![](https://user-images.githubusercontent.com/20282795/71553203-f59c6980-2a45-11ea-88f2-747e938f7f49.gif)

Source: https://github.com/voldikss/vim-floaterm

**Comment by Shougo** [comment]
It should be implemented in neovim.
I don't want to add it in plugin way.

https://github.com/neovim/neovim/issues/9718

**Comment by oblitum** [comment]
Ok, nice they're looking into that.
