### ISSUE TITLE
Implement custom#profiles

### ISSUE THREAD

**Issue by pwntester** [Shougo/denite.nvim#75]
Please implement profile options as in unite. eg:

call unite#custom#profile('default', 'context', {
   \   'winheight': 10,
   \   'direction': 'botright',
   \ })

Thanks!

**Comment by Shougo** [comment]
`denite#custom#option()` is available for it.

**Comment by pwntester** [comment]
I tried the following configuration, but it doesnt seem to work:
```
  call denite#custom#option('default', 'context', {
    \   'winheight': 10,
    \   'direction': 'botright',
    \ })
```

**Comment by pocari** [comment]
@pwntester 

In `:h Denite`, 

```
denite#custom#option({buffer-name}, {option-name}, {value})
		Set {option-name} option to {value} in {buffer-name}
		buffer.
		Note: The all options are in |denite-options|.  However, "-" is
		substituted to "_", and "-" prefix is removed.
```

I think that you should set `winheight` this way, 

```
call denite#custom#option('default', 'winheight', 20)
```

and, I think there is not `direction`  in `option`.

**Comment by pwntester** [comment]
Thanks,

I can confirm that `winheight` works, would it be possible to port `direction` from unite?

Also, is there a way to remove the source name from every `file_mru` result item (I guess it is prefixed since it is an external plugin since its not shown in built-in sources)

**Comment by pocari** [comment]
> would it be possible to port direction

I think that it is not at the present time in current implementation.

>  remove the source name from every file_mru

?? It is not displayed by me in `file_mru`.

If you execute by multiple source(e.g Denite file_mru buffer), source name shown.

**Comment by pwntester** [comment]
Thanks, I was migrating from unite and had an extra and unnecessary option that denite is not using (`-start-insert`), I guess that it was taking it as a source instead.

` nnoremap <leader>m :<C-u>Denite -start-insert file_mru<cr>`

**Comment by pwntester** [comment]
> I think that it is not at the present time in current implementation.
Seems so, I think it would be great to migrate this functionality to help migration from unite. My eyes are looking at the denite prompt, so I find it more natural to find the more significant matches close to the prompt, but I guess thats a matter of tastes :)

**Comment by rafi** [comment]
@pwntester Use the help: `:h denite-options-mode`

**Comment by pwntester** [comment]
@rafi, thanks, its actually not needed since `insert` is the default mode. I just had it from old unite configuration

**Comment by Shougo** [comment]
I have added `direction` and `reversed` options.

**Comment by pwntester** [comment]
Awesome, thanks! Actually it is `reversed` what I was looking for however in unite as the list of candidates decreased the remaining items where shown at the bottom, close to the the prompt line. Currently they are shown at the top. Could it be possible to show them at the bottom?

Thanks again

**Comment by Shougo** [comment]
Fixed.

**Comment by pwntester** [comment]
Sorry, it doesnt seem to work for me:

![screeshot](http://i.imgur.com/asdUoon.png)

btw, what are the syntax keyword used in the window? how can I change the color of the black text (matching words in highlighted line)?

Thanks!

**Comment by Shougo** [comment]
> btw, what are the syntax keyword used in the window? how can I change the color of the black text (matching words in highlighted line)?

Please change `deniteMatched` highlight.

**Comment by Shougo** [comment]
> Sorry, it doesnt seem to work for me:

I have implemented auto-resize feature.

**Comment by pwntester** [comment]
works great, thanks!

**Comment by wsdjeg** [comment]
@Shougo I think use dict as argv looks better.
for example : 
```viml
" INTERFACE
call denite#custom#option('default', 'prompt', 'λ:')
call denite#custom#option('default', 'vertical_preview', 1)
call denite#custom#option('default', 'short_source_names', 1)
```
and
```
" INTERFACE
call denite#custom#option('default', {
    \ 'prompt' : 'λ:',
    \ 'vertical_preview' : 1,
    \ 'short_source_names' : 1,
    \ }
```
I think the last one looks better, I do not want to see too many duplicate `call denite#custom#option`.

**Comment by wsdjeg** [comment]
and here is example how I set denite, maybe, some option name is wrong, it is just copy from my unite config.
```
let s:denite_options = {'default' : {
			\   'highlight-matched-char' : 'Function',
			\   'highlight-matched-range' : 'Function',
			\   'safe': 0,
			\   'start_insert': 1,
			\   'ignorecase' : 1,
			\   'short_source_names': 1,
			\   'update_time': 200,
			\   'direction': 'rightbelow',
			\   'winwidth': 40,
			\   'winheight': 15,
			\   'max_candidates': 100,
			\   'no_auto_resize': 1,
			\   'vertical_preview': 1,
			\   'cursor_line_time': '0.10',
			\   'hide_icon': 0,
			\   'candidate-icon': ' ',
			\   'marked_icon': '✓',
			\   'prompt' : '➭ '
			\ }}

function! s:profile(opts) abort
	for fname in keys(a:opts)
		for dopt in keys(a:opts[fname])
			call denite#custom#option(fname, dopt, a:opts[fname][dopt])
		endfor
	endfor
endfunction

call s:profile(s:denite_options)
```

**Comment by Shougo** [comment]
> I think the last one looks better, I do not want to see too many duplicate call denite#custom#option.

I have implemented the feature.

**Comment by wsdjeg** [comment]
nice work!
