### ISSUE TITLE
File search by Pattern does not open the file after press Enter on the line selected in buffer list

### ISSUE THREAD

**Issue by alduro** [Shougo/denite.nvim#751]
# Problems summary

- Find for a pattern using `<leader>g` in current direct.
- Select a line. press Enter.
- File does not open

- I'm using nvim on tmux

## Expected

- Open the File after selecting the file in search results.

## Environment Information (Required!)

 * denite version (SHA1): 2164521

 * OS: MacOS 10.15.2 (19C57)

 * Vim/neovim version: 

NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/config -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191107-85913-1wbgqz6/neovim-0.4.3/build/include
Compiled by brew@Catalina.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"

Run :checkhealth for more info

 * `:checkhealth` or `:CheckHealth` result(neovim only):

health#coc#check
========================================================================
  - OK: Environment check passed

  - OK: Javascript bundle found
  - OK: Service started

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: pyenv: Path: /usr/local/Cellar/pyenv/1.2.1/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /Users/aldo/.pyenv
  - INFO: Using: g:python_host_prog = "/usr/bin/python2"
  - INFO: Executable: /usr/bin/python2
  - ERROR: Command error (job=71, exit code 1): `'/usr/bin/python2' -c 'import sys; sys.path.remove(""); import neovim; print(neovim.__file__)'` (in '/private/var/folders/bs/75kn3dqd0xn27pbwprx8622c0000gn/T/vim-goee442f71fdc7a6ee3e8a6f98c94ba82d99e0b4e84b02a29360dc39d0addda428')
    Output: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
    Stderr: Traceback (most recent call last):  File "<string>", line 1, in <module>ImportError: No module named neovim
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: unable to load neovim Python module
  - ERROR: pynvim is not installed.
    Error: unable to load neovim Python module
    - ADVICE:
      - Run in shell: pip install pynvim

## Python 3 provider (optional)
  - INFO: pyenv: Path: /usr/local/Cellar/pyenv/1.2.1/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /Users/aldo/.pyenv
  - INFO: Using: g:python3_host_prog = "/Users/aldo/.pyenv/shims/python3"
  - INFO: Executable: /Users/aldo/.pyenv/shims/python3
  - INFO: Python version: 3.6.4
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin18]
  - INFO: Host: /Users/aldo/.asdf/shims/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v12.6.0
  - INFO: Neovim node.js host: /Users/aldo/.asdf/installs/nodejs/12.6.0/.npm/bin/neovim-node-host
  - OK: Latest "neovim" npm/yarn package is installed: 4.8.0

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```
https://gist.github.com/alduro/302e336fd2903ee2c990e239fae958ff

## How to reproduce problems from neovim startup (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)

![Screen Shot 2020-02-15 at 10 48 48 (2)](https://user-images.githubusercontent.com/183364/74589085-08acce00-4fe1-11ea-8736-41ccef9bbee6.png)

![Screen Shot 2020-02-15 at 10 51 42](https://user-images.githubusercontent.com/183364/74589110-2da14100-4fe1-11ea-8103-7b235a3a486c.png)

## Upload the log file
 Both log files are empty `/tmp/log_py3_rplugin` and `/tmp/log_py3_script`

**Comment by Shougo** [comment]
https://gist.github.com/alduro/302e336fd2903ee2c990e239fae958ff

This is not minimal vimrc.

**Comment by Shougo** [comment]
```vim
set runtimepath+=~/work/denite.nvim/
set runtimepath+=~/work/nvim-yarp/
set runtimepath+=~/work/vim-hug-neovim-rpc/

filetype plugin indent on

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> q denite#do_map('quit')
  nnoremap <silent><buffer><expr>  <CR>     denite#do_map('do_action')
  nnoremap <silent><buffer><expr>  <Space>  denite#do_map('toggle_select').'j'
  nnoremap <silent><buffer><expr>  a        denite#do_map('choose_action')
  nnoremap <silent><buffer><expr>  d        denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr>  p        denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr>  i        denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr>  <Esc>    denite#do_map('quit')
endfunction

" Remap leader key to ,
let g:mapleader=','
nnoremap <leader>g :<C-u>Denite grep:. -no-empty<CR>
```

I have tested in minimal vimrc and it works.
So I close your issue.

**Comment by Shougo** [comment]
I have tested your reproduce instructions.
What is my mistake???

**Comment by Shougo** [comment]
The reproduce instructions and minimal vimrc must be reproduce-able by anyone.

My vimrc is reproduce-able but your is not.

**Comment by Shougo** [comment]
And you should improve the reproduce instructions like this.

https://github.com/Shougo/denite.nvim/issues/749#issue-558732089

**Comment by alduro** [comment]
The minimal vimdc works. Some of the denite custom options broke it. Thanks !

**Comment by Shougo** [comment]
OK.
