### ISSUE TITLE
Feature request: Floating window preview

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#753]
Consider the following minimal init.vim file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', {
            \ 'start_filter': 1,
            \ 'auto_resize': 1,
            \ 'vertical_preview': 1,
            \ })

au FileType denite-filter call s:denite_filter_mappings()
function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <C-c> denite#do_map('quit')
    inoremap <silent><buffer><expr> <A-v> denite#do_map('do_action', 'preview')
endfunction
```
Now open `nvim` and do
1. Run `Denite file/rec` in some dir
2. As in the image filter candidates so as to have only few of them (i.e the height of the denite buffer is small)
3. Press `<A-V>` to trigger preview action

As it can be seen in the image after 3. the preview window height is way too small. I was wondering if you could add the possibility to open the preview window in a floating window. Thanks in advance

![image](https://user-images.githubusercontent.com/2583971/74607305-aaeab580-50b6-11ea-8332-8c90b507069e.png)

**Comment by Shougo** [comment]
Hm...  I will try it later.

**Comment by Shougo** [comment]
I have added `-floating-preview` option.
It is useful for me.

**Comment by petobens** [comment]
Thank you! Is it possible to configure the floating window appearance? I would like to add line numbers to it

**Comment by petobens** [comment]
Also consider the following minimal `init.vim` file:
```viml
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', {
            \ 'auto_resize': 1,
            \ 'statusline': 0,
            \ 'winheight': 15,
            \ 'reversed': 1,
            \ 'start_filter': 1,
            \ 'vertical_preview': 1,
            \ 'floating_preview': 1,
            \ 'preview_width': 70,
            \ 'preview_height': 15,
            \ })

au FileType denite call s:denite_mappings()
au FileType denite-filter call s:denite_filter_mappings()
function! s:denite_mappings() abort
    nnoremap <silent><buffer><expr> i denite#do_map('open_filter_buffer')
endfunction
function! s:denite_filter_mappings() abort
    inoremap <silent><buffer><expr> <C-c> denite#do_map('quit')
    inoremap <silent><buffer><expr> <A-v> denite#do_map('do_action', 'preview')
    imap <buffer> <C-e> <Plug>(denite_filter_quit)
endfunction
```
Now open nvim and do:
1. Run `:Denite file`
2. Filter some candidates
3. Press `<A-v>` to open the preview window

As it can be seen in the image after 3 the (floating) preview window covers the statusline. Can the floating window be moved 1 line up to avoid covering the statusline? Thanks

![image](https://user-images.githubusercontent.com/2583971/75102772-9edb8800-55cf-11ea-8d73-3406c4764a96.png)

**Comment by Shougo** [comment]
> As it can be seen in the image after 3 the (floating) preview window covers the statusline. Can the floating window position be moved 1 line up to avoid covering the statusline? Thanks

It cannot be supported unfortunately.

**Comment by Shougo** [comment]
> Thank you! Is it possible to configure the floating window appearance? I would like to add line numbers to it

I have added `denite-preview` User autocmd.

**Comment by petobens** [comment]
> It cannot be supported unfortunately.

What a pity

> I have added denite-preview User autocmd.

Thank you!
