### ISSUE TITLE
[Feature Request] Detect the floating previews to be opened

### ISSUE THREAD

**Issue by delphinus** [Shougo/denite.nvim#755]
Recent commit ( 65ceb7fa19cf37c82e3a1ee9553d4ed94ce3c6c4 ) introduced `-floating-preview`. Thank you for this great feature.

But I have trouble for this. I wrote logic to know the preview window has been opened.

https://github.com/voldikss/vim-floaterm/blob/b0abce2731afd976706ca8619d90bd93f8f74bda/rplugin/python3/denite/kind/floaterm.py#L66-L75

This uses the winvar `&previewwindow` to know the window is a preview window. But the floating previews do not have this var.

Can you provide a way to detect whether the window is a preview or not even  when using floating previews?

**Comment by Shougo** [comment]
I have added `denite-preview` User autocmd.
Please use it instead.
