### ISSUE TITLE
Wiki update: External new external source

### ISSUE THREAD

**Issue by viniarck** [Shougo/denite.nvim#767]
@Shougo, I'm interested in adding [tmuxdir.nvim](https://www.github.com/viniarck/tmuxdir.nvim) to the external sources.  Could you merge this branch https://github.com/viniarck/denite.nvim-wiki/commit/d2f5ba4028d4a09d5b014137647ad9d86e0b7fe0 ? 

To clone `git clone https://github.com/viniarck/denite.nvim-wiki.git`

Thank you!

**Comment by Shougo** [comment]
OK.  I have cherry-picked your commit.
