### ISSUE TITLE
[Bug] Binding needs to be pressed twice

### ISSUE THREAD

**Issue by nwaywood** [Shougo/denite.nvim#769]
# Problems summary

When I have quit mapped to `<esc>` as shown below, it works as expected i.e. I press escape and denite quits:

```
autocmd FileType denite-filter call s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
    inoremap <silent><buffer><expr> <esc>
                \ denite#do_map('quit')
endfunction
```

However, if I bind the exact same action to `<c-g>` instead, then I need to press `<c-g>` twice for denite to quit:

```
autocmd FileType denite-filter call s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
    inoremap <silent><buffer><expr> <C-g>
                \ denite#do_map('quit')
endfunction
```

## Expected

As mentioned above, it is expected that I should only need to press `<c-g>` once, like with `<esc>`

## Environment Information (Required!)

 * denite version (SHA1): c260893153a6e1378e66ef306c2cb54803447390

 * OS: MacOS

 * Vim/neovim version: Nvim 0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only):

![image](https://user-images.githubusercontent.com/3773641/78319533-16c7a580-75b3-11ea-945a-cca7ba45a9b8.png)

**Comment by nwaywood** [comment]
Nevermind, I double checked the issue with a minimal `init.vim` and it works. 

```
call plug#begin('~/.config/nvim/plugged')

Plug 'altercation/vim-colors-solarized'
Plug 'Shougo/denite.nvim', { 'do': ':UpdateRemotePlugins' } " Atom-narrow for vim

call plug#end()

syntax enable
set background=dark
colorscheme solarized

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
endfunction

autocmd FileType denite-filter call s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
    inoremap <silent><buffer><expr> <CR> denite#do_map('do_action')
    inoremap <silent><buffer><expr> <C-g>
                \ denite#do_map('quit')
endfunction

call denite#custom#option('default', {
            \ 'prompt': '>',
            \ 'start_filter': 1
            \ })
```

**Comment by Shougo** [comment]
Oh..

**Comment by nwaywood** [comment]
For anyone else that might come across this issue with the same problem.

The problem for me was `vim-surround` insert mode bindings that a prefixed to `<c-g>` which was messing with my binding.

It's not documented in the `vim-surround` docs but you can disable the bindings with the variable here https://github.com/tpope/vim-surround/blob/master/plugin/surround.vim#L610
