### ISSUE TITLE
Question: Using denite#custom#action with dein

### ISSUE THREAD

**Issue by thecontinium** [Shougo/denite.nvim#770]
Hi

I would like to set some custom actions and am using your example in the docs.

The following works for **file** but not **dein**. 

```vim
	call denite#custom#action('file,dein', 'test',
				\ {context -> execute('let g:foo = 1')})
```

Can you advise please ?

**Comment by Shougo** [comment]
Please read the documentation.

```
						*denite#custom#action()*
denite#custom#action({kind}, {name}, {func}[, {options}])
		Define {name} action for {kind}.
		{func} must be a |Funcref| or the name of a function.
		{options} is an optional dictionary which overrides the
		action behaviors "is_quit" and/or "is_redraw".
		Note: {kind} is comma separated.
		Note: lambda function is not supported in Vim8.
```

You must specify `kind` name instead of `source` name.

**Comment by Shougo** [comment]
```vim
call denite#custom#action('file,directory', 'test',
      \ {context -> execute('let g:foo = 1')})
```

It works for me.

**Comment by thecontinium** [comment]
Ah - thank you.

--
The Continium

On 5 April 2020 at 02:24:42, Shougo (notifications@github.com<mailto:notifications@github.com>) wrote:

call denite#custom#action('file,directory', 'test',
      \ {context -> execute('let g:foo = 1')})

It works for me.
