### ISSUE TITLE
How to grep files matching pattern in a directory using Denite?

### ISSUE THREAD

**Issue by nadya-p** [Shougo/denite.nvim#771]
# Problems summary

Given the following grep command
`grep -r SearchString "C:\path with spaces" --include *.txt`
What would be the equivalent command using Denite, with `SearchString` specified in Denite's interactive mode?

<details>
  <summary>Environment Information</summary>
## Environment Information

 * denite version (SHA1): 7a71d54b725344dad92939901f319223411dc102

 * OS: Windows 7

 * neovim version: v0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only):
 
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - ERROR: command failed: infocmp -L
    infocmp: couldn't open terminfo file /usr/share/terminfo/63/conemu.

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          C:\cygwin64\bin\python2.7.EXE does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          C:\Anaconda3\python.EXE is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python in the environment.
  - INFO: Multiple python executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Anaconda3\python.EXE
  - INFO: Other python executable: C:/Anaconda3/python
  - INFO: Other python executable: C:/Anaconda2/python
  - INFO: Python version: 3.7.4
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

</details>

## Provide a minimal init.vim

```vim
set runtimepath+=C:/denite_example/denite.nvim

" I was able to come up with the following, but it alters all the subsequent grep searches.
" Instead, I'd like to define a new grep source just for searching in all the text files in specified directory
call denite#custom#var('grep', { 'command': ['grep'], 'default_opts': ['-inH'], 'recursive_opts': ['-r', '--include=*.txt'], 'pattern_opt': ['-e'], 'separator': ['--'], 'final_opts': ['']})
```

## How to reproduce problems from neovim startup

 1. `:Denite -path='C:/denite_example/path with spaces' grep`
 2. Type `SearchString`
The following error appears:
![image](https://user-images.githubusercontent.com/15910645/78773961-418b7280-7994-11ea-9c03-c5c5c3dc2b8f.png)

## Generate a logfile if appropriate

I've used powershell syntax for environment variables
`$Env:NVIM_PYTHON_LOG_FILE="C:\denite_example\log"`
`$Env:NVIM_PYTHON_LOG_LEVEL="DEBUG"`
And still no log was generated following the proposed steps.

**Comment by Shougo** [comment]
You should read grep source documentation.

**Comment by Shougo** [comment]
OK.  I get it.  Your final opts is broken.  It must be : `[]`.

```vim
call denite#custom#var('grep', { 'command': ['grep'], 'default_opts': ['-inH'], 'recursive_opts': ['-r', '--include=*.txt'], 'pattern_opt': ['-e'], 'separator': ['--'], 'final_opts': []})
```

**Comment by nadya-p** [comment]
Thank you!

For those who might be looking for a similar configuration, here is mine:
```
call denite#custom#alias('source', 'grep/txt', 'grep')
call denite#custom#var('grep/txt', { 'command': ['grep'], 'default_opts': ['-inH'], 'recursive_opts': ['-r', '--include=*.txt', '--exclude=.git'], 'pattern_opt': ['-e'], 'separator': ['--'], 'final_opts': []})
nnoremap <F9> :Denite -path='C:\path with spaces' -start-filter -sorters=sorter/lastmod grep/txt:::!<CR>
```

To sort the results by the modification date, check out this sorter:
https://github.com/thecontinium/vim-denite-sorter-lastmod
