### ISSUE TITLE
multiple key mappings not working

### ISSUE THREAD

**Issue by pwntester** [Shougo/denite.nvim#78]
Hi,

Im trying to map `jk` to enter normal mode by adding the following mapping:

`call denite#custom#map('insert', 'jk', 'enter_mode:normal')`

However the mapping is not working. Changing it to a single key mapping works though.

Thanks,
A

**Comment by Shougo** [comment]
This is not supported.  Please create original mode for it.

**Comment by pwntester** [comment]
Got it, thanks

**Comment by Shougo** [comment]
https://github.com/Shougo/denite.nvim/pull/79 support the feature.
