### ISSUE TITLE
Do action quickfix target all

### ISSUE THREAD

**Issue by weilbith** [Shougo/denite.nvim#780]
Hey :wave:

I want to have a mapping for the Denite buffer that puts all filtered entries to the quickfix or location list. So far I need to first call/map `denite#do_map('toggle_select_all')` and then `denite#do_map('do_action', 'quickfix')`. I would love to combine this into one command and map it. By the documentation I thought the `{targets}` parameter of `denite#do_action({context}, {action-name}, {targets})` could help. But I fail to set it correctly. I thought because it is related to the `context['targets']` what is a list, and the docs mention to use `context['targets'][0]` at some places, that `:` would act on all list entries. But it doesn't.

So how do I achieve that? Thanks!

**Comment by Shougo** [comment]
Please use the function like this.

```vim
function! s:denite_mappings() abort
  nnoremap <silent><buffer> <C-j> :call <SID>open_all()<CR>
endfunction
function! s:open_all()
  call denite#call_map('toggle_select_all')
  call denite#call_map('do_action', 'open')
endfunction
```

**Comment by Shougo** [comment]
> I thought because it is related to the context['targets'] what is a list, and the docs mention to use context['targets'][0] at some places, that : would act on all list entries. But it doesn't.

Have you read the documentation correctly??

The `{targets}` is intended to use in `denite#custom#action()`.
So you cannot use it for your mappings.

```
	call denite#custom#action('file', 'test2',
	      \ {context -> denite#do_action(
	      \  context, 'open', context['targets'])})
```
