### ISSUE TITLE
No highlighting and filter list vanishes

### ISSUE THREAD

**Issue by nomasprime** [Shougo/denite.nvim#781]
# Problems summary
I've recently upgaded everything and added some Lua to my config.

Thought it was the changes to my config so removed it and still having the same result.

Currently in all of my project highlighting as I type's dissappeared and in one project the list pops up briefly before vanishing.

## Expected
- Highlighting as I type
- Filtered list shouldn't disappear

## Environment Information (Required!)

 * denite version (SHA1): fa9e2e133d4f7e8056f4eb00cff00986368bbd9f

 * OS: MacOS 10.15.4

 * Vim/neovim version: v0.5.0-nightly

 * `:checkhealth` or `:CheckHealth` result(neovim only): Passes

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
let s:denite_options = {
  \ 'auto_resize': 1,
  \ 'reversed': 1,
  \ 'source_names': 'short',
  \ 'start_filter': 1,
  \ 'statusline': 0,
  \ }

call denite#custom#option('default', s:denite_options)

call denite#custom#kind('directory', 'default_action', 'open')
call denite#custom#var('file/rec', 'command', ['rg', '--files', '--glob', '!.git', '--hidden'])
call denite#custom#var('grep', 'command', ['rg'])
call denite#custom#var('grep', 'default_opts', ['-i', '--vimgrep', '--no-heading'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])

nnoremap <silent> <Leader>" :Denite register<CR>
nnoremap <silent> <Leader>* :<C-u>DeniteCursorWord grep:.<CR>
nnoremap <silent> <Leader>/ :<C-u>Denite grep:. -no-empty<CR>
nnoremap <silent> <Leader>b :Denite buffer<CR>
nnoremap <silent> <Leader>c :Denite command<CR>
nnoremap <silent> <Leader>d :DeniteProjectDir directory_rec<CR>
nnoremap <silent> <Leader>g :Denite line<CR>
nnoremap <silent> <Leader>r :Denite command_history<CR>
nnoremap <silent> <Leader>t :DeniteProjectDir file/rec<CR>
nnoremap <silent> <Leader>m :Denite mark<CR>

" Denite buffer maps
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <C-s>
  \ denite#do_map('do_action', 'split')
  nnoremap <silent><buffer><expr> <C-t>
  \ denite#do_map('do_action', 'tabopen')
  nnoremap <silent><buffer><expr> <C-v>
  \ denite#do_map('do_action', 'vsplit')
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> m
  \ denite#do_map('toggle_select').'k'
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
endfunction

" Denite filter buffer maps
autocmd FileType denite-filter call s:denite_filter_my_settings()
function! s:denite_filter_my_settings() abort
  imap <silent><buffer> <Esc> <Plug>(denite_filter_quit)
  inoremap <silent><buffer><expr> <C-s>
        \ denite#do_map('do_action', 'split')
  inoremap <silent><buffer><expr> <C-t>
        \ denite#do_map('do_action', 'tabopen')
  inoremap <silent><buffer><expr> <C-v>
        \ denite#do_map('do_action', 'vsplit')
  inoremap <silent><buffer><expr> <CR>
        \ denite#do_map('do_action', 'open')
endfunction

luafile ~/.config/nvim/init.lua
```
init.lua
```
local lsp = require 'nvim_lsp'
```

## How to reproduce problems from neovim startup (Required!)

 1. Above config
 2. Open NeoVim
 3. Start Denite (sometimes list disappears)
 4. Type search (no highlighting)
 5. Enter

**Comment by nomasprime** [comment]
Seems to be doing really random stuff now:

- Sometimes it loads results to be filtered, typing doesn't seem to filter results but when I hit enter it might open the file I was looking for, ie it's kind working but I don't see the results actually being filtered
- Other times there's nothing at all to filter in the first place

**Comment by nomasprime** [comment]
Just noticed when this happens `Gen. ctags` is displayed in the status.

**Comment by nomasprime** [comment]
Denite list disappearing seems to have been caused by `node_modules` not being added to .gitignore on a particular project.

**Comment by nomasprime** [comment]
Maybe missing highlighting's something to do with this found in the docs:
```
2020.04.10
* Remove matched highlight feature to optimize update denite buffer.
  But you can use -match-highlight option if you use Vim 8.1.1084+.
```
So no more highlighting in NeoVim, even nightly build?

**Comment by nomasprime** [comment]
Looks like we're waiting on [this](https://github.com/neovim/neovim/issues/12110).

**Comment by Shougo** [comment]
> So no more highlighting in NeoVim, even nightly build?

Yes.  In Vim8, you can enable the highlight by `match-highlight` option.

**Comment by Shougo** [comment]
> Start Denite (sometimes list disappears)

I don't work for the problem.
Have you read the issue template??
It must be reproduce-able without your config.

For example, you can reproduce it with docker environment?

https://github.com/Shougo/deoplete.nvim/issues/1099
This issue is good example.  It is reproduce-able for me.
Please compare your issue with this.

**Comment by Shougo** [comment]
And your config is too long and not minimal.
Please upload `nvim -u test.vimrc`able vimrc.

**Comment by Shougo** [comment]
I have ported the patch.

https://github.com/neovim/neovim/pull/12325

**Comment by Shougo** [comment]
The patch is merged now.

**Comment by Shougo** [comment]
@nomasprime No response?  If so, I will close the issue.

**Comment by nomasprime** [comment]
@Shougo I'm still getting some strange behaviour like no results when window first loads and also filtered list disappearing.

My explorer is dirvish, don't know if this is relevant.

**Comment by nomasprime** [comment]
Tried without dirvish and result is the same.

**Comment by nomasprime** [comment]
Looks like it happens when devicons are enabled.

**Comment by Shougo** [comment]
OK.  So please create the minimal vimrc with devicons.
I will test it later.

If not, I will close it later.

**Comment by Shougo** [comment]
Can I close the issue?

**Comment by nomasprime** [comment]
Sorry, didn't get notifications. Need to check my settings.

I've created a task for the minimal vimrc. Will add this weekend.

**Comment by Shougo** [comment]
OK.  I wait.

**Comment by nomasprime** [comment]
It's been fixed somewhere, can't reproduce anymore.

**Comment by Shougo** [comment]
OK.
