### ISSUE TITLE
【質問】deniteを開いたままvsplitする方法

### ISSUE THREAD

**Issue by take** [Shougo/denite.nvim#784]
いつもお世話になっております

以下のようにしてファイルをvsplitで開くというのをよくやるんですが、deniteを開いたままvsplitすることは可能でしょうか？👀
docの方見たんですがそれらしいものが見当たらなかったので質問させていただきました... :bow:

```
	nnoremap <silent><buffer><expr> <leader>vs
				\ denite#do_map('do_action', 'vsplit')
```

**Comment by Shougo** [comment]
Please use `-post-action=open` option.

**Comment by take** [comment]
ありがとうございます！ :pray:
