### ISSUE TITLE
Provide debugging guide

### ISSUE THREAD

**Issue by glacambre** [Shougo/denite.nvim#788]
Hi.

For the past 2~4 months I've been experiencing frequent issues with Denite. The python process suddenly starts eating 100% of a CPU core and there's nothing I can do to stop it. Manually sending sigkill to the python process results in an endless loop of error messages that prevent me from doing anything else than killing Neovim.

The problem is, I don't know how to reproduce this issue. This is why I would like to debug it myself when it happens. I have no experience with debugging either vimscript or python plugins/programs, but I do know how to debug "regular" programs written in compiled languages.

Could you provide a guide to debugging Denite? Just being able to suspend the python process, step through the instructions that are ran and inspect state would be a huge help.

**Comment by Shougo** [comment]
Hm.  If so, you should study to debug Python.
It is available in Internet.

I recommend for you to logging.
https://docs.python.org/3/library/logging.html#logrecord-attributes

And you should provide your environment information.

**Comment by Shougo** [comment]
Unfortunately, denite does not implement logging feature.
It is not needed for me.
deoplete has it.

**Comment by Shougo** [comment]
Ah, pynvim has the logging.  You should check it.

```
 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}
```

Note:  Why don't you read the issue template??

**Comment by glacambre** [comment]
>Hm. If so, you should study to debug Python.
>It is available in Internet.

Do you only use logging to solve bugs in python plugins?

>And you should provide your environment information.

I was hopping for an environment-agnostic guide, as other users on other platforms could have found it useful.

>Ah, pynvim has the logging. You should check it.

Sorry, I should have mentionned this: I did check the logs but I'm not seeing any information about what's happening inside the python process, which is a problem because that's where Denite gets stuck.

>Why don't you read the issue template?

I did read it, but I am not expecting you to solve my issue - instead I am asking for the knowledge I would need to solve this issue on my own. This is why I felt my request did not fit the issue template.

**Comment by Shougo** [comment]
> Do you only use logging to solve bugs in python plugins?

I only use debug print.  But in the case, debug print cannot be used.
So I recommend for you to use logging instead.
It means I don't use any debugger to debug Python plugins.  So no magic to debug it.

> I was hopping for an environment-agnostic guide, as other users on other platforms could have found it useful.

The environment information is needed to debug the problem.

> Sorry, I should have mentionned this: I did check the logs but I'm not seeing any information about what's happening inside the python process, which is a problem because that's where Denite gets stuck.

Please upload the log file.  I need the information.

**Comment by glacambre** [comment]
>So no magic to debug it.

That's disappointing, I wanted magic! :smile:

>Please upload the log file. I need the information.

I store my log files in `/tmp`, so they disappear when I shut down my computer. I'll come back when the bug happens again.

Thanks for taking the time to answer my questions :).

**Comment by Shougo** [comment]
OK.
