### ISSUE TITLE
I want to display an `[No Name]` buffer.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/denite.nvim#794]
# Problems summary
I want to display an `[No Name]` in `Denite buffer`.

## Expected
`Denite buffer` shows an `[No Name]` buffer.

## Environment Information (Required!)

 * denite version (SHA1): 7df7851826a1e8417a9b242d4ce3bd09ae1c6298

 * OS: Mac

 * Vim/neovim version: v0.5.0-nightly-117-g4ed5204bc

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
nnoremap <silent> <Leader>b :<C-u>Denite buffer<CR>
```

## How to reproduce problems from neovim startup (Required!)

 1. After starting Neovim, the `[No Name]` buffer is displayed by the `ls` command.
 2. `Denite buffer` does not show `[No Name]` buffer.

**Comment by Shougo** [comment]
```vim
set rtp+=~/work/denite.nvim
set rtp+=~/work/vim-hug-neovim-rpc
set rtp+=~/work/nvim-yarp

au FileType denite call s:denite_mappings()

function! s:denite_mappings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> <Tab>
  \ denite#do_map('choose_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction

call denite#custom#option('default', {
    \ 'auto_resize': 1,
    \ 'statusline': 0,
    \ 'reversed': 0,
    \ 'match_highlight': 1,
    \ 'start_filter': 1,
    \ 'filter_updatetime': 100,
\ })
```

It works for me.

**Comment by Shougo** [comment]
I think the no name buffer is overwritten.

**Comment by nabezokodaikon** [comment]
Sorry. I wasn't told.
I want to list empty file buffers instead of denite buffer names.

Probably around here.
`rplugin/python3/denite/source/buffer.py`
```
if not self._is_excluded(context, ba):
    if ba['name'] == '':
        ba['fn'] = 'No Name'
        ba['path'] = ''
    else:
        ba['fn'] = self.vim.call('fnamemodify', ba['name'], ':~:.')
        ba['path'] = self.vim.call('fnamemodify', ba['name'], ':p')
```

**Comment by nabezokodaikon** [comment]
Apparently, if you change the source name from `buffer` to `buffer2`, etc., an anonymous buffer will be displayed.

https://github.com/Shougo/denite.nvim/blob/7df7851826a1e8417a9b242d4ce3bd09ae1c6298/rplugin/python3/denite/source/buffer.py#L31
https://github.com/Shougo/denite.nvim/blob/7df7851826a1e8417a9b242d4ce3bd09ae1c6298/rplugin/python3/denite/source/buffer.py#L32
https://github.com/Shougo/denite.nvim/blob/7df7851826a1e8417a9b242d4ce3bd09ae1c6298/rplugin/python3/denite/kind/buffer.py#L19

**Comment by nabezokodaikon** [comment]
sorry. I wasn't told well.
I want to add [No Name] buffer to buffer Source.

**Comment by Shougo** [comment]
![スクリーンショット_2020-08-06_09-09-59](https://user-images.githubusercontent.com/41495/89476047-a29d4880-d7c4-11ea-95fa-147372003496.png)

I have said it works for me.
Please see the screenshot.  What is the problem?
Please describe it more clearly.

**Comment by Shougo** [comment]
Sorry.  Please upload your minimal vimrc or test my vimrc.
If not, I will ignore your issue.

> Provide a minimal init.vim with less than 50 lines (Required!)
> `nnoremap <silent> <Leader>b :<C-u>Denite buffer<CR>`

You have ignored `minimal vimrc`.

**Comment by nabezokodaikon** [comment]
Thank you for your reply.
I understood the cause.
I had the following settings:
```
call denite#custom#source('buffer', 'matchers',
    \ ['matcher/fuzzy', 'matcher/project_files'])
```
Sorry for the inconvenience.

**Comment by Shougo** [comment]
Oh... It is your configuration problem.
So I have said that you need to upload the minimal vimrc.

**Comment by nabezokodaikon** [comment]
I'll be careful in future.
