### ISSUE TITLE
Configure Denite to show buffers sorted by last opened

### ISSUE THREAD

**Issue by gi4c0** [Shougo/denite.nvim#797]
# Problems summary
I want to sort list of buffers (:Denite buffer) by last opened

## Expected
List of buffers sorted by last modified date

## Environment Information (Required!)
 * denite version (SHA1): #1c6298

 * OS: Ubuntu 20.04.1 LTS

 * Vim/neovim version: 0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only):
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - ERROR: Require msgpack 1.0.0+ was not successful
    - ADVICE:
      - Please install/upgrade msgpack 1.0.0+.

## Provide a minimal init.vim with less than 50 lines (Required!)
```vim
  call denite#custom#alias('source', 'file/rec/git', 'file/rec')
  call denite#custom#var('file/rec/git', 'command', ['git', 'ls-files', '--recurse-submodules', '-c', '--exclude-standard'])

  call denite#custom#var('grep', 'command', ['rg'])

  call denite#custom#var('buffer', 'date_format', '')
  call denite#custom#var('grep', 'default_opts', ['--hidden', '--vimgrep', '--heading', '-S'])

  call denite#custom#var('grep', 'recursive_opts', [])
  call denite#custom#var('grep', 'pattern_opt', ['--regexp'])
  call denite#custom#var('grep', 'separator', ['--'])
  call denite#custom#var('grep', 'final_opts', [])

  let s:denite_options = {'default' : {
        \ 'split': 'horizontal',
        \ 'start_filter': 1,
        \ 'auto_resize': 1,
        \ 'source_names': 'short',
        \ 'prompt': 'λ ',
        \ 'highlight_matched_char': 'QuickFixLine',
        \ 'highlight_matched_range': 'Visual',
        \ 'highlight_window_background': 'Visual',
        \ 'highlight_filter_background': 'DiffAdd',
        \ 'winrow': 1,
        \ 'vertical_preview': 1
        \ }}

  " Loop through denite options and enable them
  function! s:profile(opts) abort
    for l:fname in keys(a:opts)
      for l:dopt in keys(a:opts[l:fname])
        call denite#custom#option(l:fname, l:dopt, a:opts[l:fname][l:dopt])
      endfor
    endfor
  endfunction

  call s:profile(s:denite_options)
```

## How to reproduce problems from neovim startup (Required!)
:Denite buffer<cr>

**Comment by Shougo** [comment]
> List of buffers sorted by last modified date

I think this feature is already implemented.
Please explain more clearly example here.

If not, I will close it.

> :Denite buffer

This example is reproduce-able, really?
We have not ESP skills!

**Comment by Shougo** [comment]
> I want to sort list of buffers (:Denite buffer) by last opened

> List of buffers sorted by last modified date

Please read both.  It is not same!

I think it is already sorted by modified date, but it is not accessed date.

**Comment by Shougo** [comment]
I have added `sorter/oldfiles`for it.

**Comment by gi4c0** [comment]
I'm sorry, I meant  last opened (visited). This is exactly what I needed, thank you a lot.
