### ISSUE TITLE
Buffer source should have argument (+) to list only modified buffers.

### ISSUE THREAD

**Issue by smackesey** [Shougo/denite.nvim#808]
Right now the buffer source only takes the `!` flag (for unlisted). It should also take `+` (for modified). This was the old behavior in Unite, and it seems like a regression to not include it.

**Comment by Shougo** [comment]
The feature is already implemented.
And please don't ignore issue template.

![スクリーンショット_2020-10-22_09-11-25](https://user-images.githubusercontent.com/41495/96803208-98dfc480-1446-11eb-9cab-83a338daee86.png)

**Comment by Shougo** [comment]
I get it.  It is feature request.
