### ISSUE TITLE
Unable to set `empty` for `grep` source

### ISSUE THREAD

**Issue by rafi** [Shougo/denite.nvim#81]
# Problems summary
Unable to set `empty: 0` for `grep` source.

## Expected
```viml
call denite#custom#option('grep', 'empty', 0)
```
When running `:Denite grep` and pressing twice Enter (leave empty), don't open Denite window.

## Minimal init.vim

```vim
set nocompatible
set runtimepath+=~/.cache/vim/dein/repos/github.com/Shougo/dein.vim
filetype plugin indent on
syntax enable

call denite#custom#option('default', 'prompt', 'λ:')
call denite#custom#option('default', 'vertical_preview', 1)
call denite#custom#option('grep', 'empty', 0)
nnoremap <silent> ;g  :<C-u>Denite grep<CR>
```

## Reproduce

1. Add `call denite#custom#option('grep', 'empty', 0)` to configuration
2. In Vim, run `:Denite grep`
3. Press enter twice, leaving pattern empty

Denite window opens with empty candidates.

**Comment by okamos** [comment]
`denite#custom#option` first argument is `buffer-name`.

You can use `:Denite -buffer-name=grep grep` or `call denite#custom#option('default', 'empty', 0)`.
See `:h denite#custom#option()` :)

**Comment by rafi** [comment]
Thanks @okamos, I was thinking about Unite's behavior, where you could set options via source/buffer without naming the sources. I guess this works fine.

**Comment by Shougo** [comment]
Yes, it is the intended behavior.
