### ISSUE TITLE
File source with relative directory searching behaves strange

### ISSUE THREAD

**Issue by joker1007** [Shougo/denite.nvim#822]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

File source with relative directory searching returns strange results.

1. Launch Denite file source on a directory, and Denite returns expected results
2. Input `../` 
3. returns only hidden files starting with `.`
4. Input any key
5. returns files matching with the key of step 4

And `DeniteBufferDir` file source is more strange.

1. Launch Denite file source on a directory, and Denite returns expected results
2. Input `../` 
3. returns no result.

## Expected

In these cases, I expected that Denite returns all files on the parent directory at step 3.

## Environment Information (Required!)

 * SHA1: b7c43e846b404d6068e4905cc1fc22c73e6d333a

 * OS: Linux localhost 5.10.7-gentoo #1 SMP PREEMPT Sat Jan 16 18:52:10 JST 2021 x86_64 AMD Ryzen 9 5900X 12-Core Processor AuthenticAMD GNU/Linux

 * Vim/neovim version: NVIM v0.5.0-dev+1013-gb535575ac

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
```

## How to reproduce problems from neovim startup (Required!)

I describe it in the summary section.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

Neovim outputs no log.

**Comment by Shougo** [comment]
Reproduced.
