### ISSUE TITLE
Filter of file source doesn't work properly, but file/rec works

### ISSUE THREAD

**Issue by skt041959** [Shougo/denite.nvim#828]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
The filter of file source can't return substring matches. But file/rec work correctly.

## Expected
The filter should return substring matches at least.

## Environment Information (Required!)

 * denite version (SHA1): 9848fc7

 * OS: Archlinux

 * Vim/neovim version: NVIM v0.5.0-dev+1051-g4d1fc167a

 * `:checkhealth` or `:CheckHealth` result(neovim only): 
 
   - OK: has("python3") was successful
   - OK: Python 3.6.1+ was successful
   - OK: Require msgpack 1.0.0+ was successful

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/denite.nvim/
```

## How to reproduce problems from neovim startup (Required!)

 1. `cd ~/path/to/denite.nvim/test`
 2. `nvim -u init_mini.vim`
 3. `:Denite -input=auto file`    #show noting in denite window
 4. `:Denite -input=auto file/rec` #show autoload* items in denite window

## Generate a logfile if appropriate
Nothing in log file

**Comment by Shougo** [comment]
Fixed.
