### ISSUE TITLE
直近の仕様変更について質問と要望

### ISSUE THREAD

**Issue by octaltree** [Shougo/denite.nvim#831]
d990063, c56b0a7 について

## 困ってる
`<Plug>(denite_filter_quit)`の仕様変更について、
今まで通り`<ESC>`でfilter bufferだけ閉じてdenite bufferをノーマルモードでカーソル移動, 選択する方法は他に何かありますか?

## 困ってない
`<Plug>(denite_filter_backspace)`の仕様変更について、
filter bufferでは通常bufferと比べ`<c-u>`の挙動に違和感※がありBS連打することがあり、
勢い余りそうという懸念がある(使ってみなければわからないが)
副作用が少ない選択肢があると嬉しい

※
通常bufferでは1回のインサートモードで入力した行はスペースが入っていても`<c-u>`で全て消えるが
filter bufferに"a a"と入力し`<c-u>`してもスペースまでしか消えない
(もしスペースのタイミングでstartinsert呼んでたらそうなりそう)
これは以前からで違和感ありながらも使えていた
filter bufferのノーマルモードという概念がもしあればddとか`<c-d>`使うと思う

**Comment by Shougo** [comment]
> 今まで通り`<ESC>`でfilter bufferだけ閉じてdenite bufferをノーマルモードでカーソル移動, 選択する方法は他に何かありますか?

`<CR>` で filter を閉じるようにしてください。
両方閉じたいときに以前の仕様だと両方閉じることができなかったので今回仕様変更を行いました。

>filter bufferでは通常bufferと比べ`<c-u>`の挙動に違和感※がありBS連打することがあり、
勢い余りそうという懸念がある(使ってみなければわからないが)
副作用が少ない選択肢があると嬉しい

`<C-u>` のマッピングを追加しました

> filter bufferのノーマルモードという概念がもしあれば`dd`とか`<c-d>`使うと思う

ノーマルモードでのフィルタリングに対応させました

**Comment by octaltree** [comment]
`<c-u>`までありがとうございます。

d990063 より前
`<CR>`でinsert modeのまま先頭を選択し、
`<ESC>`でfilter bufferだけ抜ける設定は
```vim
  autocmd FileType denite-filter call s:denite_filter_my_settings()
  function! s:denite_filter_my_settings() abort
    imap <silent><buffer> <esc> <Plug>(denite_filter_quit)
    imap <silent><buffer> <cr> <esc><cr>
  endfunction
```
だったが、今回この設定で全く同じ操作実現できた。
```vim
  autocmd FileType denite-filter call s:denite_filter_my_settings()
  function! s:denite_filter_my_settings() abort
    imap <silent><buffer> <ESC> <Plug>(denite_filter_update)
    imap <silent><buffer> <CR> <ESC><CR>
  endfunction
```

filter bufferのノーマルモードは
filter bufferにカーソルが残るので
カーソル移動の方を設定する必要があるようですね。
