### ISSUE TITLE
Backspace moves from filter to denite buffer window

### ISSUE THREAD

**Issue by petobens** [Shougo/denite.nvim#832]
Consider the following minimal init.vim file:
```vim
let $DOTVIM = expand('$HOME/.config/nvim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/denite.nvim
filetype plugin indent on

call denite#custom#option('default', {
            \ 'start_filter': 1,
            \ })
```
Now, as in the GIF, open nvim and do
1. Run `Denite file`
2. Press backspace
After 2. the cursor jumps from the filter window to the denite window. I expect the cursor to remain on filter window.

![denite-back](https://user-images.githubusercontent.com/2583971/107120445-78f4d500-686c-11eb-90c2-1a7ea321c194.gif)

**Comment by Shougo** [comment]
It is intended behavior. If you don't like it, you can disable by unmap.
