### ISSUE TITLE
Change of behaviour of <Plug>(denite_filter_quit)

### ISSUE THREAD

**Issue by JCavallo** [Shougo/denite.nvim#835]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

I used the <Plug>(denite_filter_quit) mapping to switch from the filter line into the main window.
Basically, I would start denite, filter the result in the "denite-filter" window, then use this mapping to select what I wanted in the "denite" window.

Since commit d990063c2f3fcc182359755845b861c9230c0916, this does not work anymore, because this mapping now exits both the filter window and the denite window

Once again, thanks for your work on this plugin !

## Expected

I would like to know if this was intentional, and if it was if there is a way to achieve the expected behavior.

I'm willing to create a PR that would add a new mapping that would offer the previous behaviour

## Environment Information (Required!)

 * denite version (SHA1): d990063c2f3fcc182359755845b861c9230c0916

 * OS: Debian 10

 * Vim/neovim version:

NVIM v0.5.0-844-g8c4648421
Build type: Release

 * `:checkhealth` or `:CheckHealth` result(neovim only):

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/denite.nvim/
inoremap <silent><buffer> jk <Plug>(denite_filter_quit)
```

## How to reproduce problems from neovim startup (Required!)

:Denite file/rec
<input filter until there are a few files in the list>
"jk" in insert mode

**Comment by octaltree** [comment]
You can use `<Plug>(denite_filter_update)` instead of `<Plug>(denite_filter_quit)` to close the filter buffer and remain in the denite buffer. It is mapped to `<CR>`.
https://github.com/Shougo/denite.nvim/blob/b7e15bbf2f6ad83309d9799350b1b16c21faff6b/autoload/denite/filter.vim#L95

**Comment by Shougo** [comment]
Yes. It is intended change and you can use `<Plug>(denite_filter_update)` instead.

**Comment by Shougo** [comment]
> I used the (denite_filter_quit) mapping to switch from the filter line into the main window.

The mapping is not created for it.

**Comment by JCavallo** [comment]
Thanks for your answers, that works as expected
