### ISSUE TITLE
Error when pressing <C-c> to quit

### ISSUE THREAD

**Issue by Asheq** [Shougo/denite.nvim#84]
# Problem summary

When I press \<C-c\> (Control + C) to quit Denite, it gives me an error instead of quiting

![image](https://cloud.githubusercontent.com/assets/4657140/20683333/6efb0c0e-b560-11e6-8cb3-576ad79d70c2.png)

## Expected

I expect Denite to quit.

## Environment Information

 * OS:
    VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 13 2016 09:59:10)
    MS-Windows 64-bit GUI version
    Included patches: 1-3

```vim
" Your minimal init.vim
set runtimepath+=~/.vim/bundle/repos/github.com/Shougo/denite.nvim/
```

## The reproduce ways from gVim

 1. Start gVim
 2. Start denite with any source, for example ":Denite line"
 3. Press \<C-c\> to attempt to quit denite

## Thank you!

Keep up the amazing work Shougo! I love all of your plugins, and I'm looking forward to Vim8 support for deoplete and the other dark-powered plugins.

**Comment by hass-laughingman** [comment]
I believe this issue is only exists in vim 8.0. `<C-c>` quits denite as expected in neovim.
A workaround for now in vim 8.0 would be to map `<C-c>` to `<Esc>` while in denite, maybe something like this

```
augroup filetype_denite
  autocmd!
  autocmd FileType denite call s:denite_keymapping()
augroup END

function! s:denite_keymapping()
  map <buffer> <C-c>     <Esc>
endfunction
```

**Comment by Asheq** [comment]
@hass-laughingman, thanks but the work-around you mentioned doesn't seem to work for me. I can wait for one of @lambdalisue's PRs to be merged
