### ISSUE TITLE
Floating window

### ISSUE THREAD

**Issue by AP2008** [Shougo/denite.nvim#850]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
:Denite rec/file -split=floating

## Expected
Opens in a floating window

## Environment Information (Required!)

 * denite version (SHA1):
https://github.com/Shougo/denite.nvim/commit/452b1800ad2f2db96847da857f9a0d67ff6ecc95

 * OS:
 Windows 10

 * Vim/neovim version:
Vim 8.2 (with `+pupopwin`)

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/vim-bundle/')
Plug 'ctrlpvim/ctrlp.vim'
Plug 'kovisoft/slimv'
Plug 'yegappan/mru'
Plug 'preservim/nerdtree'
Plug 'preservim/nerdcommenter'
Plug 'vim-airline/vim-airline'
Plug 'mhinz/vim-startify'
Plug 'arcticicestudio/nord-vim'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'sjl/gundo.vim'
Plug 'luochen1990/rainbow'
Plug 'myusuf3/numbers.vim'
Plug 'ollykel/v-vim'
Plug 'vimwiki/vimwiki'
Plug 'hzchirs/vim-material'
Plug 'ryanoasis/vim-devicons'
Plug 'ervandew/supertab'
Plug 'lifepillar/vim-mucomplete'
Plug 'Shougo/denite.nvim'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
call plug#end()
```

## How to reproduce problems from neovim startup (Required!)

 1. gvim
 2. :Denite file/rec -split=floating -wincol=20 -winrow=20

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/44343120/114269497-0d261880-9a25-11eb-8ecc-81a9908c1741.png)
The denite window opens vertically.

**Comment by Shougo** [comment]
Please read the documentation.  Floating window feature does not work on Vim.

```
						*denite-option-split*
-split={direction}
		Specify the split direction.

		"vertical": Split buffer vertically
		"horizontal": Split buffer horizontally
		"no": No split
		"tab": Create the new tab for denite buffer
		"floating": Use neovim floating window feature
		"floating_relative_cursor": similar to "floating" but open
		floating window near the cursor.
		"floating_relative_window": similar to "floating" but open
		floating window near the window.

		Note: To use "floating", you need to use neovim
		0.4.0+(|nvim_open_win()|).

		Default: "horizontal"
```

**Comment by AP2008** [comment]
Why does it not work in Vim ? Vim 8.2+ has popup windows. And in the documentation it's written:
```
-floating-preview
		
Open the preview window in floating window when
		|denite-option-vertical-preview|.
		Note: To use it, you need to use neovim
		0.4.0+(|nvim_open_win()|).
		Note: If you need the feature in Vim8, you should use
		'previewpopup' instead.
                 Default: false
```
It states to use ` previewpopup` in vim

**Comment by Shougo** [comment]
Because popup window is not same with neovim floating window feature.

**Comment by Shougo** [comment]
Popup window is added for preview window, so it can use for floating preview.

**Comment by AP2008** [comment]
But vim floaterm (https://github.com/voldikss/vim-floaterm) works on vim8.

**Comment by Shougo** [comment]
If you really needed the feature, the PR is wellcome.  It is open source.

The main difference is focusing.  No magic.

https://github.com/vim/vim/pull/7555
