### ISSUE TITLE
Feature Request: open any path from user provided list

### ISSUE THREAD

**Issue by rodolf0** [Shougo/denite.nvim#855]
Use Denite to open files (not restricted to recursive subdirectories) sourced from a user provided file.

Something like `:Denite -start-filter -auto-action=open output:!cat\ <my-file-list-file>`

The issue is that `open` action isn't available for `output` source. Is it possible to do this in a different way? I tried customizing `file/rec` command but that doesn't seem to work for arbitrary paths out of cwd.

Rationale: I want to open vim and use Denite to jump to any pre-indexed file. The file/rec source seems like a reasonable alternative but I want to source candidates from a pre-existent cache, otherwise on large repos its impossible to scan the whole tree.

**Comment by Shougo** [comment]
Why don't you use `denite#custom#action()`??

`:help denite#custom#action()`

Closing.
