### ISSUE TITLE
python and n/vim use high CPU time after denite usage.

### ISSUE THREAD

**Issue by ikeji** [Shougo/denite.nvim#865]
# Problems summary

Sometime, vim and python process consume high CPU time.
And I found it's happen after using denite plugin.

## Expected

After close denite buffer, denite plugin doesn't consume CPU time.

## Environment Information (Required!)

 * denite version (SHA1):  f88be9be638fd93c8159d3d0434c6e0576bec6d1
 * OS: Ubuntu 20.04 (or Debian 10)
 * Vim/neovim version: Vim 8.1.2269, nvim 0.4.3 (from Linux distribution)
 * `:checkhealth` or `:CheckHealth` result(neovim only): https://gist.github.com/ikeji/0fd328026ec686e3b5b6ef432c71bde5

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/vim.d/denite.nvim

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
endfunction

call denite#custom#alias('source', 'slow', 'file/rec')
call denite#custom#var('slow', 'command',
        \ ['slow'])

```

and slow command is this script

```sh
#!/usr/bin/env python
import time
import sys

for x in range(1000):
  print("{} hoge".format(x))
  sys.stdout.flush()
  time.sleep(0.01)
```

## How to reproduce problems from neovim startup (Required!)

 1. open vim or nvim
 2. run this command: ```Denite -start-filter slow```
 3. input 'hoge' to filter box and hit enter twice (one for confirm the filter and one for select a candidate).
     This step should be done in 10 second that before the 'slow' script is not finish.

The high CPU usage doesn't happen always, need to repeat few times for reproduce.
In my machine, it happened in 1-3 times.

## Upload the log file

I set NVIM_PYTHON_LOG_FILE=/tmp/log, but it generate /tmp/log_py4_rplugin only. does this the log that is required?

Here is a repeated part of log_py3_rplugin.
https://gist.github.com/ikeji/a0f1d6329ef50801ef0601a116d4b6e0
Here is a entire log file.
http://test.ikeji.ma/log_py3_rplugin (warning: 62MB)

Does anyone have any idea to avoid this?

**Comment by Shougo** [comment]
I think the process cannot be killed(ignored stop signal).
If the CPU usage is high, it causes sometime.  No magic.

**Comment by ikeji** [comment]
I think this is more like task leak instead of performance problem.

I found this command resolve CPU usage in python side, but Vim side is not.
```unlet g:denite#_channel_id```

**Comment by Shougo** [comment]
If the Python task is heavy, Vim cannot quit the task.  Because the signal is ignored.
And the remote plugins has task cleanup problems.
I gave up and move to denops.

**Comment by Shougo** [comment]
I have tested your example and I cannot reproduce it!

**Comment by Shougo** [comment]
I have changed the example.  I will try it.

**Comment by ikeji** [comment]
Updated the script.

**Comment by Shougo** [comment]
Hi, I have updated denite.nvim.  Please use the latest version.

**Comment by ikeji** [comment]
Thanks. 
I tested the new version and the bug is gone!

Thanks a lot!
