### ISSUE TITLE
Denite loses statusline after file preview

### ISSUE THREAD

**Issue by rafi** [Shougo/denite.nvim#88]
After previewing a candidate, Denite window stops updating statusline.

Notice the statusline change:
![denite-file-preview](https://cloud.githubusercontent.com/assets/147918/20893929/3953aeaa-bb1c-11e6-8216-5089c440db39.gif)
* My window settings are `set winwidth=50 winminwidth=8 winheight=13 winminheight=3`

~There should be support for actions that "do not hide the Denite window", currently only the preview action acts this way, but it would be great for other _kind actions_, like [https://github.com/rafi/vim-denite-mpc](https://github.com/rafi/vim-denite-mpc) when selecting a song, it would be nice to have denite stay open and "refresh".~

**Comment by Shougo** [comment]
Please describe the problem with the minimal init.vim and reproduce ways from neovim starting.
I will check the behavior and fix.

**Comment by Shougo** [comment]
> There should be support for actions that "do not hide the Denite window", currently only the preview action acts this way, but it would be great for other kind actions, like https://github.com/rafi/vim-denite-mpc when selecting a song, it would be nice to have denite stay open and "refresh".

I don't understand.  It is already supported behavior.
You can use `-no-quit` or `return True` in the action.

`:Denite -no-quit`

**Comment by Shougo** [comment]
@rafi Ping

**Comment by rafi** [comment]
Closing, fixed by ignoring 'denite' filetype when setting `l:statusline` in auto-command `WinEnter`.

**Comment by Shougo** [comment]
OK
