### ISSUE TITLE
[SUGGESTION] Automatic Documenation

### ISSUE THREAD

**Issue by tjdevries** [Shougo/denite.nvim#9]
Hey Shougo,

I was thinking maybe there might be a way to generate some of the documentation for denite from the python files of the sources. Would you be interested in something like that? I could take a look at it if you would like. I have a couple ideas from some documentation generators I have seen in the past that are used with Python.

This would hopefully keep your documentation / help documents up-to-date with the latest source, without you having to spend the time updating the documentation.

**Comment by Shougo** [comment]
I don't think it is useful.
Most of users don't touch Python functions.
