### ISSUE TITLE
Action name completion is not working

### ISSUE THREAD

**Issue by pocari** [Shougo/denite.nvim#90]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Action name completion in normal mode is not working, if I canceled anything once confirmed.

## Neovim Python Diagnostic

- Neovim Version: NVIM v0.2.0-1-g9956bee

## Provide a minimal init.vim with less than 50 lines (Required!)

```
let s:dein_dir = expand('~/.cache/dein2')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
  if !isdirectory(s:dein_repo_dir)
    execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
  endif
  execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

call dein#begin(s:dein_dir)

call dein#add('Shougo/denite.nvim')

call dein#end()
call dein#save_state()

if dein#check_install()
  call dein#install()
endif
```

## The reproduce ways from neovim starting (Required!)

 1. :Denite file_rec
 2. move `normal mode` by `<C-o>` and `<TAB>`
     I input 'de' and `<TAB>` (expecting 'default').
  
    <img width="205" alt="2016-11-30 14 52 34" src="https://cloud.githubusercontent.com/assets/1496543/20741466/a9d8d9d8-b70d-11e6-9cee-8eeec84ab09e.png">
   
    and completed 'default' (it's works)

 3. Next, I erase 'default' (by backspace key) and input 'y'
     and input `<TAB>` for completion (expect 'yank')
     but, completion is not working.

     <img width="206" alt="2016-11-30 14 53 56" src="https://cloud.githubusercontent.com/assets/1496543/20741481/c9905026-b70d-11e6-9780-b1c2b8595eab.png">

**Comment by lambdalisue** [comment]
`copy()` is required here https://github.com/lambdalisue/denite.nvim/blob/neovim-prompt/autoload/denite/helper.vim#L33
