### ISSUE TITLE
Ability to disable highlight on file_rec match.

### ISSUE THREAD

**Issue by musaffa** [Shougo/denite.nvim#97]
I want to upgrade Denite to the master branch but I'm uncomfortable with glaring highlight on the matched file names. Is there any way to disable this highlight on `file_rec` matches? Thanks.

And I think highlight on the matched file names with `file_rec` should be disabled by default. Because matching changes on the fly as we type and using highlight the reflect those changes hurts the eyes.

**Comment by cartolari** [comment]
I'd like to add that it appears that Denite highlights the entire match from the first matched char to the last, instead of just highlighting the individual chars that caused the match to occur.
For example, today if i searched for dte and an option called denite was available denite will highlight the entire word (like this **denite**) but it would be better if the only highlighted chars were d, t ande (like this **de**nit**e**). 
Is there a way to highlight just the chars instead of the whole substring?

**Comment by Shougo** [comment]
> Is there a way to highlight just the chars instead of the whole substring?

Nothing.

**Comment by Shougo** [comment]
> I want to upgrade Denite to the master branch but I'm uncomfortable with glaring highlight on the matched file names. Is there any way to disable this highlight on file_rec matches? Thanks.

Please change `deniteMatched` highlight.

> And I think highlight on the matched file names with file_rec should be disabled by default. 

I don't think so.  It is just your opinion.

**Comment by musaffa** [comment]
@Shougo How do I change `deniteMatched`? It would be nice if you add some documentation about it. Some scenarios on the top of my head:

1) completely disable the highlight,
2) change it to color of `cursorline`,
3) any color.

Thanks.

**Comment by Shougo** [comment]
`:help highlight`

**Comment by musaffa** [comment]
Not the highlight of the whole application, I want to change only `deniteMatched`. Currently, there's no documentation about `deniteMatched`.

**Comment by Shougo** [comment]
Have you read the documentation properly?

```
:hi[ghlight] [default] {group-name} {key}={arg} ..
			Add a highlight group, or change the highlighting for
			an existing group.
			See |highlight-args| for the {key}={arg} arguments.
			See |:highlight-default| for the optional [default]
			argument.
```

**Comment by musaffa** [comment]
Is `deniteMatched` a group name?

**Comment by Shougo** [comment]
Yes.

**Comment by musaffa** [comment]
Thanks.

**Comment by cartolari** [comment]
@Shougo Regarding the chars highlighting, are there plans to implement it in Denite?

**Comment by Shougo** [comment]
> @Shougo Regarding the chars highlighting, are there plans to implement it in Denite?

If possilble.  But it is not easy.

**Comment by Shougo** [comment]
I have improved the default highlight.

**Comment by cartolari** [comment]
It's not perfect but it's a lot better. Thanks.

**Comment by musaffa** [comment]
@languitar Here's my setup:
```vim
highlight default link deniteMatchedChar CursorLine
highlight default link deniteMatchedRange None
```
To completely disable highlighting you have to set `deniteMatchedChar` to `None` as well.

**Comment by languitar** [comment]
Thanks, interesting. I ended up with this after talking to @Shougo:

```
call denite#custom#option('_', 'highlight_mode_insert', 'CursorLine')
call denite#custom#option('_', 'highlight_matched_range', 'None')
call denite#custom#option('_', 'highlight_matched_char', 'None')
```

**Comment by Shougo** [comment]
Using `denite#custom#option()` is better.
