### ISSUE TITLE
[Feature Request] Will denite support file_rec for Windows?

### ISSUE THREAD

**Issue by bennyyip** [Shougo/denite.nvim#98]
Denite is awesome, but file_rec doesn't work on Windows.
I checked [file_rec.py](https://github.com/Shougo/denite.nvim/blob/cfbbf142e4af71fcbe5bb2400610d5e0997a3d32/rplugin/python3/denite/source/file_rec.py#L52), it just returns nothing when using Windows. Is windows support planned?
```python
            if context['is_windows']:
                return []
```
Thanks.

**Comment by AlexMasterov** [comment]
Hm.. Works fine on Windows 10.

```viml
" https://github.com/BurntSushi/ripgrep
call denite#custom#var('file_rec', 'command',  ['rg', '--follow', '--hidden', '-l', '.'])

nnoremap <silent> ;f :<C-u>Denite file_rec -no-statusline<CR>
```

**Comment by Shougo** [comment]
You must specify file_rec command.

**Comment by gaving** [comment]
@AlexMasterov Just curious how you're getting denite working at all due to the state of python support on Windows? neovim/neovim#5360 + neovim/neovim#5280

**Comment by AlexMasterov** [comment]
@gaving Denite supports Vim 8.

I use Vim 8 on Windows 10 and Neovim on Bash on Windows.

**Comment by gaving** [comment]
@AlexMasterov Ahhh I see, cheers for clearing that up.
