### ISSUE TITLE
How to map a Alt key?

### ISSUE THREAD

**Issue by liuht-gnu** [Shougo/denite.nvim#99]
I want to map Alt-c key, use the following command:

cal denite#custom#map('insert', '<A-c>', 'delete_backward_char')

but it didn't work.

**Comment by liuht-gnu** [comment]
cal denite#custom#map('insert', '\<A-c>', 'delete_backward_char')

**Comment by Shougo** [comment]
Ping @lambdalisue

**Comment by lambdalisue** [comment]
The usage of mapping custom has changed by this pr https://github.com/Shougo/denite.nvim/pull/79
The pr has a link to how user can migrate so could you check it and try?

**Comment by lambdalisue** [comment]
ping @liuht-gnu

**Comment by nfnty** [comment]
Alt mappings work great, this can be closed.
